apiVersion: v1
kind: Secret
metadata:
    name: fritzbox-exporter-credentials
    namespace: monitoring
    annotations:
        argocd.argoproj.io/sync-wave: "19"
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:78A/cJMAhDfFIA==,iv:Bjr0cmkdvqzOeX1hgknDH2fdDvN5Dtz2P0BJo9kcS/0=,tag:8DXK1QZdN1B+xb83HUwcmw==,type:str]
    password: ENC[AES256_GCM,data:wO50Vd+W0gL5XEPUxCYzbm32,iv:+3c46sHmInM+zlh2CtdQcFvdQQMx+Vzh0ltRNcPL150=,tag:LihC/viDQl7yK4XEOfeUwA==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid1ZEY1JkbEpxeU9rTmx4
            Z05GUVZRRkZQaFRTZU9ZUUM1NWV2b1l0bnpVCnZGeHhqZUVwOU00Z1RUb2VIV1RP
            eVRKcWtjR2s0dXpVZmZWSEdWQjVCaWMKLS0tIHNQTVQ2RXp3R21FOWZQTEdMMENs
            SVZ6UDEvV2xQRHE2SHhZb0FLcExOMFUKDSBTZjlM7LqgZojFh83Azpo2a06JrU6T
            Xog7x99usqANrb6KARYJZeVfOTUwLt3yClp3njJnPaiey2LT3qNpwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YVpUVXFMVmkrN3d0WnZF
            cXhveSs4NmpNczgvQXlDOS9Wcmtqb081MUNrCjNWYVBLYWdGWHVHeGl5RVNmVStu
            dHYyM2xsYThPeVY1UXVpYTltcXFyT00KLS0tIGp1OXYvc0JWVHlVYTFUQ0hXSTZ0
            dHdDdE9Od05ZRngyRXBKTERUbytlRFkKGzVXb4WB/F993LTOLvgSXkU0zkVlqD2o
            1xoZEupii3BArA2C6KgZAwR2mUJLEBUeHcH272hLVJJvOIT0DbE6hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T08:00:27Z"
    mac: ENC[AES256_GCM,data:CH46yxZGbh3KGUM9qif8J1kEo8TEonVMIUSI9ycTQdhudBSCyS7zOCMELKEGWMIHSEwyCjRq96IwO7m4hXB7bLcEH35WXsSgZYxEMu37oM5SNkHy5NS1GjjD5EiNDgiHpwfB8toQkawat+ao4EDMDnftKDyMFHSBzFFapCncPFU=,iv:kPXHVBxuraVKHLlnDMomXG7k75t1IloTPSaHJGbTTfY=,tag:xv4afonrDs16sQa6ToN84w==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match)$
    version: 3.11.0
