apiVersion: v1
kind: Secret
metadata:
    name: cluster-tv-env
    namespace: monitoring
type: Opaque
stringData:
    ARGOCD_TOKEN: ENC[AES256_GCM,data:gJCz/BjsZVu1by7REdoh06ueUbzo6KNo69wsprGLOfdYOFQKbEAA0y3CLb5RYtwusy79ixxD+l+iQRlzsNlIg0bSuUbxYRwRtk24YdTqzATr1xZ3kSTwzgAWpiEtPcoFWdC/tn2G/+hbsO8OHmnPHz/5N1Z9rPF2/N+0WLxzX/x17nA1vdaxRgawIqow7wuh9ITEuo0DwEGFo548ovNaOSN70nHUQQmPiSzxjTQPvTFqWzBjiYFxoXpF9K1dkSmcYlvQBpAQhuFvTtbd+GUpHGDOsM7JxI/wqrlBn9EhUaJMpErsv0hg6NPQZk0uh7dXlHVL,iv:GEZkDbs93iCSyZrJVYcSw9LulMnYVau5Hl56CKeDE+0=,tag:ZkmO8DVlvoIBLH8PFUTRAg==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUlVxVzBpSVppU1M1YTBX
            dzJ3ZzlGa20xMlRMUEl2U0ZoNTJxVFI2YkVjCmR5S21aakMxclB3VWdac0N5WFhl
            T25OOTJWb052SEowWTJ6TURZVzhJaDAKLS0tIFhDMXlncXJYMElCT3c0dlQzeTBa
            T3dydlY4WGd6Z1o1cjY4WUtlZEVkME0K07x9FzpotgFSkSrmPMIo6E4Z/+s3Tl1M
            a69sO7FcUdiVcx72mkpgI9r9Aq9xcnD0qbGTR5PyZ21AD9CYkxG63g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd2JqTURmai8razh5bHJn
            a3FqMDNPbnlMc3JPRHBWa2luSXRsRmF3OGlrCndSdFZDbHJ3eFlJSlJHeVdjSHpm
            N3l5TmRGNCtnR2NJOHQ2Vjl1RFJoY2cKLS0tIHk1YnpLcTVzdEdJUW5YOTllWVl2
            Y1QwRStycnl3NEJBSVM0QlRvZmJBVUEKnn1CxxAi0GntCMGtxVhJYXYPzXggEosf
            8EY6R8vJSrizFnT9mkWrwOCzMXRWjm6BtYdQYDeB7CMYz1gNbaSZvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T17:40:32Z"
    mac: ENC[AES256_GCM,data:AJkzqxC8JGEHg4b2TV++YAyVfBnUB5YbOjLjzXZQNzKlSMeEv8fcNjnErhD1nGnbNUybMWIZq3aontPm/AqOEcUK+OpJcB8/SJbg1Zk91R2CLvr2yvTqLnz//S2SFNbCrEJIQr8csriCZ2uZSTZGPw+feUdjXF5HDg8aKpMNVjg=,iv:2Sgz808Yd7JnBk5yzF5MNR4IYyDGSMwPCOgEAarXLcE=,tag:s52XI5vetRhfW0exY1vKHg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
