nameOverride: pihole-03
image:
    repository: ghcr.io/pi-hole/pihole
    #tag: 2025.11.0
    pullPolicy: IfNotPresent
revisionHistoryLimit: 2
serviceDns:
    mixedService: true
    annotations:
        lbipam.cilium.io/ips: 192.168.1.238
    # type LoadBalancer with externalTrafficPolicy Local
    # requires 192.168.1.232 on the same node as the pod
    type: LoadBalancer
    #externalTrafficPolicy: Cluster
    #type: ClusterIP
serviceDhcp:
    enabled: false
virtualHost: ENC[AES256_GCM,data:YkKDoZVE3kwJmGT96COkW5gRcszsjzI/o0mRPNOv,iv:NZDmutD0mRLREcPLNldsNm/sYTq9JEqFSA7mgzpHruM=,tag:gnwxBpclWxAiY33DsfLXpg==,type:str]
ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
        - ENC[AES256_GCM,data:YOjlz12JilNyozujG0/Xl6N6dYKTAXaRy37ZVLTq,iv:TxY5iud9h+8w9OJRzbEp+ehYAoqOb7NwEfCl/X+gpIg=,tag:54z2/n/XlHyXp4dx+ctjvA==,type:str]
    tls:
        - secretName: wildcard-cloudflare-production-02
          hosts:
            - ENC[AES256_GCM,data:lmPHUp41lJjaM/a7iG9MdHLQS7XdANm0fWRQoH9j,iv:JOEhoXqr/wPU6DQnb3HKjYiDuU/LhNcpGbufbqh7coo=,tag:slSRCy+M792aX2ZVyBMxIw==,type:str]
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web239, websecure239
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd, traefik-root-to-admin@kubernetescrd
resources:
    limits:
        cpu: "1"
        memory: 768Mi
    requests:
        cpu: 100m
        memory: 128Mi
extraEnvVars:
    TZ: Europe/Berlin
    FTLCONF_dns_bogusPriv: true
    FTLCONF_dns_domainNeeded: true
    FTLCONF_dns_domain_name: neese-web.de
    FTLCONF_webserver_interface_boxed: false
DNS1: 127.0.0.1:5053
DNS2: ""
# Not required because secured via authelia oidc
admin:
    enabled: false
doh:
    enabled: true
    config: |
        listen_addresses = ['0.0.0.0:5053']
        server_names = ['nextdns-735278']
        require_dnssec = false
        require_nolog = true
        require_nofilter = true
        dnscrypt_servers = true
        doh_servers = true
        odoh_servers = false
        ipv6_servers = false
        bootstrap_resolvers = ['9.9.9.9:53', '1.1.1.1:53']
        timeout = 5000
        keepalive = 30
        log_level = 2
        use_syslog = false
        cache = true
        cache_size = 4096
        cache_min_ttl = 2400
        cache_max_ttl = 86400
        cache_neg_min_ttl = 60
        cache_neg_max_ttl = 600

        [sources]

        [static]
          [static.'nextdns-735278']
            # https://dns.nextdns.io/735278/pihole03
            # https://dnscrypt.info/stamps/
            stamp = 'sdns://AgcAAAAAAAAAAAAOZG5zLm5leHRkbnMuaW8QLzczNTI3OC9waWhvbGUwMw'
#podDnsConfig:
#    enabled: true
#    policy: None
#    nameservers:
#        - 1.1.1.1
#        - 127.0.0.1
capabilities:
    add:
        - NET_ADMIN
        - CAP_SYS_NICE
persistentVolumeClaim:
    enabled: true
    size: 1Gi
    #existingClaim: pihole-02
dnsmasq:
    customDnsEntries:
        - ENC[AES256_GCM,data:9d3OaO8QV91AqV6UttiXBakBMADFSOxPuGnmwG7aiIjFIx4=,iv:xOQiYra6YN3XifPf0QhU9mPF90Tgs8wExQWwhACEQ00=,tag:P8pvggfydHXbZ1oPPIc9uA==,type:str]
        - ENC[AES256_GCM,data:BCFlaUftft1Z+yw4s6/L6gtxym6S5L3Lydk1NzA=,iv:x9FJZIQYjOoyWiWXlUqe7+Uaw3otDRxomJsbOVd46SM=,tag:lCfAgEUfqDAY5vIpsP539g==,type:comment]
        - ENC[AES256_GCM,data:bg582jg3qFPOji8PDddcqSTRf4XS+WZP4+mJ9Bk9zelc6deLaf1Lsg==,iv:+GAPk8aZbzUhmXu6mS+/oJ729wkZuszPbGgZDC6TN5k=,tag:Yxx2Fry6LNYy7ITsyV85dw==,type:str]
        - ENC[AES256_GCM,data:HAybEx2dkk3g2aZiLyPeuwQjRcIta7ivank3Akf7xl88,iv:H9tslC7c43xs6BAdFxS+rdv10d29ZsioLnHfxU9ZpiM=,tag:s0qNEnjcpinObEOH3Zzxvg==,type:comment]
        - ENC[AES256_GCM,data:skhrxb/Ivze5/TscPOSW9LU44BC8J4mkodAvcZkougws4oLevbkiDxFDRO3V,iv:2stOoem+eRo7SbDp54M8ukU352NniavsDdbLeunYC9s=,tag:xiogdpuU+4KCrYNh3LItSg==,type:str]
        - ENC[AES256_GCM,data:WBKxTM1lkTlZ4hp218Ywm+EdP0MOo+Z6tBFtZ6XHjh084fvVtE8=,iv:R7yVck2YehXXSOf2YYQXFIemztBxb6IR/XDLXGQsIaM=,tag:/wByv3M68IoBiFiVlP1+3w==,type:comment]
        - ENC[AES256_GCM,data:R1hy2fMkSrkg5WdnhPoFfXXHuc/TLX/8R2RxyaxGm6/zEZ1x/KIefWDKsvYXL9vXig==,iv:ymHb5QLzPARSb7rRyAx+eaKrIIMkvf7Hip6gu8uV/bU=,tag:3l51v6eXqBuwFkJX9ClNkw==,type:comment]
        - ENC[AES256_GCM,data:0VZOhK4pqEBSFCdwYSP3bBBcAZRXlopXw6On5diUH4HCq3ABaiomxeb754Q1og1sG3gaiWk7I6M=,iv:7fmKGR24SRhMEUvOZydag/+oEiscms0LgLTzvBW4wB4=,tag:hGMJnZuOeI9cQIySA0Ob6g==,type:comment]
        - ENC[AES256_GCM,data:0qOmil8/afPmrb3Osy+qNbD4xsAVe8sXZLdR1TX85kSZfyRndgNthAQ=,iv:5klIQYsDcm4h5Dm29pBgx+8mMBXva4PcW8rBP5Lkt5I=,tag:nBsDrSqLhsEfH0k3acGVvA==,type:comment]
        - ENC[AES256_GCM,data:EUbP6DS6FJYe1OGmkn0B0i/3FugZXZ0Z+9Da1aRieE3rToWSPnMdvyh8zFDfJFkz,iv:9KCvgcURlnU8BVzLZ7YzVRtZjh9r3gFpeTX7CceB7bw=,tag:KyDvlabZzPBSoG7WppAfAQ==,type:comment]
        - ENC[AES256_GCM,data:4Y6G9Wdv9C8+1VbQmBZMHTrfQXDG03EPBJq7E6Tl0tiNXgbBHRyi,iv:8f5HS252Kknp93noSbDjQgtXr6NQOfSsTAuSrcnaLwQ=,tag:vAEbU+SsInfJ6e9+4yuH2g==,type:comment]
        - ENC[AES256_GCM,data:R2OEVhqWpiwRLlTMhO5n3ehkETPbEaRgEhhMjzkDpQyWygIiqd0RMiOZd2555A==,iv:/2mGsLr9nQoeBa7Pz5E9d4yeeCVO0YZls78/abyHgZg=,tag:AoWW/rPv6WMrgc03cR9fhg==,type:comment]
        - ENC[AES256_GCM,data:CG2eUqy6VAn++dNIK7GJrvpzHvKsuUx+LqM7oGOKKCHRQWQLDJs157n/uDcPdwUv,iv:9NQfZ9Ctd4/LSk/fJ9bDDLJ6piLcmwASP49G5xyDi3o=,tag:XNVQ4pDcMohrqHY61p2UBw==,type:comment]
        - ENC[AES256_GCM,data:y2Ika31ZQsgC/fORv5Z2i5BpkibsXDu4MffDC6tDdnaor8aOQ48ERCD/96dYezwKRNashWDuMw==,iv:U+IIJSeoEJ2zIGaJpDhEuhXi60dExvJq5Sf2f/vXeFk=,tag:DmXFcqpAyDVNHWuuUThgtw==,type:comment]
        - ENC[AES256_GCM,data:XJOM24MR7C58qs1qZQ29oJ96LNw0od/sN7pa9R9d+iX1YZlfrBexDVIh6F1d/AtKjwU=,iv:CT+YYT4LpV8k9yb3/2DqxPyBpI9vZwcWgtdNhKvp+VQ=,tag:O2HvcDT5XyvWNP8iaF83yA==,type:comment]
        - ENC[AES256_GCM,data:YwVv4LuZhlg0CfwtCrWi9Z2j7ksDyDQ9f71DVM6TzOtlkNev40fpXMopGf8WihsE6KY5PSNqXYnu,iv:Oc/yyGBCR8WNckFxVylrdhfgTOJU5hXl3EU2sgRUbAs=,tag:kmGa3KXaJLWKsZaxBGqmWA==,type:comment]
    customSettings:
        - dhcp-option=252,"\n"
        - dhcp-option=vendor:MSFT,2,1i
        # DNS
        #- dhcp-option=6,192.168.1.232,192.168.1.1
        - dhcp-option=6,192.168.1.232
        # NTP
        - dhcp-option=42,192.168.1.1
        - dhcp-range=::,ra-names
        - server=/geekbundle.org/192.168.1.1
        - ptr-record=1.1.168.192.in-addr.arpa.,"despair"
        # TFTP Boot
        - dhcp-match=set:ipxe,175
        - dhcp-boot=tag:!ipxe,ipxe.pxe,dns01,192.168.1.45
        - dhcp-match=set:efi-x86_64,option:client-arch,7
        - dhcp-boot=tag:efi-x86_64,ipxe.efi,dns01,192.168.1.45
        - dhcp-boot=http://192.168.1.45:8043/boot.ipxe
        # DHCP Reservation with different dns server
        - dhcp-option=net:customdns,6,9.9.9.9,1.1.1.1
        - dhcp-host=net:customdns,EC:79:49:51:64:16,192.168.1.187,ipl06002-lan
        - dhcp-host=net:customdns,F4:4E:E3:2C:C2:B6,192.168.1.56,ipl06002-wlan
        # DHCP Reservation with unrestricted youtube dns server
        - dhcp-option=net:youtubedns,6,192.168.1.234
        - dhcp-host=net:youtubedns,AC:3E:B1:A6:AF:D6,Pixel-7-Pro
        - dhcp-host=net:youtubedns,E0:80:6B:37:56:83,Redmi-Note-11
        - dhcp-host=net:youtubedns,74:58:F3:E7:3A:04,Fire-Cube-lan
        - dhcp-host=net:youtubedns,48:43:DD:6E:CC:2D,Fire-Cube-wlan
        - dhcp-host=net:youtubedns,F0:27:2D:D7:41:97,Fire-Guest
        - dhcp-host=net:youtubedns,00:e0:4c:7b:c2:98,Sanctuary
        - dhcp-host=net:youtubedns,8c:8c:aa:32:ce:7a,IONB000201752-LAN
        - dhcp-host=net:youtubedns,4e:80:5d:ae:a9:dd,IONB000201752-WLAN
#affinity:
#    podAntiAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                    - key: app.kubernetes.io/name
#                      operator: In
#                      values:
#                        - pihole
#              topologyKey: kubernetes.io/hostname
podSecurityContext:
    seccompProfile:
        type: RuntimeDefault
containerSecurityContext:
    privileged: false
    capabilities:
        add:
            - NET_ADMIN
            - SYS_NICE
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydWxlTHpqa0Z1WkFmNzdC
            MHJZSjVEdWRJYUtmTDNEL0ZWRy9SdHZCSm1NCmwzaktzRThHT2VmYksvdWFQaDNv
            NFVpamQ2QUVvSXNCMkR0TXJ0eWpmTzgKLS0tIHlBWGd1cDRxemw5OUozSlZid1pv
            Z3lxYjZXUytWV0ZReitRcWpFZEloU1UKCtpoAnsDviINJLAPxWYSjJZ5VHBasFsW
            6SCaZ2lTxkHuT+LfjNfgMx1blTGX3wFZvDTlwkOzFuVBaKPjWb4YXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNVVZNHhsVXZYdHpCR01S
            RlFnUHk0cVFNWVlwT1RNOXpTWUFna2w2Nm0wCml1d0MwMks5c2FyVitreUp5UHhp
            WnYzMnB3ZWNiQ3VxQklObXNwUnoyMUUKLS0tIGhGOTAzR1I3YlJlNTdpK09oQzdB
            N1NkaE1xaklmamZMeHNDbXhWMXhuaVUKd9Nw1E57WfYk6OkThVeZBM3WyMdl659B
            8NNE8Aiq8GwAoQwGYfqI+fWruJNT9YwGubDcERKTzTzoNc8Qlm5EYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T16:03:46Z"
    mac: ENC[AES256_GCM,data:oMx0Nh5U+kuMlbgoF6Q0tcqoHtDNAwiJAfd6/tiNtkMXw98NPl+WNEw4yVfX4iKB98fmM5U3QQz++2fqIZKk7COgthtCSA9IM/OKrpABr/CeupumlfvAiF3mJpn7J/In9tY6sMdXvwoGC3dNhT3MQUrgEbW3BxZzg7jUu1H73OA=,iv:BCuYAAcy8t3gRzEQvwEvkcSgyWf9s8imM5EZ2Cs7lW8=,tag:2q25V9OREcVelhGiFUgjPg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
