---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-td-sync
  namespace: td-sync
  labels:
    app.kubernetes.io/name: td-sync
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
