apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-grafana
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:AvotzUiOyY6BG0gwUxvK,iv:v3s1XC0d7uNTeyfJveUeKHtFBnrwsMVLq6QCqX54dlQ=,tag:ifV6AyfN+xay+VrwpfZOGQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:C4x6IDz2EKsngqHWOt7Ek6iR3euWWQNF/X+YcfM6sA+YQgkgEuGaQL29V6vQYiNQwS0OmxneUqhjTsXKn09NlYnKHpFzFvehOGpfmw2TGCvTLwBfGn6tf+usBck3fw==,iv:zOO6o2QRBkyLjf3LXTC48XbgQPzPiyEpSSDVlfKsUkM=,tag:vqhK+6ytuTJ6Dt3NkZXepQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:2WQVcYE6fam85ZmTf+0FrNlQ9AWoxynqfo0P7watW40MOOPpc9vK2+R7bLdu30WgKoazG7MEvSDEWOn0J2UNFA==,iv:hbrY5XGl7iq0FKVMRcBKojfIXlfR8v+Za8p/K9yT3uE=,tag:PFWrKznN0H4LhrCh3YBCbA==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:7QMHtMnjDw==,iv:BlBon8+MM5AKC7IJHasz3Efv7nItAzkNzJqzofOHsoE=,tag:ds9Wrdzq9zBxHU1+TVNthg==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:HvKbuQrmM3tqvXcr5/kXyp3OPxhwQA7eCWXnUY1WNBXp+w==,iv:tHZUs0fhAov56g9ofw5pOyTmRPwAOKrkr+wmqhBnWPg=,tag:xxR48/t/gHPQ3N9AXNfRlA==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:iCSmqnI=,iv:R8kTs3JD9ZWXFDJxJOEIeESNjZ1yrJiOH6DZ6yc87pM=,tag:5hkvuDf2RnzOtUsGnOIogA==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:aci6YQ==,iv:Tz8xTlWBmSmHE3rkSfPTybzrBKyNGxmQEO3ascF/unY=,tag:qX8khGPMS1yk/qoGzfNORg==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:eynXfs1+lEETFdgQcxDKHBCiZVmSF8NthvQyFPXmTo5iQrUMAl4iBuhWW4ZaDLuazBlq+F12GOv775/Ve++b3IyDksL1ZUm5fy7S,iv:jH0Pwe13Goc5yN8RdODflQdh1wk6UZljnDtx+w9uBlo=,tag:35RhTxH94/guIOPdywtt/w==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:Hz8vdoxl+Wpu05LxKnVNfeoZ5wlrL6B9wjUp,iv:J5D53Qo8DKsmAjVLO6ozph3YrUCkA1bAcfcRmjUYwew=,tag:TtpOQE31aqOJn5jkj47tDw==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:mE/PzQRkPNO1I+VRCjeyL/Pv,iv:IcmVFO+qLyP5ivPnVMD3KnFklWjPgQiQV29jDClSXrU=,tag:JZtOyLa2it1XYWiBEgkWyw==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:s14j+w==,iv:x6WidCCnvsHdfGYrrzL1EBwyqoTsMjoiUkuSk8b4Pps=,tag:Zd2y7StU1czIn+GRvYOr3A==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:vVfHuh+hGBWuuHJfzjkBjY39X/RliHSmki5oKiIFfRhavqxWUrxDvcH4AjcqzJQthSWChwdL2wsd2sOL/Qwb,iv:viJI0aMB68fyHyy3l9N8UoNaahG1xeDIwkwAdN1jJxE=,tag:zjC7kOQOUf+3bRvcgKlWSw==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtU0wvRlVJVTVnc3hBRWxq
            dXhXQU83bjBNcjcvZllwektmLzN3WWZ6OFh3CnpHVURhZGFUdytpOUoxQWtKYjBM
            cHgzSk1wdno3UDNGMm5KUnpYRzhFVEkKLS0tIDJBb3hLalgwMHNIUUdnOUpEVFRi
            V25ScG5FdFdnSUdxSzBrM3JBeEZUMDgKdfdZVx/bOgKJd2BZolCYmQVPKG1J0fQl
            5RxsoyDVR9h2eunLHmnQUZo1bmlteAEOnVYamx5Q2g6qScgvNja39g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcHQ3VGxnVC8rMEtHUG1H
            R1h6UHdHU3ltdnNoVE9NQmlqOHlKdVdMaHdzCjM0NWNuYWc0UHNKSXpaU1lTd3g2
            eHBJRU9Na1hmbDIyT2JPVklLTFIwWFkKLS0tIDJRSGZYMU9Rd1ZEVVFGQzZUclcy
            UnJmSVBra2hPSVl0ZzBFVUtaR3U5bVEKKTBc6grs8COStWG33OJWbqv89BnP+J7C
            t+b8b3xCKlK0DCaOF8l8qMKzY+bTOMoY5/vdUpfBi8WO9IRcknAJnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T14:05:27Z"
    mac: ENC[AES256_GCM,data:mcKSQl1hjO0h9FYxCWqenUBvRSBU6n5oaQxduJZuShCZ2ICsaIUjchxJcDiU5bKAHDoVCn/sX3Y3St2go7w1zncJb7JtCLWgeBWeCkh55xGU3XqFbBEmgaz9jBiG3s66jcmrWIiLZqXA2CB6+eEJPlLB1lIsU2e5I7OeeXE6njw=,iv:v71J66WcIhwsrQHVEaDMA3C3iuwEPv+bslExH+jCptk=,tag:8gf8u27sWIe3xUErzsIfig==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
