apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-grafana
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:9//MiXdKqZn5wTlvQNwF,iv:M6/bmJC2tuaYzcSB9jPSM1gBvDbSyfZULM6bL9q6M4U=,tag:sIuej43rpIEmVhF6hucU+A==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:VOzoANPoDRi4E1q9pORd+LBbr9K1xYhLyP3IEKOW9JpQlNa0OOihxUMYxcVGdQ21gW0GpTdVCdezwMJEJg==,iv:DxTMhiXh/io/f40cSQyT/FgyFZVXdng9qpgks29ykCM=,tag:q5HqXWJNAKElIGWz/DB4Ew==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:vU5T8+vDUwrTQ6d7B0CEseHQjj/0UOIskLlVR2HUp2ccc6RTeXPTBgcJco8uw2S266jthWwfxbcwtWXO1XUURA==,iv:7Orr1cX1ECB2x2bToS2XZB+WgPNSsRaFaw4qxdTa59k=,tag:B1vVuNoi40KMkhwa+fDtlg==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:obSzaNQJ3w==,iv:g0ro2Y+Jz7sA9N64gB9TalFr3765HnIFV3ay7wYR9b8=,tag:jNob3Fhel8SOIKchovfNLA==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:nZ3HupoTLXAdLFsgs3oSxfXBeUcGQWs9x/dNWAOHMSqnxQ==,iv:IWupo7MDqcO+bQaauGzEUu0bGOZ4EtDwB5rGCrE6YKY=,tag:eq9kX60Eu6Q1ihmV1CTZEA==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:Gi2K9Pc=,iv:a5iTiCD8apvzz3YoiNdy4V7AiumaTS7AjSbFMNqTjRc=,tag:lehqFxZbnPHPLHy8i5vhTQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:mebq7DEwVVGU1QLxbX3FAY2G7aY=,iv:izzHVZr70JR2z4JElj/V+leqMBrRmuPU+fKSWjPnB3w=,tag:o358ugrwtNrxNLZ7Y/hedw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zBpQm7FUTCAyi9m3y+LieJFtRijBrMqevToy/vPmsbIkP+ltyTNujw==,iv:ojTdUSPmNwA4Im7NEOruxtSQvCzcR2pLi2dDyS6Nnd4=,tag:S82R9r6yOtA0xOkNPqWwmA==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:+CwyJQ==,iv:lS0XFlQ6vwDbX24/D5gUFqk3YP+TwdRCDaWeRj0/HhQ=,tag:HwphN9cASNB4//uiAh7w8A==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:LFgumMZUU7lXN31rVnFGgL3tpfd+Qm5jPN6lqMm0vNmf8ffQPYCwvcUZkbY+syAO3fLmsaMdcVAOlVIe6J3tVq1uqtHxFccK1xDe,iv:A0ih2+CC6w5n0mMIzhxaAQyjWr+GNl7YIq3Ph83WVRY=,tag:pbJ82W1M/ukWEjAlcCei0g==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:Ofo08Wz7w3qopcm9UrE1QH7e0fMN036QUuLa,iv:qB/02p4hLE4wLtW+X/A7jayJw32T6NIWWg0vonDzCIY=,tag:2xW+NFQ1SSn6LZx4Q9Z2mA==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:DOlrmKN/n2ww04Z7fehvk8IM,iv:LvInk04gZuiIz+xTYmHGxy8jbb0lxFHUOg0F+5RRl6Y=,tag:Hr7TUSuQNlhkGYOQt8UKxg==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:Cn+ffw==,iv:4L8CWC9NAVwZeK+DFqBlbGAjifK2G/Ob1a5arXfVpYE=,tag:zID7a0DTZRZr77Xc9k1tVg==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:Qpgt1sEPQLVHLJAImfK/d5i1A8BM5P7c0C1mXOtjuO4f+8uVOwkguZCoBnHsvs6x7H7RspAraq8gPNCDzXW1,iv:TTrDRgZot5lxqGI7megOfB3N1Ik5g0DUDFnjbb1n9Po=,tag:miQ7Yn0iYM/3l2Ap9ngBoQ==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCLytqL0VxSkdmNDFzTEtt
            RDMyMTF1ZHpqeXRjWWx4NEZ5bkx3S05CZ2dZCkVHck00OS8rR0FnU3VuR2I3VlRO
            OVkwcFZXNTNPYWZqUWplMTZLQitQUDAKLS0tIG9la1hZWHpTbENLR2FDdTJFOG1y
            aUk4VU1qUVVUMllYbS83ZkY0a0dNNWsKuIXwQ/0LJ4JNqOGFTIprvrKeEJP97QZ3
            HLQ1z6bTGNoYNZstoCUaYrjlsf1mBiVFlBBIc3QHk5k0cerrFYuaLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVakZKOHhyWVgzejlCdVRT
            Qys2eDRkdFNFUVByYTlwMmQxN1FmcHB5bzFJClpIZlBSU2FsbnJxVnN1NThiRHBj
            aXFQZmJkU2ZhT3hMV0MzMFRHcTZ3M3cKLS0tIDNuOVdidmJBV1dlcmwxcUdIUDFF
            YStKaWttU2NTSUNDQU4xL0djR2NPK0kKaWShJV7W3xl2U/7o3Mmlzu4Phwqwh5Gw
            CkSyMNWFknIDl2CiGbARKe++0FkKhm658pz4VBf56uZ4p17c9FMIRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T09:04:41Z"
    mac: ENC[AES256_GCM,data:a0cIsC1fYY/12E0jGfa25qC8d0/WaPq4L+8JxmmFpl1Kv24r0rRerA+UhpQCwFZ+MQVymqL6HvtMz1kbzwmgiWzpP3jwqXW35ksZgERv6soEWUn0T6hrbkR/FTZ9yW/Cr9sDuUEAzyKlrP8Mxnig1vBFGbIrQLL1YKesjpgKTNE=,iv:ivXipjsnlQa4W1g1xDs8aJOUTp9Noshy8t6iYX898mc=,tag:hFMshg7tRq7BQm0+gvkP+Q==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
