apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-grafana
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:QEPtAueIdMctzQgvaSHh,iv:j6WErVTmLuciSmtbQO4BBhSjXpu+2/TN50D3ghXG1MI=,tag:lpZopbFCtY3YGGNdZdEJIw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:OJ5YMUj4ZxLWdBKgiDTsvef01Jy9PTs5XYtDsSTJsze4gvjhiv9YaV7AWidKAi1YeShyZcvLSaQZ1PWmkQ==,iv:2siuGGpVBT1JC4PyiFy6JeUdJlk/Ls+7BbIw81PHwug=,tag:gYsMzwoza6Rh4Hfgv/yQ8A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:5rBtNFpWejNcf6o7ICMcgsIi3pcYFhiNgneSnMioK/jWy5ryRXXhXipK46b3/xDGzhJB57OuQYyYGI+mrGB2Vw==,iv:7NNHPbAmP+Q59rhtHhCBjjZkUWFr8vzHLQDHAkaqIEE=,tag:Hy+z/gvz7sPBU5dDSWDs1A==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:9p2Ioh3r8Q==,iv:an5p0QsgSGy5vlpPRcyp0wFqdnplIPAZP/84FVroVtU=,tag:G1U5Gh7lSAXRrCIEB4FoDQ==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:Vs9k3ZXNm+yTWRrSXA==,iv:chgc+AONIrQ4pFfCTRR4+RYMkY6rdNts9Suy5wSjblI=,tag:FfabPG8Ms6prsvMeewpHTA==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:bMq9Tz4=,iv:tF1/WUZ3C4jzs87oDBDcsbc+mSO81LuWjU2m1sx/UiM=,tag:XN7NmfhzB35S+twUAqGznw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gnQSNCGo84RJqopfMmexHwVGB84=,iv:PNSeoIPrATRqJJQSJ71nUI1AG+nUKKCfz1tXn++SzBA=,tag:AiFzRoSL/SNzBvGA8yM1Xg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:395Kx4gxl/HlyiD2uPZy56Gl8X5Gee/dz5YO8SKNzQtE10ueYvnLhg==,iv:cY2rKQRi8Q/QMaaUlwyHsKZagQ4GybfyZx55ImL07FY=,tag:sigVss7XDZ3w0ij4mrxDHw==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:6OUgJQ==,iv:I98Xr+NprhPfO5wo3Yff4vzfFGRcyiDrtmbV18rZkJo=,tag:GMWqpCjG38FyYt8KilX3kA==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:UQSFeKl/T2ripofLZTYXJIAXtVZ/FyYIXHWEyngv65PwhVyk8l7CMSw5ZJMXsWQbxcw4dgeYnlTFWhccXw+cUeJybJCjFWwq8VQU,iv:k5MgZLl4yKGVq0uNTPs0Lg5JZcoKgTUs6a5ije44Xf8=,tag:p60EXPSSkb+eB3U0fxGwiQ==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:aBg2NNaV9DzSifjtjDXCT9FDAHbocOhD73SD,iv:hDRsj1zFvy5ZqoJFVvOJl7rTcur4RWRPyA9ONt3KB9M=,tag:cSsCyW7uartZrkudUkpHvA==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:7NKmNOFN+ZAVFk+BMKR0qj9y,iv:EwHIh9VgXFdbgNco8hPDJDUOQaZC4PVTyEpc8RKYBhQ=,tag:AolRsTpMl0vXr11aIr4Gdg==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:kSsZNg==,iv:/1Z7vBhURMVLIBK0PDMMsaC5EKCD+JT3PI/bbbd9CYk=,tag:gDQwp7zlgpqiC2lVXDzJ9Q==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:EhXj1QyrizJGFIPVWHkB+ezGWUG+TESJcx75SdvpAmskaWUr/7OseotTG7Q3Yi+EfN8jFS1RMyMm24tiYJQR,iv:4NDSoAPHf6y2IH6tTvG+gNk15P+/5FnAaVPbpHxO9k8=,tag:zlduQV8h9u51TAyK3p/wMA==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweEljeFhvQTZ4bFgxY1Bk
            S3FVdDJ5d0xyMUtLZmNzajB5aUVkTTVKOWcwCjVSSmkwc2d1OVExRkhzakdJRFhM
            YUdKV2drNzkvNi9laFREUTlzdExNRkUKLS0tIG56RjVyU3AvUC9RTXlIaGMwYW93
            Tnp1anB0QU5Ib2pvaDlVY1hGN2MxZTAKnTw8LiDZS7VqTY89eINlcnfSFeRcLe7n
            cE4YXBju7ljm9s9PC00XV1nrH1uMYUsq+68oT6VE3PlyjptneFAytQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQmdvbGFTZ1ovOEEvTWxH
            OEIyMXg1bURvZ2V4WUxaNDk5T0hCcnVzSUVVCktKVm5LMlNyRDZvakxSL2dHUVVO
            QmN4L0xrdmIrYVFVVFZpWkhCNFlMM0kKLS0tIGVsK3c1RElEOFNLVXN3djd1clJ0
            TTRWOXMxanZoQXpsUk5WZEtNK3UyeUUKS35BhiSoFNEP75V2XBcLYRCKIW8FDdBC
            vXNSA9ono4qP9+3Sf59zRZUFBHMWOivX0kpyNlYYoym25hoT1jwsZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T08:47:33Z"
    mac: ENC[AES256_GCM,data:DwAIqhmVTriXYJM/jam0f8trPZ98kJi5WHbroZH2i35nCOwF24+hLFHQiuzzCr3wqdY8d2eQUMmu+59ZVUOZwVpYVu/1t9xztred1ZtQMv8OUzn12eBgZ+Trtq3U/h36UvfcKXcpWHQRG1a/Z3BdBxzQkF7k/zIIZs35VV49Z4A=,iv:AqtnHs7DrV/rm4YXV22T5vkicZe1nEDr5IobYD7Iwyg=,tag:RD3SG7anyowfqa55PevPdQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
