prometheusOperator:
    revisionHistoryLimit: 2
alertmanager:
    enabled: true
    ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web239,websecure239
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        hosts:
            - ENC[AES256_GCM,data:nmUKTqEzT/3lH8wvhaubQ0RYXzPbppBuTKC4ENwvtWXbOQ==,iv:73Sdd+gAcpT9GcueXQTnjt+093iMBaRG0349hNjMxac=,tag:6LpSW5ufbi+dGdK1S199QQ==,type:str]
        tls:
            - secretName: wildcard-cloudflare-production-02
              hosts:
                - ENC[AES256_GCM,data:faMANfoelVsBE+V2ec6LL8bc4HDqpiGo2feY6oPgxxL7YQ==,iv:93/hZbTDJro3AgsNMGm6sEjC8EujAHTaKQ9XJFUGdAk=,tag:Y2NF16nbi/4PTMh3HvA+Ag==,type:str]
    alertmanagerSpec:
        # PVC configuration
        storage:
            volumeClaimTemplate:
                spec:
                    storageClassName: longhorn
                    accessModes:
                        - ReadWriteOnce
                    resources:
                        requests:
                            storage: 1Gi
    config:
        global:
            resolve_timeout: 5m
        inhibit_rules:
            - source_matchers:
                - severity = critical
              target_matchers:
                - severity =~ warning|info
              equal:
                - namespace
                - alertname
            - source_matchers:
                - severity = warning
              target_matchers:
                - severity = info
              equal:
                - namespace
                - alertname
            - source_matchers:
                - alertname = InfoInhibitor
              target_matchers:
                - severity = info
              equal:
                - namespace
            - target_matchers:
                - alertname = InfoInhibitor
        route:
            group_by:
                - namespace
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 1h
            receiver: ntfy
            routes:
                - receiver: "null"
                  matchers:
                    - alertname = "InfoInhibitor"
                - receiver: claude-analyzer
                  matchers:
                    - severity =~ "warning|critical"
                  continue: true
                - receiver: claude-analyzer
                  matchers:
                    - alertname = "CPUThrottlingHigh"
                  continue: true
                - receiver: ntfy
                  repeat_interval: 6h
                  matchers:
                    - alertname = "Watchdog"
        receivers:
            - name: "null"
            - name: claude-analyzer
              webhook_configs:
                - url: ENC[AES256_GCM,data:q4HlZNPHBZ6rzVbdN5iYRMU9LoA+hg9b7pzJjbK3Tubahr+lWJbuIRCs4lq6nXy8CUHS6vfRTiOLWvO3l3K0jotlIPCFRQ==,iv:4cW/9dga177dYhk2BpWXzyTr74Trw8Ks0K2JMvW2Ees=,tag:WQ7RtWtcqepkNHOmy++xhQ==,type:str]
                  send_resolved: false
                  http_config:
                    authorization:
                        type: Bearers
                        credentials: ENC[AES256_GCM,data:DydvHPIEakwuJBfuKo0YiJJI5+WQlf/0KN6Ads0I5FOalIBGjJvg3jrQ8/mOGVOKVeLK+bxvEMyE3j1++NFouw==,iv:EogGAtoyRp4H2w8v1WIR3/J9Lpdvqj17CvHWOJlwLqQ=,tag:9XecSrubB7ywrkZ02noLeA==,type:str]
            - name: ntfy
              webhook_configs:
                - url: ENC[AES256_GCM,data:Yx2GQaeNqqFtF3SCTxRhNBntka3MbmXPxK/2ZQx61T7ySbN2DD81CWXTvZR93alNa4WRMHZcjG7KDA==,iv:tYPT/l6p+EtxSYz9SK90fhJaJ3+OXOvG943FB8WDwx8=,tag:Va3HYtXMpAn8kifhz7/RPQ==,type:str]
                  http_config:
                    basic_auth:
                        username: ENC[AES256_GCM,data:XxO81OJ3ydOEdU6aF/xAE+vQoWaOXyTn,iv:r3Ni5EzD+uQbTMG105+a8YEggzJjEldYqpwW9eEMVi8=,tag:/xVou7+n6lUA7QUA80o8lw==,type:str]
                        password: ENC[AES256_GCM,data:nvlLwoJh6jPbLhj48jl7w4iWGnpIvnGa,iv:25HmtwI8oJe0rJDRADcQTqc2+NexNUN2U15Awac/xEM=,tag:s6asH6IzCd9cpo1XaBhWSg==,type:str]
        templates:
            - /etc/alertmanager/config/*.tmpl
prometheus:
    prometheusSpec:
        retention: 45d
        retentionSize: 25GB
        # By default, Prometheus only discovers PodMonitors and ServiceMonitors within its namespace.
        # Settings this to false disables the behaviour.
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        #containers:
        #  - name: prometheus
        #    startupProbe:
        #      failureThreshold: 500
        # Resources request and limits
        resources:
            requests:
                cpu: 500m
                memory: 2Gi
            limits:
                cpu: 1000m
                memory: 6Gi
        # PVC configuration
        storageSpec:
            volumeClaimTemplate:
                spec:
                    storageClassName: longhorn
                    accessModes:
                        - ReadWriteOnce
                    resources:
                        requests:
                            storage: 35Gi
# In K3S, these services are not deployed as pods but are part of the k3s binary
# Do not use the vip because there are node specific metrics
kubeEtcd:
    enabled: true
    endpoints:
        - 192.168.1.21
        - 192.168.1.22
        - 192.168.1.23
kubeControllerManager:
    enabled: true
    endpoints:
        - 192.168.1.21
        - 192.168.1.22
        - 192.168.1.23
    service:
        enabled: true
        port: 10257
        targetPort: 10257
    serviceMonitor:
        enabled: true
        https: true
        insecureSkipVerify: true
kubeScheduler:
    enabled: true
    endpoints:
        - 192.168.1.21
        - 192.168.1.22
        - 192.168.1.23
    service:
        enabled: true
        port: 10259
        targetPort: 10259
    serviceMonitor:
        enabled: true
        https: true
        insecureSkipVerify: true
kubeProxy:
    enabled: false
    endpoints:
        - 192.168.1.21
        - 192.168.1.22
        - 192.168.1.23
    service:
        enabled: true
        port: 10249
        targetPort: 10249
grafana:
    revisionHistoryLimit: 2
    assertNoLeakedSecrets: false
    deploymentStrategy:
        type: Recreate
    # Admin user password
    adminPassword: ENC[AES256_GCM,data:S7Cf1U/hXx55c/jyOOR4yN6f6IAKqvyF0q6p4QALqLw=,iv:JTfoT3L2vBoEL7GeTIA7JeKE2AYUO5l6A6emvhKeNG8=,tag:0b+izyEzl2BbUKKbnkb69A==,type:str]
    sidecar:
        dashboards:
            provider:
                allowUiUpdates: true
        resources:
            limits:
                #cpu: 1000m
                memory: 1000Mi
            requests:
                cpu: 50m
                memory: 50Mi
    initChownData:
        resources:
            limits:
                #cpu: 1000m
                memory: 1000Mi
            requests:
                cpu: 50m
                memory: 50Mi
    downloadDashboards:
        resources:
            limits:
                #cpu: 1000m
                memory: 1000Mi
            requests:
                cpu: 50m
                memory: 50Mi
    persistence:
        enabled: true
        type: pvc
        existingClaim: longhorn-pvc-grafana
    # List of grafana plugins to be installed
    plugins:
        - grafana-piechart-panel
        #- "https://github.com/Checkmk/grafana-checkmk-datasource/releases/download/v3.3.0/tribe-29-checkmk-datasource-3.3.0.zip"
        - grafana-worldmap-panel
        - sni-thruk-datasource
    # ServiceMonitor label and job relabel
    #serviceMonitor:
    #  labels:
    #    release: kube-prometheus-stack
    #  relabelings:
    #    # Replace job value
    #    - sourceLabels:
    #        - __address__
    #      action: replace
    #      targetLabel: job
    #      replacement: grafana
    datasources:
        datasources.yaml:
            apiVersion: 1
            datasources:
                - name: Loki
                  type: loki
                  access: proxy
                  basicAuth: false
                  url: ENC[AES256_GCM,data:MEV3OmaRcK+UAAMBQGCilLAvo3AiUev8fgKf6Zshd8dsVg==,iv:fDPIIN9Cs78Fla2kuOOQLMkzTlV0dE66J2MckB/z5yM=,tag:r7Ofh6K3el39d26c0sbsYw==,type:str]
                  jsonData:
                    maxLines: 1000
    # Required for the dashboards configuration
    dashboardProviders:
        dashboardproviders.yaml:
            apiVersion: 1
            providers:
                - name: default
                  orgId: 1
                  folder: null
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/default
    dashboards:
        default:
            # https://grafana.com/grafana/dashboards/13639-logs-app/
            #logs-app:
            #  gnetId: 13639
            #  revison: 2
            #  datasource: Loki
            # https://grafana.com/grafana/dashboards/13332-kube-state-metrics-v2/
            #kube-state-metrics-v2:
            #  gnetId: 13332
            #  revison: 12
            #  datasource: Prometheus
            # https://grafana.com/grafana/dashboards/15757-kubernetes-views-global/
            kubernetes-views-global:
                gnetId: 15760
                revison: 32
                datasource: Prometheus
            # https://grafana.com/grafana/dashboards/15760-kubernetes-views-pods/
            kubernetes-views-pods:
                gnetId: 15757
                revison: 42
                datasource: Prometheus
            # https://grafana.com/grafana/dashboards/15759-kubernetes-views-nodes/
            kubernetes-views-nodes:
                gnetId: 15759
                revison: 32
                datasource: Prometheus
            # https://grafana.com/grafana/dashboards/15758-kubernetes-views-namespaces/
            kubernetes-views-namespaces:
                gnetId: 15758
                revison: 39
                datasource: Prometheus
                # https://grafana.com/grafana/dashboards/17882-kubernetes-event-exporter/
                #kubernetes-event-exporter:
                #  gnetId: 17882
                #  revison: 2
                #  datasource: null
                # https://grafana.com/grafana/dashboards/10176-pi-hole-exporter/
                #pihole-exporter:
                #  gnetId: 10176
                #  revison: 3
                #  datasource: Prometheus
    resources:
        requests:
            cpu: "1"
            memory: 1Gi
        limits:
            cpu: "4"
            memory: 2Gi
    grafana.ini:
        analytics:
            reporting_enabled: false
            check_for_updates: false
        auth:
            oauth_allow_insecure_email_lookup: true
            disable_login_form: true
        server:
            root_url: ENC[AES256_GCM,data:vA1Ij64CEjTIk7Ay6r0Bu21/JAcbW/g/s6Vx3qFuzdd6H+0xtg==,iv:fjKzx5zT2upUtDcPL81BRHEvfEuE17gKAWWZP6Y4w0c=,tag:DA9bXUVgDedGAFjJ8eKk3Q==,type:str]
        auth.generic_oauth:
            enabled: true
            name: Authelia
            icon: signin
            client_id: grafana
            client_secret: ENC[AES256_GCM,data:sIooYJfp5ZijMbhcSxa82StLdY+l+h5J2yg1CgDW4hs=,iv:0Euy8Sfp4WPVW+i+g+zBFlKrbHLHeCWpgvyOJR/D6xA=,tag:effSNgnNMQp/QRuted8RzQ==,type:str]
            scopes: openid profile email groups
            empty_scopes: false
            auth_url: ENC[AES256_GCM,data:Ja58cRuumRPhhcqZT9g3R6CUWyhalJeIY1/5gpkOElDNYWqL+N8QxZKuhTPBJFO+MYQ6IQ==,iv:qj/mIohcmnHcaG9/SLLORwc6ka4jn3B01iTeghfLngY=,tag:Q9VyREjj/DBktcp35I0pAA==,type:str]
            token_url: https://auth.k8s.neese-web.de/api/oidc/token
            api_url: ENC[AES256_GCM,data:q8miHqBhy+2VD8wPEsU3p0InoQSC+HR/97HZFSHmfzszNajsXeBHBIc8W2333SA=,iv:sGZyebCssvGuAITpgTIHUtwYNnmE7lvt6Vvgw/mecYA=,tag:F5PgIYkFpPK0K+FHFi8uNg==,type:str]
            login_attribute_path: preferred_username
            groups_attribute_path: groups
            role_attribute_path: contains(groups[*], 'GrafanaAdmin') && 'GrafanaAdmin' || contains(groups[*], 'admin') && 'Admin' || contains(groups[*], 'editor') && 'Editor' || contains(groups[*], 'viewer') && 'Viewer'
            role_attribute_strict: true
            name_attribute_path: name
            use_pkce: true
            tls_skip_verify_insecure: true
            allow_assign_grafana_admin: true
        auth.proxy:
            enabled: false
            header_name: Remote-User
            header_property: username
            auto_sign_up: true
            headers: Groups:Remote-Group
            enable_login_token: false
prometheus-node-exporter:
    resources:
        limits:
            cpu: 500m
            memory: 100Mi
        requests:
            cpu: 100m
            memory: 50Mi
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU0VWZFNoRlV2ZExqOXFq
            QjQydkpOOHFpbjY2VXZpdWtGRHUyL0drTDI4CmU0Wm5JOThDUk1PZlNnejRZeEgx
            ZEN3MnhyRjd1NmdGcnNTWFJYd0l3dW8KLS0tIEQ1S2VmVDl5Zkx1S0Fqc2RmS3Nl
            TWJ0Vllzam5BUUFuSEx0dzhvZkJRT3cKzrlCncC4PXZUW5urH1xsrZsE6deMtzE6
            ww7qsDComEBvhn/h7+1ucK4K0+WNcCkUytf8NWZMtLpcRTeiL9P+/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaGIzZ3ZSZ3p6UExDSHlO
            VGV3UlVyeGw4QVgrRmp4Q1pwQ1VVdWtrSVZVCnlReG52NURTdndnK0M0WFRzaVg3
            UG9ncXpHNExqNXpDTXdWdjdJM1BkdGsKLS0tIE9sME9EYTZDZ2R1cDlRRThxMDdS
            TFBsR0xGakYrWFkreklhTEpXempwVE0KTLR+E61eMNJ6slximHjDi4SDl24EhFir
            lkhoXoMBjkRzYQWgXMP9d7LsHE5eEgtNHUvR6xG2LoxgGNVlWXpF8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T21:22:43Z"
    mac: ENC[AES256_GCM,data:xBoLS9IVFyFuu3I1xGMDMNtG/bdWSFx2VQo+KbGh/VDXzdsQv9KJqzcUs784MbyaYFqGE8OA35f375D2jje0IK3sZSxM5X3ryN3ympZQd1oZMJFGN/xWSpe9FFYYSA0/yeiIahNu262AzURZp5AJQpXSnJporTHHWaHWwtvkGkQ=,iv:8J4/fTPIPa934HawiD24vI7ZeLA+28r/L9OngiMDHPE=,tag:lCc9DyCr6axneyrZjdWbAw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
