apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-emby
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:sZipgNrEPsXR/RCkubmZT1XmQQ==,iv:Bhp9FyFTSP5LjN1DLF7DY0uo2LE9KQj0HRtYfaP7EVM=,tag:d+Hrm94OqKdhpM4Petlqqg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:mJe7iZ9ITNArQ/GyXQJJXDbPYLa6uCjFEmBumOW7dTlv8Pzu3b0OcZ7o9rEX0Nhay39eb3TBI6h/Khdr7Q==,iv:XwDzF8wJ7MPQj0zexWm7aI8fsiMBCE1QOAU4RP4t2Yg=,tag:1DqwkIoq6XArqM39d9wjLA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Dr4T8tAxTrijtxDzwPF9uuG5DQJHhJA1Jl5YEOdb260hgP6lH1SpaAxWCUc7z4ufUu+7VXTFEtO2l2Vg8PzIYA==,iv:n5BPSSvZn6+7caZuXazw316aXIeuwq3h1asUHkwByY4=,tag:FzC0FG7sGYygUUDxrtp5sA==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:cWpgcA==,iv:9NCIesBEPdJc6V8vudQNFRnUssJ4mCs9hwND83ao9SM=,tag:Zug2Wu/UXR3oPPBPewKTMw==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:+HdOtEFvTYpuikciLfRmL1DZ47w38de0GU50Vh0NtCVb5fki7w==,iv:kCuzepYsQpsaHPehvMJdFFMYvbxfd6VzHYB7FNtK+/4=,tag:KP2oQnHTmFoJNfqvCTabTw==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:SuVafTg=,iv:bIqIcCF8g6aK1+5vLrxgFduffyp5fH8EwaJatjIk6bQ=,tag:AS0qOKtyf3jq9qxoW2qh/w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wMNhBB4rzgTiU1py+UKCb+GOtuA=,iv:Yz0MCpwqeUb2DabMLd8M0gss3qIq6b7tOJR6QCm6a4Q=,tag:1RX+8DTPPL/79vT9XDJq0g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:c0bNAYWONzmX3wJUwX2rDA9hX++QS37Jm6B5o87awxkJxvDAF5tldw==,iv:QwLWl++0+pc4ySZ9yCCon4wpKmqHOVnmeCEzVyvLD6E=,tag:ajnYCsNM7pEZXh0+/9Rmbw==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:puIP4w==,iv:w37GAZQephutXRVOv2g6hu8zjM+zu0LmV8l14MB+XZc=,tag:4NZkhBUf6GkqenkU/8PMnA==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:a7Ozk4RuYy0OxwBAeGBZxBL60kMP+eZtcjO5VxeqElTdeRFU7m4FuNqNJ8fQdMjjzlEn67iN9QnSuAXrhNs6fuDZ9Tddi1V8YoVs,iv:dTprpt6soqx0nOkl94eIo64gbx2Wn+jpFgHWxP6mUJ8=,tag:hi7ueCu3b3DGdHxCVWrM2Q==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:qvjsvxfRgXYRF5g1w1f39ua4fOtC4MQX1CWM,iv:qVWA3LT+giPm7RSQzb23MKwAT6Qtv0ieu66l2MO/y+Q=,tag:fmq3esasIrOpoqZ+65u/Ag==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:eJK/PMpznDd/T6l938upruUb,iv:Ji9P3opoZ+c/VQ8ybY9MvH5AeCZsDitkU6t5NUF7ZSs=,tag:1ZRUbbDGa3SFfmnQ/PT8mQ==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:zQfgDA==,iv:KRikTpfAUWzf2dZIV/yhqpIWjiThEMxllQIxxa1P1zo=,tag:ruDKLyE/ytzwYlHFD7viKg==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:PQBovrv73Jtc0QdJ7Wz5cUx7G/U2Py1oodUdnzXBBOTTS4/iQzq+o2E00gMIAvUr7s5WPGYt/7NfHn741WDT,iv:iRcnqVVtvBvDiV/rMA0zl18r35zFiZt3wPpjRJ5Y5io=,tag:1rM19By7CnSRiXM+60egng==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTU82U21zQWx4alRaUWtI
            clA5OGI4M29ERDVxOHNzU1c1Y2ZjWGRRaDFnCnIrWTJNNzV4TllKN0hEN0N2RVBK
            c0M5R3RyTzZtOUxpZUh0SC9pRzFSbUkKLS0tIFY3WFVDSjd6SysxcU5mVWIrRzFL
            VGY1eHgxamRZd0dxMkhRNkwyUzA1Y0EKUBwKwePtLxrAwSHzvv2aMh8OPHo8a5Jl
            AznG5875BejgkgOZlpTU1zn+MMqTewDwWHZO2n25dHNEzDRmDofhGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOFBPdjUyZ3FucXZib1BH
            S0xuWitSYTBLaVphcjVNTURWaWRyRlJFRjM0CkQ2TDNLVS9kSkF5Tk9IY241eHYv
            YmZ2L2pYeG9OcjMweEs0SEdoeDlpMHcKLS0tIDJ0MlNoc1duRXAyMG1RSFFFak0w
            K0Y1L2wyMVBVOTJybFRCYzNuTzd5dVEKahEit3EFjtq+QC1rOB0juAcLayckmznA
            RFAg+tB79TE6l6lItlB28EXO/g74YOXkIksG2gNnZ9gIsFdGVOdljQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T09:52:48Z"
    mac: ENC[AES256_GCM,data:kK2Irqqou9//cWJA7K+dVIUbyr31dq9/mF3+GTDosCfcxQAEvKKPz5PChx4DJa9dEXM2Md3dW5KAKa0RbmRwwLI5+vlqTxvF0bHcC7+4/IIj5o4zdi5newrnNP427zB+55p/mwXNsCGIKZTRDaNdIRmH8ztOYy0N8yd9iXtaWT0=,iv:1N9EkkTpAOXqkiZjJNymZcDBK5pRiOJQn0za7Bs8uL4=,tag:uoaQAzczefwIWhT+NkJ38Q==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
