apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-emby
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:ntcHIxhnNNQrMbrScnQNsQIB4Q==,iv:4M253wCl0QUL7+qE81Bu/c/wnq53rDBy+Yen03zweBM=,tag:QG5LujCiv9ge39mX2H5FHA==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:5DQHzVTL8c20L12jHiHnf3RQJKI/67W8f7FDt+N3ObFJC+O44Xi5tbwy9zL6zUcfKK52ue+nxhv9ANnn2yD6RZyMPSgURSZKshVKNwmfHmGtZPQWZ1PGqMSzNZtXNg==,iv:GjviVVwgeor1D139CYHG+2IYuy79nbXuGCIpzjqqAq4=,tag:83sKcBn7u1exr8yIvMFr0A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:wpTWurL4ztrC4CRIOMV45zODH3YT/31rfjKugFTMStOTkX6oNImiuqF28uGLLBrdxlmi60V8DQMTDW4mmrLweA==,iv:Pt9t7WGh6zXY2Jzvhjjpi8a15v/xuHP6fYPfTg/69IM=,tag:TuexZfvf0N5jDnyGHQVn3A==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:B1zsgA==,iv:9KOyQvN6DGuoKkfmH173ZOF6Ht78tYyccV0bsugRYvQ=,tag:fk0sxHXJ+O1/nEFesMPJSQ==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:Bxzfc2x+vOs2lxNYXpLNYupvss1Ij4ga7VqnwooIF9quvAWKxQ==,iv:RHa1/LzqjdkafxzunxhpWKigLUlgctYlgoKE/NoVLG8=,tag:QYi8HdtbdjWb4kxPmo8VuA==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:l/IIwys=,iv:jSIf/XwDNd4i/pRCR1E9FEnPL/wZ1/Fgv10g6zdvW7k=,tag:ji/XuDdsgmzhTmiH4676pQ==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:fSGz3g==,iv:AJnUQSXdikd1KxuCoeb483IyEBuy2W9Y1zvkhbcXGl4=,tag:dP146hfA/T9tjpW/l5sAGg==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:0dDOzSWEaEa2p/Q3oBILylJJgMbzNPtNPq3dtdIYB91+YGA0kWwgXOhCjAOjOG4bjWnUS+r4DjSrZV+89QE4+abUMW/0Egqa91k/,iv:0a3eEJ3MjK/fZviIgSLh/gF629miUYmXXtVZDX91iN8=,tag:a+gD49QvThwo9a+2Sgq/YQ==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:0AGIsO2ReKQXyhgrX/mXYWS8aK/T71rt74Go,iv:Ff64xo9/8nprjmlZ+nUUri73W5+0LMBe/XfHr2fThPs=,tag:4vby1vyPCC5QPBNPDwk7YA==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:+H7Uk3Ec9OxnfNMD8pVJ/vg6,iv:Syjrod+R54VrmcO7nhvxF/iENLDHHUEPaM0r5DeU528=,tag:RGbAoJE1RXWzNsP8TmSQPQ==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:PbPmOQ==,iv:o1m52PzI3RYFdB5YtetVKRmNnwn2bUVKISGQtDLjqdA=,tag:eGyrPPNgEZi+htm3XscMrg==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:1er5jSCGBoekefl/8CYZJsFp4G8AdfpMvMro3YHealcqNYiae8CcOQn3Xx04UZJyogVLz9SFLONN6EwBNgE/,iv:6ZEz715pI+zdebUMgfbH3GCE2tCHPuy/i1PvJGjFrWM=,tag:dIWetussvZpnVADxTJinUQ==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNUlsRVl5M2VQZWRzRFJL
            MCtmMVBhWGRvRlhtOEhHekpzbkQ4RW1YcjBnClZHc1ZPWWM2VUVLYXdTK3R3VS84
            WDdQSWJVaGRaWDVzZ3ZmZlNGMGEzZVkKLS0tIFFIZ1ZwRnJJb3I3OUZJbElVWlJO
            RmNBSWFURG9BZVNrOXVvSW9Dem5WTGMKU1sdwd20RYzD4gDtJf1rizRK1dfanHt5
            SZvwhs1SZ06F5XUG1BF5CN92F9aZ6J64qORmgVVoZVBy8vopGVd7aA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVFJSeFJ0MFRtZ1F1ajRz
            bFFHTjVnREtubFJISTErRjlYendGTlRFZ25RCkZwMXM2WFlybXBMajFTbVBRbDZX
            WU5iTGFLd0tjM01zaUIzb2R3eG95WlkKLS0tIGgwSElmS3NibzdiMmJKZnFWeUVy
            MFZmbWJOaVZMWVc3WFRTUkJsRWZLalkKwHPn1RUNBKB9AkD+etK9EsTCBr9eMlPf
            nmwfb/HuVo8sIocwlOCAsc+GzfPtNTO9Qq9rMXN/GSMY+p4qlurrxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T14:05:27Z"
    mac: ENC[AES256_GCM,data:c3q2x6kqWo8zCYdJSKaEOEccx5diTmLOOZd7cp4IaG6N3LoH4wVnjGvdFs+Rm/dBDyEVeBjlK0Gncnwfltuf088k9vBhtfmOKJJYejcc6FxkPHdGoCA+PlYGMmx+3c/RlfnJAWoTHr6U3whX1QTc8fwomwkvZz6yiIBSWpLvKHI=,iv:gcN3+z3JCDIoubpCzhvWjROlg0TrgwPqBk7RHMzXw/0=,tag:uSKbElIHYTlj0rfX9B7wIw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
