apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-emby
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:fQepERCrp5bW2U3Ulp7ZMoZwzQ==,iv:M5D5cIx2XZCQSbNbn+xB728JpaW5PTrOEl207w9SSrY=,tag:wvTgoicQTUtHaEfpbKB1IA==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Uohr6D/Eg2tj9oWTViHElPXI1hjvVXEPbb0FA4RRHR6+DwZohoNMc36qbnRa7h2kpwkhVBKho9VfH6pJJ0auxZqYTgO6APisBNDpa878XUlYR/EhYx87LDA1qyqKTQ==,iv:m0p4r7CzizQHjqpCqbKi8Ru6TwprrpqYEm2JWnDP4ak=,tag:zp7eO119U8CRBVS5w6zRgw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:BEg1SV0SUSzfbUicvInzKZ2fMDTaSo7cWszOQ/OQDV520WrnIhsgOsx8mrzVsIJr59ZjLZ+v/uFxUK1Ji4ppVQ==,iv:Ny9IlPAHNdOLYTC+ys9LoBM4oaz6xaT0jkR3CYislRM=,tag:Z3E+TZJwImMxqFwTqvL2yw==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:5xnkpw==,iv:qQYhijSEdrAmqKiYa6jTsoGPU7k/t3diCGAgbfRyoq0=,tag:2e+5yhoYE+Na+1gg0xIidw==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:GNxffNdZ0gFvzM88cgRFMnLmPL/DPP4jlQX5kp19r6n44S8NyQ==,iv:DPQ0E65PbHS0B1vaH20qCcC4HKFJykL+/y/hYIu6E8Y=,tag:1Quc1iz75J82VhreSYZhLQ==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:CHhZnQE=,iv:6zP8rzDulqGP4g3+GohDVowp+7vp0/c19lcL89Paowc=,tag:yF1NOhgX7V5j+Wl1676HJw==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:6tSs9Q==,iv:exFRQN1uiZZctrn3BzKx3wbKXOSUT9E7xUiopyf2u5s=,tag:r0C6KO8j3SufHmgTK46Xrg==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:d/pXgkJ+OqxxmCE9907g58v53SPnWtler6+VhuQu5yZ+AdpxZGqpZqLSpgrm1x4xHQQ81yS4riziuebWbrKQuBZXlgY3LaXKeR1T,iv:B/bgu4XG/y4zYORfvyIy40Fc19WEiUJ8mHdHJh5GL+M=,tag:u4r3EgUaU7mEfFpQO6cVdw==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:F2pfNPAS8G5DlR6j+9nzjf0XWdTQSM2y104p,iv:YfNLuAW5KeaxJ2zBLUx7eXR5ZL3tYxJQHsge8DJMylE=,tag:NRKOwRHUJnMGcbm+0VkT4A==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:3LU5p32x9hwF6lO2HhZLyCEG,iv:yBuYUTCMlo0B/IK/Mip3xWzGkfEvAFy87gcmaMTLAC0=,tag:gnVtZZhHEcwaO6hx6AWABQ==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:SCNuQA==,iv:PIqa8x5kCYQ0SNSC/Q6pfXkkXLCqLkGwwrg3NuGY8IQ=,tag:fxETNSODlBMNqulXfujhUQ==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:xFJckMgBS30YE6VobEVm+yDSxcySamfFveJy1l/yTHCeJDSHauK0ofcNl9VJfvTf6HAMU/cHap7nKEgfh2qI,iv:VPRH0r71XcXmYiZx4BRQOApbeqQU+1m5mNvEozilAK0=,tag:9w5oLDYDIZ70573FUjTy6A==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bGt1ZzlrMjVHNTlHbG84
            SDAxdVhrVEdzTy9aZGJBUHRUQlVDYTl4RGxZCnZSWTVhcGdoK21XeFc2YUNwNkZr
            RHRrTWhzaURTL2Z1TGJUUTNIbVhiaXMKLS0tIEhIS1JqRjNnNVVrWENLZzlwNk1i
            MzZvSEpjdXNaeFVQVExEZ3JLWTZrS2MKV8AeQQTtyZwSCsQ+C21vpoUYvIRab0zm
            x9WRtBkZDGVLWMKDcV2KNog2fR/eoCCCIJ2FdZe8Efo4GNIyqjomZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSGtYa1I1SStFK3VEQjlL
            RWZMdU9mTmFkR3pmQWtDNnM2L3p0TUFMUnpZCmRVYUtHZmd3bTdYaGMwdkRTMFd5
            Yk9lM25CeDA5bVQ4WFlZb2JpcUMvVU0KLS0tIDJPZC8yM0k5anlsaUw3c0NFSW1U
            VnczQXFJcVBSaW5YZWhwUm0vL1N3NTAK+FOvJZ2Fu+pG3ellfw2o49lguoDOW4q0
            X1d5hYA7s8YSSNSVFYBzgyS01RqJcI5UmLhxGWLXPBCY2x2/Ybx3pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T18:39:40Z"
    mac: ENC[AES256_GCM,data:D0rkufIBxb05kItDM/MXqstUvd8zVge5tle0T9dwwcCWq29bGDkd+mBp427TXXflMn2zf9iMGoojZwDB4/5Sus0IHic6EM3ZUSPa7aLPNQOckVcAa9qghvHP7aizOVSNN5sSLvuV5+2FMNCvIqrNhE8VlVqog2iNtF9ofngdnd0=,iv:xtT7OppuZW00GSdVIMI8dXh34LRUb+7dZJLhrJCMHVA=,tag:UFn2GT1f/ISwlp3Un9SasA==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
