##
pod:
    kind: Deployment
    revisionHistoryLimit: 2
    replicas: 2
    resources:
        requests:
            cpu: 50m
            memory: 96Mi
ingress:
    enabled: true
    className: traefik
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
    certManager: false
    traefikCRD:
        enabled: true
        disableIngressRoute: true
    tls:
        enabled: true
        secret: ENC[AES256_GCM,data:uv7RSytKxK3wic9HO0aJY7Cg0WXgH/KKTTkbFUfMpENf,iv:zrQQtgx+wbGaTY5Ifj82WDxxlXGimB4NzeIS+Za8LH8=,tag:CuIvpDq/8GrZjqHjtXUgmA==,type:str]
configMap:
    #log:
    #    level: debug
    server:
        endpoints:
            authz:
                auth-request:
                    implementation: AuthRequest
                ext-authz:
                    implementation: ExtAuthz
                forward-auth:
                    implementation: ForwardAuth
                    authn_strategies:
                        - name: HeaderAuthorization
                          schemes:
                            - Basic
                          scheme_basic_cache_lifespan: 0
                        - name: CookieSession
                basic-forward-auth:
                    implementation: ForwardAuth
                    authn_strategies:
                        - name: HeaderAuthorization
                          schemes:
                            - Basic
                          scheme_basic_cache_lifespan: 0
    identity_validation:
        reset_password:
            secret:
                value: ENC[AES256_GCM,data:d0EaW6K2vQe5xnNo6rObP6iO+ivV7ukoK5SqejqFx0M4h6ziKpMR3RImCd2545G/UGRbQOVPmyhuPTBtdzCJOBvLLxC0KHMLCwunMZFihPse0TGL73es5v/Agevl2O7MZuC35ckUIttUWxmDzt1gpsNSbr4AfxC/uw8hAk2dL9U=,iv:iGD579hkBNhkUhwOWvTdxc5yIKzkBqPOMQ5cAZwbT3w=,tag:SJZRELwtgsCPEVG2rH/0vg==,type:str]
    authentication_backend:
        password_reset:
            disable: false
        ldap:
            enabled: true
            implementation: custom
            timeout: 20s
            address: ldaps://lldap.authelia.svc.cluster.local:6360
            base_dn: ENC[AES256_GCM,data:1TTANplpv8sZGbR1Q/7h4fZF,iv:ENJ8zN1iMsxRVSZqFDdtT9b49GE6s5VoXeu3nhVdgCs=,tag:tq1yWI4u4IBjxA8j9MBmkQ==,type:str]
            additional_users_dn: ou=people
            users_filter: (&({username_attribute}={input})(objectClass=person))
            additional_groups_dn: ou=groups
            groups_filter: (member={dn})
            attributes:
                username: uid
                group_name: cn
                mail: mail
            user: ENC[AES256_GCM,data:mdtQP6DKRFtom7derXUHTOVlJlg6jyn7TUv7VbE16TbTyUes9ww=,iv:XYNc+cZpWddY9akGJx7S5hnd43TVN5a9aEslP+Jyf68=,tag:YCx/io8xAfYA5zSZB2Jlzw==,type:str]
            password:
                value: ENC[AES256_GCM,data:ZGa8QYiTozzeIZLdQuwR/KZTWtCH4uFDkZSMfI7yIF1lWoAQ4H3tKjgkaw5+igxPRRjJYu49L+Lv0dbJ04lhgw==,iv:MBTVBa70dyq58jSQm3SsTSqQ+3yxPvxmgnu5QAExY+8=,tag:jUDmpJZdsFV3PpUlOzUZ0A==,type:str]
                #file:
                #  enabled: true
            tls:
                skip_verify: true
    access_control:
        default_policy: deny
        rules:
            - domain: ENC[AES256_GCM,data:IBlFB54dV+JteiJvXZHND38TGwO4vA==,iv:AasxusXzgw8aFpslFT2opZWWS24oRXn5u5EPgi6UakA=,tag:G3EAPO5TNgdIhIpMJ/b4gQ==,type:str]
              policy: one_factor
              resources:
                - ^/rest/.*$
            - domain: ENC[AES256_GCM,data:JxnOENbvVfaZwnWveJlMUvtF,iv:UYNHpKkxg8/2CRB+7YsjAq+mkyD7azy6tYA1HrMCzgI=,tag:jCgQiEauwA1nGMio58ajeg==,type:str]
              policy: bypass
              resources:
                - ^/favicon.*$
            - domain: ENC[AES256_GCM,data:cg1YOniY0EEY+VIagn9WsU2d,iv:KnLiamiNYZZg8CCgjtyOGMN1/1QjMAcE8QA/eMwSm0o=,tag:vvWlhL2dbf/oFEy8+rfGOg==,type:str]
              policy: two_factor
            - domain: ENC[AES256_GCM,data:jCAJgV2bMzieCXkJZSAKx3A=,iv:YYfjAk1QDhlmjJhR6v/Cp9by6OTYygH/I1IKOAQNtGA=,tag:Gtw1JLe3atqw+VJGQOaU7A==,type:str]
              policy: two_factor
            - domain: ENC[AES256_GCM,data:u/618Ff36HclBzKnRNMGyZ40cTivyVA/yc/eMw==,iv:+IeyNSWVThsh3ww4ULWe+iti16Cdf0W2+eoWwiWVYq0=,tag:xa3j627sgEoZ8EVrryS6OQ==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:d03Ti8IkuRFzXjN8uVzHs2JzRUCPBwRrkQNxup1UNw==,iv:tbpZWnHmlwsccQjKV/NGrvLdincL5Y2x1iMmPHa5Rs8=,tag:dj+70keeqgqrBuuUsQD3Jw==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:h4JGN9l+6VDzbNb/nqCa0y5G8nyAHwCTGwpu7g==,iv:KTlDwWUh2AAsQfUxnIJeXSTPLXqq+YXKvuc26eZxSdM=,tag:1Y4fdKXmVVE4Mxx0nEy6Yw==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:tJ1pw5DYGrBO0HjSEwdu1S8M5X+JOZkz6OEhgg==,iv:E0wDWpfQBUl1qJLPseXpDsyHGVS6IASrKg61EF827Ao=,tag:dd/qdM2WppA31QOtdFLnVA==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:IydngdHu8juOjinsoEQ1VaJCHRVIN5QUn2GoFw==,iv:FhlbUtfDw6B/ABA9/t4hvStln/DxdCas1UIbIPNMZMo=,tag:bT34JmWZUQ4MoObJfaBi0A==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:leIHWoDUy1sbQC3iedeNf9jWjTXGkYY=,iv:aRHkaGInyvLyyvug/QTywsvcjCS9xNGhs6mY0K2+ERA=,tag:ysYLSjE4k7NTWaatMVaDJQ==,type:str]
              policy: two_factor
            - domain: ENC[AES256_GCM,data:e32fhJxMI1PqqHl3WLwK2A==,iv:H2PwSqmxi2cXdDwQwl/laG9QuHj+geBZLuvYHgfvvxE=,tag:UmZKcMA2T1J9b2P7ld8bqg==,type:str]
              policy: two_factor
    session:
        name: authelia_session
        #secret: Tu6mithie4BaiXaec6gei0Iewoota1ie
        expiration: 12h
        inactivity: 1h
        remember_me: 1 month
        encryption_key:
            value: ENC[AES256_GCM,data:qVcUaDrKgM7bK6x/Ql+AkQF9E4RGFnZCtyhH0Yd/jb+8FwmOTmK/vAMUpOMggHpnBCT8UHExOWQZbmnn6gbK0KALe4y/OneuT2D8a61je5v7t6RUmEo/oQ4VMPzCHstlIzrVHJhP9a5UyCbUA5JdvVw6RqkGhZTZW++bA55pd0M=,iv:sDqduaqfTmtUBN1UPkWUbwLZk9OIdCMb519RDUnPS7o=,tag:euw74xXkcyT8yQQpbC9Kwg==,type:str]
        cookies:
            - subdomain: ENC[AES256_GCM,data:bspKriQyOgc=,iv:USFzLDeEBDUUR+l8TugAySBYl0JAJTjsX80LJfBSvkQ=,tag:3CUv2CUr5F6OMUUX/5OKHQ==,type:str]
              domain: ENC[AES256_GCM,data:byARKQmXJsIkSFY0,iv:fGiZeEo/ItfWKcSPmxSbbLF+hIMvyqO8P4P+0dWXVLw=,tag:Tjlhegi3mEpEX+GwZBq0Tg==,type:str]
        redis:
            enabled: true
            host: redis-master.databases.svc.cluster.local
            port: 6379
            database_index: 1
            password:
                disabled: true
    storage:
        encryption_key:
            value: ENC[AES256_GCM,data:MOL+TJUdlkoO7Ay4Nkg0Omz5JjaPoUGthaJ/NFU7/6z1Nf1bMraFBe8BtBGq44SNoLjs6ZTfoD0EX/OlC4ahhA==,iv:+KrF9545RhiLSF6dheD3ePSAQAHn9zt7ulKGISBfZuo=,tag:QZo+OGvQTa4u7rqgntOBVA==,type:str]
        local:
            enabled: false
        #  #path: /tmp/db.sqlite3
        postgres:
            enabled: false
        mysql:
            enabled: true
            address: tcp://mariadb.databases.svc.cluster.local:3306
            database: authelia
            username: authelia
            password:
                value: ENC[AES256_GCM,data:BypDxwtapAIF47AVT6jyC4NZMZFVSK1HfwkpoFOY/CPS3U4tN8uBmm2hSBlsUjHkheqVv3dvQlMx6IYVskNfjg==,iv:H4AfTZf0yQjoOrGJpwWBDhbjbn4UTTMcvq499hUqBNU=,tag:xi+gOhVqzHWEZNN11OIRAQ==,type:str]
    notifier:
        disable_startup_check: false
        #filesystem:
        #  enabled: true
        #  filename: /tmp/notification.txt
        smtp:
            enabled: true
            address: smtp://postfix.media.svc.cluster.local:25
            username: ""
            password:
                disabled: true
            sender: ENC[AES256_GCM,data:oBXxU67D5X9etTMpxDD2vSjbpvNuxQgiURXTSQ==,iv:ZjYI29/W+rUhiGrOtHVou4kWdSllZ6h7a3a9lwKi68g=,tag:s3gestIkLnnlyZppBap7yg==,type:str]
            disable_require_tls: true
    identity_providers:
        oidc:
            enabled: true
            hmac_secret:
                value: ENC[AES256_GCM,data:uljqL3skTH6lrN7eAouNFagdQ72xJHLOO7v7ecsfabI=,iv:97AjHQbds3eT9eyNh7eanzt9Zo35yDGq269j+4xkE8w=,tag:zEnsEmvKidCjqVaquFbY6A==,type:str]
            jwks:
                - key_id: default
                  algorithm: RS256
                  use: sig
                  key:
                    value: ENC[AES256_GCM,data:ChwZfVNy+GraJVrLX+gkZPnAITWnSK4SwcrHD2pyTyymqdHvCNACI+vWWSEoFdw0ITUU7e4VHlb44k48IssYeUg+EOMMYa2hxY+DNEY9moIgLrTkvO3O558ax0vJ6oYYFAW4P/mNkFx7NTbzrc8nSUET8xU282Jh9YjpOCtEwX2bPbJbBhlJUpKOB9WIvkZdLz9R85ApTqVQP85UWZzIAjnNiuDjMk/bS02JkmhTODKFmz0lLESsjN1hbskDph6rRskyRUk8EFMRSw902e7OdqKK318lnMCR3/JIHBZXSvv/R0ftYLr7KPpoNvNhLrcOtrKIQHfx2lPC1F9R2v81glUh93gDLdepX8BZfjkee9tOAqb8nUVmxtvD4TNXa7Q4wG0rOgbkP5ftQDJpnJIOPQ3pt3XDBlP4PRZwfIX5hzNyvNIeKiqXNXARpn19I4JPqOnY49QEnYaXgIXCQ36PR9WdQoSCzDelC+0lBD7D27sqaxC5LCXeSuZVjyk14rGJuZpYfveTZvatVzJGZSs+1JkwvU3b8zkVjIFcNgq4BorjHxPVOZnsRYmhrug0etdq+T37xjlUQDzeJ4TGirEPNuGoOvqKNCKwYCsu7fD3KygQPDMErSILoHAfREH4CCXRVcNM7cYJzDJCZePCMDECYuUJz6ach7Nf1PfTMcql6whBe+Fc/YCSPiNQ3I+hVTEzUC4QFquFbYiRxiQwmXtoL39ZxL6H4HmIatkWaW6QbIbpSYlJEg7P2MDK1j/o9NwLu32YB6kfyk7WQ8Vk8MiXnIstlEN3MLJcYe4sYquiUGbW7HXkunTHXrxXveebbae3CwlLSg5CzCWcMzxPp3luwcLnckyLmD8LrRY/5BOixBhUOZFfeulZRc/pqv9FS7jWdRdShah0KG21TW4L8SLc2dr287+mmFSqtdapOqzEEt6C37y+uHA5ZQj+tG8NJUJwWT6Utfc3B8yqdsO2Q8tDb/0uiVb0pyRKOeS1jJnCCXGXLknmCKQMTC5v+Cn6wXI3KQgZ8AI2sWGM40Oy6uXhNVPD751E9RTX19qQapcaIyZVttT5ovLHTZaSu+0fSYnth2sHRIQap2ZIHhfkiOeGxJLKQgdbdi06ToVknOuLUsECijArXQtU6TEEl6APVB5pfTADosHdcc6Qka/shKpmgeg7BQ15VB+gcJNUXvHyHHvbAzvKWCYgjqD+6cgZ2vKpm71lZz6/8e/LV1V1OX0Ooczc97dU+Q697JyjfsO2tUsi+dhoUCRWhXNwohJTqvubhzlXcqPAsxXe9ADDADKiQRtNE3NRNuWJizaJ6qDN/eg2kHcRV66jY2ZKegxzdjeJXaGcuzL5+HCVRXNnv8aO1brN3jySD+jcqYvZOnPk4rOzgfmW3/oFL4PAPSjNw3utzOiPYZxfZMDZp17esvey5a8ZiE/XENt0fLiGKPQfm3p4vJHrpl2WMIxwY0wRS83tXNdBRZGPWYpURZsBJMN6nBq2LKgImDpMTpjvDmiC6EhHjRMvUeoZMzoN2qtMtEEd2Q/ckCQ7VZFY82deg7v9m1xnhMTy/0uYPVFsXxPBH0Lc9EE8tDt9HechfTgmrpUlnpGPMsGfUvUoEqtTQ10kf8Ba4432brpRsj1v1Iu79F+ZzDuElQ9gG4u06+kLeK/1y35wbkXhqcZRtEYYbGqAFbvBTtQjDvocNDnvyaHGRGnE6LJVZr/AkbO6pY+L4lPBZoq0Jk4kvtG4mbHSdVWUN88n268bzufMUDCXnx4uUpBffq+rgEdJeOtNe1qDvUFG4fYUcQMxaZVpYJLSAKf8zNXOnj7vxfcB0j+3NMUrl+H92h2/sZ4t+wyLdK0KGEP2LRTTEGFfvYA1lM2b8TtX6ZgXdJansBmBGi3PVgJYBi2yGNuxAra6hN0gqdsYPCSD5Sat9yPEErh8QsFH5WPAQooHnaUffOucR8HouN9Cn2AMsf224DYInEqJp1rKZNqx3jultYe56/qOH5IhnxxeQsJKqjG36KOk9ZhlasibHsLlXs+EMQMxriiFms8uOiSlAIjEiQNezE+8Mpwb+sPhBZ/J0oqoLWhMXNBC6ERnZp2g8Lmy5Pr13OvPtCoQodKpDFE6z+aS4Sar7imZAghZGl0w+euY9wsdyNMAAaq5Ep1XJ8R1NH25qTSPx/BDDl/OCmwxVbWiTwbphtJUbXSgnfTchq6+G2ebMr9m1+v3cOLBoj3N2C04EaUauFqgmyV2RiCnu0y0ntpv3Hoa0lGj9voIcM9yOW3ZdUXgrG/Ku8Z/xKIR06it8ID7wPVzIgRKSg/s2m1HjLW12q8A+N16R1zuR8M600vDI/BGfeyXJGCvRT8hRBRbOakn2/6AN/5RsRmu8oO+DXLChKKiAkYVyku8r7/ZNLVVh74I9Y7RXO9j3fM8geXGDXpY6YeKKOYoHUl9n1oIftkyW2ktFmfbYkuFMdo4mai7OQfGIK4OERB5fxim37WWU1jKgH3vDITUgLxmlpMXEEC7gvNRElj9Cs7HT7TBsU8m+hSVJOjNqsqMhbF6lykDnH+GOWPQM/Vu3BZB+fzv37o2oBRIx0YsbOgRsoLPG2cdwsiV3+rvrhnlG7hL6gNVNcP7R8MXRJjIhh53UCt9hN4f3T/FJR+r3nZKYL0V8qbvBkLQgbOd0cnCEYkbHONk3gDzOU4SD1fbPlAJSOop4eqWS2G3pLmrI8D0YiKNQduys/lL2FxRLO7lUSAbB4kSj2R+O1bkzWSSLXl8/osXsIcR6WjzLU0u82RxIqw10trCZJ2W35kndVmgw7gh47X3P0dGIqh27+/yCSMpsGJsaE+TDYpgT+WrjAth5r9szjysCGORibu4uqTdg0VxkSGBFbokBpDZIREJyjLZW4tWuaIQ50BhguSdhdixY4iEK3iLC6sPjeG08hflBTdsjdi/wpAoRJnwe8mt0qX0i7ZgZuuW51hH22WcKayvamjQ8pH69T1ow6/q3lRKFF3y2qAkvHO7tfhsIvXF4WlcCdtpKcy7l6rG2w84ygktsSELQD1SyZzXWlOoyLZk6UGMtx3f+7EdAHLeGNDOk3npsLTf39ab1V4LNmZ7bLf3VBXHbPNQVcmrd+KaQIH5kbBUwP5/IX1jmftCGeiiAc/w9mp9UZzGK6fPb4fl9bkR/hH1ITmauBfebxMAHtCxlCPcY3118SFZ1ft+XRKcLFf4o3J/pr87cD0HoWnztTruOWf5l37pBdnFJHOKE6Y0pmrCKf4wqj/2y7/YMYVOMqqYQJVP7WH/t8XuHtjdztr6oBrXj49O02IvDqsTecFhKBtF7+UXzqaypKU82KzsJBgZc3cc8HS5GOXH5mT/IutClIpgDTNoiNpkVXnS0+FfYucJZPR8bmQUfqmBci6EZYCZD51k5wNqACY9PvovVhaLT7lX3PPBf5cWm1UQ+0I7DX9bhO2h7YIhFl4Ss+4tKiz8SSBbUuFhj/Qxas1To244SUHd18RjZLDHNnMUKJxPISbKvyWSXQzBXaQDsAqnsyr/r/tFz71PBjmHtS6uj8RAQxXgdeL6G7jVQqCGEGcpaEJiN/SbEBeH1uJGqeUbyUYCeJuz6wHdB0RS7BVzoT1C7hY65ciC5ZD1O4wJJ5p5wJdPyksmwGtCxl0AAxwl8lDynjbgHitl7DFpRofyx7X+DnaWWqZRIp3x1+j+kX8Zrr4sbvRDZJHlSeUeDZChma4HNoAQP0yZPrNn6pYt7IRBZ5CuSl0r8qPJf+ixEatjFYliIBRxSaxIK1dwfMO5iUIYdJZf9jhzIeui2vVw96LjpepyuACtFwYbELsHKF64VehyWdcHS9VKHLXomsK5nD7QE2t/GLmpX35/KROzQTaV/PVpwhHCo3cteUJM4Xg8ASKlQS+8h7pZwFG8fzCpNA9Jegy2Z3Mbnsd0MPTdaQPQiZELpyit2+lewp9KqD6r1MD6F8hnervtg5PUjJOwlxUpKUIYRIXQKOHrfrENEVEmGB3Nz6xTW6JgI/nB22/GXcVyg26JKCYf+NgT/JQAFzl5g2am21pGjENxNpJ3XyRSx0DxBIl86pDp5oY+12WrpD+NCOVmwK/aVSNqmZw7tEaeuhPOawUCYD25pjSEqpu89Ddcbr2+XGtdYw0ZJioaXx/D5G/p76kdMijALB4CJge/nE/6Sl1I+3bNW8IKC1ov0BkekXfS0gaZLdha2uPQmb6xN9Pxj8xhlhzpYotR7ceykI+WEbzr3YXHHjBdqDGLokNBJltHu1A9maOZCZLE/OUY3mFygrrMXknZHzRhoL/uWHdcixxK13aOByZMHDXKip1vTmW+e4W8,iv:Ztar0PgH03lbbqw3rZdD+CfjU4ATYdFvTRPAOcvKd80=,tag:sGFPdxZpfO4xORMj9KrsRA==,type:str]
            claims_policies:
                default_claims_policy:
                    id_token:
                        - groups
                        - email
                        - email_verified
                        - alt_emails
                        - preferred_username
                        - name
            clients:
                - client_id: grafana
                  client_name: Grafana
                  client_secret: ENC[AES256_GCM,data:1ueHZ69XebRpsofe8kClFW3QEmJJYazfanopCIIX4b8BTj0Mj0glkWONVSrZMn8H+H9fUj7QcabSy6rw0U7KVZjg6Tsm6iYgB3t88x3lbK+TQxKrhuYtfxsnuQjNP//CfJ3PrWjSEfa0SWQ2VIT9tsCKrvus7gWM9HY+RfSXLtDJ+fE=,iv:cMJAtHxkop9HzebI4/buV+boRoRKf84HKUsGSEzMffw=,tag:j2ouC3ajSHBionk6rtlDdg==,type:str]
                  claims_policy: default_claims_policy
                  public: false
                  authorization_policy: two_factor
                  token_endpoint_auth_method: client_secret_post
                  #pre_configured_consent_duration: 1M
                  redirect_uris:
                    - ENC[AES256_GCM,data:1bGXiC7apjhHoh1YULLXDzjVuRpH6IAXAWz1rImvVm5sw7wrMHplTXkh0N7wWP3/chcacam5eZr3,iv:BbRbwk2QF4FBXp2O+Tp2ldwuJPGN0D8LoR14c5D3woA=,tag:+UUTLnoZKQ0BXopwT4iV/g==,type:str]
                  scopes:
                    - openid
                    - profile
                    - groups
                    - email
                - client_id: argocd
                  client_name: Argo CD
                  client_secret: ENC[AES256_GCM,data:HJhAjCAPIPv4zWadT5WYENd8O1LmT3w/OtqNz3Il7pALVQzKmKcQ4wndDS2fVrdVYsiMbNChMSSW8LvQ0aDeId9KULRFXYVWTOqaLCv5nn3TCfVFOYy48wH7NIg+3ckxCd1+jgzLtFFwalOQD3AA5jE6jERjUapw/wvPJKAsuNWTwUw=,iv:d91ZxOcnYcLNJHOjt0V6ZMWFgS1tyhZKDFCyUiHIwbw=,tag:hHKM1Fwrci8dMypom8nyuQ==,type:str]
                  claims_policy: default_claims_policy
                  public: false
                  authorization_policy: two_factor
                  #pre_configured_consent_duration: 1M
                  redirect_uris:
                    - ENC[AES256_GCM,data:fAFoeKiMAJpU1+AF/6JagatRZmzRulbmLBE1yLNTxI77urXUdjQQw7NRQdZjXpmjwYc=,iv:9rc/TjEEMYaoR9+tDcFfhHTeCfZzm52hDwNu0gb24Yk=,tag:iP3u3miNz2XpyAHohcQStw==,type:str]
                  scopes:
                    - openid
                    - profile
                    - groups
                    - email
                - client_id: argocd-cli
                  client_name: Argo CD (CLI)
                  public: true
                  authorization_policy: two_factor
                  redirect_uris:
                    - ENC[AES256_GCM,data:HLUcvdnfnMvB7GkC97LlZzfFtIuYnUfUs+BHrlYcs7qIxU4=,iv:1HX8NP9cM3O15eXbsn/GEII9UIM0UuRzPXJ9gpPtiVE=,tag:BUqlCwzq9I5wMFgsf6YAQQ==,type:str]
                  scopes:
                    - openid
                    - groups
                    - email
                    - profile
                    - offline_access
                  userinfo_signed_response_alg: none
                  revocation_endpoint_auth_method: none
                  introspection_endpoint_auth_method: none
                  pushed_authorization_request_endpoint_auth_method: none
                - client_id: semaphore
                  client_name: Semaphore
                  client_secret: ENC[AES256_GCM,data:PmFiGhZlPBlFmOG8mFBEhovLdZBB5zblYgJJWj19Tgdi5pC71uzJ8FPBTwpza5bne8GRJlCtHQqUU61EXMNii5lJ6hJMyO9ES0f2zZlwvTE2Wt0GnhyjNhrwv5rybibI2ia4RvUWpud35sxTOonfzHQGkGAyVxf5PCH1WLumGOTb3FI=,iv:opKvOuX9v1ZiN2jk0IAaFKqgAwyqk7ARWvh6j2Ky8Qs=,tag:FuxJlI6kRw7j+5IGBY8gpA==,type:str]
                  claims_policy: default_claims_policy
                  public: false
                  authorization_policy: two_factor
                  #pre_configured_consent_duration: 1M
                  redirect_uris:
                    - ENC[AES256_GCM,data:kEIjT5jfO7VSh75Bhywqi5N4FdRhoblL04DJ20W3M3lkUm6yMc70Ij9wqGVu0zQQqBwR8u0OF+Klcd+kBEHkC/r5gMPxKjg=,iv:Ip0G1OLhm6tmSGMmIyIMZKhyA0KlSi+M1GezWJyXyQA=,tag:8nmOwNBvIE+WG2yIvogSjg==,type:str]
                  scopes:
                    - openid
                    - profile
                    - email
                  userinfo_signed_response_alg: none
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbTBSL1dLM3ZHbDFzSlpZ
            NGFXdG81alZLSkN1bGQ4OXEyNzIwM3dGcGljClhmU2ZsYU9iUUtTUFV5TXY3SW1j
            RzUzamdpMDhQM0Ztbmk1bC9kWXFjM28KLS0tIDRIUDBQWFRJcWhGdWRyOHBQTUZx
            UzBqSStkdUhTZk1LUTIraENIR1FFNnMKD0uLvRqK5Fxy/ECB/mZ49w5Cw4J1utw8
            w1jxHBY0fmxlkPzoR5L4w2OlVrA0Bf8hUvo860NyokrAG78jM/Xj4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1T0Q3SlFSMm5uZ2p3ZWpO
            eWZRaWF0a05PYndRRXVzSS9lMXRZTldVREVvClpwZTBwWEF6NXNTUkgrclVZeWpr
            bytybDZaY2duemtJVUZBeWRzSFI5T2sKLS0tIG1IaUpvbXdtbHNkTVhaRURadDZS
            WnZ0ckZzZkZ0SHBoaUxIMmE0Rm9yakUKW5v0quqJbRnVHqKuZIZg9uh0ddpPcY0P
            2snKXbXsS5WD3eqLHPcBd2Z6enbLxH5/DEH2X0tlLZaqeUUtPyTkag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(value|domain|subdomain|default_redirection_url|base_dn|user|secret|sender|redirect_uris|client_secret|authelia_url)$
    lastmodified: "2026-05-14T15:29:53Z"
    mac: ENC[AES256_GCM,data:QtNtIUCmc5XP8CwmFc4F9EUomwp8V0uX+ixInoT4r5cxEMpUigraCBkmloCqtCbZTYfi0XYAyvBjNwdL3rIGAsbpYLDvxW1qP9A3r7laZxgWioDC2wg1+ZWtUncruIIwkxnU+e5NsgYYVPCAulIPBDaeteio8lLhJHWiXHca2Y0=,iv:YKrEnjpi7/nZruOktwENXw7qxJFAF/H6SSqzouW2+P8=,tag:teQy+UPaw8Kveo4upwiCiQ==,type:str]
    version: 3.13.0
