##
pod:
    kind: Deployment
    revisionHistoryLimit: 2
    replicas: 2
    resources:
        requests:
            cpu: 50m
            memory: 96Mi
ingress:
    enabled: true
    className: traefik
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
    certManager: false
    traefikCRD:
        enabled: true
        disableIngressRoute: true
    tls:
        enabled: true
        secret: ENC[AES256_GCM,data:c92U3pNT6v5/GkJSrBWWpIoSXBVEeZWjqMoJxTMBnDbr,iv:MzjxgLjeXAi8jTbjaHTY04ONdq5fC7dukMT0w2/m6SA=,tag:Eq5PY52Y0yUG8A6WQUuihg==,type:str]
configMap:
    #log:
    #    level: debug
    server:
        endpoints:
            authz:
                auth-request:
                    implementation: AuthRequest
                ext-authz:
                    implementation: ExtAuthz
                forward-auth:
                    implementation: ForwardAuth
                    authn_strategies:
                        - name: HeaderAuthorization
                          schemes:
                            - Basic
                          scheme_basic_cache_lifespan: 0
                        - name: CookieSession
                basic-forward-auth:
                    implementation: ForwardAuth
                    authn_strategies:
                        - name: HeaderAuthorization
                          schemes:
                            - Basic
                          scheme_basic_cache_lifespan: 0
    identity_validation:
        reset_password:
            secret:
                value: ENC[AES256_GCM,data:gGzMQ690/+PHwmGY6p5yb0wV3dGMGeadmf6RRntsNji07cT6lAU89gyxXqbsXcCB85i9iJvR1t4UnPCNOd8oW0NaTBbHK1RXLCJ/3lGczpN2DBuln686on89AcJ9re7fyOb+sD29mHkneG1lY447Zli08++sv//KZCPsf7CC0+Q=,iv:93mQosRGOtX/UdjB+WCGxdnsYk5g3Xa0z5Yp+N/b3a0=,tag:XQXHGAGMjYrYYZI9NppKNg==,type:str]
    authentication_backend:
        password_reset:
            disable: false
        ldap:
            enabled: true
            implementation: custom
            timeout: 20s
            address: ldaps://lldap.authelia.svc.cluster.local:6360
            base_dn: ENC[AES256_GCM,data:34o1Dme3hnfyhxvlfK+LKMP4,iv:7fFsTSGeaSZl2Betkmd8zXic7EsLNJXGFKPRyo8e1Gs=,tag:k353h/HeRE7oDupxS8lVhw==,type:str]
            additional_users_dn: ou=people
            users_filter: (&({username_attribute}={input})(objectClass=person))
            additional_groups_dn: ou=groups
            groups_filter: (member={dn})
            attributes:
                username: uid
                group_name: cn
                mail: mail
            user: ENC[AES256_GCM,data:GU3bgWqkHMspfOaL4YZqZRP6Pd48ipHOY5cfM0Syf/OJzCgVsGQ=,iv:0F1CFc8m3dYfR1hysbWONgSQCp5QiKGamoqIg5zhAuc=,tag:WRYrPBKrPLVHV6beJsop9Q==,type:str]
            password:
                value: ENC[AES256_GCM,data:vDPI+sw9b2T41uhsXD2fUCFsOmUxmGaVAFkG58w9zBnC3tYUcD0QkoPv6cymVvjYhaQnJpZqX10WZsbjN8Q/LQ==,iv:XlVCkIKqu/+9AlOESA7YMnHylzizNkcmM2YWzkAM/gg=,tag:j8xSbHV/wPRH3GoUyvtBPw==,type:str]
                #file:
                #  enabled: true
            tls:
                skip_verify: true
    access_control:
        default_policy: deny
        rules:
            - domain: ENC[AES256_GCM,data:lrQMtwc1wUSzw8f+tIARRsFlgAL3Jw==,iv:0vO7nLvnhjNrcunEDbVSvteC/X/6ZHix//R+Ws3g+HY=,tag:JdBytMVuO3nHMWLKXArjag==,type:str]
              policy: one_factor
              resources:
                - ^/rest/.*$
            - domain: ENC[AES256_GCM,data:zEEhSgyBqQvrUgvc5czibsUB,iv:1EXfSEH49/V+jw4xcS3xmjaXfEUOMxtf+Jb8VcBqXwI=,tag:4ZRjQTabQPcnFE5SAYxwXg==,type:str]
              policy: bypass
              resources:
                - ^/favicon.*$
            - domain: ENC[AES256_GCM,data:VZGqupjOV5RtPGCA7N0NnKfW,iv:Z/HfSZNS/k475ySbdQYl/u0TI4vq8HWLvIaFsdlHhpU=,tag:1D/9pgsHYsGe0z6KN+rg6Q==,type:str]
              policy: two_factor
            - domain: ENC[AES256_GCM,data:669Aaunobw+26MMhskF9Nvg=,iv:e2ZE20Jkq2vQ4T4E5kY+ztmN3enGy8KkPVYP8hPF8AM=,tag:cOjMoyi4U+g7tbtYjNzkVQ==,type:str]
              policy: two_factor
            - domain: ENC[AES256_GCM,data:YqgcvyEz8hNBdqF/YR4u1Gd2Bhpmp66IO/zR/g==,iv:BDe2Q0m9tsol+Pus0oXlzjq3BWAnzWnbLCv4rSVvJhQ=,tag:ek52R6Yog+2SrWy1myZRAA==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:sYKYXoC6j80bzJwS8iuaVrs4NojTza10RZc/gi3sMQ==,iv:FJ7QLFnRU4T/vrpa1B0qAw2SB4HOne4AGd5Vhfxw2JU=,tag:LG6VICg5ECrUPlynB4WJfg==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:i97GtiBJ3tUbE+H9RFk1PZs9i3rrE7+G9NzBFA==,iv:E5gXIy6Cony4BhtMr9nnf21/W3283s+LtKmoYIT6LeY=,tag:Bm19reXSFQE4JegUDlq5CQ==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:HuA3eerOqWS0da2SRV+LpGd+g0L5q3G64SG0qA==,iv:ekgqmvMGByVaiEFs92x775TP21HVpthDCN5rNXBimco=,tag:F9UCj6cTbQ05rJu5ttCI4A==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:Y4m9foi3zInPThWIwynnR2CLJuCiJcHaGb+7PQ==,iv:kvkZIzPOgPONPKfREY3E8tUoBvpAOVrXDJ77ehoEa/o=,tag:5mWKY1fg+jcwP/6NMngM4w==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:nWsmBYzElFJBivBpSxuVMYUW/e/kEYI=,iv:ufC3rs082hJLCxeblpg9+d2qy7DwBgCs13JQ4H950TU=,tag:Hr7I3ZOr2lX3ANcLNpFqUA==,type:str]
              policy: two_factor
            - domain: ENC[AES256_GCM,data:tvcYVJvicbNMRKB18LdOqw==,iv:0k974QNR6k1zp2YvIA8RcKwRRrbJ6+6SbQ3sBd6T5fo=,tag:EHGWWdCRYloQ2rkEnMJUqw==,type:str]
              policy: two_factor
    session:
        name: authelia_session
        #secret: Tu6mithie4BaiXaec6gei0Iewoota1ie
        expiration: 12h
        inactivity: 1h
        remember_me: 1 month
        encryption_key:
            value: ENC[AES256_GCM,data:P+6ziNFmIRkR6lnhIedArN1SS+xQV5scZeKibtIIRHNgeE/90Jdbgy84BpY7LhLamrVpynV+q/SCDfepLgw3x7X2q9o//kncG1d5HTjRc8jNMFevjSuk9cHJMFXmiwYeg3j/S3VOvUqG+Pz2FyVm2crQ1+GdSw9XLYHc1G8DumQ=,iv:YjzcV6c7IPEpytvl82IjobkyH3bygh3FklMiuSferck=,tag:o1KE1jUYWoxH9otjoBJT7A==,type:str]
        cookies:
            - subdomain: ENC[AES256_GCM,data:ZDj06qC7Po4=,iv:aN2Gl1Uf1q/Xf03VKAeHVjaf9+L7xra7pRk23Jy6o3A=,tag:JHe/s2MsJ65Sx1Tf3yJMLQ==,type:str]
              domain: ENC[AES256_GCM,data:ortAo09Cy2osB9QM,iv:/wkJPZml1nFY6V/qUuSlWgBApNKuFPNAcdpdLKtkiZA=,tag:axoidAL9Pz8gMXffIq1Bkw==,type:str]
        redis:
            enabled: true
            host: redis-master.databases.svc.cluster.local
            port: 6379
            database_index: 1
            password:
                disabled: true
    storage:
        encryption_key:
            value: ENC[AES256_GCM,data:mEADQURUGjp/hrmL78UWEaa+L/2zUONtF2KzcuO83EeK+T6RBCTngE4ENfeCjrq0HBi1py/SH+caTJeXgpe8pA==,iv:qFsFAEnAUhzFhfithXvB9Lzk5QOWadAHncxAnPdPB0c=,tag:1QUSD+c6w3w82UN4bsKaLA==,type:str]
        local:
            enabled: false
        #  #path: /tmp/db.sqlite3
        postgres:
            enabled: false
        mysql:
            enabled: true
            address: tcp://mariadb.databases.svc.cluster.local:3306
            database: authelia
            username: authelia
            password:
                value: ENC[AES256_GCM,data:de1oDbyN2+r6ANg6rmPlbq0mtZT7OPJyUbz6EuX8c1QEoTGMLfNXUA3jMW5tiuyZ55N/4ChPJi7QYzk/5CE1jg==,iv:mIKyPnXilanpR1v0VUWAqRvuDx5xD1UUkOGVjZRYpdc=,tag:nZE7q2N5cB+g/95vgu/i4Q==,type:str]
    notifier:
        disable_startup_check: false
        #filesystem:
        #  enabled: true
        #  filename: /tmp/notification.txt
        smtp:
            enabled: true
            address: smtp://postfix.media.svc.cluster.local:25
            username: ""
            password:
                disabled: true
            sender: ENC[AES256_GCM,data:byCEgnxzZ5rt0MaXtd8XiJ+A/xTp6HlRu3JkdQ==,iv:SFZVTHKQnzEA3vsuBOLopcFbKFSupn7ySGjW+7IDc40=,tag:IVKPuTH6Vs9mX8ho5g8Qzg==,type:str]
            disable_require_tls: true
    identity_providers:
        oidc:
            enabled: true
            hmac_secret:
                value: ENC[AES256_GCM,data:WnceLwqLoaw+Yg8EfhtRwE52sa/bPLzUEJhxKN0R6EI=,iv:O4hIcsx1V+GTMCcj9yNTMQAInW2VX+s7tSqBamBAq/k=,tag:9w3a7UBGrQJJTjsq2ILYNg==,type:str]
            jwks:
                - key_id: default
                  algorithm: RS256
                  use: sig
                  key:
                    value: ENC[AES256_GCM,data:ekRAUfe8DtfEeVJio+LcxtJCBZobXSZyXhHFcRpRnJeKE9GzQxL+fRFy9Utn/0MHt4bbS0RaE9fNwOVlMlH9X9oilzF12tMCz4VSHqXKB18qsLAQhrcHvxiNR0qHdIhmdSrET2TfxSnVtBIxSaFvAr2o3eF9RmMFlcZwEgSkN9aEgZPmp79Ef4B8hr4IbebuqjD9HznTNWD7M0o5+7gf1oCqIWM3BXNLt21lyGBbM+CxqYAPIEqrky4ZdVnPY2ZOgba4XH1LHAYSlHXj1g1gOVew/B/THkr+0HdEOiv8o9EGCwPmGrvt+dUSeXLWg/blrk8zG4dxNqNugOgK9GxtvMPiZiRBVqTIScbcz2BJ+IAPRJMnFlJWeN58uVKBhRsjAw9RdXEdiG1NjtXLks46mIe8vNAMlS3iGb38HBGI3zQlFwzutC6u5p1mA2yJk0NfX/UnlrO3OuFXuKzanzE8cOMuf21JCBiqahsTpAsI+oqJcWiiTYNO9ca4CpZA/8Su/Q2LmO3+KB9zNYKl6KNttkHImGs3sSQ4neDPYPXOv77YMVjgNN/6yhXrhSQtvGSVLQ6TO7zocoVbSsfNxorDMMT/5ySI5ovX4lPmA0auZsOWHolqCi2hGlqGDsHiwiJMYAJ55sJoCTMQlank+2S8Pa9bBCo63L5ICiRvFV53zyfgptP4QYJsL906LToRdUnhzhHdyOD1xr5+nEg6FxF0CIyP/lj66K/vgT11BGyEUDt4+PE47bdgoap++lR696AMcjELjxWb00A9oC2sQ8JNRg8k/rMEeuKYRC34HqYzV7TSV2J2DD1UQEHOC5NaAyVHAR72rqNT/7J3irywirgD6HHMlXdF8P0r/uCyuDhgAk6l7KuvXEjazweeIrsonQOkCyAZ6Hf5M1j01qjoP9jqZ3z+Hlv4LbaWroqWNr10TrwgtzqNs2yQuRdhg4lzmWK9I08rpAXh7Yo1D490y6J+oGPfpU+FG2RlgauV+k6eyGxlCvlpwNvbrz8SabAx1T2s1B6hkQbc7mMMcMd6MKpB19WTTAlNmGx7WaIXe23Oo97cQyo99v5gFBTVmqwk+14L1QkIC6U3VPQwWb3/h75Tw4Q5bHP839s58d6Dzrk7V2UrRzxgOlYHeCLGZUiKyBEOYZjqwy+8BWWGW5X3JFwbmuMQX6/N1qbcirHbsBCgwVIUiNX2Cib0tMZsfOsrmK0aLjCniqCzc8zLSGbxmV7k8bTFX8ILn1sAJF9/gr/KXWDqUnghxUl7HnOmxq4X9JRYUsoaVnGdESkK9A+GNF7wMk6hoJAbpDOsNK1mcoJFnILw5GN8DJoFzmU0Ay6VfcTqm8VHK/wznCRSFq2tfG2r9Xq0Z9q4uqf4lebbZA120twbbLcSTyBGW7fZkgeRMygC5dUZJzAz/bWLuU3i+JY2u6FMoFbXoW5ePe53/K2PJw2s8D4N/iftfwSP4m6XMSoMPWMS9AzI+ygaZGtECdKK2RT2ssdUtrVzPlqptBdnnBI9mMxjuwsi746BqIEwugKLrB/9PZY5AezNjH6SJFFwrDUfno6c2Y2tW9TftnnDPsX/0OzkuE+0sHjbHoxj1TOLYWIAWP4Bl6v4eswQX0GEckjtu9pGHUCsA2WOwZw9LwjN3j4UmlUl6uu/Dze+jkrSgT2IVMjF20EOFiSlxeeAb7mct+4vmrX5nuvKO0fyu8c7G8iLZ5MdG/Lx1em0Mwv+MAGmi2BZRgrAIyzeBxX/Lx5Inp3tsAwyXZ+Mjsu+yK2IRlmwISg9WVGvEF/KdYpYw8BuF9IhqZHP+KpJtGXw2eXlwY1ALHuazEOhyQQdPaN3/4OjJdVz1IrM+G3iVcMFGBO1l2Ihmte0yVupNnnucTejMBCN5r1qW0LrgB2dMiGW2osUKCd/U9Z3JLlqkKcDXIhtn4FT00OWiUWB3kMg+kQvEX728sVtCSJ1AwQfZyv2BRJ6f0hD/NQ+C5s5YwA/f04id7qUWLunRrndsAFHSkSliUr/cSjWruSwmtc6f+kMuwcZ17WHCBb76IH/nxY+IaEnMPaEvPxQM/yf7gAt4XvFALfbOmktCm6q7KiqcvJrTQekgUKBZ4mzwfgPtSHJILqDDQbk3M/g0sSGZ+oQysE1N7xgwDtlfdiB/rCfaT3BptEf1wUKwlII7S3cUzPzu68c/A8PyAixEHzyRXg7KvbC8mtDhBEOhhKrVoOXKo6MyznxW7Pk8LMOYcVzD9Mx7AoojyplpmGne2bTxJPYAgPfAr7Gw1vEZHFh17acrKo8SPqPNZuAujOLC2g6J0pzmCuiSR5NfxrGdHjntPdinNtrTSAt9bN/0bIHz3I5kVSpk7oWkemfifj6WIBrymCuJU1AeCmiU++yhzE0iLSKNeA8ItpJHraU3ham/aQbpmvhXfEDLfIsMX+bbNjNfeS7he8NFr94u0Cs6OLtcJuTflCGO9tCdQOGauWzxlPDEauZfJAmwKVvk2lVwiDT3BbPcFHh41/ZegeuR8E+YvjCZX8DhUWGibXB8PnHCtIryjtzpDsBcDonYQS8WvZbos8m/Ytb3pbJmbbIrvdaiECXbNbpDd7PzqzsGcZYKqu/2wBScwZ8KBvZfL4iR3zfIEuxHRmxgJyNlUfvjVcRyxEr4+fLcq2SqxmYVyUgd7P4KR7IcFU0kbX4ZzRvN6O3M2yev2uYBuUgEj68zKVv5zT57/NO+sqdv0RUyINPj/PX/TAMxnmVe1oU4v+LECCydIeelKSldf+huLKtkb7vvVUkK0xfUYd4QmGrhJh8Qmsh1fQ+he+0V6nqFCRjPeUn5p+CHDlZ3Lxf6vL/ZK4tB889FaAmRM3vpdUOn/nLTpg9ID/2EwS9uM/NwpGbsfR4zJ4qcrPpvig4Y9NYndjB6w2AMmaSUiwjNg26W2hVdz452kXwBHLLnDZut0xRdmGLT7/RN3ygaGf7WoHozzE0aMIUUMRubTsheql/RHlQXVneJ8iPBrvyh4FmAFrRhXpdYNn/DTk7eLq8zUc35x8jJLrRn5/VI+OQ3b5hcCsn450GFs3TMMQ9znAOEFqRQHXugGtj+C6PrJFCmxccYY3tlp7rfI6HUe7oNSg4+eDcbVEXtVhxDfiystbqjw6opfNgAUz9q5WJikRs4nhxCzDJ0lQ8Vwpx77y3XoIfxHE0cIeOSE1wgJV6MJFBL28Mp0Kxw7GI9O9WAu3gvqkQ1g3W0gemUH+JdOOK3Kvvaj/ZzQcHMqYErOOPMQMFiF1rxM+kP9F0a6flf/WUTo1uObjBgloklCXsYp102hsxuQtiYO20lVTJg0daAmzwOcfu82CACeVk0ElYYqIj/l7MnRupjl2WBNAQ9cU/ruUAfIa9QM8lqAoEsEUImjdndEiDWmIz1AyP2LiapaXfVXL6iIr92rL4t+vR1lypXV1Uwp9c+KhOuyQ8bf6ebmjanP8VoqBtY6KofCuo3pv38TMtzYjzp7h8MHNNxH+O6X+GnvoGH0UrLl12DkIqmcWz0HfJ45tsxS8CCY0Fquac73yUl+bYtibeMbjJUCaO9k2QQYjGw50ocgNMVuzkSd4PUxcuCXEy8GfgQahUtoRAOxgrWZTF08aLSY/sRC2XfMlmDrmhm4IgLfhOfbGaQwMMDbE+7zngfrg0CUZRf4mvPO7FDb+RPSn1IbCSXd55c1lvRUR6HTXLViIwxC1/LkZ3bVZ54OCHvKIEpN9Qm+jcnILxCfQyDfXNWjSIi3ppKAweWS8dOaOez/PRaAF7S6FYm+7KPZ2DHoQIeNYD/Z1rfgGgQlOMO3gUW22jjDNzRQoIAD2fEbUreOgySbsIVvs0FaJOA82XhDxYlL0RDavzYgSSpLLu/8PsvvX4D9wBJnAOj7881AQeYAKGFoqje51+jwyyU5YImIhk5p+WTRRgZx4lREDwD1bQY0mttGDGG8p2L4PfKXDlgtR49xwAPLA6MwbqaET6xQVyZHxXAKt6hPk7msPY1mq0bB8esaKU/FNMyozfO9ObXSp1k2uU+ZcQM8L0HdFGSt1qZsa/DIQI7aSEsJ+McKzfnp7w/sKUeBLUkc069NQ7yPsCkb2/c6dvEDsXk+OurdTJbyJstNTFdIDs7j5VWJ0KFDpy+xrRI2XZu5DS5qgjbciQ+QA3QJEfmLqGdm8NtGddx0/qbg5QU4bt8sMB+iyACsMTu/8gMfRqN9bIji9brsbwlXeHoEjXtC1Fv3TDRPTA/0NXwpsv2lw067B8/PCehX7fTsi0fmT5/SfugNtvF3QOpbM30d7VKcIuV/UcuV0dgGajZBQkebDJh6flIVuVUQiwDCGiLtjXhvqu,iv:n/FknfheDb3KuBi/pZ599rdwx2ym2S/Dgg8ZdDk0ERw=,tag:zTE1nQYjB0vF1wjUuv024g==,type:str]
            claims_policies:
                default_claims_policy:
                    id_token:
                        - groups
                        - email
                        - email_verified
                        - alt_emails
                        - preferred_username
                        - name
            clients:
                - client_id: grafana
                  client_name: Grafana
                  client_secret: ENC[AES256_GCM,data:2kFJ41tFZcJrk2qv+q/jClqcngpjXvN/cb1O6zo+M9JCIywyLEMQ0gbfX4YxlN/8NzJjW0MaeXhN5h3HBoLsX4PHt8ui1TTSWxGGipLKiTx7h3pWrlC3nWoABglHhBRwMowC7zs5lhMQVTunq8PXSW5rhiNmDduVyn14iyt7jto5AuQ=,iv:0HP9L9qPzbpKed5bOXjFw4IJ5+vwnneipjZBcPurf8A=,tag:2riErzHX/uFlFZHXWFXBSg==,type:str]
                  claims_policy: default_claims_policy
                  public: false
                  authorization_policy: two_factor
                  token_endpoint_auth_method: client_secret_post
                  #pre_configured_consent_duration: 1M
                  redirect_uris:
                    - ENC[AES256_GCM,data:u/uG51fSn5Hj68CtgpfSbwwduLvShSbcp1e78ttaDBGzCmrGZA0KcZyysClbRhmeuMiKS9rmXjee,iv:SBHACXQu6hd0FE+gwsthKvNuXKgnk454fCq1TXDtrWY=,tag:I/6TTDiEP5cjL3b5SLb/fQ==,type:str]
                  scopes:
                    - openid
                    - profile
                    - groups
                    - email
                - client_id: argocd
                  client_name: Argo CD
                  client_secret: ENC[AES256_GCM,data:1rdas9CqpfzEsQyYyj9a7xt/JIF2kAri5PPrxqMppdLfpWX48P+QDOyJlacK+iR9x/cjaX/XSTIfryb023nZ9V/UzJ0VWaYyAusmsyL1KR7q/K/IH62/ZCXnbTaASqtWR9TCeAuF3jLsA0XstEvhzq9D5Ib4waOeTm2z2Qik/xZbHEs=,iv:I57BRZIhaysze7E/Ge5Ng0YV40IOyIkWtnfRAv2Acec=,tag:s8BEpLT0iI1o/d7hhTbd1w==,type:str]
                  claims_policy: default_claims_policy
                  public: false
                  authorization_policy: two_factor
                  #pre_configured_consent_duration: 1M
                  redirect_uris:
                    - ENC[AES256_GCM,data:sTN11BMX+bAKGozWWWaW5mzCW03exY53W7JC4uR6L3zXs+TU+CHSozBlOpkJWoBFpGg=,iv:33A2gpBDpETFkHj7aElabwIry98AiTkAiQUps0wvR/Q=,tag:mhUu7FOFWusZuwWZKaxCaQ==,type:str]
                  scopes:
                    - openid
                    - profile
                    - groups
                    - email
                - client_id: argocd-cli
                  client_name: Argo CD (CLI)
                  public: true
                  authorization_policy: two_factor
                  redirect_uris:
                    - ENC[AES256_GCM,data:HO8BhUuvqkpK1qMU4ZEdLcaKXj62PSAr0zUG1UeCBjDWd3Y=,iv:j13cQ1IgNnXfLC316FSneLz0Rg4cvpbYNi4WKeJ5ftk=,tag:gc5fTj9skWut97aXGr806w==,type:str]
                  scopes:
                    - openid
                    - groups
                    - email
                    - profile
                    - offline_access
                  userinfo_signed_response_alg: none
                  revocation_endpoint_auth_method: none
                  introspection_endpoint_auth_method: none
                  pushed_authorization_endpoint_auth_method: none
                - client_id: semaphore
                  client_name: Semaphore
                  client_secret: ENC[AES256_GCM,data:MYk7z7kFJpcZjE9s6m/UDPcbRlZ0erMyLvII44CkdQ3bAi5QIjClqkv3yPVuki+eLvM5OAZJaIfiYUor+oI9bp58Cutzg6CXzlCrlKMN0/3ItKBbCzYlVkn5YxuhAtjZJd2t4cnNzOE/a5/BuXAtoxT6zkEVNYGyKp+uZJYsk6p5cfw=,iv:XezH/hFgcSAdBJPviZ7g2sUSj1lC+UAfAmp6wSMt3ic=,tag:/v5Mpi7Xql7qgpqsAcgQKA==,type:str]
                  claims_policy: default_claims_policy
                  public: false
                  authorization_policy: two_factor
                  #pre_configured_consent_duration: 1M
                  redirect_uris:
                    - ENC[AES256_GCM,data:Gqtk1dRxy5RCfSQ5yaPqa8SMPGA8OX6I8ygY2jCPf6vaYcSpzwU5juy/gBbymIN+NKhSVnoBpNiAevpkOHdlcbSBHjp95t4=,iv:1nnzCbRM2yqGHcrcE6LXUYqOrL1LTLUjrRNWlw0qsP4=,tag:ghKmZccMdw9SGU+a3/DVtw==,type:str]
                  scopes:
                    - openid
                    - profile
                    - email
                  userinfo_signed_response_alg: none
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOUR6MlBpZmhnV2FZNlRr
            dHdVeGpHbXBvaDB4czdpQ0tKQUlSSzJNMlZjCkFNTWNuRDBVV3ltbnBDdjgvdzZC
            Zlp4MjZQYWlnMGpUa2toOVIraHU3L3cKLS0tIGg4Zk5Qc2Y1WWZibHFIYkYxWFdw
            NVNDVy83SyttRWlBRG9mZWZHMmJLZGcKFiyp+m7JXjHWRns5F6/uEy7JtwIB/92Y
            eV0SvllVivzd9WqtrxUHVP85OypmvcSt8Owl3yWRZPPT4yUtG7xbIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvakVFVDBEa0pqczZ1MFli
            MXpPR3JjdFl3ekdGYzVDYkdrMEcwVjdxQXpjClg2bGFDenIzaGQ0VmJpa25ndTlJ
            cmRzbVJYZzB0dnM2bVRJeks4VWVqRjgKLS0tICtIMG1HZlNZS2M1L1B3YURzV3pv
            UGFPOHdMbytxNDRoUzI3TWtTYWZmUnMKg6q7cbrGmqTkB1Gj35ekfCDRrTb+f7/Y
            4SKjU4CE+w0bqZFygn7j28sceNpu03UmM0Q7xqIRWTYS9P/DUvA6gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(value|domain|subdomain|default_redirection_url|base_dn|user|secret|sender|redirect_uris|client_secret|authelia_url)$
    lastmodified: "2026-05-14T15:36:10Z"
    mac: ENC[AES256_GCM,data:9tk1bNdI2eEfo0G3OThDNTPRyUydWnXwkpdXwqwXCTyQ7BgNLPiPoSkqtQdeUnEUfu7ZXs9LoVe83gYhQnZpR3lvP7ZKugZ6+Pfxe48BkW9S+IpazHAQTqQFxm/X+VdjzjslbVfoQWdKpbiIdM8+rKuK5o1kNyO884QDyA7Ye9A=,iv:PEHmkBT3ujMh1wRezh7elw9DqxH1rbExpTkxRm9UieU=,tag:+iHZ+B9ycze2sSaGuZ9cdA==,type:str]
    version: 3.13.0
