##
pod:
    kind: Deployment
    revisionHistoryLimit: 2
    replicas: 2
    resources:
        requests:
            cpu: 50m
            memory: 96Mi
ingress:
    enabled: true
    className: traefik
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
    certManager: false
    traefikCRD:
        enabled: true
        disableIngressRoute: true
    tls:
        enabled: true
        secret: ENC[AES256_GCM,data:/omu4nOfCaY3pghv9NBMwer1HyKLU5CW7rT92SB5lUpT,iv:2TwLd8vnH4emLbmCEc1k4qaKCqm9dOTcapK0kmlXPvA=,tag:oiyEnTdkpzRewWcuvJus7w==,type:str]
configMap:
    #log:
    #    level: debug
    server:
        endpoints:
            authz:
                auth-request:
                    implementation: AuthRequest
                ext-authz:
                    implementation: ExtAuthz
                forward-auth:
                    implementation: ForwardAuth
                    authn_strategies:
                        - name: HeaderAuthorization
                          schemes:
                            - Basic
                          scheme_basic_cache_lifespan: 0
                        - name: CookieSession
                basic-forward-auth:
                    implementation: ForwardAuth
                    authn_strategies:
                        - name: HeaderAuthorization
                          schemes:
                            - Basic
                          scheme_basic_cache_lifespan: 0
    identity_validation:
        reset_password:
            secret:
                value: ENC[AES256_GCM,data:wo2C9Ggh6Cq92k3fxgkpRLdVmUZSxzx8OEQQb9PrgEvG61C4dFGoNKyXzqabTNcUNmTSz/QckxOui3fKDVCzvLqyMkNRgmHPC95DdoOXpIKZ9PonNhZaBjVe04NuTJraAIXNExKY4ZIcIHwVed1ic/Bw4RfZP9FLQHPgpF0eanA=,iv:KL7dRZy/Y5F0dnfZ6+38hfj7V//A6q+GCOm/2GUxKYI=,tag:ckn8mLbDmlqsbAicqBDK7g==,type:str]
    authentication_backend:
        password_reset:
            disable: false
        ldap:
            enabled: true
            implementation: custom
            timeout: 20s
            address: ldaps://lldap.authelia.svc.cluster.local:6360
            base_dn: ENC[AES256_GCM,data:0V/FphXuT0U3hWWN6iw9svc7,iv:YXPvde/ibmSyBaCHHKrswRhPIch5o/eChOkRM8K7VVw=,tag:b3frxHrCfS07EdEM2xWvZQ==,type:str]
            additional_users_dn: ou=people
            users_filter: (&({username_attribute}={input})(objectClass=person))
            additional_groups_dn: ou=groups
            groups_filter: (member={dn})
            attributes:
                username: uid
                group_name: cn
                mail: mail
            user: ENC[AES256_GCM,data:ktMMZPiBl7T5jU7Vjc4xdes1H/Fe/ZxCQG+226mv7h0XX/nM3I0=,iv:eHcxLJ4R7d1SowmARzSCS5K1E3T2hQWSAkrglvb8ip0=,tag:NFZqdNhTvNeT/D70NkVG4g==,type:str]
            password:
                value: ENC[AES256_GCM,data:7ZcjnizT63iJ3R9hGNQWYP86FCMcinkLSlrMW2c4dLPZNTHFoT7XUWrh+nGdAqfgYbNzqFjmZbqLQigHQoN9aQ==,iv:J7emgB1iBCkt9MBHqOV8M/eMpV4rAwbe3txEhEDy4eU=,tag:oUtQLm/jF94pc+vwW94ZQQ==,type:str]
                #file:
                #  enabled: true
            tls:
                skip_verify: true
    access_control:
        default_policy: deny
        rules:
            - domain: ENC[AES256_GCM,data:n7nMcN+XRCdjeb6vbEVlVcPTGeNUlQ==,iv:Em2/IiqHxNIMCr9ai8nYqmjjTX06s7hY/e8nH2K22xE=,tag:IJ4Jm7xmJWF4ICdYXy8E1Q==,type:str]
              policy: one_factor
              resources:
                - ^/rest/.*$
            - domain: ENC[AES256_GCM,data:U+8hmOb9yYbVZl/aBo2r/KmQ,iv:yUZrevjLMmPaLWC3QFVD8GhyRdSCjFv61KofsjdkHHg=,tag:g9pXw3ikQ3sOWSAyO7wKhQ==,type:str]
              policy: bypass
              resources:
                - ^/favicon.*$
            - domain: ENC[AES256_GCM,data:no423rmGgnXglhQ96Ix9X/98,iv:KhEvO5qf+7PWxoTkPrHO17xGq5rdyTAdhp1RMuuf7U4=,tag:xM7K2D9M86AopFrTJx+4Pw==,type:str]
              policy: two_factor
            - domain: ENC[AES256_GCM,data:paHNQrhyG4ViklLRxs4JvY8=,iv:ooXf2K/yqVUlGi4qF/QXONkX/zdag9SDBHBQ2flrlfQ=,tag:zb69p2rhOMxQ44mhICdV/A==,type:str]
              policy: two_factor
            - domain: ENC[AES256_GCM,data:OYuqQMmPlizzD+A5z1nFKsr6LWCI,iv:L+5aAKCVhFaPMdZRAQPh7YBYSf7E5ATkDCglRms87NY=,tag:tX8bQ4D4YnIn5XoU3HySOA==,type:str]
              policy: two_factor
            - domain: ENC[AES256_GCM,data:NP6t4elqKlrhG/4nassAL+VRmtO/SDmO2uGpbg==,iv:o9QwCFaBLPhOuY4eRORvabjqEj9sZ6zvANKbS8YDT4k=,tag:RuE+I7dTDhm/6GxcjwBCRQ==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:PzGuRQVs7dzukoDaZ1LcCMWeifOfiWuixz2rnMCsKw==,iv:qd15I7HLbXqY+i7OplNuKIuKzv+PuKzAoMFABblcKew=,tag:dElEzMIEALwELNylYg3Ihw==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:G0yr1MxMmJWRAi2V+w8x2H4J8HEh5wViw9ezog==,iv:fpRygPttI/fOPfaJWKXj/poXk78Ap3uFnuWg8corZgc=,tag:j89Z9nmt/TS+k85kkgbOCg==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:NsGmM6dHkmAyzrdrONDb0ilwjeG1orBeVoUahQ==,iv:sqGCqMD7AzSxys3/nuzHFnExaYABy65kHyHU7CWp5vs=,tag:lY3zFYX0ifY1Hg2wEH+KIQ==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:NRnwu4INZFEZlTXk+FCvsy444dgf/a9h6svxtg==,iv:QxCAeZOfkGNJ1FDZ2C5Rfm550lJvOzRTJMFo9+/LlJY=,tag:92clY/onp6PMzWabPC+GKQ==,type:str]
              policy: one_factor
            - domain: ENC[AES256_GCM,data:rsNEgXdlbudA3kGX68Nt/fL01XDDS7U=,iv:lnsjzFRbGQABgGf9BE8D/hUdj+Y/Ed1Gu8BpXnkQZQE=,tag:nw0TnPGdzvW5KbSoKK8eKA==,type:str]
              policy: two_factor
    session:
        name: authelia_session
        #secret: Tu6mithie4BaiXaec6gei0Iewoota1ie
        expiration: 12h
        inactivity: 1h
        remember_me: 1 month
        encryption_key:
            value: ENC[AES256_GCM,data:XitCCcCVJaMZsWvxbWkBmCnDhAFquJMS3sXfI+CRmxfyL+a/DSGokGdoQgglFs0M0XRCCn23yipX9aE7928scz7/57B3RPaFPY1zWkmS9bOCaCpFoDKSOEr0H8k1CvpysVcu+6v5rYEjuDEqwZkjQ/N27xLxaTkBK8C0vyuSlpk=,iv:cZAa4eeoXG3YZu1j7Pd4OGcYWUS2ReEnBbY9X9ZosYw=,tag:w+UquGFY9UWyBBauRulqZg==,type:str]
        cookies:
            - subdomain: ENC[AES256_GCM,data:tiseR+y3YYM=,iv:wJAFtt6tvHOY/nXSEd4ddudSB34l8ub5HU9thkTVzM0=,tag:ECtjzolKvJrjbFJRlMaJHQ==,type:str]
              domain: ENC[AES256_GCM,data:Dmc7EHQh14qjMn0c,iv:JGT4I7A7wlW9gJF5FawavN4AshfNQLsX/5keqwD6uAk=,tag:IQLTlKkA5LFJW3P6hnuxoQ==,type:str]
        redis:
            enabled: true
            host: redis-master.databases.svc.cluster.local
            port: 6379
            database_index: 1
            password:
                disabled: true
    storage:
        encryption_key:
            value: ENC[AES256_GCM,data:/rjWGAxg6b+FZ7D3Ytdo1Hhk5Ld9kK9FlH10edgZMjFax6gSbR4Ib3qrRNBGNE2VkTxnoepuURv0sObfaR30iA==,iv:KawaG6O2J9X5nmL2etjtkthQm40FprymO5A00HGqJWg=,tag:WfYQCu0/AbqfAg98XaNtBg==,type:str]
        local:
            enabled: false
        #  #path: /tmp/db.sqlite3
        postgres:
            enabled: false
        mysql:
            enabled: true
            address: tcp://mariadb.databases.svc.cluster.local:3306
            database: authelia
            username: authelia
            password:
                value: ENC[AES256_GCM,data:4e3epLrFdS5qdTFLEdk7mS7QysmYQdPQQcZUr8p+E/Z3f+hwyZz608MllI2kQ7OLDU+RQxgmsaitPKnz+rbpLA==,iv:lOlQOO9f2BbUUPvnik7JgZ4qB60TEHHbn8KvDimpJV0=,tag:zCLbEMYV8e1WBSziwUgv0g==,type:str]
    notifier:
        disable_startup_check: false
        #filesystem:
        #  enabled: true
        #  filename: /tmp/notification.txt
        smtp:
            enabled: true
            address: smtp://postfix.media.svc.cluster.local:25
            username: ""
            password:
                disabled: true
            sender: ENC[AES256_GCM,data:hTMPxVI1AJN04N54o5hXuuq59PcyAzlLftaFMQ==,iv:iqaehaX2Yy90cYc8kgXHKJGZmE/i6bn8ocyJGnrkMf8=,tag:qUVIlj5cxpr+MFSx/MbEeA==,type:str]
            disable_require_tls: true
    identity_providers:
        oidc:
            enabled: true
            hmac_secret:
                value: ENC[AES256_GCM,data:/6lfNrQJdt3iq8h+lmHo8dFaeb/T+sLhLxbg2BVPX4I=,iv:tYrL0TE3J8u9FGt7ydFo2rmmEk/TqpHQ3ftUupJnTfY=,tag:VWYxxyZb9hx39aQ4RyOFAg==,type:str]
            jwks:
                - key_id: default
                  algorithm: RS256
                  use: sig
                  key:
                    value: ENC[AES256_GCM,data:1pwrFL1o8+1DX1XxmPb3bJjpCFKiMYfp7Hxm06Wm2wWSuuSefehWNpJE6AzIWqgWWK7mR/rSLwcbgQMZG8tjdGVwIjVazTRS+wzGX1kG1DFWgu6wOPriNkDKfhmhG5LXNx4MDnfZrQxNqcUtYkLVGuUcrzFJoWFT0Faltk1WyWecVspYpe6k6wWyjlN4QjcFIcDsHMGV0tVe0yJne8RlyC32lbsWVIsgjxqrtpOohomyxTOorHHrl4JaMnr7At+swJEprO5GufeUC0rd53j157g1Oj1B7fHOVkTHhJo2k4XOeiRm/Ep3u6XAsmIk72kjhZsRXVUJh53L7zkZnjVwLMgCENsqrWGqOhx3crRgv/9dq63MGbFF6hI+OXZBoP3zYphWnbzSaUHeErCA5VZKVZygZw77YiUn7SxqXjbIgYTCjbABV9INsLYXdr63clHFXYj7WcvzkoS3nxiAzzgnRcsSJnnq29nh0N96nrUyrZbWOZBeprBylC/4vtO1F+sEx5eQkp6JBDoVxfADv57r53noZEIJHXXAxHpQxeMOue1ziGganDtNhzMyJyjiiDNBZH0YkBId5RDCNjxbbwqlDZUyLFl/FDeQ6lglxHrQs76fZ+Ll84jfziWx5wUIiuSwYrSrXk59Sbdpy8V356m7AIS0CkhKFM4gKG5Rr0SM0DO21Jkbr61pJNm2NhrApyUbnVcY8NJWvAS8k7oUCjD27u9aG8kOAoBbeaeZNZxlACK71i7LCnO1c4YUh/yk1+Eoot2/9drrcWF0pVGRPVOTJ39cG2wRvSCVWeLbfaPDNqPlJaKmR4H6jZrLseh+TMneFCrMCHphXJWeIXwJnXALVs9y2csmwhpMqXevf3+wxMprLgR4DZGcNx2Fg2ZQDV20VFZkmlkzzlsg7NC4Gde2EP/LkfIVdR8l/p9MzOK4BprDMdALPbAH3qXydFbSy/hTvkELGkz55WJ5mE8gYdonJ3FPXsCgl1T2FG7oRH5zk9kudsbjUy3ylZzvAnqBjzus3R0HKKHDyNDpC0EgP0qdCl3fEp8JVO2opFMho+LsaMEUxXWXRcebGeBbaD8J3knFFtND8innXX6rhUNh7O9GAcjQ299hjh6mLiMekB2/lcmSHzkipervTtX4iGL3sUSZuozOl7m/UpMS8274HlN99EYZhARA+eY3jprEk02m9uDzSqRbwo0ja1ycMoHGW7X1//c4SMBfSbmMsiOgf4jF2zInd8hcfKtvGB9JPlLb3WoI2658mPVtLYu5Njwy/RcmY2H55o/kulI4RVG2iHIeCQ9pd+aQvssvbvlhG4xPy3dBzN88eebx9d1i6CDSlwCOBFXnIKiB9t/lE7mE/LuNEGk5gLml23W95AIuJLm28T12wWQqv82qRasRvVNGL1zpM8PUiLtj6gQPYtGVctC43QuTsWatV0lPtXKDyOF1NBXKWwwoi53k1G6ecBP6KO+WE0YmyUhRO1BTs06Dq9LcguwEykgJaiAEobgvXRVzhRIwWbj2Qv08SKU0g6alPDr3lgVA34YDd8KMGE6bMx3ts06ZzHcCX3A2Yhgo36biFMmZFTi4+2yUL9lUq37gWyQX54w3YOsfU1DMqVJCLRUN+CdhVZa2GeezZsIHzRNh7pv80okXHFj4zWDfPeGUjcvfVES4vB9eSWAqqGRXVC6oR0pcqNJPWZyMwev/5x5ni+nQIslDEP4D8ePTg045VxKrTyKl5Xmk7o5I1w/yAsmTdrv74RuaKt+ciXUZPqPwmEhc4/xcSyhyAEFPSQ+bmibYO1ZTWIsuVX+CJkPjFwNQPfSuXZNsnAol72j8iGbGMfPrr6pkJHLGSDF85jbSmWqT7xT5j40VMwLPdorh4pfS/F3Hg1UQ3cdgIrPr+1epuuhOgiOITRRmk7zKE5O6xNid895YiJdbTRDNukJKcSTMvAZS3npJqq3hutB781tPB66lKqiD+N9vYvVM37ukgoieOwt5JTRALb+rWxT12EYwYGV2xoXu4lC0wtABqrqGOgOz9v1qgF4AaTqCxhYMsrBAYxKoczkbv0JtuuddGEcGzG6plP/PjUxoJBuRWTkaPFfMvNj7nrmUc47lfgCqqRpr2pa2O7hfTj6BhtAEhjEdnLNv7kxnLEEv/m/vDzxfySghgWlhCo2ovi8TVaT23c7HLeveuQ7gAO8zg6F2+gOv71stpDYVEfpvj3JDF3B4WBVxHEXBTZRG4ayLlHtEZX+M9IcUKgWMVz5VvV5V6GgKiGviCZ9hAVA9JZnhnaeiCp06htw8mToSDQtHMVIAFLVvnzwgVBIbDMsOapxakLytbdJZ7AAG0mEulcHV2lUWbvdlLx/MQsOHwLNGmmmVtkiUnBOq6bUxD5qjGPi6wikQwQ2QTaSQKFt+QVlsIAodlvZ+lSkCoTMl5yTI8yK0tE1m8pX4fWtjGbYE+2skI+J72nQTAqNq9MhmY0x7cZ51JJ9p/y90GURxxTG9tldmwM0D+Uij4nkhlBtSRXb/Yyz7lv/J8/CGLT8eAiQZReFNcG+Cy1n7CE6vJnunZo1Zt4e9rbVQbwGHIPH7rPsk9LzEqg4wqaLdYWwRRlNjMHzbS8j4ZLssXgE8YZp79OdRkURmDPziAQdTNyfPk7Tx+qLakKVTpRBHejSuP8o7+CmbU51suRH8hCedIfY+xeHlK8mnI4Baw4zTRFY7gLM94DS50BBgC8xSvCQrK+NXzjz5IOFZocdj6chLCNvXo8RqAITTwPgVuuOz25lBG7Kpqt1Xm/DsTFEu86drcI7S+GJIe31gJXtRxGlhSO49YBLjj6r1X4lTUthKV1PyHsJaLBtl58cZbk5oJN3lBnoy81uZw1o/rgmecnfupSxSrSXLxxnShdHhy4QBGAVPKFFM7CKDzSQ1Q2s6IkeQminiDDGJEeiBE0I4WfkPkyZxAeTf3p3KS85ZaG4M/r4hc5LsQkYXsf4bxTUUPUItbl7jZV4BxkeNdVXvgQoERzoojStGQ7H6KwNSBl8kgqiX8WHjKII0qH2rsa6IZQq7jZDjA8G454OdWw/kAxXtNoXquVZ2i7IOAtAWa5VynxpLHxX18DEjbBkHsbHyfJOqG0f8XALduwrqLa2USTSw4Ne6O++bIdIH4YpdoY47hy9xLWj86v2i8uRCtkzNQOUA/MgWD2FtGzzolF7u2znfTpslFPGp3B9P3sHuhiNrqVNtuYjHTcoc5+/2HeDfTUkhrV3FliQk00uCaQ1+PSBwih6LiHaw7ACLnqC+wOZe5t71ZaxV6EV5BCSIHE5lRVPC0OYKQ3mRIWMHh/eUXHrQh1eshOySNsjIEMcIYN28Gksal7uIwMxmKBqn+wWYdG4JxL/1cNyl8GPkTX8E0l/bIUlbvSMC6PsiGDJxtIs56Ggc38fGmriGlX9EbDqcuukpXQSm8j0lXoSnnuVPjevbTKzGg/akdNMs5jlHhTIniIc4J5t5QHwl0nym9BII5NK8tobrL4it8pYKfgfa9Sa/YqGN5B/kUd9xqIdIA03GOMhatEMnxC2Rn2vprl5m4Q460Fr2ENG+oqchTfw5+e23ptyEHueByXZnjjDRQSZBfP8/OAumB5oeEmOBmZWer9DRjF3A2wHtfC6otRhLCfiNAkv5ALCBgr7HcUiZXN5xh5gNMmap0uUVIE4bshgqS3YtCBnd/vpnG0dPQK5x+lsjDUvgENFemUBwpdQJF66zD7oF4TqgDHMaAvHkpyEO3KBPEVuzTZyDR2Q7xG9ojEMw9Y31Ap0bLomdtvUVObZ19hPKbzFwTRYRsrNdAovsQoHoG3R/9nvfU+m8Jhkg7B/dT6Vej4T462kloZNLEW/s/MR4q6hdncBuDFIsiHKMDYm5lFKCKWjvkXnDwXlW2n2LRsa7C4jl4HXoZNCBlivRKKP8b+h55MU455u2YQhT5hPMz1YGqM1HYPPOkAmDDxjXfIOizUfbWNVPd2YrMNP+XSMt82KDR+2Kdpp/WgX7yLfKWT7MpX7BCvWelcqd8QcWsilI3s/xNwIFoS0doUPdEwILKlmtqqUr/jiMIJtvlJVlegjv5FUaFzUWugLq1MukcyDgzu+2aUZ04MSGtROHFmDTr6xrtGwUzq2FTLmTJIvpOs9V0X8PcP8es5pGH9qMpZnYa4WUMln1U6znhmXXWEkwkwWpEQzPMrog4qJnNzxJn6sEBOeqFw9M4b1Y6P80z0OlxwRYYrzA9EIqZu16Ud1htXgq9pOV8aKLj7JqdM9xvuRPiTIxyApjSvLTh2/Xc1boVMLyRMrX5kZYRnCe+k0+5A634ViVs1kU22tWwdSnRb57,iv:HlXQba8KOjgGYJJ+gkJAJjTFueWuegmaOLoWOU+H13A=,tag:IIfhp+7xHBZHZsJ9ouhq0A==,type:str]
            claims_policies:
                default_claims_policy:
                    id_token:
                        - groups
                        - email
                        - email_verified
                        - alt_emails
                        - preferred_username
                        - name
            clients:
                - client_id: grafana
                  client_name: Grafana
                  client_secret: ENC[AES256_GCM,data:LWbwPvN7xe1ocTpvGhDhns4rQnhy8bkpPVfbq91tIj/2i8vUS3plP2TFPrarDUaqfkJhT6JXFV+0ipv98h0wuYPm/PHIxTCq6WMt2Qo3QeKL6UZQe6tEIZhcx8qPRqsg5h9+7s1U63wwlRT7sxjlLC5XwPmLe5sbCWokLqOvSsnVpDg=,iv:P8KkBKvl4y692Ils766Itxt82q7iJH+Dmy3sE5lUdsg=,tag:XvG+gm4YDqZLVqrjwYIj1g==,type:str]
                  claims_policy: default_claims_policy
                  public: false
                  authorization_policy: two_factor
                  token_endpoint_auth_method: client_secret_post
                  #pre_configured_consent_duration: 1M
                  redirect_uris:
                    - ENC[AES256_GCM,data:n3rz91aMfQhUv/lHco1PE8yI+vDccE3bbKLZcAP2qBbNDIqh9dWTp/TF2IYSIoD0EVA8sSkYZly6,iv:3AUb58ytJGM0i+IYznHWrcBiLKLi9S0WygC2aO/C5Ik=,tag:SZltcLSHYV6r0pERGJIxOA==,type:str]
                  scopes:
                    - openid
                    - profile
                    - groups
                    - email
                - client_id: argocd
                  client_name: Argo CD
                  client_secret: ENC[AES256_GCM,data:aGKotFeMdAyl/SAqI+eByNZWYru2rSTaduJ5qRnGlst7k599vDHUpvi963G8IPIYdq4Hya7WaEWoC1QYMDNOpeKQuzx3hTvoBov4TyleW6CFo0jHpjeXJBcgLRjOXWMJq1r/e7382fTYe96/Dt78pCATbFJ2flwgoPWOKQTfTQuJICY=,iv:Neam86WGxFko2zkKxc/F43PC6p46cb4SHdW05u+K23g=,tag:TvEwezKFqMHDxPfS2969Eg==,type:str]
                  claims_policy: default_claims_policy
                  public: false
                  authorization_policy: two_factor
                  #pre_configured_consent_duration: 1M
                  redirect_uris:
                    - ENC[AES256_GCM,data:OOnlt1TCPzU2ombCRxxmBIk2dAmh3rCVkZytxya69XuXI12kw5NCqTZLYg6qEpHex5g=,iv:PwQWu3x9jhHVp0DBkiZIPelMJEt+VTm1e7Pb9wEaZN4=,tag:ashjYSMfrFAQmv/vPg0Bbw==,type:str]
                  scopes:
                    - openid
                    - profile
                    - groups
                    - email
                - client_id: argocd-cli
                  client_name: Argo CD (CLI)
                  public: true
                  authorization_policy: two_factor
                  redirect_uris:
                    - ENC[AES256_GCM,data:O0whjrNplCn1KQtcdtXj6VH8ANA5nGiaRTiIJy7oe622ysQ=,iv:E6Aa6tnwgAKXMLjUnbuz3Mj12jKgHcgppJnv9VpZAqI=,tag:FvvBS1f9bow9dC2/VWDahQ==,type:str]
                  scopes:
                    - openid
                    - groups
                    - email
                    - profile
                    - offline_access
                  userinfo_signed_response_alg: none
                  revocation_endpoint_auth_method: none
                  introspection_endpoint_auth_method: none
                  pushed_authorization_endpoint_auth_method: none
                - client_id: semaphore
                  client_name: Semaphore
                  client_secret: ENC[AES256_GCM,data:PUSR1Y+so4SHSuoDdBrMji2ynAfj99LG9jq6v3xjMzW2TCWNRuVg/dudYOIN/5baoVbIvTtVcHD+1Xx1sVDwcJ2D6CKXCeuBXD3oQnX4B3ZgFFVh6XD9TDhlXuADYzQlyU/SSL1kyxQiq4HLTR0/d5PyEjlOrhAZu++K/RJa0rTzo2M=,iv:HD2XoBsxLjlSUyUbNY59cxa+MNSij1Z07mElyhTupNA=,tag:wHIbCXa7jskjHpfFH0Ntwg==,type:str]
                  claims_policy: default_claims_policy
                  public: false
                  authorization_policy: two_factor
                  #pre_configured_consent_duration: 1M
                  redirect_uris:
                    - ENC[AES256_GCM,data:fR0vNjUl6DgTfZ/++vcX7upRDgZ9oJQaxtT+vz1dr6aqRnNKotwTgGfv0HjDs2EMVuGOFkzwLVz5Yt0KDmP8cQ7W3IHzZwA=,iv:ybm1Z1QgyFRUO+eyKDbQjhhugRTIdQHFWcJjY1G6nu0=,tag:s4OTsbsrj6yWEw1JWAQ6fQ==,type:str]
                  scopes:
                    - openid
                    - profile
                    - email
                  userinfo_signed_response_alg: none
                - client_id: openwebui
                  client_name: Open WebUI
                  client_secret: ENC[AES256_GCM,data:02CIW364Hms3Oiw7I3hf2i5BKLyaJ4Ch4svLMAVyxcTNpBg2gEITlgDvh/CT++O63eYGAd+wXgOhrTJuuOlzksIH1YACXNTSqi7WqyvoYdMPs8WXSYPIQB4nSvWhOy0PI3uOFQLM62ODwdFxhvZ+8fPBYrB8OFL8E9RV1IsH7pRsRA4=,iv:Y2DsZxQJjLdPBjo/mC6fiMxPTQ9/5s4/Aaz/6jO85oU=,tag:tRtPrqqbJt383v/w4Fiviw==,type:str]
                  claims_policy: default_claims_policy
                  redirect_uris:
                    - ENC[AES256_GCM,data:0jWJcC0PImaK/vKQa5tybe5SzhYxyMd+jqfuDNTHjvycC/bCCRg8gweVgRfw9yQief4dGtzE,iv:u8Yna7NSeScDbQZF8R93Pi/Xzu2MXiA6zKCOWpuaeTU=,tag:l1lZHUgayNWbtsjN+KxOOA==,type:str]
                  scopes:
                    - openid
                    - profile
                    - email
                    - groups
                  grant_types:
                    - authorization_code
                  response_types:
                    - code
                  authorization_policy: two_factor
                  token_endpoint_auth_method: client_secret_basic
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSDhyUkdwU3RrOHowakdv
            ODVaRXczS2ZTV2NmcXdCeVV3TWZRUXVleHg4ClB0V2llL2VPUzhTbTdhMkRlK3Mr
            QUZvRUhCaU1RYnl3RWJtT3BZS1I4cWcKLS0tIHNhZUo3cG5zaC9SdFdlSDRxWlBH
            aEZyWGplWnZQTWJvMENvZFJxUURzWW8KnGuAUhz4lW3Cr0ekX2B5UmczuCHV87s1
            TE73nLLQnFae98gDuWxl4T4JfJzZC6B48r+aobyJnuFjaGcE8cNpMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRDk4RXlyUFFLTnVhc2pR
            cVhqWFRhNkJuaUluVXk2UWkyblNDTGVraDBzCkRtU0ZkY29hRmxKRk9KYStDMnRa
            UGRTVDNQYWhPZndvcTh6YU1DTEVCejQKLS0tIEEvbllJVDBvR2JWbmdkVXo1dnpy
            Y21IbkRpNzhSNC9hRHEraTlpdTRWVGsKNSwB1J1DdQEluiYv4exvkYmJr76NA63t
            z8qtNUoMO6btRbsrXKXDZH9JKAG1rivHcxVgvAYpAEeuQhTIBqId9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(value|domain|subdomain|default_redirection_url|base_dn|user|secret|sender|redirect_uris|client_secret|authelia_url)$
    lastmodified: "2026-05-20T14:20:21Z"
    mac: ENC[AES256_GCM,data:0iZUyo0S4jOlEr6Ol10jfKUNWuoyzNxN4RSjNGaExAWQAZMJr0DwnFUrvjIruBB2pgNZTU4bXtUv0qbYhq9xG1JQQK/h+5IAmxrWNjRsaPzM8LHjR48264NdTHOnP4Pz0aXQypQzhZyylLMt2EfmmPOxMUlfdE93kSPi7dLGjGM=,iv:gcQhH15t/kolkMHVO4xTkjXDlU486GQ9UU6oNzMhF9k=,tag:7O6zJlOuut/A7HGH67PrNg==,type:str]
    version: 3.13.0
