apiVersion: v1
kind: Secret
metadata:
    name: shelly-exporter-credentials
    namespace: monitoring
    annotations:
        argocd.argoproj.io/sync-wave: "17"
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Bvw5tZ/O0KJUI9ODSHLbs+eLheWVd5QSY8WvB8FyhiE=,iv:FYSFUlmWzRRQY6k3hx3PnuuJ+ZWfbQqJyqCplyOU1KA=,tag:vrgsnZWC3DAJnjz6QAyVHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVUluU0lwekxIV0d0STAy
            RTR4djBLVUNYRXlSL2ZXTVc4amdneHJRRDBNClJSeU5NQnpyaDh1K0pqOUhDOGZP
            RDlidkF5WUtkZWpYQjhUN3JZVmduaHcKLS0tIHd1ZmFQcHhxY2VKNG93cE1mUXVL
            R091ZktheFdndHU5YVNqZlh0MWk1ZUEKKXo0Q455J/8ogAvgTdQQY36K4ewbabn7
            1NAUcP5CT72JCT/BMimHruEJgXKD0g1o7aCPKCwA1qOWvnXDQRdmSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWCtaVjl3cDJPRFMvc2JW
            dnVhVnpCc2hWMUdzMFQ1OEt1M0VHSXk3UmpzCkgvb25IRVdRazJjYWUvRUdza2E3
            SUlDV0hLMWJrbk5VZjdPZ1BWTXBFcGcKLS0tIHg5bVBpZVZsQnJEL3lqWEpiQ1VC
            aDRmbzc2dWNvbENpajdRZHZ6UGdnNDAKJsVvAdvue+rykLSwme9bMXzahqqsoRqA
            e6JQbfvEgLcQbXjSUXB0xrXAr2gkZMTvWhmQ6AIz5y/wLr+vPUMX4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-09-09T07:57:33Z"
    mac: ENC[AES256_GCM,data:H/j6GoW3cNaawS6kUHkfGlN/70z3xGoTA1wprtWObdjZclA9qlRDwg2h+MiPIjjQj22W5qq3Sx9CI9bM+1CkQMVVkCMrov2nUBdY8Ke/MBknNhLhJ/05+H3IPDbAxwysPqgTWk9c0RH4ap4DqXc/mYBHAQZpnmOnOXdxfcOS7a8=,iv:42n2POZeQo5popuMB3iAi7WgiESqlzvRXIrAuwv8iWg=,tag:9H6wRCAPF+wbJYnV5d4fow==,type:str]
    version: 3.13.3
