# htpasswd file for the restic REST-server. Single user `backup`
# shared across all backup workloads; rest-server uses it to
# authenticate any client that hits the HTTP endpoint. The plain
# password is also embedded in each backup target's
# RESTIC_REPOSITORY URL.
apiVersion: v1
kind: Secret
metadata:
    name: rest-server-htpasswd
    namespace: backup
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    #ENC[AES256_GCM,data:bUdH7ekhUJOz11t6+D3PpjPv0Ip1/kv4inNbh+vx+QYj6ZJ4Y1qHshtJodkfOmr9sa1wY2PRYxCYaVsM,iv:wf77shjE6jaQsM011L3Nof35A5bag2rFKNj5OXJbQPM=,tag:Hxo4POWb8DVhK/Ya4IGjeQ==,type:comment]
    #ENC[AES256_GCM,data:5BDyH+lh/V3LnqE311muyGF1ZGtUNFSJM8jBUaMm5iTIWPTynt0Bh4cDb6LxeyF/vM8q6bu3HcarkLjbWe9GDw==,iv:fkkgNggAHXSMJDSEvRpwq9RBIRg9+QJWmPfi1lwPv8Q=,tag:du0Swpkn1MbF73Vi0+Gg0Q==,type:comment]
    #ENC[AES256_GCM,data:qSybipeVpoPw90/Xn9MYX5py5d92eQPVIgdDhqOq6u/7gT76fmo1J9MGcwwKt5NfKlclB5QWxM/wxYvskZOc9HI=,iv:8LVAHVoYRGHsNvqJX9UlOrlNeAiY/5PeRUild3XpqEY=,tag:gRbBcJPOCRoUAcj/vAixsg==,type:comment]
    #ENC[AES256_GCM,data:RP9T64S1pVZp9H3SPE6GdDU=,iv:y3HyfzswTAQ1hTIoCwQ9IMdgbM/AEcXgoyLXWMqjiUY=,tag:lnRgMwovnpjA4vD3obb2Ow==,type:comment]
    #ENC[AES256_GCM,data:3+7o2ffFFu6zVUpAl3UYaPKkQeVzoR8PDJmqF/4hT0lorntermaWQHvSkm0R8XWoX5LO9vQoD/lVct10hADTe9cgtoZqRKw1MOarovLZ6Y73218jl3en+jHAumQx,iv:qB/lvnSskCzEAp9NaOG6HFXF8si5eKw1Ew4hrnMdBKY=,tag:wp2iFfcv1Y3z7X9MN7i9dg==,type:comment]
    htpasswd: ENC[AES256_GCM,data:oKHJWl4Zm+5X1gFahagIGbs5FbOXROJVOJMWPsO6EoIzWYyB3PQztWlovRjso+JYkhNlAco6l2eeSDX1qhkM6LllmdQ=,iv:ENYzYES0TxEpQQWpeZ5OZx+eBpzCw6C45q8RRUH5QGA=,tag:I4LBvb6+leDeUA5wk6Pccw==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3alRGTmpscXFvK3VJVXhT
            WFczWjA1dzVEWmZ5eE9QSjNOb0NaZHA1ekdnClZaUkJsbGdVYnpzN1A2OGg2a3VE
            Vk9PNjZTWVN1YmNSSmFsUzhjOXJmZ0EKLS0tIHI3K3RCaDFwYnIyYWoydGZDUTNw
            UklIb3hrTWJJL1crQ1BTWjlKYWlqLzgKiVOTzyF2kEmq0T6+v8cb1fDYU6PHo7ZH
            6Pa/N05bHLI6lue5C7OH/IJGIKKpbqaiURUu53V2EkXUt+LLvsMj1w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTnRYcWZEU1pReUhlbmRN
            ejZsR3JZQTdyei9LKzFBbkZhamVnd285Z1hFCmxZd3UrZW1vSkVVcHpTK3NwUE5x
            akpueG9YVUtVeEE3RHNYUnJkd2lFM0UKLS0tIHZMeVovbG5ZVjZJYURickJHaGRI
            MnFMekJ0VjM2Y3RjTTJIOGUvWHFnTmsKEen5qHMJMZp1SZfaMnPViqRwXbKjTbb+
            V3VN6xV8OMo3MrSsMTowdwI1lIQVrHgUljKI02ucMlt+wQm4vRRijA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T15:25:32Z"
    mac: ENC[AES256_GCM,data:Vcfh0qHZ2QFspZdomUauzFsdirr9As88sLDTuzt4lrlOlSGweqF2eDveIOw3GZ7seL/PWtguGCYaLmqEY04MwrFQsSo0WOZ32Cs3kFq1gZDS+sbSkFyGRAdkPpYVzOlC9qzHMGPQSBDinzgfiyMp9Xl5reOEndcljoPhN0TdpRU=,iv:xtmPtc1zEijQPdR1tgIv7Km6+YqWeEr1OtJ57aY2xcQ=,tag:fqfN6ECkj2G+6ubAGOuqCg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
