# htpasswd file for the restic REST-server. Single user `backup`
# shared across all backup workloads; rest-server uses it to
# authenticate any client that hits the HTTP endpoint. The plain
# password is also embedded in each backup target's
# RESTIC_REPOSITORY URL.
apiVersion: v1
kind: Secret
metadata:
    name: rest-server-htpasswd
    namespace: backup
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    #ENC[AES256_GCM,data:LPI4t1FXh8iSyxKDYkjeKMIEJCb0w2eawFkoNo9AJh6JqDpLhzDXd0JuKkGSvW0ellLYFzq+KtRSUL07,iv:xaBA1LwCKvA/RjHqtMW6h4f6KH3lKst7KrXs9jRPYc8=,tag:7URr9mJsvnf/dxL+dZwBBA==,type:comment]
    #ENC[AES256_GCM,data:Db1YuehzDibHRswHql2OgiBtKEVjY4YnIHnuaUSnbFHQVKwYxnk+Yo1L8Hazqni3USO63PIvK8SN/+VcHDWg4g==,iv:xUs/9WJ32g05E6mC3gV4YGqNVqjQTFKN1gxqUypTJWc=,tag:ZHz8CaG3fj/PXI/BZKUidQ==,type:comment]
    #ENC[AES256_GCM,data:OC9H90ANduMwggltV5bTSscNJRiFEuybQcYNtMXeuhzYHvV+WCL4OpN0PEDSSOJHXZYwasnuUrIfc136jO3BX7A=,iv:0MWzo2LuR14WxXbtSvQtkzGtLDDxLJxOsyyuXsQGWWk=,tag:kXKQNjfT9K2VgL+/ggmRqQ==,type:comment]
    #ENC[AES256_GCM,data:wIjuiZouosCX//WVnQTcJuQ=,iv:eSDvs1aXT+EySnKpJJiqA0EuxYzcQmWlDAzRIWxTcBU=,tag:VK3+cveTOD1z+QtuWyR3lA==,type:comment]
    #ENC[AES256_GCM,data:wRpK5Kzjp7OgaZSA3qV2ZiDwIOy1FXyux1+3UNDLEmebcFOCisFN8otssBThDyw2OCmHJTt3w/ngRcgDngitG6KH2Emvk4KzLng/RqMtjZLCJ0gjgQXaPwf2374X,iv:+pwAHxTb0xXsxFJCZK/yZCxAYthryJYyxzh+UOrAhfQ=,tag:VdhWTceC+t5heewnpRkFyw==,type:comment]
    htpasswd: ENC[AES256_GCM,data:EE1Uwu0LTEsPZoEua5VePNFqAKTJE+0JkyJwpAftKMk+vtoG7VB7lachOewgD3fYG82G9HupSzEB/McbcvCtmfs+88o=,iv:JPtuV40w31l/Ww+n9OnGtcM8IlbL0wFMBVDTY+dQoqA=,tag:d5W8oIgvsVNCRc65YP7DAg==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VnlPb1pOQXVtQlB6UmJS
            b1IvN0tPMHl6bElreFBwbDRraWhKelRDcXpnCmZ4U2ZtUGZ2dTVmc01qSG05TDk3
            TERKUEZaNllBb2xZaDBHeUpDQlBHRlUKLS0tIHp5ZUsreUlhQU5URkMwVzhoYmMy
            ZjdHRVlta2NPWUluWHlocXllNTlPREkK04tSYXocryWhcu+zssl29VHDJJE8rLaE
            lgJ16ByUSZ3vFIWuDDwh5WDHzguMWeqwlx83Bn1VBtM8frwZRzIvJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMzkydllwYjdaTU5ndVV0
            TWRmQlVQRXNubmpzbjFDdkJ4YWZBdGZTTUFzCm1oK0VaUTZBVGNpeHNZQmU4aFBS
            anplTGNlOEw5ZWhWT0FFbW5BUkJQeGcKLS0tIEJZNVJNVWViNWtkVjloNUdaWk85
            aVZKVzJISlBBUVFJaXdIQ2dBMjRQWjAKNX4PJwUmY/YqY9ui+sQwVSJ1sbVK8LYX
            3y0pe6jbWdthbqQwU4lpl8aHM3th2COfZElQIfBKN1IDR8BmFwGw3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T18:38:53Z"
    mac: ENC[AES256_GCM,data:TSRWcSb2yCMiB+HV1Ujxjku/sIkt0xVTqHmZ9sNqO26Oq5SY3g4B9E7X7eGz3wH6yq6xiz0NYN9sk9BO/Lwjc+LfT90fy7i9JJx1SepQJR/n7uJzh6MIgw3YxFx3k5WIMFrTDOnbl0fgdyjxE+yHak0EVtW4v0CFnQ74F4gj2Iw=,iv:M+uqKw+Z8yRsIS+t5ACy0BZPeZAY6QH6Gbg5nY8uGpc=,tag:KAlBH/2d909miYfh8q5+sg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
