# htpasswd file for the restic REST-server. Single user `backup`
# shared across all backup workloads; rest-server uses it to
# authenticate any client that hits the HTTP endpoint. The plain
# password is also embedded in each backup target's
# RESTIC_REPOSITORY URL.
apiVersion: v1
kind: Secret
metadata:
    name: rest-server-htpasswd
    namespace: backup
type: Opaque
stringData:
    #ENC[AES256_GCM,data:ovfPnMfaUX8InF3F8SUoANe+mZhGtJDqzcZoR1Gk7V14bqHn2lVkYJKLLf2AWe2D2TraIUX85+oAXvf/,iv:sLndzV591GGiz7qa9QauysYDaUVSjvFSbQHFlnSu584=,tag:LS1HMBplDbqVBVh15r6wuQ==,type:comment]
    #ENC[AES256_GCM,data:dnNaIzEDKhcd7y7h61syfCCxS611LjVNnFyIySOKOUv/ITxI5kuALzW0TG8WejX9rs1U1QjF23zdOE5/dMef+g==,iv:wlXs00GgHGFvvC8cW8H+FiSCExh9thubYchcD2VnwH4=,tag:4GvkYSjCcXiaUMaQpBmAIw==,type:comment]
    #ENC[AES256_GCM,data:1JAYel1f++VSPH5qBE8+7Aftv/89MnAaktby3O0imdGmSDTNmhWvkBkECxBajEbQI6ZfYWiYDy/BlE5f+QcaCmo=,iv:W4ZjBoBr64nWkh0giYMIIOj67JTPGhBwbsBbKZJ0cPg=,tag:bzC3PuHdRAyeJjyEgwvdTw==,type:comment]
    #ENC[AES256_GCM,data:XFRZ3dKhmiZLcwtq9Eo3aOQ=,iv:695CjPmxf5s0/RLrctRDAObFqnBpvaZKZcvyPQNwmc0=,tag:Vv9zQ0+VTgAWJhv/2V9yQA==,type:comment]
    #ENC[AES256_GCM,data:0E2r9efrdyat/zL7ScfwMr/buXD3ZRnKVFYUo0f9EuUBj69v2z9RCyGfHh8P8SVCcInOY+Qh8nxYFuP+7ITTm2jfQmvZP9wPE3FrNWpzlZ6E6JY4/g9lp/YnCR3j,iv:EWFmq5sKDbnG/W8eGBvYyXlpR3fjZfPt/sATP6h+bf4=,tag:kDaY4sXontLWq5YPJGgkRg==,type:comment]
    htpasswd: ENC[AES256_GCM,data:85xSvXeYRDywrxdcMjIeeN06PqDRWeer0lrZ5fh81Bxv3dMjJoM6n1tYvTvox6eXOan0ZVlh7LsKblb3bPJ7cu1cOEU=,iv:dWv0cQoBIgctyJNN0H1iPrC+xRdM9Z4vvZQ10eySddI=,tag:VJYXMcpWG3lQvU9B/rMvLA==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMENnTkdHUXhMUVJYb2Ft
            amVucmU4QWFxeXJ6ZE5HWC9lRitOUXdCUWk4CjJiSExJVzZ1bE5zeDFWZElPN2dK
            Qzh5elk5dEwzY1hjL3hJOFlOUnBBZncKLS0tIDdkRFdzak80elBURW81T3NZektw
            U3Q3RFEwdFQvQ3FETFhSbE9LU1pNMkkKAJGbrv7JiyMnYqye78edZTjb//AwRK9l
            QxyXl6c5hGUgBYHZ9SM8It36lGqyqZKPOzI8yBGl5trhGh00gnN14A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQzNmcXdGclhNT3VBZ2xZ
            UEE3RTlVaTVyQW5mRDE4SVhGQ0VNZ1l6NUM4CjVtblhwNFBsNDNXTFdneUF0eTN6
            ZWFlUUJTemU3cWtISHJ3aTJOV1duRFUKLS0tIGlDMERXd0VwVGpRc00rQkRSQXNX
            N0J0MVF0MW9DalRhRVJYQ3ViR1NRS2sKzAAQwmVzbm9CUUcEQTU+tKAe84V99XA7
            hEpARAgD3JgYg6qmP1DVbxre77QbPiitPdYbDf8DfEnk48wTKYOT0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T15:24:41Z"
    mac: ENC[AES256_GCM,data:X7jyQvQ8XXZhJ+/iozr+4nGEAioNwZHGGbMZEhBZGrr4dauHxPhCV8SgWfz8Dy9ZpWhLAMw0uBmq5/nwFZeXr087iZg1HEoBeFIg0P54amJsbvCo645x/Xg6rJbRQZ9BLZlEqfPkoF+dtxNDOos8G/0J2+GHrUkyaQCiOVOQroA=,iv:6s6LKnhlB8oLLNuKppY9yrvOMDIFDVAtxtTKxcxIIG8=,tag:hkNnD+UEcRvcrUmeRLjNyw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
