apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-nextpvr
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:s1fCCm2PMUC8nKBknB5erlAC0s+lfg==,iv:sfNS9DQNLZB/7yYY32H7hWh35BOsCynMZTqZCmU45HQ=,tag:EYNktOrTk7mfSXuBOvK+vA==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:g4IY1z8eqdcSz16VHFr2Oo4Apjc9K4DFQsppq+0ZzW+JmBWSYrQgqIA95IBg0YZZik/ej30Ffd6Onhauo0dvBGp06blO70vBPM1tM6PQusbnrzMSYZemiTJznjTmJA==,iv:0PYdKdWwdxwVbrckgveE9srCzcSnX16A1ciLh2sHH1I=,tag:4p8Zrx3uSUXD/e75oEW8UQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:/y77Oe7LIbqV1Un3dLJRnwCx7XfLO3huoebVGB2jdwWa94EpyNN4evd+MeNXo3LOOVA/9IPfuWnjX2yd684gQg==,iv:rfwjB1fEQlL5Nb0+rRw+k0MbNzKT4gqEjd6YB9sK68Q=,tag:EKLiZ3hiSdfd3WVfUinSfw==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:0yvaUjn77Q==,iv:Ee0Pb1UXeADluNuKKblmyuxsZLLdb+iGlSe1BSHiK6Y=,tag:2z/x50+wAnBzVgXUVodLaw==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:LpvvUdL69iyROiOFmw==,iv:RVwAOufc6xTwRAzAJFsm1UQVBFfMCls4eIWgLLPIZJs=,tag:VtTHOnIX7852CWoTdRNHNw==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:iQkU17Y=,iv:sOLbsKkhvkSBnY2loja5icHrWpHiXpggzK1S5qML8VQ=,tag:UwsOmJoEGNSCGKppZpD2Iw==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:V6B46Q==,iv:pLJ7Vod421VRsq0tFABO+xMmCXckCKmyGGwGTTmSAGA=,tag:aiN6DWMGPRNAmxizCq7R7A==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:yYXCA+sopxLrPlM9ZcFPenqJKJvr+8Qe4S1I+NWTb7YPbmWvYiZHlhX1B189ZjguVIef+jgOVldQt8SiKDxGScnkW9hREXz45FAf,iv:he0Y583j+90XpuQGN9bXZc4M6RENS6MJXT6PxxEtwsQ=,tag:szJY1vNxubOkh1PR+relZQ==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:CUNM6jBRr5OXLEEiSqhpE6kdOPqLiOuMyNM6,iv:ycQxn4vJpntIrTwAcPf3F/jrQjVNJi+IR5WgW2F0mPA=,tag:+SWe5GpjUokR+5+mJkvvbg==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:y7wXHSFeRI0TBB6qcZtdy7h8,iv:SW+Q5sVuJxdJXoqDDDFjEN6DeS+KJ7JLGpnjTPxeTDs=,tag:MzxvS4FXFNmMUA++B+ENMw==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:YdiM4g==,iv:9d2+gz6qoZsdlSKAl1X65Xtnry6ozfQk8ql6/DDXSvw=,tag:ZC0ixOFzkfeJxL6dQ6PbLg==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:LBexCC3rICCbnAtbWhFXksqPFHLIcDt1Q4mg2tqHmGeNXQv2zQYyBwvlLzdbh0xoNdlcbiDY9TjA+6uDDOxG,iv:EJQguHD8WSHPxtPRF5Z1ihK0DXu7CqpoWFT2+DEy0lw=,tag:s+CnIKfysBy6zeZfEyhpNQ==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY0xJVEloZEhXV1lkRGVB
            QWkvSlVtbXdMYkgzM21jcW5TY3JZQXBWemhnCm5kcXJrbzlJbnhtdWsySHZnN3J2
            NWY2TzdlYzcvN2pQZDhpcFA5bnBwY2MKLS0tIFhWek1nb2N6UGVOdlhsVmp2eGVj
            S0VtRHF4bUZzcGZXUXFUY1RwTDVZbDAKc3iZL9qzGHahOwOnxwfRL5+GmgPeZhDK
            8RhESGuOieJntGmrOXDIOwqK5kkxaRYYBqNpkZrvv+YMeLAFeGOq9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTjJTYUVTbEZGaDJVbWtC
            WlRVZTRQQytxNU9NeGZMUFJ0bEtKTWh0S1ZJCjRPV1JwcmpnY0h0Q0VEdmpDcHJO
            Si81MFZvZjgveXJLNFJSdDdhcllDdjAKLS0tIHRaejZNcDc4clo2cHg2ei9RWHRk
            YmdkcGVEMUpVQU5QSnVKUlBtRkxpV1UK+PHk4Y3eqJbHCA1HEyRmOoBTjEx4FdAL
            5+KrT6RqvG34o8laRsNuSrFsQE0yXKlshHWiNqXFB/XOOF3VD3XnQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T18:39:40Z"
    mac: ENC[AES256_GCM,data:7TYC5V+r19xbQc8W69AeC+1L1O5L1ramHo35ISZMZtybAf32N7gVQOq9nyEKoVYbveYiZ+wFsGLJhbWKCBBEYmwxhtwyOUTi9/JtrehxFieXL+ckxIV3o/Dnv+8aawJkJekF1XBEo/nA6nietHqtujG2MmIeEG+pwCFsaO/Q4vU=,iv:EEn8m1pJhtmyIKD+PKFVkcelMmJyFWxxHXKumfuYXdY=,tag:pLrLNVV0k6t0828mSSnayQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
