apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-nextpvr
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:qdtZUp63QxC6DfXEUqW6CKyblUSPlA==,iv:/qdP0ilZ1scOtads0FqK/Cg9+s8xhPJQ6GQNLQAuPhc=,tag:SZceBIbmmrYnEdzH9zHCUg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:3QA2GJ1HQYQbbqajw1ckVbV3qO2R95B0BZuan41jb8pvycqOnDAquBUFxQz0Ndc/GAUyXMKs9XkCwPGDUoNd8awXB3S+d8PHURGlV7nEiktOD/qqo7JerqJyoeKHLQ==,iv:tTjpCpTjnWlE97/b/zgJJpO+3e6aePu9peozOcvTZHE=,tag:1tIMZZCGmdU1LHtaOTUaNg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:eK6MFvqaWAA+X4I5Fo5DEZiuOaTQT852yavMIQcauPwK7WUMy/Bd7++sC7RqMt+MMfEIfxeTH7dVz0M+5rqQdg==,iv:4bjxd2KaenetMqB5znigTjFLv5rgOW5RXbUy6MICGY4=,tag:2yYtvbYJ4tLbr61j3ls5sw==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:XyvmyJ+S3A==,iv:m0tek2lk6nD9obxW/SOswvNyVR9xWHC+xIQz2jHNFCQ=,tag:lHBtlpaC58x27j8xMcEEXg==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:SIs/U8h9M3NW6sHZLw==,iv:Rr1kCDORDrcFBhBD0qGu2JbiO6Tg3eXQ7yjuN4hEujo=,tag:LGDZz2Ewifgj+mRf2cfgFQ==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:hThhi3s=,iv:B3cPiulZyH8FGZ1IK29EKCGdHKW4psBOyDfm2zYfyOo=,tag:B0nHWx2ggbdDivs9HnxUVQ==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:aWdaDA==,iv:Sn4Zu+McmL8aQ3nAOVFCh5o+5GkOEdnZBzOidSRJ6UQ=,tag:ZtF0YiVPkC5PLC3KDbQdNA==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:VAkcw7HLHGiYxwsFOHGimx1Mcea6O7EET8txZjdq1OsmKu1T8iOPr7JhQm5w5UxhPoRbgFww+y32Fs8wJRyfCOFRU1iU5Y86kP2M,iv:AFjbjA4nPM1KYghMxUQyBrgCg5SocXjGkeo9lXjrzN0=,tag:WKPpY06ZWb3unklWqQgKXw==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:zGrwYdJ1X0IK13BW4jIFCNiw9Qqlay9CQIp3,iv:R3bDcTZzcyWOZhhPcW6vhHmFZeNmnvagtKnoZOCYDMk=,tag:lg/BEyxtVfW5u5CsPJuUIw==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:v27ly9jLe2It6SRogPE6bDZr,iv:LgYYMiP1h+SWzoUvd3x5hfGv+4K/oQaHX49R9mLaRno=,tag:QPbGxoFYa6lbCBDiZyGWRw==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:P2u/Pw==,iv:ueToEDZueg4TzSCOfcB8SniTAV3wkimzJe+hSokGU3M=,tag:xSiZBzuJecnL2eJINjfUGQ==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:8ygvUuNsQ7rofr1AjjKDMAnF8eXccE+m/AikrDA7W7d1XLaKAE8mn6bIPgW+1iX3UnNxKKXP3KiZGcwARoPL,iv:/kfmtk4LDmStNEMaNhSHSD/G6edAHPmwYAHhZ3p/wn0=,tag:I/czszsEtDhhuPhVIG9TBQ==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBta0pHMDk5K29kUXcrME83
            aFhaQk5kUDBhVk1vSi9MQU9hUXEzelQ5OUJNCmNRWEZ0Rmd3OW50TDh5ZDBxWmE3
            TkdLZFI0TnBJZWdmNFdzQ2k0T1Iwc1kKLS0tIFpUTmh0ZzRxa1lUc0dOc3g0SUVG
            dG0zRXBQdC9OQ2lKVXN2eWRCWUFBd3MKphBz2KWd9x/cMXcXhkDHq4fuwpTzySZM
            TNx69eECvq41I5KjtcWikO98n7KMwXqzMon2ZyFLgxRP8sfzZbQMUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN24xY1B4T2xSSU4xVEhX
            c1dEaE1XOEtuVkgzV2k2QVVIelQ0Vk5IRTJRCk96NldGTFZ2a1RaWFNLY3pMVDR4
            UkNKbXBlaUdQYmZ3YnZ1eUQ1TE4xSHcKLS0tIEVCSnphN3VuUEMycWtXZU1EanZq
            MXdqVkhxY29vUmVEazIwc2h5VEJGM2sKSm34oTnMqkX7lrHAFsUwrVOoOxnjM4CK
            mutIXOm5to9cm1eisNoTB5pxDayed+H1K42p6438F21OeFitpiE0YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T14:05:27Z"
    mac: ENC[AES256_GCM,data:t7TGYN7ZI8uRzoZHRXMBAuh9z7tQbUPYqkxtZrm/6rFJZMHGfRtOmNNomzUASn1h1kiqNzfuQeexuOU+avT90mPTs3kZka4lk+BWfrqlb+RNLnoOHnSzt5/NVXoDg2chh/A25fFhRjCsSXXA7Fnm8lhFNbianknoerDsRlsnRV8=,iv:3DxFxLsEpz2WPKcT1JthTxkVVh4ZSAl8CyaZ6sTWUyU=,tag:XtbanV060BsnJOzOfZ5xlw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
