apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-nextpvr
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:AUE6ZxLGo85MHJlcKuJDvAod8wQhdw==,iv:UTXgffaL7mYp4dLEvB1v/sNS+SQ9jVjlNErmNjVoatQ=,tag:0gXD+KEYTDZG7OgH4/BBlQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:9GN+iPB2PWUE5tOJ3+mZZcckmfa3rJWRMTSCwhB9ANbXfV0sPIp2Yt+H0qPxokvGV7zZoVTrQ0KAUrGevQ==,iv:af4FEPU16EtJoc/4V/+ixuzkDO8girQTjiwdbRJ1tF4=,tag:IU+3tbu5ivr12//eUAcEvg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PP47aCUA4A0tF+pptvJgd1LZGZNXYme5nADuvB7xvXlHqBKM/b6mjKb9LYYGeoTFPzUfp5XfEAFkAi4bux7u0A==,iv:eDocx1hbaPrPv2jX6lPElsgGw2gETEHJ5G6aM/DxT/o=,tag:sG8HejASd2aHUfb04oitvA==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:estU2w9mRw==,iv:O0lvzra/g8d9XexaQv5LjDlWa3uAC911TaRd8ajrkuU=,tag:u2OX3a5yQHcnmoJDBBLIYQ==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:djmn10ndnXPldu7iZg==,iv:TUWZRETBMqRN3DUb4rC9y8NsOv5/EXktXgazpG04dQs=,tag:fiqJP3k4+goV5MGaOpLmPg==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:+Z21DQk=,iv:VnDf8ng/EOa6ej0gIU1lL6b/luV3k727fvV9HYmFeIg=,tag:vkBdpxR4v3GgX3zyOHdcpA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SDohpgNdqhK4TzY4xOlKlUXqrTw=,iv:ZUYCWWfh+D28sZiJq+GbK7vvHYjjaD2C+swvBHojnhU=,tag:mTKrt+sV3G7ZPfi3W8mouw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tK2O/mI89dZYRGyavI6BthDdeuL9Jpy5KysuWqGipCeIdqg8IFBOkA==,iv:W3PXK/+wTGVesFQpamRnPTdiCBKtVTcNMxH/6IAmrf8=,tag:nKG5zYYxF06/aDUJSG30uQ==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:i133/A==,iv:UpkQdF/L0KaaaQ6mtyjZNLlfWI8ZGAmuBj83vv0L/is=,tag:ZbQNuo1Ds19eiEOMM+gzeA==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:XiJIJ3KA4en8JH33dATK1T6reVVEtu9bpaZCgZhmpchAVJhkkLsVwGvVVv1oyk5iI7GUiDcqCHjwOucJjhLEnXIjyET5lKj3YpXB,iv:UgLdlTllbDjcaARhvkOrc+fEKm6+SLOTceIfIIpsdDA=,tag:8MjwxcZUC9BwKjucc0I/ug==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:y4NuJ1/V2NruXfjDe+xMyiVZQ+Dfm0+eJvfy,iv:iolsMSj0CAtVeVILvuKf3Hwoyi5g0Xa7/DJfKL2Pdw4=,tag:8ig5h0IwtVf8Wxq07VBRCg==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:+J7x3kSSAdf2rm6Gsq+xFbmR,iv:igmU8bBrtOSQaGb6uXJ3c61WabWPAy9ARC+GMtCPQ9A=,tag:QuGf5qb4MELkP/FNmIjkWA==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:21C9qw==,iv:Y3JOKHUAl9P8nZs1DMlX0H78vNLODVMqlQ0WcirMmjQ=,tag:rC3ILV58eJWV0Bk4i+MFPQ==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:Kk1ie7ho+ClmIi+IMr3YVBqec9ntGybYFxIK0FO6ire/y/DwpT06D6sOy0czlnUcVSLU+VyDT/zEPT//02n+,iv:OYMUjOf5T18Bz4y/N0cR+9lus0yM/3C9RWExEZWjgzA=,tag:/xvqLTFL5S6oeFrH7WDkDg==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5c3AwbUlGSzkxbElMWEdt
            c2NuSDJWdUFES2dDd3JmNFpOdmNOeVhxS3ljCkhuN0g0bWRSai81amlqbnpCaTJi
            OW5ydlpIOE82R2FqVWFKR1BSMTkvd00KLS0tIHJTTE0yZXhPU2lEUDJVbGNNQU9w
            dXFlVVBhL2x1cGJWUG1INGU4R1duK00K95MtcbCoYDBFgRTnW800e564nsF6NE0+
            9H6p122E/539DtJ7zL761bcnZ98+3dziFPQrpNErRHPPC85sP/fqcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ1NzaG5mMjJONzN6WnlM
            Y2FmRG5BV2VmTGllVmpMRGtqQlYyOG1jSEM4Cm1FSzJQck5mMGtLSlJwa09ZNGEv
            M1doVUdvMy8rcGl3RE9NdHYvRTNBVDAKLS0tIDdna1NYZVAxODIwY0RQWVFqNXpW
            TzV1VG9kVStyWldoMWwwYXArcXBOTEUK2smzpsoJ3O74lH7rjFiYDgd9NkCxa5uG
            NRqIGnbvT83HkigVdJKX6IElDRjvutZP0KxzSNmsUMQOCLyth0r9DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T09:56:43Z"
    mac: ENC[AES256_GCM,data:xKxdb1xBWvQLf9Ts4v1Y3P48E0m743oSPt2Xya1geeINKwViKHzejEFnnWZu1ZnOusj172GlqKXt84/fNENiKYmvoIHuOQYg3HyboMkG7wtyhNf8/Kgc1ym74TfBa5VDqsoWwN3hd0L4ZCwNV/n6a0LceZIkScYoI6PyakDFe/4=,iv:jCVZsPjbLTC39SZCzEt+BLuiCl3KqPPKhR/2HgWofU4=,tag:bfjxfLatZKR3p7o/miai3Q==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
