apiVersion: v1
kind: Secret
metadata:
    name: restic-backup
    namespace: longhorn
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Mq44845UqCgkWmrw6N/SMuGynWLX91ANOYg5yWEgcMM8t+NEQutttN6b6rR5oJMA6s59ymKNR64dmo8=,iv:y24rLUSPpvTcjCdmVcw0AO/xa/NalSdzISJg9CwzpYY=,tag:mK1May9pcZyw/odRQOeiow==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:x++iC6AyytODcPrc7xRuY0voFbjKyGLGyhAktYTusLCGsV78WIDpmvZam1GeYvAgcrJ6iOGinW+RIIZBJz4DUDAJ3LruBd1vJ1erErgFKqb/YpvYlT0OPD2wIU38Iw==,iv:g1fDwwUIhDamG6TAuTC/ZRw4mDHdMGmKIPauuBQe8lw=,tag:BEVGAAvQ1bAYoq+0VZQVog==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ccYtzxyHZPJutbnJ97h8yL3uwVGht6HfB6LgG0yNQJRp4QNyfYUg+tcz3fv8fsburFeNu3Jvy+WZ7JokQc6Ndg==,iv:jBzDR6Voi1sbqsOKKkNYkaeJeXIQojy6CALNNE79zfo=,tag:tGp5qgFOAwIhU2QYkPrZUg==,type:str]
    RESTIC_CACHE_DIR: ENC[AES256_GCM,data:rKg4/xcaEA5V8sEL7r2G9tTWP2YsBbQHnOs=,iv:YOazD++aoUd+MHT5CrFX7RVk+xQ1rA1jKz26Qg4uxGg=,tag:xfvJMYE1jYXxfJL2+mvMXg==,type:str]
    #ENC[AES256_GCM,data:Qq+UJ3zZ2/FM6plN0qyUUrBQFevwjF/12FVp09pQRAzGeXOxAQHpy5/3mmEh4QOI/UCjUrz+zOYKZT+S2Q==,iv:cFrX+1oX0m9VM5VZgCBK8g2ExnZUgp4YTrOlcLAFOyw=,tag:SzohwLFTp/4tQHorUMJGJQ==,type:comment]
    #ENC[AES256_GCM,data:PbNMWSuB88h/jBYN/FfB0hIO0xj2ZGD7hjT99ECjLyUM0NAx2WPu4yp/xR+PG+4XJOaENLoImM/gtp1ctDJwS3p8zw==,iv:AxCBVACV/4RaUzpDjXpACeVkKTlx/oK+yesTvUyOxnI=,tag:abA73PEj6cFc5IThacaakw==,type:comment]
    #ENC[AES256_GCM,data:DGEwnFfRBwr7jk8nv8pHGU7Qn5Ij9Q==,iv:gmWZ08afXXqCZcxSCvgM8NYrkQNaNWGo8XS2+thyjhY=,tag:A8N581s1loyTmmOLlh761w==,type:comment]
    WASABI_RESTIC_REPOSITORY: ENC[AES256_GCM,data:zeRg44MdyyIvvClCapdud00xl9+Lth6z0QtvxcmE/ij6fkXujVxrEEnPLumP/bB8ZP0tNnPhr2hkfMqyRQ==,iv:f6/+7sAL0SZ+GFY+dCatsnDfhFzgClmUgU3nYsjSeAA=,tag:l5we0C2f+hmzA6VbwTdJag==,type:str]
    WASABI_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:xolp+Uin8KeCKvOH/Zi2p3DuMj8=,iv:q0kj7RAh6vFcVMU+KFWVWR+zrl0O5uENpq+XSENkOEg=,tag:hZKXS+JKDWnnAfKwhCbJ5A==,type:str]
    WASABI_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:E7IE9iSh3FQVv7gsqXPM9crBx9mcsP32UM9NQo+SQ9SqRbW78ORqEQ==,iv:DlB6KudjLkFIApra245ENcYdDUnMkFmXQpQaxwY+afk=,tag:1bvhHL1owSuElBmyd3ibOw==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWDhBZm4xaEVVdFVvYXdL
            cWRvN2pnakE3Q0tEZG9TWFR0V1Z5bzFUSnc0CmZiTFlOY2hZamJWNExvbFdUdUlv
            ek94TVBDWmhqM3BGelhvS2lRc2tOMEEKLS0tIDZXRWhWRHlyNEM3a2NQZTRLOWhQ
            TkxkUGdGZERES3Y1bzg0RHljM3NORDgKugWET/YhZZd6GN9EWMHt20nPdrI5vW8r
            toIBUxFJ7qDjfcy9Qt1fY3lwlXZUfWwcB2Y+rmY9mLrH1Ml+PZnXQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZVRlUzQyRnFUdXpjL0F3
            elI4YlVqNE04eExKRmdMVzRWbnJQMlRhL2lFCmg5K3FvL3U3T3RPeG1QVmVvZXVz
            RmIyY3hTWVVjRURJTHo4eGpxU2ZWaVEKLS0tIDdLWWxuWTJudVZyWG9qSTUrdGM5
            bjhqOEs0WHNkOHVDaTcxcWJOTzdmdWMKpLEF2fxVWWXyJxUaURok1ap0vpxCijwm
            zh2ADdo31cNmcS9XVvZSkdhB2YBV/VoAC9Xoi1t+iRRSZeimhtty0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T14:15:15Z"
    mac: ENC[AES256_GCM,data:Ctp7d/9YuWk4ShALAFhAP3ys5YsA+tjS6yiR/eWE5z02cNbPqoUD5VK7HFGLM7NQxVarooWaBw1I3fK9DqWcpkGU38hiSBXz/uJbGB/521zmPkVxJvvQpqvt01Na21SPBM8YihTrKudLdCEs8TNM9clwwSA1btZDuICzD76Rn44=,iv:nAKjaAPsHoYaGuyG1NU9aAUq6mGE0y8L0q0WmbGiGew=,tag:DO+2gYh83MgCr84/ZBwlOg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
