apiVersion: v1
kind: Secret
metadata:
    name: restic-backup
    namespace: longhorn
type: Opaque
stringData:
    #ENC[AES256_GCM,data:97fHJKocQfOOATIdeWjoT/H07L5eyab575kvmdKm4c6ICMONgcjOaA59tnf9XBbRnXlcYGvesQ==,iv:+i9PdgYu674oR94PW2vxXck5in+OtzUv+gMsT7kk+QI=,tag:YdtqtlhuU1CddN3PK8OsWA==,type:comment]
    #ENC[AES256_GCM,data:+zSy6SNusLIIgCjTVLJEMENPEmED54ZaJjrfg0I/XRUxC5Tmb+rkt3scICsubWQHgnaOwYoe1tvDSiHTORk=,iv:cy1hmCvrkAbBRrRvCXyW+zxtjvkC15PkpwyUpC0u1zw=,tag:dWihuwuN3x2yTd/P0SDbig==,type:comment]
    #ENC[AES256_GCM,data:l64vmdODnVoau12alc9fAQF76JDAZqiqy+odbaFywNd6PL31tDGEX5kTqsY=,iv:FolNat4c8lJIkB6p4vEBJiUrTVqPpcyXdwecNqV+AGc=,tag:n35WIGPDCNAU2m8QThZVyA==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:DxCPR2AMV9tiQkWhtBWaVMA+RxnkkaxKjklhOMCC/x2C9qR4oo1S/WCbXN+4eejfPl7zcFZy+ldY6VNIuOLr7kIc3dclnV79usKwFqqdf9J55J62KWRgfK4LDIRfiw==,iv:h+25mxFiyfttfyPivMMMY7QYmzbbIiz1ZYJL2ZnVg14=,tag:GyCW7uvz9SNNxdAePBA6iw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:PXNSXPpnCjMUNSHr4dg7R3H95rpvybLHVCLKGOZTZ0wSv2CpmImbyiH3zdX57D5GblMPAql/LDV+5qhmuMVrUA==,iv:pWJW94PAD6DpgKA/b4luTP9NbBX8hm45A7yd2JNdiQ8=,tag:a6CMi3o9bqhPl2GOTEJuvw==,type:str]
    RESTIC_CACHE_DIR: ENC[AES256_GCM,data:+zF8Q3V79+Q7VBSTIth+qr+yme7SWv/VcII=,iv:nciVfhe8lwJL+wIEFhZcMFp/MNAZu34vBzqnSMZf2YM=,tag:OjIN+c1g5sKrmaOZXuSEnw==,type:str]
    #ENC[AES256_GCM,data:b8zBDaCrdVkGF8ixhI2yNdnF2TB54rpaxH00kLCM1YBr7hctiFh4wACVemTPFE/SgOW/ElXOmUQ2GtY=,iv:/qR62ijdtgHdz+36sP43Rf3OaKlZpx8CY7hWN5rDS9o=,tag:rgv3LBCgtj6X5bkaTptRAA==,type:comment]
    #ENC[AES256_GCM,data:hGVmjBtUuGBS8GH2Wsi1SGQoCNdmQF+JLg9NzhxSvod9GGxGgC1L8maU8LhNF2bL4sA9nVmefF7dgWXcjh9RTQ==,iv:LvPnlAMKyFmjqXb4h6+G768Vai07SZETlPWHlq1uD5U=,tag:beAPW8tM53C9p+sAxXYz7A==,type:comment]
    #ENC[AES256_GCM,data:VQTfV9Ap4u9xL6yXTsZdItXoxOnF7awSTLKjIlnHwA/mUuFTwDRSMw==,iv:5h4nNF/fC+M5/3zKnkmWr5Lb4du3ZMCF978wA9wsvLA=,tag:qCPDSK5g78EKDkUWk2ZYxg==,type:comment]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:aZwLTcktJODDGDZXu9rIcPHABfm5tqsarudC2HJfCokNpIUgRKG6bttBkTBGzaEjE3Sx6yBTOtKI7t9xZwW4,iv:TtxNSY3b+OWz4hXK7lNvUxPr/e0pQvzVTXDOtby83cs=,tag:4z8G5eR2+tlyRbgsOZixbQ==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z2RtUi9vMUZLWmo1T0lC
            c1k4bThQZEt0Q0JYRFRpdWhhaGlOUW9kMlJzCjBzcGRMZ0JsVUZMMFpxQk9oZ241
            TmErK2xOdmNwUnRIQ3hPeG83c0RyTTgKLS0tIGxoemhsTW0yLzk3MEVPSXJrUHRy
            RWdTMlpEMWZzZk1lVC9zR2JqMUJYNVEKyfV3EnrhNYcem7X7FnWS9DIZpA99trTm
            3b3b6PNViYcNBRKjcLXFVm8NBXKD/Fzgxj7l22HctZDJZrJzFgocsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaElkdHF4Z3hSVWhuYlor
            dXp5Z2xrc1pOTndDQ2liRzMvaEhoejNWbTBrClp6WW1TREpZcnlVTjZPckZMSkNM
            ZU5MYXhUcmEzVzdhNnIxUklGU3J0U1kKLS0tIDJ0SUdoa2s4K3N2R1FlelZxUWh0
            ZVVLditXMEF2eUt2YjRncjVSV1NwY1UKkz95P2Ugc3ul9bialRAbA8m0r2aZaM/X
            afTfvJlbTbhU9UENZeK86C0OTPcPMqSnFD8JedGKGYN1FY52aLSGRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T08:32:34Z"
    mac: ENC[AES256_GCM,data:1Lym39Vzcc09ysFQ78hWPceVVClA+8lJnduF5OZZZf4X2S/FfpqVXCn7ygfVMWU1ox+NH8kt08cez/9QIpA6ep+t3LTkVpBnWg7y7IwAcZHCzQZPNgytDp7NbTTVzxfC2APRtEqx3PNb4DgZXYru1N3YY9v1/RtSFvIAhsz3/OI=,iv:xe2qC+LdfkpuivPD7fnA523BQBzergC8MuVRHXpG2jA=,tag:eEGwKwxxka/w/R7rxIorTQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
