apiVersion: v1
kind: Secret
metadata:
    name: restic-backup
    namespace: longhorn
type: Opaque
stringData:
    #ENC[AES256_GCM,data:1aJMsAkQurJKdIP6PJnThMmFXceaZHVnPnSwsi0m2u0WnVNaEEm88PLD0vu8cwnJyqehB3/ygw==,iv:vLBjARENKctLKLxlFK66CRpf+6namLGAMiPEe+MKWE0=,tag:F7vCz8B2StrqTctz4Vd07Q==,type:comment]
    #ENC[AES256_GCM,data:wbt+9Ohox7qEgiNJLCirBpQCxduWYRilKWZi8pEhbX0AUiAY3oVrxbeHcPrTA1SSnI5KCAU5+9hOsmTris8=,iv:8eI6T9DhFJe5nd+wjXNHBMoiPVotfy8o+XhypCyOSBc=,tag:PutY4xXZp/xMesXPUTfnSg==,type:comment]
    #ENC[AES256_GCM,data:tZMg4yr1tEGnkUWwSFDoeXGX8EFtfXp+d9RkpRCKOA+hJ3SpvW4CkPu+9lc=,iv:KTLAG5ptsCl7kx/Ky8HrqxnDfzGYtou7lWrEznfVK7g=,tag:48LFtyDShVNH/ZGDLrSodA==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:eSSuMy+pBmR/mH/SNDwQf6piJLNqqTmGR+Rnv/LEsleXtq0RlmMrhYnoaOdyPfeEiXsajg/laqHNfDn6GrViAYwO8Rt8+KV5SHXnR5OdYy4MiGsjj3/h7Oy+I7qeuA==,iv:YmWVb0eoCHdGOmfh55U8eP1rkvlsQrRV/IIkcgn2jPc=,tag:9dOkqaqAYvcSHR9SB80ipg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:dzF81f+RWpQysjJXfeCFDO13+71eXtBZEWgFgkpE4dqcKj/Zu5qeNPChYy+KSJC+top/p0uDT17LkcDzfaGhxA==,iv:DCm8Jp68aSrGkcBwAgNvz8THjP2NXkGGBpTXFWhyh3s=,tag:hIixgV/ipWQaBOUZJ0iHJw==,type:str]
    RESTIC_CACHE_DIR: ENC[AES256_GCM,data:n0tcm8xtnXaLD/3evzLa4xeMJqoEe/DVjRA=,iv:YMUeKhGwWr7Gj8h4c9Is1+gFgtQEuQYJBR+RXjUSkuc=,tag:hLeIJPqQjf5kM9MfcQrLyw==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNDBiWFhhQmJoKzlTZG0r
            RDFVMFZVRC9HL1IzVFk4TU5HUmF4Qi83TEYwCkNNUTJtSkdqSXZtdFBCSDc2c0Zi
            SjhNUGU4MzJtVE9MQWZPcVVXcStlTm8KLS0tIGdzNDNOa3FrUUtNcUhBU2g2MEFt
            a1NZdjY1cXh5dkNvb0t3MVQ5SUJDRlkK28hV7CrAa4pHTHBUoYEQ6oUhhErIJBYD
            3FIuqI4RgJ3RAuVhEtxfdB+UbhVEUyLt3Ruvk+JMTohyh0VhHQD6vA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWkxEMG1mYVcrenEweWZ0
            dzBZdnJkSUVYdFFod0VOR29zRXJqY1ZIdXpzCjJZZmhLN3FTQzN1V1lpK00vVW1I
            SlJOZHNTVmxQQXcvZGE5Qk9KeGs0NEEKLS0tIHRvMUNxUm1heERjLzBIdm5vQ0JV
            TkFsellJL2tJZEIvRzdleHhiVldITk0KDOWwnrd+QmlaB0kbzdIYUqpNw/t9ewU3
            0vs/3RGedP290TCkV/lNtPwDuJOUYYudX9xV5bSlMEZjvf4ru4qLtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T18:39:40Z"
    mac: ENC[AES256_GCM,data:FFmxkKe5dKaO83GRuOvRmkPCBNY6FxirY/mcO/M2J968D8OKpZtcsITx5pPlGr+SjhNxbWVsUjbSpn2TPdLHHLR0HJT9iH5DlWIsEZ52mzkPqjAeP2Fq4sit7/+lnF5yeuBREB73PbKjEXLFT2zqXoA+T8YqYndsoibIQrSiprk=,iv:rggKWPk5yx+gqPsa6Eo/NiCUgiegKSUHL5O2ttM/jPU=,tag:jbJmHurwwObalTSkLSZssg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
