clusterCollector:
    ingress:
        enabled: true
        className: traefik
        annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure239
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect@kubernetescrd
            kustomize.config.k8s.io/behavior: merge
            kustomize.config.k8s.io/needs-hash: "false"
        hosts:
            - host: ENC[AES256_GCM,data:LW8KqgSlwEqr6y8Ad2qxyTuXIzmOIOi6b8GCL3OSzly0rvvFfe4sUOdjT/5/rF4=,iv:G3pFGZif1VbfC0AOuy6tp2R5Z+ndzgwjr1EAnEzB7Cc=,tag:KD7NRtPYlJzxPtEnldrJtg==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:lA==,iv:kJjPIpOBhzEPyvPf2MKUuvfcOgCTjliXFe8J1xjV16E=,tag:b12vemAFwIe5HsfdSJAdGw==,type:str]
                  pathType: ENC[AES256_GCM,data:1C9S/bZE,iv:2VO+m+wpMQURh/EfZqU80d37bXwfaPGvG1hOfIIrTdA=,tag:nFu5osnTeI+ehBFhu1xyoQ==,type:str]
        tls:
            - secretName: wildcard-cloudflare-production-02
              hosts:
                - ENC[AES256_GCM,data:3rND2qtQEDj0r3YTmn/m+QX5ns9GL/YnkxdRedP/flTl42qHY1CjbYoJe4dpb4Y=,iv:9IwHI/ZMhjPQLYzJ94xjimWN+5WNt4Wd/tLyDrBa1w4=,tag:EZ5R/sVhOhKWBhoZxftVUg==,type:str]
    resources:
        requests:
            cpu: 50m
            memory: 128Mi
nodeCollector:
    containerMetricsCollector:
        resources:
            requests:
                cpu: 50m
                memory: 128Mi
    machineSectionsCollector:
        resources:
            requests:
                cpu: 50m
                memory: 256Mi
containerdOverride: /run/k3s/containerd/containerd.sock
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4K296ZzVVNlU5NEZwTlpv
            S05jNnU2TkJNVlVJWEdFMGh2eHBqQmwzWFVBCi9VTWY4ZzRndmQ1VzZ0bUhwa1Na
            UU5kU05QSzFqaUE5d0NRZlBybHptVmMKLS0tIFIwUm9maSsvc2NNc0FrZlBUQWVi
            MmRWYWwzcG5yUExjSUp6eDhRNFhHMjQKpmi9HR96b9OHKMmUaCSGnP+bscaW6BiV
            361jmyTfNznvDXYgFspW0Ig47KLr9I2+HkibsSmQGDoOW1j7wzUmkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4T3BZU3lHOHk4c2tkVlZq
            Q2dhbGhRTkdKeXB6L3VMNlh6K1Eyc0hDdWh3CndQblU3S2R3SlZwallhTE5YekNP
            T3dIcWpkemlGY28yZXA2SXpGTE5mOTQKLS0tIGljSnJUQ1RJLzg0YzkrdXJ5UWdu
            RjRXWUpCdkJOZmd5R0RDT2I4UjV2Z1EKCraBK6KvfIyArcck+1mCsCFqzGN04byv
            7grPXY6/ZH+Ker5teGi52bymu+hvw+7cHBXO4oPW+2jjC6o1y4hFLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T16:30:03Z"
    mac: ENC[AES256_GCM,data:qquAdvWSLlG1dWbUR88p6tflbDCto1VXtegW4msz2GPOSJffY2PqFC5gfhft899NBS2wzWv2eSaWduZzz1UNqwSrCf8AUwciRKlair+hv2mzzgWkS/WwJ9wmBfmE43sVDNAAJszk5IhOX5WdX70q2kgFFfDXgrXIYTxWGHvLGWo=,iv:iCQMCxYyomXCK02K6W/Opc6rQT+g4wPJ9KGir82iGUw=,tag:Pj9nQ9BZXCbsAqfoxtNvFQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY)$
    version: 3.12.2
