apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-mariadb
    namespace: databases
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:/ZzIblidMQ==,iv:STq3UMYuJnifrzklNUD+0uSELN8Ah2h0WnMYPZeYnFY=,tag:9j7478QWBC3VmZMV/sD/uw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:D4DMtBZvo1bJcLkas5N8MnGILj8iRZtNzldhGxjsL6He/ff2h/IUhO9Yitp7jYq8Hsukc2kI78NKi2zxcjuWilYmwkEx6hwvjgoHrrmgOsOUd4Gphv5GiyWpAbbgGA==,iv:GKMp87Wdfp8gypR97xkNS7gZDv3U09QJsaDGMEgQiY4=,tag:PC9i/3OGKbRZVFHwffQ35A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:WG/OQo2PDc05qS04drUGuyt+o80k7ZJFWXKurw6RUbYCmmuDzn5wJ24cd0GxDqj3j9VrtsOHTUVJHrI5oJo7Yg==,iv:i7ygR5zQs8osMzz+IknlCLC9L2aqeiYEeN4Khlh85do=,tag:tJ9Q4N45U0LliAk0wr5TUw==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:y7/l+lrAXQ==,iv:ZS99Zyu36RWtQ3DOrlE8izvq7lwyYgAJPCHRpvxo0AM=,tag:xFGt3VJKf6LiUC8xY50vsQ==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:jZb2CQl9E6/rcCoOMkqpiCaTRtQQllL3UOoSHty15UrzJ8sIp+DWbiEx7AsM5aukqb+lvqSA,iv:xE1klQUTMwzhepFVjHWKYPZvyKQ/UnKkYGENmuXwTvo=,tag:9BauiNKG48c1RXzHGiQBqw==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:QoPVRSs=,iv:nF2eMn1ZAFJl4jWRoc7QC0A8v/4Yq/nZeOWkBkjVSLY=,tag:L0QHPlSlYN6jVu/h+htNww==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:puOL4Q==,iv:OMLMsf8JekHJBj6su2ITu0+KvM6VBrYzXeNlWy6tHvE=,tag:42yHM5ny0z/YGabk74FZWA==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:dfJjLUXe2SrOXIA0kJ2/qJt4+R8kg6qb9mglz7FWiBwYOfz8zSXLtOtfjtino/8ZnZwzUsU0r0LeOlr7VOZIA5+phDlJMbx1CSTW,iv:ygelyOm9gcKZ7L6w3SvoNDnF5qYEKaEsrlGZqTf4Y1s=,tag:QiEHaKuZ4g8I4tUpZVh9gg==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:2R/aNh2AA17XCfmfYfwz21wdxm9pUijNy7cf,iv:TiWfyrjR66vvnmO95YEojzhxjHWZzoKn7krCnCoovVg=,tag:BfBQLPua+Z7XkzhkV0JoJg==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:FfhZP9ZvoSMfTYEzBnOxxKJg,iv:lbLhSNkt+PrVWlN0R0Lnta1h9pmwVwgDzLnz0ubQ0Ns=,tag:M5Q40BvuJ9ukDp+ARmc6dw==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:YgNhuQ==,iv:5lXzfmYLEXB1KuxLYYgRiSRyUhRLBb2vcHaTdrKvEJs=,tag:WR8UPFlLFbCKJtDymg0hsQ==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:Dd2le+AHbILcdPCs3XWRXonwfgsPeBYAlhU48o+WYeqiRFHIwUzR0RGfm+mvW8eLhKviWi8CoOtHnwudV6Li,iv:+t+XRumAX/Fs3XFii6HopvxNUcZscWUTJn+dIuoO/4c=,tag:ekxhNDA/FosAS2S3yEbHAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV3huSm40L0tZd0g4MGRM
            ajRLUGxnMFBLZjJOaVRqaFRhSmVMOGhOTlVvCllTbGR0VlZobkdLa3JLR3piNnRm
            L0dzbzdRTU04N0RQV1lqWFY4VVV2R28KLS0tIGViQWVCbDVpbGJjU2k4MEtxWDU4
            R3BBOFk1WXd1Q2lqQnFmdTQzR3ZBSXMKhLXNbaWczbUEpykKDJBNqImKS8dQWuJX
            WexbW5RAu6PbPRgv/peVEQR1Wk6tX+B301zIAsPzQaaxJv6U4ViMoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWHZlY2FDdWsyaG1pdk5x
            Y1ZsenYzcTd2Z3o2QkoyS1FnSEt0SXA0Q3pjClhieG14SE9sWE1uRnpHSWlMQW91
            SlBlZmYvNXRGZVNMSUJ1WEVNS1BUVVEKLS0tIE5kMVpZOStGeDZwTEt3QllDODE2
            TVBzcHJ3K05aN3hxWmwxVmpWd0NBeFUKN6Dx+gPRq/lZ408OqOOY0VOY2Req1ZHQ
            XCENQR68B3zXR9ZJXG2AWCGD8soPK9FzGevw1tdl1xvwGdiu+RT61A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-05-28T10:21:00Z"
    mac: ENC[AES256_GCM,data:cEXSH+JrIK/LG2Ijz9suAy+VFY3tcNAQH1nJFjiGUVhURXBEm9LDzewTzMjAnjwlHta1AmLokTBAM51v0a+zldU4S0n1eD++nP+3Ib/dOvNh0+yvgTvwUcvoNheNFHxdkOls7LdAILWiP/v295V2XP45gNH1sdKz5UfLDLEx4k8=,iv:kJsfyq2mwWSD22bgZIP1JiyF/CA6adzM24FR3MV5MIc=,tag:SofWYKMkKHvWxWDW4pcrXQ==,type:str]
    version: 3.13.1
