apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-mariadb
    namespace: databases
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:iFAPUGMtGw==,iv:QGfn0T1XNkjrmX6uuSzL4r0dqjhyV/PX238GrADtBiw=,tag:GXTIZSXTdKz6wiVWCX9mKQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:8rS8xyYgK1z33l1gQ/8Jrifc74YBz1qWiNjoM5wM/v9+eu4piYIvtjBXSKFSs8OtfnyMN/Ux8qEfC/v/zg==,iv:wKsfaEh29VFllKFASHTAlfn/GHRFigce6GPQx5s3KuU=,tag:OOm4fbrWjvmnTh75oAYJww==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:8tFKq417wfyROuDchzQnwNpcwB/RONEby0LPPATukc53pAoxsCMCeID8q0qgwpbrJLMBIvWJnXIfb5BYzvb2Lw==,iv:rnqjMUoLldV8i05n86N8t4tDzcxW5RVtOdvqgE5k3O8=,tag:zHUApv/m9rxhQRfM0J3I3Q==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:QhSV2Dlxeg==,iv:hwgROPZEE7Lp4xOrw7k+ZPCXTicXBaGLlPZVrji9wFI=,tag:bhO2F0O5jtbPy/eWuGdueA==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:s53eEwZ95899d8WeMw==,iv:ag8jBF12rHK1ZEXJv9sq0PT0bzgkrfyBQO/1UFOpOfA=,tag:vk0+eIEmvTyw3+HmcUq3Ig==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:6EqUW78=,iv:MWuFFUsAvat3p0qQmZ4wy1mje0DeQyXIfCT3ROxI1g0=,tag:A/1A2cFQz0CWqMPfUMG48w==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:s76Wxee6z3P+UGwlZQvmbZUrl0M=,iv:+0ltXzfhO8CNydkOFVyOjtCES1J1aGHUCMfcQMwJRN4=,tag:kOTSk0ONlBDF9gZm9pFFLw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:51zOQOJru8qpeCp/o12kANqhPB9b+65wdMqfFmZB4msg5ZFmpOVZqg==,iv:agACItt2C6t4Czkil0S0Fc2ZU69nXVsZDX+IF12Embc=,tag:xNwPrp/kcXLiY+eOr9IIBA==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:R4uD5Q==,iv:MmpN1K+VvBLJzU+6dzezNRczj4C60UH3JBI/PwYiMg4=,tag:21VRpCrNxUwwVBNHHLgByQ==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:J7j6s3LlZpe30sPLJcWRkfQEQxvRhudxmSZIFJV04fVEspeSPJ/VjLPa+AbAoTXzAUpdAcJSA5x/jhylrXOtBHfA8F9OQVrdxpB2,iv:/lHhcsSyp51TSfJrEpD8ouXbhVoO5igCncVJLc/2WdE=,tag:1+vGkQQOxRbhtXFBme+cUQ==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:0ezay04l1SGeZkL+wGhtX/TCtyryyiJgkGHo,iv:fXGrBhT5LXVI40Y4I2Yqo9z43dgJKekpjcsFKi6Z9TE=,tag:o3x2QRXfruvhqQwucZ5/Iw==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:sWKtIKfN1XWmHYEjW56jJHe2,iv:dqY9eaXMhlgpFQCEong9wgDXSj4t1E8KNWUktysPhYs=,tag:tsuNYRqBCDdLyCik5eCgtQ==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:jSMbHw==,iv:ksiw1PpeAaliE1HEcDBlrbULqoZKScUjDl/G4C7Ae8g=,tag:oJ3iQaX//BrLq5JjCCLTlQ==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:IyHnuTpDZDyhUuU7TpfwccBkE/Ku2QPNGlCIR7CosAoWUUojbuCJCIyI4Ek7ppYYGeEgM2GG7PJZ2ed5yIjK,iv:GVGRWHJvC02IMNAwx/cSvvh5iufp3HUlGBkPJktRRZ0=,tag:6bi0KfzocwnrUUwE+hKvhQ==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaStLd1laS2IzSjZXc0wv
            ZXVQS1Nick1sNTNOaS94bjhLWVp6ZHBpbmgwCjNlNWdmRjRIeGVMVHYycHY3V1ZN
            UExFcUxBdTNNYm9ONkx0eG9pbUh1QXcKLS0tIE5UNHhDQlVIcmNoZzd4VHc5ZG9U
            NExUS1pJZWtTZGx0WWg3dk5IUk82Y1UK4IwPVSuNCg7Z+p7PdQKqrgPPGWv46bEI
            DglEoHjHbd9FSO6AaBRZtElI+xTSAccGFdl2NYuWfq/z5MS/G10Few==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbFNGY1VKWEsrK2J1b2I4
            ckZmeTdoSFJNVWRiSm0vWlRnZWFKMHJ0NmlJCjdra3oyNUJ1d3lhUjBoNmNrV3RX
            aFJMMTBrMHA1aFM3eCsrK2tuTjI2VzAKLS0tIHZtMGFTTWs5UGp1YWJHU1A1a0J5
            TjVQYUh3VllZS1ZTUGpqK2xoc00vWkEKF9wc4ghr7l2ddGpf42AzwKCtkeud3oOY
            lVX0TcvgG94EpCkj2NtnpmmiC3N0BuatbY49Nkp3hz4/lhTmcUjc5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T10:21:37Z"
    mac: ENC[AES256_GCM,data:ePOTfvww7jelkJAu9j99uOGdRuLvsiGijvQLHciwa4B+09GFSh0W4C91K19rs+I+BEOU1W7WdCnI7z5wpqJoTwL+Cvrjrz0FlvaLQwWG+4SYSGmA1+OgFzRJ2VArsdYj7fUECOzWD6b5FjHkvn3JfB5+sGIVZK30FyLrVUUHn/0=,iv:p7qGM3PLwrez3m0ZirceoShlITwEfDav4jbVfz3klvk=,tag:XHwfjunX5o7IEsSzMi6eDg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
