apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-mariadb
    namespace: databases
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:J3jzxvEN1g==,iv:hGKN9CDvWV0+BdwWjkfirMW1DZel2FYg5GD6dubdFqs=,tag:BfRJfIJhtqEqnF1RQAs4Hg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:5VBf2ytKNBKGH+xluDoOrIOPW4rNeMRKgaH2WfO/BmsKZrMJW8ECx3nHjilXeWFhzgJJk2YVXM67yZ9paKKMEfl+zPesMe43KEbomksvMzVNPgbSRsdcmqrEYnDrKw==,iv:j8gqlsSkTfQWvqpFoZhALycStEWWN3auXiNaB/0/FZQ=,tag:moVdO/bdkhhsKtqIgDyrmQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:WWeRomBBQDru7xsdba5baJm7fibjWRm5SkVA20jcDICg1S7YtWPAiK2yd7jB+ftHMLlGhszypwH0TnkvL63Igg==,iv:Pz18nAJ7Gmq1NdWozdHya1+ZbrNyuLy2oJVVGb39ZnY=,tag:2wScx4QjqILhqWc2vRXIIQ==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:pM+0eCat+Q==,iv:h60bttkjONywqxVw8R3d9LFbWnoUVny9iZkKRKEIyBY=,tag:gOh9Ijom2EsUpATIVILnEA==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:/o9/armAGWtwDTZE1g2w8DbLuYPKQppde34JWY7WDxn7oA==,iv:hEBo2jGhiOEwBf2vxgljs0OxUSgD9247k7HF8331qYE=,tag:R3l5if5m/Q4cumZqo6OdZQ==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:aJ5Oycs=,iv:kqEqVrishmSMsjeggrp/wP9y/QR0qTjB0lYGiQVMADA=,tag:HJn7KDK6D0ivw20Ck9jBow==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:I8qg9w==,iv:50VAQdisVPvrF2+wnLdc3bcd0LtPBQL46ubmMwVeQ64=,tag:DcY6gW3h6OPzFTz157f1Aw==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:st3YQbsUwSgZ1b3w9wt0bD4qnQjNLKPt6WWq1cXDSvSIse5BsQssVQkuVSPdyPNLXSkFe5HatwyGJfjeLLrZN7E4e0v7fJAQb5Vm,iv:FQH1WbTCiOYgx3EF3Sc+da+Wd2a8Uzwjbv/SlIB4TH0=,tag:Ks3HJtYZrhpi7HzG9mV7PA==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:BGSu1JEdYc99b3RYnQ9Bu3fshxC2QjySrEo3,iv:60cRtCzNYH6titZwSO2DlRX1LGs+hxiP1URXhVG4jZQ=,tag:icJbI7Bp3PxchCqDsHz1fA==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:/v42I8zJo1bbAT3xsC/j+yJq,iv:u4iuSkMDt0urhorgzxGs4/5+i2npHOKEV0K3RKQaAx8=,tag:pnX2T497ryWM8f75sVOblA==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:h3CqpA==,iv:V8J29PH0dDqaZ6XwaW2cpwGrSpZWc2fWS86tqtuS7u8=,tag:rvwOjZk+8rVtmEE33SI4JA==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:HTNLZ1dBDUQJTJML1JF6yDKvAYzFBP9nTN3McOKFcZUfUacCVO7h7f2OMN2MUyzebUai1/Up4WvN7RCnHmz/,iv:h8uA7C8Aur1+yg0YTZcQQ4a62Yp7bZmaY0pV1MZG9D0=,tag:PYUcxX7hd7WvX3hgLPB3mw==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR2ZwK0p1TkFSdldRcytz
            QVE0S29zNkVKYjJFRFl5WFF3K1p4dUJvdlMwCklVUC95SnA1WUk2UUx3L21Sa01l
            NXExbko0TmpneFlvbjE0NFRybmZRQVEKLS0tICtEUVJkVGI1UzQ1aEtRSmlrdk9w
            QXVxQ0JaVDF2bWJ3UHhNbHhMSnVzK2MK8kX8novVZlVMlwAdpq83yBu0Q8TgovND
            DMxtiBm0SdSfGb9EdRBUwcY40SVzIHjG5WNodV5lzssLlK2lL7YNvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSG5LYnBHMHJ6QkdjUk9x
            RXppUDVpSUVpMWU5RkwrZ3BCaFZXb0VSK3drCkRjRm00MzFjbnA4amMrWjlTWUhP
            aVRoQTdGYVhib3RWK05NNFM4SVU3TGMKLS0tIGZCUndLaDkwckdDOWg3ellkUkNQ
            T0lvbVdFQTdEYnRVSTFEVHVaWXhoYkUKdU1T3MRaU+Pjc3M0hKbSBuBgyRv6D2Zc
            j4uNQe8uE/CiJedIKDDFVbpCvZ93+SFG7vQI4B1bj4ONM5bsAlqjGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T18:39:40Z"
    mac: ENC[AES256_GCM,data:8C1Am1HXwkjRi8luGxXqpAGcJVlw1erH3wtLIUI9vpSvvk7DnrJjTk/X40k8SQgQPPi0Q9Mg5qSWyaco/1qbAPqVsfxEXpzcrfSlDNIO7fXH1fIZXPFxNogAP9Z09LCfyqcszXP7q+ZjP3LdYlvOMxW1u7P25zgK3X/Zj2Q+kDE=,iv:jxHZjVhzWX5wTC/mMFt21z5Vb7Wp++rnXtJKuyut6pE=,tag:bw1okE5j9QnJQRCLBqXsBw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
