global:
    storageClass: longhorn
architecture: standalone
auth:
    rootPassword: ENC[AES256_GCM,data:H+7TV51XyFxeHMTzLtjS6rleEoTsDGRrHRNfptBzHuhRkNhZGw9M/Ak2EuV4pLdC7PuWsS0kGgVRW2kVVGpo+w==,iv:jNE9Vm3RAcxou9x62bcyI/aBr3bJ6G5p0b5Z2TFlPwU=,tag:/HXCsEgNrmw13BUtY+nMuw==,type:str]
    replicationPassword: ENC[AES256_GCM,data:/affk+SOIf/rJxPCgG01vAHCf7YFaUEFUZgmggDpswiuOh8IwaEzKSklm6C1DyynC+xILwh10sW3zIMdbKxl+A==,iv:sTpFy86AE2w7JHsw1RV9j5H1u34RLyhZWXP7pZfOh64=,tag:IzEfR97UCdcBxLzW/zsL+w==,type:str]
metrics:
    enabled: true
    serviceMonitor:
        enabled: true
        interval: 60s
    resources:
        limits:
            cpu: 450m
            memory: 256Mi
        requests:
            cpu: 100m
            memory: 128Mi
primary:
    revisionHistoryLimit: 2
    extraVolumes:
        - name: backup
          persistentVolumeClaim:
            claimName: longhorn-pvc-mariadb-backupvolume
    extraVolumeMounts:
        - name: backup
          mountPath: /backup
    configuration: |-
        [mysqld]
        skip-name-resolve
        max_connections=300
        explicit_defaults_for_timestamp
        basedir=/opt/bitnami/mariadb
        datadir=/bitnami/mariadb/data
        plugin_dir=/opt/bitnami/mariadb/plugin
        port=3306
        socket=/opt/bitnami/mariadb/tmp/mysql.sock
        tmpdir=/opt/bitnami/mariadb/tmp
        max_allowed_packet=16M
        bind-address=*
        pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
        log-error=/opt/bitnami/mariadb/logs/mysqld.log
        character-set-server=UTF8
        collation-server=utf8_general_ci
        slow_query_log=0
        long_query_time=10.0
        binlog_expire_logs_seconds=2592000

        [client]
        port=3306
        socket=/opt/bitnami/mariadb/tmp/mysql.sock
        default-character-set=UTF8
        plugin_dir=/opt/bitnami/mariadb/plugin

        [manager]
        port=3306
        socket=/opt/bitnami/mariadb/tmp/mysql.sock
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYUN0TXF1STdvcUNmei9t
            REVwMDdlZ280cmhqV0szQVMreThGNWRxMkVnCmdhOEdmeVAweE9PcStTOWVxa1dP
            dkJBM1VSaU1kS3JiV3NjTFhGUjBDbFUKLS0tIFJjc0ZLSEdHUFdROFVVc3U5dUwz
            MGdYaHliVllWV2RNSXFmbnJpK3FGbFEK7ls5HryWmFHrS//odJJWUf5Q+R/Ctnz0
            TYA+f6p461F303l1di8bIFm3ez/XjD9tbrt4bqi3RknTDZRXuWkwLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTTZ6V2tzamM1dzZCeWxT
            azVqMFlyNHEwMkNZR2xhcGlxS3hCcmZxblNRCmhvVmVLYUMzRmR1KzFnOE1rcWlF
            aWhkUmtQNzZOKzNWVnpWdlZVSmpvTkkKLS0tIEZsM0lwb1V2RHJGRW05dEJTbG1J
            OHM1ZWZER2hocmhUK1J1Zks2U0l5a1UKFHi4vvX9XiTIxqAfCNb5bEY9IAJmPCXt
            xoelxMetxBbXpcICoXSb9LgMElSi5P8qziymPF9mxr5GQ6J1KxRWtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T06:55:29Z"
    mac: ENC[AES256_GCM,data:W9yWgbHDi5OCIwpNbK7aH9T4LjFU57JHAvB75h8Wqn8Ko82Bnen4vbxFqxfALO5SZyGkMiqYWqDZ83In9uGa3p10P7ZgpRpvDIOyMaQNfsUKr64w8MLX+QKgux2vSC7EP9/804FpxW/v4dQ8zEPuJRYhEgAqa0gP9gDH2VXw8LM=,iv:luxY+nJg/Lr8L1PVIB2xzeqFm0EdGwKf+ys5OSot/fo=,tag:eXBv95wmCeF/Y4T3ehgoUg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
