apiVersion: v1
kind: Secret
metadata:
    name: tamagotchi-env
    namespace: monitoring
type: Opaque
stringData:
    ARGOCD_TOKEN: ENC[AES256_GCM,data:Eo1j5DQxVVnLUcLjfV81edV2k8WHpixf1zNaK8sVltFAnsG2FAHx6E79HSZ3PgmOEyJjJcKlPsDTsl6AXi9RPGcrOOTmQUvi8mZd2ONF2bYuR4smvZavs88zvI3x6N9WlhGD4L7cq58jl7rTTFYofzTgD35bjTGbBAVANFeEzDzLve84C2H8TdBQNrVUNpzX34h/JF2CyfGCScX3R0KA5eZb43iupXgXCyfZpig6UOzwtHxKXC2p28zHoEGnxn/bWpt0DtchlfsJa71wiVtjBaNB//xxUCkjTTLjCGOWhgZay4tqyQUQPcyDMBwRNKpionav,iv:TFkc4pGC3zGkI76XwmenWQNMGPBFktnCU7kBGV3TQ10=,tag:wj3QuDC3WihgAf/KsC567g==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbzhHand3SHpYY25xRkt3
            QmpkVGxSWlIvQkRMemFxSFlYZndlZUp2Z0IwCkZTTWxONEg4NE9oL1FkbXoyamQ2
            ZU9OSEZRMWRHREpnaXhZZkxkNVh2ZDAKLS0tIEFBcGt4NUU3cktSTkIzcnNCakps
            YlpNdkpzR0hMTnZOeldmekVkM2JPbW8Klft/HNR1ulKHuiKePkiLpSqttP77RTRZ
            2kVD37k99EBKyjYUv/aBy+1UEoo7hB+hkX6n3O+VGvWCySSf4voNUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVnkyUWs5QTZCZ0dicjFH
            REZuMEc1Mmg3aDJvbHBrWEtCcGpXY2R0YWlZCkZSUnZBRjY4QTlpaUFaOE12eEN1
            R1NNODlySVVuQzVOL2dET0RxN2E0MkkKLS0tIFlhWklDdElNZ1cvTGZ2Rm9DaTdx
            NkVlekZUejJYVDROWjVDbW4yeEpCdmsKOajErpHLDpu6BQN7M0COrhOLFqCZ2s5t
            aDMiSEDrDPwlcZdpDnlnv//GVMlMBnV9jF1r63Ixq0svZWyBX4tCPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T09:50:40Z"
    mac: ENC[AES256_GCM,data:NCZ1e2/9Zg3j93sONI03heHhR1UvvNI+ItTn/UnGCaWcwAjWPHjJUJP5YsoH6C57JCk6exclYur/nINetLJb1PIcTzSI1dzX0Tll49YwPUm2R5zu/T9188GrmrwhRVtQr4GZxdUboUmulO9IPrLKHSSraHKtZ7uQYTKRwsMvIr0=,iv:1H+MIbQRd3MEm6ChVxNnlRRNEXv0h6+y1B2LsFZGU0U=,tag:LGsIZj7lQUBgI9Pf5LoPnA==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
