---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-gpt
  namespace: paper
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: paperless-gpt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paperless-gpt
    spec:
      containers:
        - name: paperless-gpt
          image: ghcr.io/icereed/paperless-gpt:v0.25.1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: paperless-gpt-env
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-gpt
  namespace: paper
spec:
  selector:
    app: paperless-gpt
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
