apiVersion: v1
kind: Secret
metadata:
    name: paperless-gpt-env
    namespace: paper
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    PAPERLESS_BASE_URL: ENC[AES256_GCM,data:8IPN6gWoKzOjzP98Z4WZex5/LSlwx6mgtyd/jGm5nuwdd90yjiP86H8UpAV2,iv:LbEDCKamW49ibxVa7dRzncw8rl+SHORPp47RNoF2AxE=,tag:G5bevWIgEiOfTrOx4SvDKA==,type:str]
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:LaH0DLcUbyedaitxJvgoTopMEQkdSf3uPMFK9pRp8997Eo3zdxLwrA==,iv:UZpzrV2mxaz43V/LjtOifMwLxCkAIbM68S6nqRaUE4k=,tag:2yBFiLHLliif6EMerYHuXA==,type:str]
    PAPERLESS_PUBLIC_URL: ENC[AES256_GCM,data:9w+mlQSAwthjD60OhyJfr3VbhldbS/cr4+dvpUmbySNnYQ==,iv:XaV2CjHjRjLG0m11QvhihDuN/GU0rfnIJaJBVUrKDUU=,tag:n7xl1TZ3LXNytMrCpoBY9A==,type:str]
    #ENC[AES256_GCM,data:zMnwqOxp43E+UWBBtWWelCAyOmH7tKC7EkbS648=,iv:Rj44ZGJerl4Wfj7Utu6JFsOfgOVkrv535ofUzSg4jDI=,tag:+BT4fLSV9Vk/jKbXyiMzgg==,type:comment]
    #ENC[AES256_GCM,data:OA4hIGnAY75LjVFwrp/Jz6MB++4=,iv:1/vI+jLZXBdIXtBNO/VQR7gM+nmtMhd/QfdHtNvT//o=,tag:ps4xnjYN4OsEVgJUa9pg2A==,type:comment]
    LLM_PROVIDER: ENC[AES256_GCM,data:PHvKbsoD,iv:GvStX070Jf1lPnGR3ivQjDC2RwKNFlbJwY9rpzBDVq8=,tag:nYoZb5XqvcwuL3R1hZ4xqw==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:t8n7kBGRyAatP6PZGfGNECi33A==,iv:ge0uY3e3F+K4+RC28xuOlsLOYyn4+7XEFN0uJityQ2Y=,tag:O9IxbdYHq65U1C5RlAhWOQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:AKeBWti+YwqdTgag3Gi2TpeNlK+xcmwlgLciPqMPeVf+jKicNwO1lVyg0P9/h+F7bb5h1mluePs4mPzS/xzyQu5PCuDTBtbodA==,iv:RNYseNKa/1AWfOy3zrzimJ39p9IK+ryfpQuH6ftI6ek=,tag:0NoIqyJs+9ITrST2fCqgfw==,type:str]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:Nd60PUU22UrKivJ3ELHU+sLIIGR1nXrJthQwCw==,iv:mOqDzqV3i3zwUCyzSWfwp+8GtsC3mx3zzeFisArnBL8=,tag:buZCUWYk12lUnv4i8IO3ag==,type:str]
    LLM_LANGUAGE: ENC[AES256_GCM,data:8YBpxE1a,iv:r1TIW7iLr5q4uLndUtX6OfjPc3QOIgiZ3TE71vw+e04=,tag:X5ce5XwF6kydmVZSZTAUKA==,type:str]
    #ENC[AES256_GCM,data:5pBUs5pNeRP2OvUtYahxxgdU+Gu7UKj3,iv:M8J0ly2XsktIPDJnSGRoneGSuNBtpVzB9kh7eD0NPnA=,tag:PT6+bP54ydH6+rg8B94KMg==,type:comment]
    VISION_LLM_PROVIDER: ENC[AES256_GCM,data:A1KUfQ6s,iv:QwZnWkEYNyXBVuYjLff919pQgDoFdmO8aM8/6ymOhbs=,tag:BoUI8B8Q2VDhXoGbalnkcA==,type:str]
    VISION_LLM_MODEL: ENC[AES256_GCM,data:eXoI2GsKizi1ZE0LU9NrnFF3TAx/80kaRbhkgmM=,iv:MDcor5KBJjJ3ycWqo/pyMUK7/iOSmnQfAWQEigQbd2s=,tag:sfeaMhpQ2AHOAu0HJpdSdQ==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:tqwC8A==,iv:MhciT/J2zxSTDRLeO/46BA9pbvVZigkVEe8fH1aGKPc=,tag:wVDn2K8IlgcSCNNoCOzG1Q==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTkJ5NngwbGYxS3NaK1cv
            N3MycVdldnFRaW42cmFyTVNVV3cycndQancwCmpNZnl5ZTR5SW01V1VFV2o3enhj
            V2FrWCtwcnNMUWVJRFBHZVFSL3pzRUUKLS0tIE8zOUdaeUsrYzJ2d0lwUnVCZGJ5
            NGhBTFIxKzk4QnRQMGlub3ZpQ1BSZ1kKaIizlgRJ2sEpuea2nxnsfmmHJSjnUpDE
            +5AXn/XdNobKELfG8iRjdYE7LM6hHI6Zx1k8EM02QjCwSiS+gsG3aA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByY1JYZi9uYnhoTm5rTmFy
            MytCSWRzaGFYR21TTmwzQkxGdENXd3NjQVY0CmpmdkdvU1VXU2lXN0FlOHIrVVdH
            S0ZpVzJZbExuM1F6YmlxcFdEQnh5cHMKLS0tIDlYQ2k0Q2doMS9kTVpFS0QxVXVr
            OXJ4RVhLSHRaYm1tM3hCNGE4REJpeE0Kw5GTK98D53002DN/B15Hioc5Jc5wFpJm
            czClYOf3Cil9WDkbMoJTC3XK84BiSITdtl0aEgSmOHgTSLziUBBKqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T20:06:18Z"
    mac: ENC[AES256_GCM,data:bQ6salRgyOBXd7+qa7J9ouw7i/08LqeEOF5ONiMJbBcGOt/YrHzXlqycqmrjh0BqUHQz4i0sKz+C5h2Shp6UyZb2JWaQXy2WiLnmgqShi85CUi6kDaNljYBr87BQWdmcqdTi6eYSUJPUro7OteGaQGQOW8XsdUCoXbp9xGK7mY0=,iv:A1dDYCanTwYSqYmUzVf6hNgPu3Jckjnxd7K2F7xiOk8=,tag:sFyTFJvAjKF8egwJLqwfWg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
