---
# Config volume for sonarr. Replaces the hostPath mount on
# /vol_raidz1/docker/configs/downloader/sonarr/config.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-sonarr-config
  namespace: downloader
  labels:
    app.kubernetes.io/name: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeMode: Filesystem
