replicaCount: 2
runner:
    config:
        instance: ENC[AES256_GCM,data:Ertl12wV9DDM4kP9eTCzNu/UX9vsoJ3TmbMZAQ==,iv:3A+grKHvMyN1gEMGvVO+ZkWayAClIpkHt1vJUxrQ6t4=,tag:AKj7zxrxiB8gCAHCSU9yaQ==,type:str]
        existingSecret: forgejo-runner-secret
        file:
            log:
                level: info
            runner:
                file: .runner
                capacity: 2
                timeout: 3h
                ens: []
                labels:
                    - docker:docker://data.forgejo.org/oci/node:20-bullseye
                    - ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-latest
            container:
                network: ""
                privileged: false
                options: null
                valid_volumes: []
securityContext:
    privileged: true
affinity:
    podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - forgejo-runner
              topologyKey: kubernetes.io/hostname
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SW1USnJsa2EvdUZoeE4v
            SVh6S3R6dXVnbHllMFFsWFBvdWsxUlJZZVc4ClBjYmdxVXQrUFJaWXdtbUhQODJK
            M1J5T2IxZU1Lam04R0pZZTlZZDFHemMKLS0tIHF4NG50cVR5VWlYaVV4RnRHWmI0
            ejhINDJyM3hQT1p1QU94NTRYZHRxZW8KUq6rh+pora3TXYvBPUUZPCj9KCOtfEhy
            f+756z3thwcQ2sdKISoKpDm/1uP883WgD7u2fZwsVf7P+JQvDWgMqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOXNRaVgvRGRvcVpXYTdH
            bmNQdERwVC9GYVFRU2h4UzZLb042VkZrYVU0CkNtYnFYS21CMGlDWGt2WXNMTGVJ
            b3JTNUs1ZHVEWmZzZUxpTHcxUE9BYWsKLS0tIHJuU3dLaUVkNkFIWjdPSFZvaFgr
            dk8yd2NzdVlnVXpTSHd6cHJUNmxqMTQKHi42m+/MazFaigpXm9u3KXm6TjETNsyi
            G02Jqw+VM+/R2IACN2VfuZ2dEm47DXqeXeoWW3htaUJ/nOvvzE2Gvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T20:16:09Z"
    mac: ENC[AES256_GCM,data:D743yV/f5nUqq7xiLP3u0IVkvDY/GTaAEQv5JEjm4a7oUn9bfmCdJ6RSgEC8x9YwCEaanN+WiVcDsRbrlCYz3LqrBoNfYMUVjhjVT9sQ0yws65l5JglY6E58PPVT/KZkzhwQ34BfoklOc3EeStyH2dhRSBJ0NPrSEiSdTqJTdNg=,iv:wWD97oooIkaS979PfloG8+KoPL2KXyE6BVpB8FFdq34=,tag:YgJdvxFQjMhW3WSulOa7nw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance)$
    version: 3.11.0
