apiVersion: v1
kind: Secret
metadata:
    name: fritzbox-exporter-credentials
    namespace: monitoring
    annotations:
        argocd.argoproj.io/sync-wave: "19"
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:F7pIe52YvBAZYA==,iv:gHFOnLlEm0sqFWN1fDKs+o0kB0U0d/1NrQGQj1n0lAI=,tag:T0n3p/JxlbBl4/5+wHNdMw==,type:str]
    password: ENC[AES256_GCM,data:IDSVrmeKPg1AltNZQ3oaj2u8,iv:VglNgcu8QwN63xYdwJgkrkDCMrSRyPTQ7Kmo8Si27cg=,tag:TdVg1IWZifkCf978BV+daA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SWdXUy8zUTh6cVk2VGxI
            dDYyb3VwbXRQb1lXb2lKbmMzdVN2MDJMN2lZCktKa2tUODA2VDFPTEtUUXkwVDZ3
            Z2FHb05QUHdTUGJzWFJOelA1ZzQ1WEkKLS0tIGQ4RDFseGhpb2xWL0o3SlV4RUNs
            MG5PUWlOM01qbkNha2Nab1hBQXRhWEUK03A32aaMi4UVdvhw502j2nGtPJx7T/uK
            U7qB2/2+8mku02aSFvXMimOX700HzX7DIwWfpi6ATKFW/G9CaTC7hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ekV2ZEErVGlueFM5eVFT
            R2RwWGNTdmR6Y3ArL3VhNU5FUU95WlJ6MTJNClM0eFNJSkUrajh0QjdsNGVWZkhN
            UlNXUEI2U3Y4dkpPT21BMmFWVFRJUncKLS0tIEFnUkdiWG5ZeWhZMTFZWnFBcmV2
            cjFxTGV6VWJYdFZNY00wbWdhakt3SEEKj1uXxC49ldtQ9ie4HkbHHEMkdwDgA5xy
            C+CbrkcSbILonCjpW1DNRbwyOEu46UO2X+vvL9sut4pUmfdFufk53Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-09-06T08:44:36Z"
    mac: ENC[AES256_GCM,data:/gUOqpdBPFrOF5oDfVuP/YGjESYAgZC/iPbV6cInqa4sWSMMbYPd5cvOjfzNK8qHs7/PIcDLGvx96PGrRDBT5wdl+zs4lGqMxERoE3C74VDJ3DNw4LUA+kqzFL3noO353y/1WYZ/2FIZhTm9HvwGKMNejm+T1Rcz4iEQfagY6Mk=,iv:L4ep/HbtY1Uz5V/1aJ2p2GGnPqjmtiu9zjIr8STfI5A=,tag:mDks3A7fWFbBCJt1i+jDzg==,type:str]
    version: 3.13.3
