image:
    repository: ghcr.io/pi-hole/pihole
    #tag: 2025.11.1
    pullPolicy: IfNotPresent
revisionHistoryLimit: 2
serviceDns:
    mixedService: true
    annotations:
        lbipam.cilium.io/ips: 192.168.1.232
        lbipam.cilium.io/sharing-key: piholednsdhcp
    # type LoadBalancer with externalTrafficPolicy Local
    # requires 192.168.1.232 on the same node as the pod
    type: LoadBalancer
    #externalTrafficPolicy: Cluster
    #type: ClusterIP
serviceDhcp:
    annotations:
        lbipam.cilium.io/ips: 192.168.1.232
        lbipam.cilium.io/sharing-key: piholednsdhcp
    type: LoadBalancer
virtualHost: ENC[AES256_GCM,data:HPISZ9tPOHeL7OrifwjjxCQE6So+DRH5hoHcBw==,iv:7/Ebp4999WShrYpepo/Yr+OO/KTesAnbYrLQp1rluhk=,tag:DqCM7kuQBHlyHr3YMtdq7w==,type:str]
ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
        - ENC[AES256_GCM,data:+Rn+0l9fE7nUrWfl/gmY/XPi/+OfolYvi/FUUQ==,iv:WZlSc/gUK9uOcrGaiM992lZ2CWVQWkO/CwQ2biqbubg=,tag:LCV1BsLcEFPUKcg6QPuwGg==,type:str]
    tls:
        - secretName: wildcard-cloudflare-production-02
          hosts:
            - ENC[AES256_GCM,data:wlu3QcVtb7Xzv59SGzxUihuaAFgcbpz5ZOssxA==,iv:rjmUb6hGcXcaIzNURCBqGVCxu30DTeqfE6hw/t7fFBU=,tag:MEyw0obMwzxoNMK2x3T4mA==,type:str]
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web239, websecure239
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd, traefik-root-to-admin@kubernetescrd
resources:
    limits:
        cpu: 1000m
        memory: 1024Mi
    requests:
        cpu: 100m
        memory: 128Mi
extraEnvVars:
    TZ: Europe/Berlin
    #FTLCONF_LOCAL_IPV4: 192.168.1.232
    #FTLCONF_dns_dnssec: true
    FTLCONF_dns_bogusPriv: true
    FTLCONF_dns_domainNeeded: true
    FTLCONF_dhcp_start: 192.168.1.50
    FTLCONF_dhcp_end: 192.168.1.200
    FTLCONF_dhcp_router: 192.168.1.1
    FTLCONF_dhcp_leaseTime: 12d
    FTLCONF_dns_domain_name: neese-web.de
    FTLCONF_dhcp_rapidCommit: true
    FTLCONF_webserver_interface_boxed: false
    #FTLCONF_MOZILLA_CANARY: true
    #FTLCONF_BLOCK_ICLOUD_PR: true
DNS1: 127.0.0.1:5053
# Not required because secured via authelia oidc
admin:
    enabled: false
doh:
    enabled: true
    pullPolicy: IfNotPresent
    repository: crazymax/cloudflared
    tag: latest
    envVars:
        TUNNEL_DNS_UPSTREAM: ENC[AES256_GCM,data:9cd2B0aXclM4qNlvpXq3xWKX/bTUFG09iWgv3yft+UFF1y1K,iv:aBCORhurUPts54vdAdALW5SUmvveUyCyOdWd9DUHkow=,tag:KA55ykLmA4uF6F/sDdGDXg==,type:str]
dnsmasq:
    # Contains internal wildcard domains:
    # - address=/.example.com/192.168.1.45
    # - 'address=/.example.com/::'
    # - address=/.k8s.example.com/192.168.1.231
    # - 'address=/.k8s.example.com/::'
    customDnsEntries:
        - ENC[AES256_GCM,data:cIcthaJTGxVrDINzVhgdtkDR3vsg3NNOPVMKrhIsE5j1frU=,iv:U2PZrX4/uSudo3ZFUHV7vO+/2sbQttl4iLYqu35m1vs=,tag:125FWU38N7kEyxGFQiF/WQ==,type:str]
        - ENC[AES256_GCM,data:5Y4QU1vomtCiU42hmqlGwyqiBNWYKCZgkIspchA=,iv:AkpwgsutxhdB9I82ZCCaSLYcnSyORf90l7B6NT9iIDI=,tag:5YkIT1wjRjv3LEr2JME7SQ==,type:comment]
        - ENC[AES256_GCM,data:n81+bA2kOl+8cS4f0ke3VzHifP0bGP7mqPrKqNP+qcJfhAxFlQzwXA==,iv:GihIn9hEijLlJTSB40X7CZrGPivKmSueE4x9ohCOLN4=,tag:hEeffvoJa3Hhf9DBI07WzA==,type:str]
        - ENC[AES256_GCM,data:MDlfp0x5ODGcMTHsqP4YO5qMDA2CJAtnrcbFdrRxk6Wc,iv:SLWUP4ZoajcOTgYuqh2gJ8rk+Rc7XL+i9mc0ZYPKzho=,tag:MCwDsiTgf3VWKOmLVdQ/pQ==,type:comment]
        - ENC[AES256_GCM,data:eMS04RGI0Oxsivd4CZTXQJop836XJCINm8NgGBbBDzBOGtfB8BnXK3iA3FX8,iv:cVVx1iqiagBTqO42LYwW/SQfO/hlhBC1NcMx7XfhYUE=,tag:TBIV5d/ZuBSLLqwpUuGt1g==,type:str]
        - ENC[AES256_GCM,data:g8Orv/Scq0Ngqf1c8T++JaFS8nO9b3vRMYd2zG0Frovu6z5fhLc=,iv:nE/EY/b8TtuyfGqXSl/Camw4u2LI1UuVrokiO4dGQ/Q=,tag:6UQnzw/ClBqCG9nscajCzg==,type:comment]
        - ENC[AES256_GCM,data:TPYre/YpkLNYe6AJFUkZv+xviGcyyzjcHNV551ianwKwj+zTZjul6U22deNK9xI=,iv:LGV277CxkPkQYKesV4QRcjBO1+4vzPLyd3goraKEcuk=,tag:UCPo71CxMTUa6vRlNRousg==,type:str]
        - ENC[AES256_GCM,data:tMXy3R4E0PvMFBOZEFxJsECNMTCTDaRt6h/P4QkNbsSdkhwUEGxG2IMcbPxMpuPgQG0tTgS4,iv:BXr6KLqG5hD320FQNEF8vZo05qo609nY44FQQcl2eBM=,tag:0l3xeWdF1BlpJjexhYfJtw==,type:str]
        - ENC[AES256_GCM,data:A6xU34eqWKqvursVFIz7ymUxP2FRbGKTdB94IdgSseZKzRYdUhnn,iv:PFAgfOrRmgDa1HGLtjZ8ZVwKTLy5bqwhkd8GPcLnFqQ=,tag:Z0s3fAwJQBOT25SjgFoX4g==,type:str]
        - ENC[AES256_GCM,data:c66gAbEPhTIrUIH6UuFDH/THD6AADb3UihFEYNJ7gZ9m5pE/SeZjzaDIQZexaA==,iv:BHRgbOZFRDB9DkT/1RyAuDbCFrUmJsrNga979TNEVOU=,tag:mSRjWZA9t9TbmJEWaVNVDA==,type:str]
        - ENC[AES256_GCM,data:cKkb7BgpCqKAxVovPWnugxlejEFaMjrTxOIpfmG2izl4Ra9Zhg==,iv:adhAB627kagCJmIE0leccqL+tZNs9fzap9CYxNL2Qks=,tag:Xxxu1nso94mgW1V0oj/9YA==,type:str]
        - ENC[AES256_GCM,data:mHHcoMVTvEUxxSZsp7l10wXgnxMUkn2MzCYgSG7Y+5k0iOiH/0c+DWskpD0=,iv:fmZP2KqDTtf2O0YAaDqgAKW2jdqk9Gx8MEfWDQXf0xI=,tag:pSFgJLusKZkVu3xDg3EW6g==,type:str]
        - ENC[AES256_GCM,data:Ipo1AJoff2gA6HHh+q/3MVKoz3fhKafsWii7K6cBU8WLf5VQ1qm765+Incv+Kw==,iv:YWjEP3V0sXAvAHS1rZt6W5ETLxiWioYCziqUAH0Y7oc=,tag:HULXuEqt5CCwuo7E3KsFfw==,type:str]
        - ENC[AES256_GCM,data:PFlKHlhFOaNnZcAa/ebLxoX3pvw9yre8YuojIIIksUgJlli6yKZSRlNZt/x6DBldMVCqaFg=,iv:LPfn5aBtWPZXVzMFj55MOWYdcS81KN/L+hDNRDd9E+A=,tag:tro0OJ9AQbmQLbVxxqkh7w==,type:str]
        - ENC[AES256_GCM,data:grHS65Td954PLxuo4hU/lKO9QA4GbOlWnUa0L0usH+Rd213Xk+1wqGih8fOk8Dl6,iv:R+iz8RbfaprCNKps0jwtlyKisEJk3BWeGst6uNZ3CK0=,tag:s80npgWkn0Kb3S10pYj4Vw==,type:str]
        - ENC[AES256_GCM,data:It4iseRXWewr+8FTeP5RiNYJJYpGhI9G2/UYiQxEOGfj9FfsiDPl8GyE5gERzYK1hpGINq44YQ==,iv:RbX2DjfPCYvAy8CBxXT5ksZ6QYgxEWqqUbKNJgOUDRA=,tag:ep1UfgG1oWmTyURW6BczSw==,type:str]
    customSettings:
        - dhcp-option=252,"\n"
        - dhcp-option=vendor:MSFT,2,1i
        # DNS
        #- dhcp-option=6,192.168.1.232,192.168.1.1
        - dhcp-option=6,192.168.1.232
        # NTP
        - dhcp-option=42,192.168.1.1
        - dhcp-range=::,ra-names
        - server=/geekbundle.org/192.168.1.1
        - ptr-record=1.1.168.192.in-addr.arpa.,"despair"
        # TFTP Boot
        - dhcp-match=set:ipxe,175
        - dhcp-boot=tag:!ipxe,ipxe.pxe,dns01,192.168.1.45
        - dhcp-match=set:efi-x86_64,option:client-arch,7
        - dhcp-boot=tag:efi-x86_64,ipxe.efi,dns01,192.168.1.45
        - dhcp-boot=http://192.168.1.45:8043/boot.ipxe
        # DHCP Reservation with different dns server
        - dhcp-option=net:customdns,6,9.9.9.9,1.1.1.1
        - dhcp-host=net:customdns,EC:79:49:51:64:16,192.168.1.187,ipl06002-lan
        - dhcp-host=net:customdns,F4:4E:E3:2C:C2:B6,192.168.1.56,ipl06002-wlan
        # DHCP Reservation with unrestricted youtube dns server
        - dhcp-option=net:youtubedns,6,192.168.1.238
        - dhcp-host=net:youtubedns,AC:3E:B1:A6:AF:D6,Pixel-7-Pro
        - dhcp-host=net:youtubedns,E0:80:6B:37:56:83,Redmi-Note-11
        - dhcp-host=net:youtubedns,74:58:F3:E7:3A:04,Fire-Cube-lan
        - dhcp-host=net:youtubedns,48:43:DD:6E:CC:2D,Fire-Cube-wlan
        - dhcp-host=net:youtubedns,F0:27:2D:D7:41:97,Fire-Guest
        - dhcp-host=net:youtubedns,00:e0:4c:7b:c2:98,Sanctuary
        - dhcp-host=net:youtubedns,8c:8c:aa:32:ce:7a,IONB000201752-LAN
        - dhcp-host=net:youtubedns,4e:80:5d:ae:a9:dd,IONB000201752-WLAN
        # HTTP Boot
        #- dhcp-match=set:efi-x86_64_http,option:vendor-class-identifier,0,10
        #- dhcp-boot=tag:efi-x86_64_http,"http://192.168.1.45:8043/ipxe.efi"
        #- dhcp-boot=tag:!ipxe,"http://192.168.1.45:8043/ipxe.pxe"
    #customCnameEntries:
    #- cname=www.youtube.com,restrict.youtube.com
    #- cname=m.youtube.com,restrict.youtube.com
    #- cname=youtubei.googleapis.com,restrict.youtube.com
    #- cname=youtube.googleapis.com,restrict.youtube.com
    #- cname=www.youtube-nocookie.com,restrict.youtube.com
# Not required. We're running a dhcp relay via host network.
#hostNetwork: "true"
capabilities:
    add:
        - NET_ADMIN
        - CAP_SYS_TIME
        - CAP_SYS_NICE
persistentVolumeClaim:
    enabled: true
    existingClaim: pihole
    #storageClass: longhorn
    #size: "10737418240"
podDnsConfig:
    enabled: true
    policy: None
    nameservers:
        - 1.1.1.1
        - 127.0.0.1
#affinity:
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - node03
probes:
    liveness:
        initialDelaySeconds: 30
    readiness:
        initialDelaySeconds: 30
affinity:
    podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - pihole-02
              topologyKey: kubernetes.io/hostname
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCV3hQY3RKOFdMRVkzRmsy
            ejc2MFcyblh1TlYxMnBnWStNSE1VVHhWMEQ4CmNHNm1GTFJWazU4U05aUW9DQkxn
            ZVEvWXN0aFRhUFYrUmVYZkZPMlIrb3MKLS0tICtKWDI3a2ZoTUE0aE9ZMFQ2cFFw
            SDVoU0hzQjNwc1RHOG9nMi9BYTUyYUEKcTDWrxKQ/bQoffEG39yY57ixX8IqWmlk
            EfNKVzHi0MLERn1Jv3Us57Eeed7DBuWtmbugT+im6ARRSh7wAB0JEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIV2lPd00wMlltUmNFWHp3
            UURQMmNWanEweGJiUVFrL21Kd3Bud1FDVG1FCjVweFVKTmxucWt6YnVDYzVkcTNm
            YmVtbUQzUXJxK3ZpUDkxd1BEK2wzVDgKLS0tIEpmcFMwWUptN21DckRPSFZtcW45
            b25UdUZvOExLVDRUeUEyRlZzdGVsR0kK8ByJJu/gxTYYL/DTme12Xz+UnluWHT8K
            0GN6oQf38pQXb1e9BvJdgogBWmUsvYaQ262z28WuACQ1F+6dPqrUeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-05-09T13:26:49Z"
    mac: ENC[AES256_GCM,data:dEkBvd73Ojf1Sjpf25HN46Rp3BkAeGZzbSQBWx7Msq/WUBP4CjHJGy+hW862+l7iV7IBrei/L56EVjquPAx9ZDMEElhyO9VRL+gnSRV1wMthnZngnS++TWJ3sHjmi/gRZpYezFmf5gj68+AvuvJsv5fxUOyTdEDmAyy1ju8V9ws=,iv:Oiqi+BYwmyCQOFsDgY27VRGKfHAW08nH0PIRuiWrsAE=,tag:/+4zwoIZYV3xtkGiXr8x0w==,type:str]
    version: 3.13.0
