image:
    repository: ghcr.io/pi-hole/pihole
    #tag: 2025.11.1
    pullPolicy: IfNotPresent
revisionHistoryLimit: 2
serviceDns:
    mixedService: true
    annotations:
        lbipam.cilium.io/ips: 192.168.1.232
        lbipam.cilium.io/sharing-key: piholednsdhcp
    # type LoadBalancer with externalTrafficPolicy Local
    # requires 192.168.1.232 on the same node as the pod
    type: LoadBalancer
    #externalTrafficPolicy: Cluster
    #type: ClusterIP
serviceDhcp:
    annotations:
        lbipam.cilium.io/ips: 192.168.1.232
        lbipam.cilium.io/sharing-key: piholednsdhcp
    type: LoadBalancer
virtualHost: ENC[AES256_GCM,data:ssA/qYq4HFjDZR4aKKlRAtEwy7CSN9gXtMkB3w==,iv:3w4yN3kqJ3WK6CtuyiMUSrTxLZWRfj/Uqc438HNz7N8=,tag:RtnB2mZ7o96qw3544xzZnA==,type:str]
ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
        - ENC[AES256_GCM,data:4D5Fc850/7z4c+aAkQr36vp0mKgfSn9XScTQeA==,iv:fhCxVM4sEO85pNknKYsBWWyaGo9y/mQN+YPDLusnz1Q=,tag:7pZ1IMiVEx9idrJp1NqC5A==,type:str]
    tls:
        - secretName: wildcard-cloudflare-production-02
          hosts:
            - ENC[AES256_GCM,data:7lu3mBHKTRrXup7y/UkguhlJO2BhKgXFiZmLOQ==,iv:IKcgB4SmwohPX6DPtv7s4YyVYfXUThNw3lqGhaH0VB8=,tag:RGXw94RL4uuii9u2DGl/1A==,type:str]
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web239, websecure239
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd, traefik-root-to-admin@kubernetescrd
resources:
    limits:
        cpu: 1000m
        memory: 1024Mi
    requests:
        cpu: 100m
        memory: 128Mi
extraEnvVars:
    TZ: Europe/Berlin
    #FTLCONF_LOCAL_IPV4: 192.168.1.232
    #FTLCONF_dns_dnssec: true
    FTLCONF_dns_bogusPriv: true
    FTLCONF_dns_domainNeeded: true
    FTLCONF_dhcp_start: 192.168.1.50
    FTLCONF_dhcp_end: 192.168.1.200
    FTLCONF_dhcp_router: 192.168.1.1
    FTLCONF_dhcp_leaseTime: 12d
    FTLCONF_dns_domain_name: neese-web.de
    FTLCONF_dhcp_rapidCommit: true
    FTLCONF_webserver_interface_boxed: false
    #FTLCONF_MOZILLA_CANARY: true
    #FTLCONF_BLOCK_ICLOUD_PR: true
DNS1: 127.0.0.1:5053
# Not required because secured via authelia oidc
admin:
    enabled: false
doh:
    enabled: true
    config: |
        listen_addresses = ['0.0.0.0:5053']
        server_names = ['nextdns-135128']
        require_dnssec = false
        require_nolog = true
        require_nofilter = true
        dnscrypt_servers = true
        doh_servers = true
        odoh_servers = false
        ipv6_servers = false
        bootstrap_resolvers = ['9.9.9.9:53', '1.1.1.1:53']
        timeout = 5000
        keepalive = 30
        log_level = 2
        use_syslog = false
        cache = true
        cache_size = 4096
        cache_min_ttl = 2400
        cache_max_ttl = 86400
        cache_neg_min_ttl = 60
        cache_neg_max_ttl = 600

        [sources]

        [static]
          [static.'nextdns-135128']
            # https://dns.nextdns.io/135128/pihole03
            # https://dnscrypt.info/stamps/
            stamp = 'sdns://AgcAAAAAAAAAEjIxNy4xNDYuMjIuMTYzOjQ0MwAOZG5zLm5leHRkbnMuaW8QLzEzNTEyOC9waWhvbGUwMwA'
#doh:
#    enabled: true
#    pullPolicy: IfNotPresent
#    repository: crazymax/cloudflared
#    tag: latest
#    envVars:
#        TUNNEL_DNS_UPSTREAM: https://dns.nextdns.io/135128/pihole
dnsmasq:
    # Contains internal wildcard domains:
    # - address=/.example.com/192.168.1.45
    # - 'address=/.example.com/::'
    # - address=/.k8s.example.com/192.168.1.231
    # - 'address=/.k8s.example.com/::'
    customDnsEntries:
        - ENC[AES256_GCM,data:fjF+IXxTCbxC5qmI6+EsS9f3hY1vxxoO6iYGbPF7Q2PQN/A=,iv:JKfVwtfUqq/KLBllPZLeae6KWD+hh4hoR19nFVdjrSI=,tag:SksEivuA/DULQnFP5lBFdw==,type:str]
        - ENC[AES256_GCM,data:Tiks2MezfeTHJfclEKfn0ufuPNzMNp3fktdyYss=,iv:CsKSiBQl3PH8eE3K9LakqwZ6/y/IEfepaU8vWr1uvDw=,tag:iOhzTVptIXJ7p7/0UPL+wQ==,type:comment]
        - ENC[AES256_GCM,data:6R70g4NZ/Ksjes8l62P2MddKzREP1QI1DjkwJNGSkCx+L1AQPA5LNA==,iv:CO88NNw9Y2g2HawUOXHp3B1bIv3VyXfM12TArIzvqgE=,tag:F25XXtFIt0PEiEE1TdvFQw==,type:str]
        - ENC[AES256_GCM,data:D7J8+C8/T9NvU6zp4EhXmzsQEIKW4j/QLT65Ju8rQ3s8,iv:aLIE3Bjeo19+/1hndF2tBLScg32Y1DXHvcSYZYEXCdQ=,tag:MAfFknRU1UcjH6e6LZcvzg==,type:comment]
        - ENC[AES256_GCM,data:8a3hAXr+eUFf4NRjwN4kTo/dW7To559kW/s3ff6fd1cM/xJLYW6+zVyzcgI0,iv:H+WtqKupCowmHHNXYyt/KsbwInWFx2Ny9PknN0h8x7E=,tag:qnklISU9AfJMPx17kHTLHA==,type:str]
        - ENC[AES256_GCM,data:7/ZCZ7YE/dcT0aQL599gVhIK4+rxDIkUDo4s28uGqFYPX9iSY+o=,iv:nRVyxLz4/JqHRmsQ4BCcs6NksuwOzl6D3cvW4IsjZ6M=,tag:LcqyZz6IJ4d/1ruHaIH6gg==,type:comment]
        - ENC[AES256_GCM,data:iu6h84YLXEhJa4IkGpGq2KsKnC5ELvWZiSb3/8mKpgQaJCST+t/ah57jPw/MsJM=,iv:v2egTq8d2KO34lgxliho2iyTHGrv8TTaj2WrAsa7n9Y=,tag:kxiFChZoCaW8OZMB0MwT5g==,type:str]
        - ENC[AES256_GCM,data:h7cKLmPAAdpwiipGoAEqg3HD/hnUQBBe1yKQXtTXYaZcJUDClAMtQ8x7cPzDpZAfv0uKUd/9,iv:YynboLWKJoSgUYg8EHZcLCBqyeijxfyUVjbYDDA+Ei8=,tag:4hh+w+Duf7rq0eFhcQBrsw==,type:str]
        - ENC[AES256_GCM,data:8POSXB6yEeDTAGkc19STgY1MNbngyJBg5BzmJovcnSepRPiprNRQ,iv:h+gSxoOZmRz0yTqv4kCAjqW9QLPFSvvt0k5tBNEn9+8=,tag:t2LTDUogvarMETAchdjNhQ==,type:str]
        - ENC[AES256_GCM,data:2gRGirtH3Wze5RqwsLWraF2flscSPhN3L34t/swZON7S4lFfZWWprXbSouPp1g==,iv:SQlhtkO1P7HdSowut9KPT34VECOfQI3xnYaLATZkt/Y=,tag:A7dTyYUJTkieMyiwOvNLsQ==,type:str]
        - ENC[AES256_GCM,data:5hniLK3VE98+dmgKAWpvfRT12OJtgZDZB/BAqALw9jNie0DsYA==,iv:tb0J04WRthkoib2ZCY4WKqzntyXtAKre1COe/09+wJw=,tag:IOCKLnYmUe57Xhaeri10Cg==,type:str]
        - ENC[AES256_GCM,data:9S8kOlASvXL4LJinAimTWbYtc9LnvhMPyrKlh0NZ3bOqpMWrjFHSkKvOPOE=,iv:1vVHzYnUD8OeLcR9fa4MArtNud25sHfHKYt9IlNTvdc=,tag:xL6bxgHXG0HAS7n94GrP2Q==,type:str]
        - ENC[AES256_GCM,data:z+1p3bujsewpC6LuHwL0+m8wCKPwK3yy1XRaVDX1z4ykgEzu+Ko0N62MEocwSg==,iv:5YDZqf61mdfrJeD2oFD4sVDD2jzciKeWdcYZ8tdFitc=,tag:NHYOEuTvWx+Odsf7XkngVA==,type:str]
        - ENC[AES256_GCM,data:HbWNzm+yldyLPe7zcawgs1HPPjVl5GGrqMRWfffjcdEt+rfiwqFPLwiMMiGgX+L64c6IC7c=,iv:tD0l0Rga07d+nRn8nOLNegpLQqSHCmuOIBXImMO6N/g=,tag:Tv7XLxOBTSS7VTA0pp6KxQ==,type:str]
        - ENC[AES256_GCM,data:ITwV64qjDMzrMzpKf9+oFDXom4MBAAX33zrg6TaTjEEfEseKC6ur2nfKWZq7/i+8,iv:3VdhTfCCm5Ecbgc1JkAdnpWmGBpaUhz1vYUVAytFe3g=,tag:R6CK6Js6RNylNjYFVQHOjQ==,type:str]
        - ENC[AES256_GCM,data:pz9wLnCcc7u3NwAeeviQlGAMCsbR2ElEBoqqORf1XqzTrYfA9JbmJSW3Wsv1AauYxVhi8EtYgQ==,iv:ghKc7xkjFdGh3EzaT2hG1DhfFIBMgz2DP/skTg+TIwA=,tag:MFx9VSRwQO9yf2iH9PrnMw==,type:str]
    customSettings:
        - dhcp-option=252,"\n"
        - dhcp-option=vendor:MSFT,2,1i
        # DNS
        #- dhcp-option=6,192.168.1.232,192.168.1.1
        - dhcp-option=6,192.168.1.232
        # NTP
        - dhcp-option=42,192.168.1.1
        - dhcp-range=::,ra-names
        - server=/geekbundle.org/192.168.1.1
        - ptr-record=1.1.168.192.in-addr.arpa.,"despair"
        # TFTP Boot
        - dhcp-match=set:ipxe,175
        - dhcp-boot=tag:!ipxe,ipxe.pxe,dns01,192.168.1.45
        - dhcp-match=set:efi-x86_64,option:client-arch,7
        - dhcp-boot=tag:efi-x86_64,ipxe.efi,dns01,192.168.1.45
        - dhcp-boot=http://192.168.1.45:8043/boot.ipxe
        # DHCP Reservation with different dns server
        - dhcp-option=net:customdns,6,9.9.9.9,1.1.1.1
        - dhcp-host=net:customdns,EC:79:49:51:64:16,192.168.1.187,ipl06002-lan
        - dhcp-host=net:customdns,F4:4E:E3:2C:C2:B6,192.168.1.56,ipl06002-wlan
        # DHCP Reservation with unrestricted youtube dns server
        - dhcp-option=net:youtubedns,6,192.168.1.238
        - dhcp-host=net:youtubedns,AC:3E:B1:A6:AF:D6,Pixel-7-Pro
        - dhcp-host=net:youtubedns,E0:80:6B:37:56:83,Redmi-Note-11
        - dhcp-host=net:youtubedns,74:58:F3:E7:3A:04,Fire-Cube-lan
        - dhcp-host=net:youtubedns,48:43:DD:6E:CC:2D,Fire-Cube-wlan
        - dhcp-host=net:youtubedns,F0:27:2D:D7:41:97,Fire-Guest
        - dhcp-host=net:youtubedns,00:e0:4c:7b:c2:98,Sanctuary
        - dhcp-host=net:youtubedns,8c:8c:aa:32:ce:7a,IONB000201752-LAN
        - dhcp-host=net:youtubedns,4e:80:5d:ae:a9:dd,IONB000201752-WLAN
        # HTTP Boot
        #- dhcp-match=set:efi-x86_64_http,option:vendor-class-identifier,0,10
        #- dhcp-boot=tag:efi-x86_64_http,"http://192.168.1.45:8043/ipxe.efi"
        #- dhcp-boot=tag:!ipxe,"http://192.168.1.45:8043/ipxe.pxe"
    #customCnameEntries:
    #- cname=www.youtube.com,restrict.youtube.com
    #- cname=m.youtube.com,restrict.youtube.com
    #- cname=youtubei.googleapis.com,restrict.youtube.com
    #- cname=youtube.googleapis.com,restrict.youtube.com
    #- cname=www.youtube-nocookie.com,restrict.youtube.com
# Not required. We're running a dhcp relay via host network.
#hostNetwork: "true"
capabilities:
    add:
        - NET_ADMIN
        - CAP_SYS_TIME
        - CAP_SYS_NICE
persistentVolumeClaim:
    enabled: true
    existingClaim: pihole
    #storageClass: longhorn
    #size: "10737418240"
podDnsConfig:
    enabled: true
    policy: None
    nameservers:
        - 1.1.1.1
        - 127.0.0.1
#affinity:
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - node03
#probes:
#    liveness:
#        initialDelaySeconds: 30
#    readiness:
#        initialDelaySeconds: 30
affinity:
    podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - pihole-02
              topologyKey: kubernetes.io/hostname
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWXhYUW5TSXBnSFUzaUZ0
            NXJhcmZrV28rK01QTUNqMFN2a0ppazVUK1c0CnRiSFc5NnMzOFdpTHRROVI0V0lB
            VXY5R2NXUlY3b1JPNjVvL3VGZmprcncKLS0tIHRzMDJVeXpFclVTZ01EZ1JHZFp5
            Y3ZOand1eENISnF3NzJnSlIrRThOSlUKKtQoA+3FdaAbfPuCeeDNMbYaS9FeijS8
            IyTltQBsWuhEhzmI5NlHKODlYOY/QZP7DTErC2yWFcURFeAXT2Abeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArc0dSUWIwRFI0ME9SenBx
            YjJRUk95THNiVFd0WUpLYldHaXpkSlo2eDBBCkVCZFRoWU85K3dxT0xhL1lMeFFs
            OFgrK2dNQjVpWi9hSFR2M3o2SWFHTFEKLS0tIEhBYjhSL09WVkFKWjJTQU9ISjJx
            ejVCRlYxSm43THY3c05QT3YzMHQwV2MK6aM8OPnRBjJC80CXyaKQT22ItoS3ZC1E
            Qzraup8WOUdxRnM84J7WygHw8p+87CW8spUSmJYuLb2cw5N/Q81vjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-05-09T13:48:45Z"
    mac: ENC[AES256_GCM,data:tN9ScL6kMscBKzQBktOCWnus4Z4Q/sWhb7PVDjQP0oPUNruIhmX4Rtcj8rO9KdimnQUgvkIzhQdF3rcLKdNeq8Ij8/rfh1ekYHjeuJ7l4Qerq177YF5pBFUaM9uVYMPaAMCXF7XQBf52BV4B2F2RavlcL4Ek+tjKLtXl6+TarX8=,iv:lUpJZKny7/ziZNtAC0MnR8jFt1CPxQa3tzx6NBRTfPc=,tag:IiJJM77jhcLm7aWvFl+qwg==,type:str]
    version: 3.13.0
