image:
    repository: ghcr.io/pi-hole/pihole
    tag: 2025.11.0
    pullPolicy: IfNotPresent
revisionHistoryLimit: 2
serviceDns:
    mixedService: true
    annotations:
        lbipam.cilium.io/ips: 192.168.1.232
        lbipam.cilium.io/sharing-key: piholednsdhcp
    # type LoadBalancer with externalTrafficPolicy Local
    # requires 192.168.1.232 on the same node as the pod
    type: LoadBalancer
    #externalTrafficPolicy: Cluster
    #type: ClusterIP
serviceDhcp:
    annotations:
        lbipam.cilium.io/ips: 192.168.1.232
        lbipam.cilium.io/sharing-key: piholednsdhcp
    type: LoadBalancer
virtualHost: ENC[AES256_GCM,data:UQ8YmlpxroRZJYQhwYXjrHX9QbnUVgtyspH1Rg==,iv:3AP9FcHoH6MkdrCk/kuRye2t4c/VP7bV7zgaxtUZe9U=,tag:blIfieoT4XKFXMyrYsC4ig==,type:str]
ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
        - ENC[AES256_GCM,data:X5e7pCEOfsfsizM6a+0sE0s2wPgtqsaa+Yl0XQ==,iv:5z3YHIxM2/g8DzaztK38eKWu3wr9mWPHogVCCTzzkxc=,tag:gRJt7f8X3utNSVoyH1glaA==,type:str]
    tls:
        - secretName: wildcard-cloudflare-production-02
          hosts:
            - ENC[AES256_GCM,data:TKtBsfe+LMThAIU+dZT705E+ocibMKUdz9EiMQ==,iv:fIuMyfCIy2yDxia3FAXb30b+JRgTnxse2MvH8bJd6IM=,tag:3ta9RRgaB7toU142H/qj+g==,type:str]
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web239, websecure239
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd, traefik-root-to-admin@kubernetescrd
resources:
    limits:
        cpu: 1000m
        memory: 1024Mi
    requests:
        cpu: 100m
        memory: 128Mi
extraEnvVars:
    TZ: Europe/Berlin
    #FTLCONF_LOCAL_IPV4: 192.168.1.232
    #FTLCONF_dns_dnssec: true
    FTLCONF_dns_bogusPriv: true
    FTLCONF_dns_domainNeeded: true
    FTLCONF_dhcp_start: 192.168.1.50
    FTLCONF_dhcp_end: 192.168.1.200
    FTLCONF_dhcp_router: 192.168.1.1
    FTLCONF_dhcp_leaseTime: 12d
    FTLCONF_dns_domain_name: neese-web.de
    FTLCONF_dhcp_rapidCommit: true
    FTLCONF_webserver_interface_boxed: false
    #FTLCONF_MOZILLA_CANARY: true
    #FTLCONF_BLOCK_ICLOUD_PR: true
DNS1: 127.0.0.1:5053
# Not required because secured via authelia oidc
admin:
    enabled: false
doh:
    enabled: true
    pullPolicy: IfNotPresent
    envVars:
        TUNNEL_DNS_UPSTREAM: ENC[AES256_GCM,data:cw+FTHU8DTB9L1SwFFBC5wkhrp8L3ofKAd9PDbrucm8IFLqq,iv:Q++ziYukbUcpzlwSxfJByTrOfhp83WD1nuKvYqjZkGI=,tag:19Wx1g/pkyFEvh2YJkvbKQ==,type:str]
dnsmasq:
    # Contains internal wildcard domains:
    # - address=/.example.com/192.168.1.45
    # - 'address=/.example.com/::'
    # - address=/.k8s.example.com/192.168.1.231
    # - 'address=/.k8s.example.com/::'
    customDnsEntries:
        - ENC[AES256_GCM,data:4hc1rq8u8X4PwEnDe8tzSL+qJo+ahKpKi3Nemh09Hb/xQIo=,iv:f3i42Cfp/yf5QGB5WNVzIJeLjhh7ZULudJ3q6/LlaDU=,tag:d2Bof3rHT9Wd7k13iqCU/A==,type:str]
        - ENC[AES256_GCM,data:rDksprr8Yc1cNWVdvoibMsAVx52iCgvbFZMiWXU=,iv:OdSdFLHcu6ieAOeY4uj06w9M0fV5vPh6DcZ+XeBgFF8=,tag:suR9RntKKsCxsnKlqp3GPw==,type:comment]
        - ENC[AES256_GCM,data:9G6Kdqr5l4HIkIf8IXwWGh+ImExp3sK1O+Jhcq+2jWWMoTY6speglQ==,iv:Y2oRRbpEpfjwtgfR0V5e8D41X/Rci6BC1A34sekLXXg=,tag:AaMKVCyxJoR0HUi5F0HF+Q==,type:str]
        - ENC[AES256_GCM,data:49lvSimCJRbRyKEY542KFHOC8u3ErVz4Ckv/wY4bjc97,iv:8RFgd/TcWFkhEE2gBuI0k8My6tOGNC78zN1LSHo80ec=,tag:1UUm+xk49eNcvUWYRHWOKQ==,type:comment]
        - ENC[AES256_GCM,data:7sEiWmnaX71YARPUI9J0rxehOxsazLFiqw4oQ7Wo4NtXyTQxdaftITVXyZnM,iv:J2vLGy9tL1C8RBj3IN722OtpwXv+7wT88Yqy09SXPcE=,tag:Fk2NEWo22BfyJaBR7Bv+WQ==,type:str]
        - ENC[AES256_GCM,data:pn/RbqooUD8UBeWComHXjcdEnoVoPak3C7Mx6pj/gfAgA+Mbks0=,iv:XUiAvkyTL47YWTyJywq8UEUjCwkRwSq3BQ+ZuV/3Ilg=,tag:/j0ebydyD6Ab34fFFZwe+Q==,type:comment]
        - ENC[AES256_GCM,data:90hZUrPcEKi1OVWHJaCGfhAwjeNsiyYUdx9+n1/kLyhk7vge/nTf7l12y8qvK8I=,iv:yxtHKoPX6P2vVz4Bf4hz3Cp8wMrkxmGgnNpj/HdCfUU=,tag:VDwv2hHI9uH9VtsDN0cL3Q==,type:str]
        - ENC[AES256_GCM,data:SMe9H6N0XW45bWwZCwa1s2UeAuiUqq+YcUWr2EcmzcgBK4R4j+/auGxULViXZq27RYtdxBW0,iv:59up4cVIelF4xYFx9krqJSNbliAb0QAPHCE69gazUbY=,tag:yeo/OmSrGhACZ8TvsziORw==,type:str]
        - ENC[AES256_GCM,data:jWyD9jkSZ4nxG47oinknKHz6wuwJDQ4ftiy9r21FaNFIUC5vxgqs,iv:86iJD4tUQ6cNUf8+Rvtgqhdk8PsC0qr6CHv57jqvy6c=,tag:XV7eMxD0Reg1g/JxJoF62g==,type:str]
        - ENC[AES256_GCM,data:9eBUdNwSn7DnLWA+Yd9anp5FymBb/4Jipa1RkkcoV5sUKhXrLFzZT9TD+ijhzQ==,iv:06sLi7tbEO/LocO/XohNzST6YgvkSBCjaGVYWee9lpg=,tag:P+6z/MZhfB8gLJS+viv6Jg==,type:str]
        - ENC[AES256_GCM,data:ASjAR/kEPTSnXDiS3nZRzjNw3sWIQ9G5YXMPJz0CJCXiP+OTCw==,iv:nNWS/Ha9rJJ2CZsk/gSNIpAMcICVyN+aQgaJRDzbLl8=,tag:dCrJFEOmcNr6VaSOFq/cCQ==,type:str]
        - ENC[AES256_GCM,data:MNLm5T7hI4YaWYFv2q2V9F+yKADrdAm1NgAHoPY4M/oCpIDnf+es4w2omy4=,iv:t7waIDnAhAa/PL/f9pScINzQmAy7wdLT9C5RnR7XkC8=,tag:6GhcivOmkq6ZwNg1jdXNYQ==,type:str]
        - ENC[AES256_GCM,data:sEASHm6mHD1Q9VgJeoxXsXUrcMO6Djq1WbQeoYrLOD7SJ24LJApLtlgt20Rk3w==,iv:mjVFd1G9GCnqdEWFxiFqs3qCY2MnTj6OwoDakpX202Y=,tag:zeITz/20DRgPyaGGTaNc+A==,type:str]
        - ENC[AES256_GCM,data:n3nuj2+mlYMS4/kNVFIfxwn5PNP+agjHWl0lVx30SrE5EJ4QP77Vhh4rBUmC2wML9S2Dx1c=,iv:1Vqu4MCN7V0k3kJXeZGXjRngXIDPtLPG/17+vwnKa5A=,tag:vgkzfq4xCi8CfA2lHotmvQ==,type:str]
        - ENC[AES256_GCM,data:CDXWOBX+WosWdOPjY64xwJJ8cFWjGeygLir/gcfJQnMSg7ppOQJJv9VPAnhIEoba,iv:lom3pzJKGRyks9sVl3X6zjmKNe+XMALWtD1yu0tjmV0=,tag:xg+C3kN5lZIuUmCho9nwWw==,type:str]
        - ENC[AES256_GCM,data:8dhx09i98ctFqnIAUFz5vpIIoVgbBFshTI3fa8MD+4LVLO2ZZvEO8AW/6zpi8tryo69rKdOcmA==,iv:MAdqOMZSNrF85oAmDH/JOVlNnPh+mdEcy49cpqtejtY=,tag:lIuuu17aq77M2f3CHZu1Aw==,type:str]
    customSettings:
        - dhcp-option=252,"\n"
        - dhcp-option=vendor:MSFT,2,1i
        # DNS
        #- dhcp-option=6,192.168.1.232,192.168.1.1
        - dhcp-option=6,192.168.1.232
        # NTP
        - dhcp-option=42,192.168.1.1
        - dhcp-range=::,ra-names
        - server=/geekbundle.org/192.168.1.1
        - ptr-record=1.1.168.192.in-addr.arpa.,"despair"
        # TFTP Boot
        - dhcp-match=set:ipxe,175
        - dhcp-boot=tag:!ipxe,ipxe.pxe,dns01,192.168.1.45
        - dhcp-match=set:efi-x86_64,option:client-arch,7
        - dhcp-boot=tag:efi-x86_64,ipxe.efi,dns01,192.168.1.45
        - dhcp-boot=http://192.168.1.45:8043/boot.ipxe
        # DHCP Reservation with different dns server
        - dhcp-option=net:customdns,6,9.9.9.9,1.1.1.1
        - dhcp-host=net:customdns,EC:79:49:51:64:16,192.168.1.187,ipl06002-lan
        - dhcp-host=net:customdns,F4:4E:E3:2C:C2:B6,192.168.1.56,ipl06002-wlan
        # DHCP Reservation with unrestricted youtube dns server
        - dhcp-option=net:youtubedns,6,192.168.1.238
        - dhcp-host=net:youtubedns,AC:3E:B1:A6:AF:D6,Pixel-7-Pro
        - dhcp-host=net:youtubedns,E0:80:6B:37:56:83,Redmi-Note-11
        - dhcp-host=net:youtubedns,74:58:F3:E7:3A:04,Fire-Cube-lan
        - dhcp-host=net:youtubedns,48:43:DD:6E:CC:2D,Fire-Cube-wlan
        - dhcp-host=net:youtubedns,F0:27:2D:D7:41:97,Fire-Guest
        - dhcp-host=net:youtubedns,00:e0:4c:7b:c2:98,Sanctuary
        - dhcp-host=net:youtubedns,8c:8c:aa:32:ce:7a,IONB000201752-LAN
        - dhcp-host=net:youtubedns,4e:80:5d:ae:a9:dd,IONB000201752-WLAN
        # HTTP Boot
        #- dhcp-match=set:efi-x86_64_http,option:vendor-class-identifier,0,10
        #- dhcp-boot=tag:efi-x86_64_http,"http://192.168.1.45:8043/ipxe.efi"
        #- dhcp-boot=tag:!ipxe,"http://192.168.1.45:8043/ipxe.pxe"
    #customCnameEntries:
    #- cname=www.youtube.com,restrict.youtube.com
    #- cname=m.youtube.com,restrict.youtube.com
    #- cname=youtubei.googleapis.com,restrict.youtube.com
    #- cname=youtube.googleapis.com,restrict.youtube.com
    #- cname=www.youtube-nocookie.com,restrict.youtube.com
# Not required. We're running a dhcp relay via host network.
#hostNetwork: "true"
capabilities:
    add:
        - NET_ADMIN
        - CAP_SYS_TIME
        - CAP_SYS_NICE
persistentVolumeClaim:
    enabled: true
    existingClaim: pihole
    #storageClass: longhorn
    #size: "10737418240"
podDnsConfig:
    enabled: true
    policy: None
    nameservers:
        - 1.1.1.1
        - 127.0.0.1
#affinity:
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - node03
probes:
    liveness:
        initialDelaySeconds: 30
    readiness:
        initialDelaySeconds: 30
affinity:
    podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - pihole-02
              topologyKey: kubernetes.io/hostname
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbnd2M0ZjZU5oQ09nZ2lO
            QWRVc2ZFQndUQ2JJSFpmZWl1cXJYaEYxQ2hBCktlU0ptekJvNjAxNnZ2L3YzQTlV
            ZTJHRUZDeHNqUWJncHUwdFF1TmNLZm8KLS0tIGpFZXgyTTBOT291YUliaTQ4SUZH
            cytoUXpJL2owTnFncmFKWHpNbS9RUnMKyKO4x5qoIk5TpsTSZ66lToZhdgS0BG8V
            TqGDndIvjiEfsXr9UTjA9AnBJ9KURwiSdPgHi97a0jkCTkpJStaDJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eHYxak45bnkwV0dZSHVE
            dmJYbVZ6a1FWUUtCQjlUeGhBSDN4V0YzbUNNCnNEcUlkSlZFTGVENUZwQnZMN0RY
            M2QyQW84Rkg1TGxWelBxWFhWV2JUeEkKLS0tIG1tajJLaWdONVU3bFRqQ2MxZHJm
            T01GdytRZTdnVmd1RDk0UklLM29McTQKJm8PmJqLvkq2FzOAliSJQ88ajJ4OSpTo
            vlMQjQKWx/dlSwD3cItRn50eQQ1zHbRYAMnu41jZsGL2z0jEBd5pow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T14:55:19Z"
    mac: ENC[AES256_GCM,data:fSA3xvFGXxxOsi9r1X0BUzNhzgWBCza38zIHOQjqETRbjbv+yswMyA3KP7rdyI1BwIOQ18aeK9EiWE4Vy1D/CTvxTadVXvHe7KyXruWwtKKZQTKWHVSYXlUPlTLyL1N3KOdsw9Y84g2W+Otc7XO2pOoYhpeKn/k2MDJAFYTOeqw=,iv:e1wbSCtSMh/pTrKs2DmhUBWNwOs7MQRo78EXsrLDp4Q=,tag:eujXr8jIJ9eAbXk/hbFfdQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance)$
    version: 3.12.1
