revisionHistoryLimit: 2
serviceDns:
    mixedService: true
    annotations:
        lbipam.cilium.io/ips: 192.168.1.232
        lbipam.cilium.io/sharing-key: piholednsdhcp
    # type LoadBalancer with externalTrafficPolicy Local
    # requires 192.168.1.232 on the same node as the pod
    type: LoadBalancer
    #externalTrafficPolicy: Cluster
    #type: ClusterIP
serviceDhcp:
    annotations:
        lbipam.cilium.io/ips: 192.168.1.232
        lbipam.cilium.io/sharing-key: piholednsdhcp
    type: LoadBalancer
virtualHost: ENC[AES256_GCM,data:B3uq95y10GM7B5c23pqjyw9G/y8ycQkRMFmJ0w==,iv:IDmwEK9yV1H5h9deGcDANpSwZ7e4H1voIqzMVA1i8Xw=,tag:PPagKpHx8371d09rdFUKdw==,type:str]
ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
        - ENC[AES256_GCM,data:0IOqNj9ZhIGwsFhu7ef/bvkCv2RpeHXEh3g2Pg==,iv:DxMuiBOTd2Co+FxU9lIoWID2jl1NIsMeyddr3Lv1SLo=,tag:a5rgdgyY/coyq1YihxTGkw==,type:str]
    tls:
        - secretName: wildcard-cloudflare-production-02
          hosts:
            - ENC[AES256_GCM,data:sgIyG4MX6exF2f+C9TckpX7NlGaaYDiFVA7vHw==,iv:JZPAMtpXTuDaJAwimGozYZjuCNpwoF+Dk+BiEfHKnP0=,tag:vWCIaA57qA3iSxQOx8imgA==,type:str]
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web239, websecure239
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd, traefik-root-to-admin@kubernetescrd
resources:
    limits:
        cpu: 1000m
        memory: 1024Mi
    requests:
        cpu: 100m
        memory: 128Mi
extraEnvVars:
    TZ: Europe/Berlin
    #FTLCONF_LOCAL_IPV4: 192.168.1.232
    #FTLCONF_dns_dnssec: true
    FTLCONF_dns_bogusPriv: true
    FTLCONF_dns_domainNeeded: true
    FTLCONF_dhcp_start: 192.168.1.50
    FTLCONF_dhcp_end: 192.168.1.200
    FTLCONF_dhcp_router: 192.168.1.1
    FTLCONF_dhcp_leaseTime: 12d
    FTLCONF_dns_domain_name: neese-web.de
    FTLCONF_dhcp_rapidCommit: true
    FTLCONF_webserver_interface_boxed: false
    #FTLCONF_MOZILLA_CANARY: true
    #FTLCONF_BLOCK_ICLOUD_PR: true
DNS1: 127.0.0.1:5053
# Not required because secured via authelia oidc
admin:
    enabled: false
doh:
    enabled: true
    pullPolicy: IfNotPresent
    envVars:
        TUNNEL_DNS_UPSTREAM: ENC[AES256_GCM,data:6YRRAt1+Ei9SmdiMr36TOXNurv+uLzxMA7/jrkx/settcrTe,iv:TgZD6S2+putF8vHAlMc63KcFSlejE4AKeIbIzwOMej0=,tag:Eyh8Pm9PYgU6trUkDOwS+Q==,type:str]
dnsmasq:
    # Contains internal wildcard domains:
    # - address=/.example.com/192.168.1.45
    # - 'address=/.example.com/::'
    # - address=/.k8s.example.com/192.168.1.231
    # - 'address=/.k8s.example.com/::'
    customDnsEntries:
        - ENC[AES256_GCM,data:SlaA/VSpFejGPsJEinZRliIrwUZazKLGgGzfk23XrMQ4HEM=,iv:W6UIGusea4n8+t0YJRS5mZmitkxZkUKwRZlghs6qi/k=,tag:44YHF4HoPo3nE43IMQjHUQ==,type:str]
        - ENC[AES256_GCM,data:X2J0BCPaCt5XdL5Oy1cbcD19YklQwt3tqOhMVHY=,iv:ZH0ks5e52Hiaucl8PpuvNwkPZo06fVVT43BrRznacgc=,tag:jw9anUt+0RJCDiqw7p0bhw==,type:comment]
        - ENC[AES256_GCM,data:wQW9jd0Ob3AZmcxCjLUhxSJvK8c5qak7r1ocsU19CiwnSSRovtLaHw==,iv:gHRq0cqwls1xDOJQCNXxbbbjyyxYdwZOjyHAVTas7nY=,tag:kek1R3cwgUAGyfb+95+xhA==,type:str]
        - ENC[AES256_GCM,data:STGHUVajkBFmsYT/fHzpw+Y8PCKsmdDNQhttOPXw/cSO,iv:z453ZxegICdP/MdF7WlYnT/kscHa0esFfzvme+F2baI=,tag:Hj40w/eHktZhTJ7QEZ7Wpg==,type:comment]
        - ENC[AES256_GCM,data:l1xoO9fXODNdsMqXUQgbYu8mO1ra15o+PTQmXMNJZVDaP4CQRJBb4wnbiief,iv:hNSZNSohEopz45BjRfbJ6qZfZaWtocVFAUqA6sRbqFI=,tag:OcOQfqkJNyMgYqG5bF55Hg==,type:str]
        - ENC[AES256_GCM,data:9AOJyO/kGRqLb5oNZOvYKrEROMax9vj7hfGjgiFx0PbtuSivYU8=,iv:Rj+Z5iNVHLGgcgLrDG8HKmQlzFPGqi/nd7kiYicarFo=,tag:v5rNs7LgRirOUjvlVSy6Bw==,type:comment]
        - ENC[AES256_GCM,data:knAUK00RSwYHgHtyYT6tLba+eVau8heEnoj8w864RKTHm9v8wj2LjK2bL0dhAkY=,iv:cS+bPUv3wcBCl8qT4XZoF0jj7X6rIxREtaNyuqP/WSg=,tag:o6hM8gYNGP9yTgwECuTWgw==,type:str]
        - ENC[AES256_GCM,data:P9i225QzTCIE6hMEaT87ruZhAMXCRP4YABtXQ/Dm5rIU2q5eGaGSrkOMVnwmaNXjDLs0jzdz,iv:xG8dvbfUYHtHhhTuXBL+EGvQPV4N2A67WcN/PnyDdO4=,tag:LLBFHakQkHvrdaOiEjS6ow==,type:str]
        - ENC[AES256_GCM,data:ff2TQ63Y1rja/UFIZ1oxrSrffA5yh8W8HyFfUSinZQMAjVvCqZTA,iv:lxMRg1FURXR1iRIxPMOJirl1bZ3sP7V83O75doWzyH4=,tag:ldiGNp/6ONiz1A4XD/HyJA==,type:str]
        - ENC[AES256_GCM,data:n/42oakikNCD4/NqMv1huzVMHYB5kZrv4R2mkOOxZYNXgvJleUOLD/pdtHpwIQ==,iv:69L0TdMimPD19Wfhkq0OxLksOdOhOMiR0+HuvsTX9nE=,tag:ae2EsmRjsaImOMW95g+vsQ==,type:str]
        - ENC[AES256_GCM,data:EI1hKK2LImSMKvSbzfY1MiVuWIYwd1Bqmg1wt1M9HyxgGtom4Q==,iv:B6za5GU2A3fTAj1ziONBOi6UUh36Te6eIz9slEYbN3E=,tag:V0OSJMTxe8pC6vG2+VNA9A==,type:str]
        - ENC[AES256_GCM,data:bHygM6k3HOvJazdRJkXBWzbIeWlGvL3yr1PqM+OsJ50cQzTT9AICdRc/F5M=,iv:h2F7gaadRBdQpM6ELpKfx38mZigFq5BKIb2X2Tgr0E0=,tag:aiV3ZuRIIguwUcFfVlFdjg==,type:str]
        - ENC[AES256_GCM,data:ndkucwIaSJtq0dbvLLe40Zu38edp0RqzejDjm8PH6LpSYEm27GrZ90m/zcGx+A==,iv:m1iO2VlF7v26gT6RKs2GwG4PdztfCJ+6L2V0rf5DPzk=,tag:OzSyxf0jwlH3VZ6R1EV9qw==,type:str]
        - ENC[AES256_GCM,data:b5/zJAUzaPFLAQP+StHHDA97rGsLjKVy7iYUIQiem4mGE6lFHLuvmcPFMcouPrqopQ/4HPM=,iv:Bf72Udd2roFQeeaVbE9AS7a6TlfpYKwQz0Haxji+RJE=,tag:tE7hepsgVUveHk//xTTWpA==,type:str]
        - ENC[AES256_GCM,data:eZ/g/ohmV3lTRfyxaG0EetH2lenNPvOin74GMD+MyKQODKVI2SMyxtnr1/ImeUck,iv:Bg7RYa//cnDHONrtzhwiT24T39+suDabT9Za0zLnNLo=,tag:fVLVSBicm3nUiShbbvFLbw==,type:str]
        - ENC[AES256_GCM,data:yFTNyXIPr6G1iLa83/QqQs4vu05CfLrlr9LP5hVK+D1RXxl9dzl7pQY6G969sRTBNVzUyKJLvg==,iv:zfogZfCwEfn+KzTegLFnhwlB2qVLxrvhBNpiAykjo1w=,tag:n6l9ObgRR6ej9qt4AcLnoA==,type:str]
    customSettings:
        - dhcp-option=252,"\n"
        - dhcp-option=vendor:MSFT,2,1i
        # DNS
        #- dhcp-option=6,192.168.1.232,192.168.1.1
        - dhcp-option=6,192.168.1.232
        # NTP
        - dhcp-option=42,192.168.1.1
        - dhcp-range=::,ra-names
        - server=/geekbundle.org/192.168.1.1
        - ptr-record=1.1.168.192.in-addr.arpa.,"despair"
        # TFTP Boot
        - dhcp-match=set:ipxe,175
        - dhcp-boot=tag:!ipxe,ipxe.pxe,dns01,192.168.1.45
        - dhcp-match=set:efi-x86_64,option:client-arch,7
        - dhcp-boot=tag:efi-x86_64,ipxe.efi,dns01,192.168.1.45
        - dhcp-boot=http://192.168.1.45:8043/boot.ipxe
        # DHCP Reservation with different dns server
        - dhcp-option=net:customdns,6,9.9.9.9,1.1.1.1
        - dhcp-host=net:customdns,EC:79:49:51:64:16,192.168.1.187,ipl06002-lan
        - dhcp-host=net:customdns,F4:4E:E3:2C:C2:B6,192.168.1.56,ipl06002-wlan
        # DHCP Reservation with unrestricted youtube dns server
        - dhcp-option=net:youtubedns,6,192.168.1.238
        - dhcp-host=net:youtubedns,AC:3E:B1:A6:AF:D6,Pixel-7-Pro
        - dhcp-host=net:youtubedns,E0:80:6B:37:56:83,Redmi-Note-11
        - dhcp-host=net:youtubedns,74:58:F3:E7:3A:04,Fire-Cube-lan
        - dhcp-host=net:youtubedns,48:43:DD:6E:CC:2D,Fire-Cube-wlan
        - dhcp-host=net:youtubedns,F0:27:2D:D7:41:97,Fire-Guest
        - dhcp-host=net:youtubedns,00:e0:4c:7b:c2:98,Sanctuary
        - dhcp-host=net:youtubedns,8c:8c:aa:32:ce:7a,IONB000201752-LAN
        - dhcp-host=net:youtubedns,4e:80:5d:ae:a9:dd,IONB000201752-WLAN
        # HTTP Boot
        #- dhcp-match=set:efi-x86_64_http,option:vendor-class-identifier,0,10
        #- dhcp-boot=tag:efi-x86_64_http,"http://192.168.1.45:8043/ipxe.efi"
        #- dhcp-boot=tag:!ipxe,"http://192.168.1.45:8043/ipxe.pxe"
    #customCnameEntries:
    #- cname=www.youtube.com,restrict.youtube.com
    #- cname=m.youtube.com,restrict.youtube.com
    #- cname=youtubei.googleapis.com,restrict.youtube.com
    #- cname=youtube.googleapis.com,restrict.youtube.com
    #- cname=www.youtube-nocookie.com,restrict.youtube.com
# Not required. We're running a dhcp relay via host network.
#hostNetwork: "true"
capabilities:
    add:
        - NET_ADMIN
        - CAP_SYS_TIME
        - CAP_SYS_NICE
persistentVolumeClaim:
    enabled: true
    existingClaim: pihole
    #storageClass: longhorn
    #size: "10737418240"
podDnsConfig:
    enabled: true
    policy: None
    nameservers:
        - 1.1.1.1
        - 127.0.0.1
#affinity:
#  nodeAffinity:
#    requiredDuringSchedulingIgnoredDuringExecution:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - node03
probes:
    liveness:
        initialDelaySeconds: 30
    readiness:
        initialDelaySeconds: 30
affinity:
    podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - pihole-02
              topologyKey: kubernetes.io/hostname
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZ2c1RVl5UjFlSlh2bW1J
            c1pEdm1rWTArK20rTnlvN2wwTC9qR3poUzNzCmltUU56eDNSWnpmQWhSMkRwempV
            UUFwRFFhSmtMUE43SXpxS0dWNm1FMmMKLS0tIFdJVXZad1NlVGNaSTIwTWp5UzdL
            OGFwTmpXTWZPYTdYbHJzajZrM09kY3MKq9E38XMl/8NY2SFBJYl5nilardA8YSYl
            ZMjw5NPot+syvBsI2UTP20bImUNztmhOFsbEXZmqNV21ootatsWy4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNV3BwaHFiSW5GZlEwQmEz
            bHZOV0ZBdmNXM1ZWWUlvREZ1OFZtSmpnK1hRCmF0RzVUcFpFOXhKLzIwbmFFUDky
            NU90MVpYd1A4M2gvMlNDVzdFTFNDNEUKLS0tIDFWWEs5SmJ1bit1NjNINHdTZVpQ
            YjVTTVIrU09xY2VaZTJyd1FOZTcvV0EKnOdwey6BoEjI1tNLPO6IwEx5877+tubF
            DokRtGOCGUYJtNfdibpL8ZMKXJ6tfLB3KO/tR2MKXTckd5foP35uhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T08:05:49Z"
    mac: ENC[AES256_GCM,data:ShTkQAzJtYqmq9MzSEzBPv/xMH70hAR/b20zvAxO8ZureBaqX8gXJZIECCXQLTysmWuYtAlijwNZCq1MkOsU7jb8/xY0f4E+o5wc5mkMDfwc0grYSKUXp+zlFpLtaPFOefOkQF8wnFbz8bg6zn7KFYSAyrhKY7SaEOHlVF5dJUA=,iv:FypmbDbKPikhdlnzR3MyFu3+p50QHACQlHuN/QMNAK0=,tag:5udR3J+L8lI/b/o5i1bXGw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY)$
    version: 3.12.2
