apiVersion: v1
kind: Service
metadata:
  name: nut-upsd
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    app.kubernetes.io/name: nut-upsd
spec:
  type: ClusterIP
  ports:
    - port: 3493
      targetPort: 3493
      protocol: TCP
      name: nut
  selector:
    app.kubernetes.io/name: nut-upsd
