apiVersion: v1
kind: Secret
metadata:
    name: nut-upsd-credentials
    namespace: monitoring
    annotations:
        argocd.argoproj.io/sync-wave: "29"
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:7czCCIB3lNtqa8rLAyAUeE2DVFY=,iv:XLjQAxUjH/KbFc6nTxwIGjIFwuySXYOG9AK4ychmIX8=,tag:bztQWgmF4f65+bKrNZgK+Q==,type:str]
    api-password: ENC[AES256_GCM,data:B5NR8PSlc3XyrYqPOaA26zzuZyw=,iv:xxkV0R7fkKWgevcoy/GzXLS5+kT/S+oe9qeUVRF53DE=,tag:kW34BtylpWkwNm/21zwDbA==,type:str]
    api-user: ENC[AES256_GCM,data:4vzgwPe8iHickSix1aWe5jicNs0=,iv:2jGYsknqrC0TcVnHIwZba2h1V1MWQ7Rx7jyP66rJbCg=,tag:tltn2uV5AUwdM1sgRovrNA==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWFEzaFd0VmJnMXFXbCtz
            Ky8vVndXQ2VQNmt6UXc5eTdmOEZSLzJSb1I4Ci8rT0dnMTRPOENWSjI2dWtyV2E0
            bEh3L0EwTmcyTk44bVlGSy8xNTlTODgKLS0tIEtUdnVyNmR5TnVYL2ExMDNma3BZ
            YkJST01oMWYrMjBXYTc5eG5GU1NHVHcK7sxd/AqImY48g/1Um6J4pM2fcu7C1m+Z
            opr+/WbAnxwwT6Kj6fiL9oh0ZbqrQExvRf53Y17aBPtPKauTtHGaDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eEFDVGxva3RPeGFvSTBM
            aUs0VWNQbEh1NHlydFFTSU1mSXdhVUpuUjBFCjRLRmFQbU5MdzgvNWlpZ1k4SGor
            OTlzR29UMUc2Q0xnTnFEa1FqVU41ZlkKLS0tIFYwWm43TE0zSnNxS0xBb1NWczE1
            a251YXVWWXVJMU5KYTJqQzBaSnIydDgKN1TDbzdMa3svPRIxexoIrjVnm833Umsl
            gNQVin87YqWJjNzaSwm+fKdg8W8uejUE+c9iyTjY/lx4rlVAttmmpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T08:08:11Z"
    mac: ENC[AES256_GCM,data:Sxwnc5bAzZpGiXXe6B+uqr5rg0BmgjYMRm1YTaUsx6HHnEXNyl5u3ypPHk2VYsWWAAm+fcxqfL3oFlwuyIvXgFMOp5LjfoxBuUquODLdxkdhzoES/eqnbie9Gm9ZENl4WXlzNA7Pq0UGFizFQSgTa+pMZQbnoRnmNHHl9lnDZGc=,iv:C98DlDXgr9eBVFVBLCIK9TJJz/56vGDUS/101K5vaXg=,tag:Oefd8xGFnF+atDBTcgtXFA==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match)$
    version: 3.11.0
