apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-unifi
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:sI10j5axxq6YtbRlCdY8M7Ey58ZnU039,iv:me18h60xLjtprd0BjTwey1aqEL+GXouc0qKGh4yJcjY=,tag:CzyEmSxiCkAfMwfpo+VDzw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:QE/s+IrzJXDea/pOPOn8Et3uCKwdE+D/CPk7wIrf4zbUHs8T37UwLKJxM28fcNI47khZTJPLg8IpB8BoyQjAxaVC/gQX1zcq7awv1vyp4J/mD3EfgbcHfHG9eI2gPw==,iv:6x0F8HKeBPVaAbkpDpHQvTrMokeYUpwcoxPZZ2rlyD0=,tag:trHKdsxI+HTk84vdqfeH5g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:lGl9Z0U4q3bYQp2Qp8F8NGCNxlcQDLw3g84/+j19rOV4gX5aXZ8mUgAfrtCdTAQEqvSh6x3gHetl7gSbXOTkDw==,iv:mryaQAfBFXRJHPntwz0qs1Ixut4MvQfw/AeSuXB6Q7Q=,tag:0fvd8ENsRgVCur/LvTojSg==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:/k3r/JI=,iv:kms98Ht32pEJT+eWhtSiaLUR2OR00G5uR5oGN6ajcrU=,tag:5cVKbL002k7ieZOvXL2CnA==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:AmjoR7BLjNqEbTprpMI7bd7c4cUunpquh+8fZuxhHRPwSX0gYSfWvVkj9EJNs/rdJY0+oOpjEousJ1exLlM=,iv:AwqbDJZKYPDrBVSGoyNc0enSnQEYS5Tu91pZOkI7VDo=,tag:h/WAPOIeDo0XauGB/Sghuw==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:9y9IKzs=,iv:ZxAv3dWwvnJzOJGb2J0gCL1g+fARnHw6BI3u7yBsJhc=,tag:NsRVsNG4iGYEV8jzLxiu7g==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:Z/44Jg==,iv:5lSnh+Rpoz79rIeh04K81gYh05P/0L2HagA/E43pX9s=,tag:fPOezLtCP19u7nAgXvCowQ==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:ICikW1lTw3+kwZSYhkuOzxKz9p3vJLqPMrufzbdwRqfr3SbrFPBrfI91fFhSqljkjQ4e5Iw0kaolhwmBaE6RiFE6Yfy1Bbyw2iFv,iv:ShOwoAsAM0EWk9Z3K8E7+8tee8q3BCfnEPA1St+hupo=,tag:6EL4jS2JCuS+fWKyuAxxqQ==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:o0PEVzvcKJGZlCzE/SYLIPqG0DC55pqo1LsW,iv:yCebzJ0Y6e4U80SodGxl60u+/RpLbridZmirLQvgowQ=,tag:e7ryJpm5B0sSUPHb4nZ2pQ==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:FnJiSaekmd4E8VT01ea/hg4o,iv:FxMTcZgCk4Hp8Hm/ybjtveHRXjwqQnRgTReERrZAHnI=,tag:Ln6RCbyQHgbkv8JklVjRug==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:OI9f0g==,iv:DUVAAzezm5PpKknmVGBX/NXfjabpSkC3fZjpz7EPa3I=,tag:8CTuLIsDTCpgdB/HDzBI0Q==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:vIi0PWN8thsKeafMGqMmRi3CjYTmnS3qN7I3hap2N4O2ubxyXcBePktbpoDyxOWshRC3IqcWCuWZB1SpFUus,iv:e5tCLq5VOLXZjzySTiERpRhA8DKdo4Xuoutc7qgmL4U=,tag:Yfgxs1PRThAj90Vbh8gKxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSWxoY3dGSU50cGpKd1Rq
            Q09RK3pCOXdBcGFramZPdXBCOXNFTUpWclFvClhQRHI2N3hMUC95eWlCbG0zODEw
            YkxHSCtBK3ByRWxqTml6dDJsK2tlV0EKLS0tIDdvRDNlZ1daaWZxYWtaL1BkbEJK
            Nms5WWFEM2Vjcm5lMFZ1SHI0ajV5LzAK1rmvjga6a8Nm+yjNBkgjDaNVFlz2CSEJ
            H30SMPu5hFUJBkWdT4HkfyUlC0mIn83jNFjOrqxP0PHX+cYzzWhb8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M0R5MnZpTzk3dGswb2t3
            V3NpK2lDTGtUcHRhVVdVNTlPc1drVlZrYlZvCjhYakJSWHYydHY1Z285ODk0TUVU
            SWkzdC9zNXV6bGFCdkU2ZDN1NWg3QWMKLS0tIGJka3FJTERQOE5LMnNhUFVOVHV4
            cjArZGo4anhJaHhpZDdmdU9NQjI2N1UKq6lQ+cy/qEOw1Hz2G4bU9qLXlsE5pbq6
            wghMekTO6V6l3YIfSEe2XfjpFFEyydYloK7OryixlPKPWv+pXOgSYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-07-24T06:36:34Z"
    mac: ENC[AES256_GCM,data:kg/p4JNuX6l6N2E2vXu4VUQ2EUXFB+gQISVeHP623zNNJXdvVg+iN/52ufUNyTfKsoHdSu6kygvVE7ClSUDkag8fxm5ADD7m7fsKU8Q/nGnc83ojvnshhaftpChRZ4+ysbhN8YnZGAeOqSFSDQ+A6cwn+SKTp8QN4L1cnlGeXDg=,iv:awKFJP1kjVZyXHiXe7OH/QypZVF9NoPzsrfVq98fhoc=,tag:dI43GeGUkChII/HY5E3DRw==,type:str]
    version: 3.13.2
