revisionHistoryLimit: 2
serviceDns:
    mixedService: true
    annotations:
        lbipam.cilium.io/ips: 192.168.1.234
    # type LoadBalancer with externalTrafficPolicy Local
    # requires 192.168.1.232 on the same node as the pod
    type: LoadBalancer
    #externalTrafficPolicy: Cluster
    #type: ClusterIP
serviceDhcp:
    enabled: false
virtualHost: ENC[AES256_GCM,data:fUv9S/HM6tMbWIa0VhQM0KgoppJmEP+3Qp4QBE+Q,iv:gjOD9N5L2PJHEQqJVHYkEBG2B+YEAW/+zQLmrbN0kr4=,tag:nsSTFFzuy3xcKu2JmMSetA==,type:str]
ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
        - ENC[AES256_GCM,data:4vqn4eie2IxWK0OVqTAnUNyQXj723IbCTTuIxrM2,iv:6KQF2oxsFray2n8/9vk/+HvZ3H1WI9tXmkvOhUll0ZQ=,tag:NTBuQ+8OvjFdLxAdPd9x/A==,type:str]
    tls:
        - secretName: wildcard-cloudflare-production-02
          hosts:
            - ENC[AES256_GCM,data:M7q0EIvcs5WM3HYrfMEgC+vnELZkIvjPo4QqdmHZ,iv:FMJ4BV27UOlPhdklONq67dFmmg0QdphL8gWbnIOqAR4=,tag:1Y/ip8t3FOzhIdiL7B8HVg==,type:str]
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web239, websecure239
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd, traefik-root-to-admin@kubernetescrd
resources:
    limits:
        cpu: 1000m
        memory: 768Mi
    requests:
        cpu: 100m
        memory: 128Mi
extraEnvVars:
    TZ: Europe/Berlin
    FTLCONF_dns_bogusPriv: true
    FTLCONF_dns_domainNeeded: true
    FTLCONF_dns_domain_name: neese-web.de
    FTLCONF_webserver_interface_boxed: false
DNS1: 127.0.0.1:5053
DNS2: ""
# Not required because secured via authelia oidc
admin:
    enabled: false
doh:
    enabled: true
    envVars:
        TUNNEL_DNS_UPSTREAM: ENC[AES256_GCM,data:V3BemN+kMapHW73nsLwEOyZfWUP/lwfpTnKAbCch7VMjFbE/a4c=,iv:6oakGGGJLBEjTgV6C6cAogo4N1JMT6ox4q88dnbFOVo=,tag:TAkj7DmxUe2SIxvJ6fHqUw==,type:str]
podDnsConfig:
    enabled: true
    policy: None
    nameservers:
        - 1.1.1.1
        - 127.0.0.1
capabilities:
    add:
        - NET_ADMIN
        - CAP_SYS_TIME
        - CAP_SYS_NICE
persistentVolumeClaim:
    enabled: true
    existingClaim: pihole-02
dnsmasq:
    customDnsEntries:
        - ENC[AES256_GCM,data:P5OfJLzLm0WOS2msApS+pCFq3AwOgZ5I4PcvOSXnLVvZyfw=,iv:S/x8R+UudKMBYJ6SY9sgDuyYup5R8fUQnElx0IdjZhA=,tag:oBu22aUKO0qIzYkVLggNtg==,type:str]
        - ENC[AES256_GCM,data:c6DMWnhUdpMdwKUM9n16c77U7mM2Xx8yvg==,iv:2kKOMdfsA4T2MTnnRJANzYf8GpNYIKqM32CJvA9Wcas=,tag:Cf6S434NmETN1BgIM2BLUg==,type:str]
        - ENC[AES256_GCM,data:5HcgiQDDA8+Gr4Rv8r9nmb3Gt3MpCfPc2mTsSrjOsDScznH3Cl6RzQ==,iv:x/d3rbTk3G1o/TXC0g8xOZFz4d/U6Qgk9gVw6x4ntIg=,tag:2fibZkHiziCAq1BtdODpLQ==,type:str]
        - ENC[AES256_GCM,data:3wzaDGwieWiyQADHC3ALC6ZEdOWB+frcuEzW8tE=,iv:YF8P3I7DfA8PJxaVU2E/9oPvKhrxqm2645r/Y5KXK6c=,tag:43voRXpeg3ToSHntxJ8YMw==,type:str]
        - ENC[AES256_GCM,data:ksDTOfZVtoQj1hiJikLjE9et6ChQz5zo0GH/Uc9xDyvDU8WqNqUYO+lIivAN,iv:EiFToTJKuUy8DkX+VsTZwsF68lSoIr9xQjkvbbUlLlQ=,tag:f6sj+cDL45GRbBGlI3vTzg==,type:str]
        - ENC[AES256_GCM,data:iuAFSDbfiwJdFkaR6DS7LdFSWW5L7BCnTQ7Y+h5bRAckLg==,iv:GwfHGWjKHknyK5rI+ESeCLjbVA4R21ZC0StT98lt4DE=,tag:tQVot3UH+VG3B/eBBDgVWw==,type:str]
        - ENC[AES256_GCM,data:zPjUEVme4Y/bEdk09O46SzSKsLrokLYcQoJcvCDNJnE3KZEbDlAKsPnT+lfFr4VIVg==,iv:9GjxyAXeh5Hyf4qxzWW/rJ26omrREZtoekRWU//s7ak=,tag:C91QF6jiG9M23mo4Vev9+Q==,type:comment]
        - ENC[AES256_GCM,data:CSCahg4kniHMbqM1T/8Go0h43mjGkGIJAfSifLbPUMepY00kQdUYA/KMhT2FODdnj1I5bWwSahw=,iv:/tuXM3ac5HyuHaGc93sum5qROIzgnGTPbJ/KaeTLTN0=,tag:PnIgUxdqxgNB4RkaOanyiA==,type:comment]
        - ENC[AES256_GCM,data:1vbCZpfbWcN5YgpSf00kXRb5gUEX2iTnPNBJ/Cv6E5dkgM85YnJB424=,iv:4qwMMbbzHfcox8Yx6+thD7sfuWU53KvNIRZ5mdFuUdM=,tag:PcsaHteM8xVlL52udPKFXg==,type:comment]
        - ENC[AES256_GCM,data:8Zd9ce4746s/0qWWYuYIP6KFOfMYH2QLNPND/kf5nOVDHt4DpqadDS2O5eQLjnUk,iv:vlSamkrg2Fwoj3piUxd841WL0DhGYa3TrG9uAb733M4=,tag:Fr0z9ZR4AuyNEo7mQQOR+w==,type:comment]
        - ENC[AES256_GCM,data:tYrYdKkkMAZRpGhyQ9upN3rbqcv2pa5K6KvhUqTy3m/YlnPvLG6a,iv:6cDqfckSI6GiApQM5ukJJDrrlCrvRPL5z9mZsE0D/b0=,tag:fkhOw2LKXYB/+GMmT6NTDw==,type:comment]
        - ENC[AES256_GCM,data:weMpXTteUDra6ejMxWjBr08OF3G0nE2Z1opKQNz+LNJGVyPm5h90U+BGFX8I7w==,iv:q79ZLALNdmOsxOTKMGmwmSpSFjcxzlDIj2NeDRjgxQs=,tag:1lHksNQCRiGEyiqlvi5UXw==,type:comment]
        - ENC[AES256_GCM,data:vpFy/g1R9yf1KpOjz+gOo0kEp8bQBVjz3YQiAnqovADic5zZIdt+SH1tdTMMbmVU,iv:JebWLpBgNmXz2cbO+eNQ99FKyYzXcXnVjgA1A4LQbvE=,tag:KGXPb3Aytb3xBtXM41zmMw==,type:comment]
        - ENC[AES256_GCM,data:hL5rbFi5iHHibUuW9doiu1V6OHAGSo6QHfuNiviDeV+HW2xTzpz0GhBamgXfQIiTsK61aTV4Qw==,iv:Qs5hV/5B30LF5yzIutJpRp5DMhwlEEvtU7wrdZ3mvfg=,tag:3r9UZj3QRHbjNLS2iKhG1A==,type:comment]
        - ENC[AES256_GCM,data:PlRdhME+4yQ0EGakY9WALyi9K+jV6nU3gOXdSotzoe6vJvAMuCetODNF+ZM+eimHKe4=,iv:kd5I9504W2mhz1AbPG/Rm7vMJmntOjVMOEMVlDjDj4I=,tag:otDuKJ05eCJ5HiDmV3jIIw==,type:comment]
        - ENC[AES256_GCM,data:V1ZIusLnmnKmmf7sTPorXXdabLWxz5iz6tOaCvEbaPe5nz0PIf9qSq10te+bRSNx75ioCpWGUNov,iv:Mipqfa3lDekYBsK5kz+WWgtzfWVjuJHyI884r8W7teI=,tag:niuVO07MCxSYU//ZpzaRMg==,type:comment]
    customSettings:
        - dhcp-option=252,"\n"
        - dhcp-option=vendor:MSFT,2,1i
        # DNS
        #- dhcp-option=6,192.168.1.232,192.168.1.1
        - dhcp-option=6,192.168.1.232
        # NTP
        - dhcp-option=42,192.168.1.1
        - dhcp-range=::,ra-names
        - server=/geekbundle.org/192.168.1.1
        - ptr-record=1.1.168.192.in-addr.arpa.,"despair"
        # TFTP Boot
        - dhcp-match=set:ipxe,175
        - dhcp-boot=tag:!ipxe,ipxe.pxe,dns01,192.168.1.45
        - dhcp-match=set:efi-x86_64,option:client-arch,7
        - dhcp-boot=tag:efi-x86_64,ipxe.efi,dns01,192.168.1.45
        - dhcp-boot=http://192.168.1.45:8043/boot.ipxe
        # DHCP Reservation with different dns server
        - dhcp-option=net:customdns,6,9.9.9.9,1.1.1.1
        - dhcp-host=net:customdns,EC:79:49:51:64:16,192.168.1.187,ipl06002-lan
        - dhcp-host=net:customdns,F4:4E:E3:2C:C2:B6,192.168.1.56,ipl06002-wlan
        # DHCP Reservation with unrestricted youtube dns server
        - dhcp-option=net:youtubedns,6,192.168.1.234
        - dhcp-host=net:youtubedns,AC:3E:B1:A6:AF:D6,Pixel-7-Pro
        - dhcp-host=net:youtubedns,E0:80:6B:37:56:83,Redmi-Note-11
        - dhcp-host=net:youtubedns,74:58:F3:E7:3A:04,Fire-Cube-lan
        - dhcp-host=net:youtubedns,48:43:DD:6E:CC:2D,Fire-Cube-wlan
        - dhcp-host=net:youtubedns,F0:27:2D:D7:41:97,Fire-Guest
        - dhcp-host=net:youtubedns,00:e0:4c:7b:c2:98,Sanctuary
        - dhcp-host=net:youtubedns,8c:8c:aa:32:ce:7a,IONB000201752-LAN
        - dhcp-host=net:youtubedns,4e:80:5d:ae:a9:dd,IONB000201752-WLAN
affinity:
    podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - pihole
              topologyKey: kubernetes.io/hostname
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERU15RW84b2ZZbXgyRVkx
            Y0JDWEVQU25Ed2NYUWNuejIvSGVkNS9ES0ZNCkQwaUFWSzlCbFlxaWpLSmlPU3pR
            cW5sK0RCaFo5a1BjaE5iWi9BNmE3YTQKLS0tIDdVQTd2SnF2ZlNLeDJqTHZ6ekly
            OUp3Vkljd1FCWjRBd01kM1JyTzZ3UHcKmpkiSxt1l8apcATUGhzo1M3ugTFn53a9
            Gc4BgbM/JR+VE+OL7anneKjpCiZ9ht5dSv9xkbdWInGoApgz9dxr0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSzZ1ZEFkYlVITGNwNkp1
            aklxRGdZRzJNc3oxWjl5VXBqSGt1dnJJT0hjCkVTT0ovYUN5c0dtR3NHbjJGMVNk
            ZEQvNithTDllSk5rbkZ2djhFbnFpSE0KLS0tIEN3ZXQ5bmpoRGh3M25uT1RMU2dx
            cU45TStjNW5NcjBva1prY0VCbHhYc0kK03o2/Rk8qeBufg498Tny1pzoxgUxmBmL
            C5jKLsr5z1UCWEnV1smW0ByYoMJ7Go5CmwVFFB3OjrLauMZX8NVUzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T08:05:49Z"
    mac: ENC[AES256_GCM,data:KCzPbINDykm8oVq+H6w+Hob1SVesRiwlqRalA2aN7NsYAs88KopanA70FWAvWNieb4GeroOimZgBbRo35KR61yMi8fzu2vL7agH9m/d97janpzXBv2LBqHu34bKHjyvjhJm5ZCbCyR1yIG03MoBknn6b500N8dm7NUlkufNj/9w=,iv:dZoQaBxAeTu7kfBMkCOhHe9Z+xPU7ybY/3n6DP4Jte0=,tag:JUD9snjD0OzzftMWtgDofQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY)$
    version: 3.12.2
