apiVersion: v1
kind: Secret
metadata:
    name: claude-alert-checkmk-analyzer-env
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    ANTHROPIC_AUTH_TOKEN: ENC[AES256_GCM,data:mw4MfW2+Qa0S+oBR48wD+EsaIMsFDXuMYtClRaGMHn+haYil2/VoPn9T1Xivtev9Yz+AwbTrrjsQ86BcYeFAKSTAlxvRVGBr9A==,iv:wbmFktH3nYBHXpw6KiH8Jsb0SfE8IEJ9WMf70BbI5Jo=,tag:uT0Vkqduj+BqZM0wmT609w==,type:str]
    ANTHROPIC_BASE_URL: ENC[AES256_GCM,data:sBg6VlQHlTBBg7ys+t8U50JUu+H4TK+uIg==,iv:8vakv2QNcJsSmC++gFnD7vodk+B2sK0b2gDAt7iKIdA=,tag:TR1G7N2p3OV3YoN5qEIRHw==,type:str]
    CLAUDE_MODEL: ENC[AES256_GCM,data:mrd9MaNykR1AnAlqxvXKdArWgCk50gIUz3pq,iv:Lpi04oA/mg4IXfE93/MpY4qGmb1y2PLJkwZEDcBRLK0=,tag:VU6IbfFiOs7bH27hVFJNMA==,type:str]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:MgxKMiAyoOZobxJpxTXjegDmY72vNGYZEzVBYHHVl2M=,iv:/tTRHn0pEmLvRN4abC3iTOcgYZnyoJEHe+j7kLCXIxg=,tag:6UgyWmKgB9IsqzbG0U3yZQ==,type:str]
    CHECKMK_API_USER: ENC[AES256_GCM,data:B32wezqyF0Ht+A==,iv:7iB6OG3y594vexQH+Ou9+S5RTRsfocJEweIPkByIAGw=,tag:cwDfyatg+hrOWurYz5wv+w==,type:str]
    CHECKMK_API_SECRET: ENC[AES256_GCM,data:KsZf1MexhIicH+AVQTs9l8WywRHkaxhzVB6WTKjqiIM=,iv:JZGzxxk7XAuXz6xT6XNURnJOzvraWBBLBmALe7k2pl8=,tag:mYySNBqsSNJ1Ra9qrPFTig==,type:str]
    NTFY_PUBLISH_URL: ENC[AES256_GCM,data:ewUhqwnNpsEXqcacfaDfMHm3R5zaE0p6BlRb,iv:mYk3ll+phGPznXGYxGvQPHQIafkoTCwvusvLrNqf5dM=,tag:oFmU8oknOUF3uGYB4V/Rig==,type:str]
    NTFY_PUBLISH_TOPIC: ENC[AES256_GCM,data:CFlVr6P2AtWBVXf8TfFEOj467A==,iv:DE5nYHoMuMoD+vL4i3sAsASUEFs/+j2HUrHSRa3iKaM=,tag:0eBwwgZTmINEu9XH/NogHw==,type:str]
    NTFY_PUBLISH_TOKEN: ENC[AES256_GCM,data:hjVl9uFA6P6ehesgTvuRZDGorFRaWjYor9HOMfId9nQ=,iv:sBzJlwqex7UVKYDnW5UHItycqrMr+VHQAeJbSDWTqsA=,tag:86QmNcZ/zSSWl35XirYvQw==,type:str]
    PORT: ENC[AES256_GCM,data:+2kMLA==,iv:JlMFNY6a/dG9Pgt5vuosi5/ZU/iCHBBo1iafu6ybjnA=,tag:BtLirzoEdkG9bV+s+Z5RMA==,type:str]
    CHECKMK_API_URL: ENC[AES256_GCM,data:yVLpQhTLAgcjBHF1vWCZjFnIdmNye9NDpCiVuQbwCqGkbb4dYrWhsPTbbYsjLkcolyIafafTT47kycuA,iv:esxDkHYLFFH9YPXOqulO9/dAu3FK172C1XDeLGM9gI0=,tag:uyCYNxq0QjFkx4o4Y6pksA==,type:str]
    SSH_USER: ENC[AES256_GCM,data:2v1FeeQ02g==,iv:AffgxD8yIBn444hHDMNrykrSS4c/F4xzwn9uwEX1pEc=,tag:dQBnRQl9+SuKflRqbZXbCg==,type:str]
    SSH_KEY_PATH: ENC[AES256_GCM,data:Da+8K6YmbsrzixF9qt8x,iv:VLIex0D1R1ZTeJBwELe8HSlC2940iZeoQd7y/4OmkH4=,tag:/G5pMjywZwRhB9vm/WdN/Q==,type:str]
    SSH_KNOWN_HOSTS_PATH: ENC[AES256_GCM,data:Is6aPGfg8l5W6QaHYqUQuw==,iv:VNGi6kqeqFZ09VLMpOVTpdmxfwrmbKU77hcyw1RNkj0=,tag:MhATHqlcGvYc2zicwD4cqg==,type:str]
    COOLDOWN_SECONDS: ENC[AES256_GCM,data:Rk/qmwA=,iv:2qTBFtGR1n5JW2I89t63f0jQDJDhrCMjkE6Ar60TC5U=,tag:BUDFzlfqLwLhTbtiSEtE9Q==,type:str]
    GROUP_COOLDOWN_SECONDS: ENC[AES256_GCM,data:JCo=,iv:na+NqN/V49MiRV/iUNuu9GCHCtUmF2cArHQikI1bBL0=,tag:bKT2aNR/8swbe/JP7PqsGw==,type:str]
    STORM_MODE_THRESHOLD: ENC[AES256_GCM,data:Rus=,iv:5lkpFSQkCRPoVmANJ40y+kc3jq0MpCu8hP5da2SPtuw=,tag:FUVXFNDDh9I/1FeW0rjXaw==,type:str]
    STORM_MODE_NOTIFY_INTERVAL: ENC[AES256_GCM,data:wcaG,iv:Cqf2jZZsGezBkjhyHzVoqjE4i21wtZpIA1wajcy0s9I=,tag:vwXVbF4eF58iNi0JjJxDxQ==,type:str]
    CIRCUIT_BREAKER_THRESHOLD: ENC[AES256_GCM,data:1w==,iv:Wz6kMiI42zbVncagxhlAvzmVeu0Pkjef+n1aYlTfKT4=,tag:7uyW+vJ2Lo15aMON+YSKig==,type:str]
    CIRCUIT_BREAKER_OPEN_SECONDS: ENC[AES256_GCM,data:SXg=,iv:CrEjTNhVo8f3bElyBy96vpE3waDdWOBjqDVxP2gsa8Q=,tag:6KiXCF2iY3JjL4cdFFe0VQ==,type:str]
    MAX_AGENT_ROUNDS_INFO: ENC[AES256_GCM,data:Lg==,iv:4HF8xOqOX9w1fKaFsGORWM4W0tXpH/iTeDKLldB8/LI=,tag:EpKkCxqsI+KQPTJNpwrHJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTCtQbUtoQVc3aVU1UDFx
            ZmdsbVd3MHdUTGVtaUo5aWtyRWFaSUJIU1hjCjVaL2hjcXZhbFBIaXBBWWtsUTkv
            MGtEQk1UekI0c2UvcnBaYjZRRUwreFUKLS0tIG1hUm9WTS95UTFtL3RDeThZM0x1
            NDlyY0d4SmJSL1c1eWFnVUo5N2hMMTQKzAwdyqL+qKETQ55l8NR6Uqii/aB29pPB
            z6ohxZBAxS5sOQy/fMrg6Yw6GTz/FZnjrxLOKDexHXl8MdMyOapmmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYkZKamlWSW00SWpOeDJo
            b1pWQWFmaTVwLytFazVrT1NwSE1iN0pGVTFJCktGTHFOSWZRc3dKNjVRd3FUWnY0
            cit6cmVVK1JMRkJ2NmxjbjhSMzFxTG8KLS0tIFlEQWZwSHl2d3VkZG4wdmh2K0FY
            WG5mUmF5VDlYNFpjSzN2MFE4TU80SVEKojz0vxFkwEI6B1LH4iVts+y2c9qCkiE5
            wvokz6nh7UwxjO59a/OYZioClkV5TrEJPQFJHmv77Z3zBgYy8CaEAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-05-10T10:17:26Z"
    mac: ENC[AES256_GCM,data:77cwnmore04zykYq4lBqFoDyfXj7qoBUl4HF44RNaWFqmzl85VEJAL+VFXEtIc0q3xrNdx7SfTu2syTscA4S4ReBAbatD/OfukXg5jnYJRRtz1g7JnrfiRC+oq2uJHExjsx5ChnI1EobcUyBmc/V1lt71iU9igQXGspPHL3j0YQ=,iv:pOkimbBjss8tVdK+gd3vjYkDGXJ4lst17WYlrYoNXmc=,tag:5uuENT/7WKnybKGthHWzzw==,type:str]
    version: 3.13.0
