apiVersion: v1
kind: Secret
metadata:
    name: claude-alert-checkmk-analyzer-env
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    ANTHROPIC_AUTH_TOKEN: ENC[AES256_GCM,data:J8vb2f0/0QEyXY+BCpJSBBJ0Vo5W+Xei+dql6OuzKpqAI3D34KWWBk05VWkOWa688220wil3EGVeRT+uh3Rfmh8QREe4+nvWBw==,iv:AHG3+W2IOrl/qJrYH0vJfuWrPWHVxtoT7GUA7qSRFM8=,tag:m9TgvGmD6EGsMP3d7QVSHg==,type:str]
    ANTHROPIC_BASE_URL: ENC[AES256_GCM,data:j8mAosAF3nCjSo/W3YRrUONfwiiD/uF7XA==,iv:8AluhkyEtmWztBljvRu3nqy0UymwIvQaX9xD0Lx/8v4=,tag:cLYJ+xftaPrpwhR3DK7Ffw==,type:str]
    CLAUDE_MODEL: ENC[AES256_GCM,data:MoMNdNXnvbkrnrGF2rhaRhqEV3E1e75F8z/b,iv:qrWBllqkeATSuY45rLD8CHQWaQAWspIVtrPbY5hVi4U=,tag:8/MDRluYyTatgb4UDOB9Cg==,type:str]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:cj3JxmGZ3t+RdIHj9mrtSWATBuGbtVD8iO6y7+L4Azk=,iv:3lRcU8+/crHgV2ttOtETpA3DFb6KSJqtND9J/nCCMh8=,tag:22GxrFIm5QDq3O6ppDk9lA==,type:str]
    CHECKMK_API_USER: ENC[AES256_GCM,data:qJ4oJq5+kVem4A==,iv:rJN1XFqQ+JRCPWRQWf93+BalRs8UJem5+xIVJ8upu+I=,tag:38QIVrkeoJFt+Qtuwpj8lg==,type:str]
    CHECKMK_API_SECRET: ENC[AES256_GCM,data:AyR1RZW84mTYl1ExF0QVTMAnTF8cXM+CnHZY/2HA7ns=,iv:BHPrdeN6H72ooeuUJfiTF5hjDXuZQNem4JgwmQOr3ug=,tag:+WBTxXZgOmRIep9P2HlryA==,type:str]
    NTFY_PUBLISH_URL: ENC[AES256_GCM,data:BZSMtzHrVxFN6tLI5JWEvDtwhw2wFSWCcHPO,iv:tQ2k6lgaQblvWhVWzNWbpHgzEbxPGHh+mlk8cUAzNRo=,tag:TAFCk02ULn+p/Q4a4pJ2Tg==,type:str]
    NTFY_PUBLISH_TOPIC: ENC[AES256_GCM,data:Uxpph0OYSLBLpCmPQylpX3RIQg==,iv:HkQvHeQFtSphX+sksgCm5diMkA8R7S13M0k/XqjtEfg=,tag:wLdwBGaYA8ZJNjgD5IwFrw==,type:str]
    NTFY_PUBLISH_TOKEN: ENC[AES256_GCM,data:3j/N8J8YEjE7Yb1TMvy1n0hvp3rLzqFB2k1UyzbU8pw=,iv:6hS7PzHUpXGVlR3ENTcLkHlTol31C+X2Eji0yrHKo+s=,tag:dHfNFW/adsBsQ02r3T3dyg==,type:str]
    PORT: ENC[AES256_GCM,data:s10AUA==,iv:Yc1hUoYYVm9BTZ0sJoOinaHAIPOlAiuoFNJW/KMx2s4=,tag:REdQJl0Oz3j3iNkxtqLsKA==,type:str]
    CHECKMK_API_URL: ENC[AES256_GCM,data:hA2oRq6NAdMYWIwfB6ufJdhTRlbg5AWsgrN52oWr6tJIna342eUX95hc1gU1mIWJtgOkIwaVCFkngiep,iv:Nu9T18lorhOdnE+Nw6uGrDjXvqozeD6X1R7BY7eMwNs=,tag:BxJTJoGZ0Lhik3e0mjfd7A==,type:str]
    SSH_USER: ENC[AES256_GCM,data:TAymHmQykg==,iv:JkI2OZl1rWKdctZKgPVxQeqA16prwaN9Rnv1ddWAB3o=,tag:ddpwnjtnz96+MOJHYWTnMA==,type:str]
    SSH_KEY_PATH: ENC[AES256_GCM,data:OY+cviz7OapJxXJvBMUc,iv:gGn0NrawL+KJLsKnoTeFh83hXqkXOIQ/EdIg6cefoHs=,tag:6mkuudAxsWWEdvghi2T+SQ==,type:str]
    SSH_KNOWN_HOSTS_PATH: ENC[AES256_GCM,data:z41G54cjNI7wqLlLUVSmmw==,iv:GMlVr+ms5g8HJKRZCNewtGm4O3Zv/eMqtNwmHjJhyig=,tag:vAy0Sg0wImixxsCznA3JpA==,type:str]
    COOLDOWN_SECONDS: ENC[AES256_GCM,data:ztba,iv:9zHiNcUopIZ6pONLfDYClvBrZmSxl8hWGenWA2qquxU=,tag:sa9VTGO370fz9c2JViVGcg==,type:str]
    GROUP_COOLDOWN_SECONDS: ENC[AES256_GCM,data:F4Q=,iv:O/sDiKP0JcmVKzIz9wuO0sLz+1XudDb2FZgDcWE7+1w=,tag:vXwhN+DRaI4mtZcsSa4v1Q==,type:str]
    STORM_MODE_THRESHOLD: ENC[AES256_GCM,data:PdE=,iv:P3kLeunYCbexUIQtvi3ACIdz/5XtyYcO8yPAQ8tFOps=,tag:xR/G+aldAGWM8gMsd231kw==,type:str]
    STORM_MODE_NOTIFY_INTERVAL: ENC[AES256_GCM,data:HIM=,iv:U3s4En1x38eFNAs3E8bcx3qXKN+sh8EZTNC0otREgPg=,tag:KQQ7Y9YLdKarq4VAifTkBg==,type:str]
    CIRCUIT_BREAKER_THRESHOLD: ENC[AES256_GCM,data:tQ==,iv:k/Ee0Fb/+heG8K+ZpR82VaYw+0+B5ARoeMuw5gE0F/Q=,tag:3PwOANqLcqIEZCYDheuTqQ==,type:str]
    CIRCUIT_BREAKER_OPEN_SECONDS: ENC[AES256_GCM,data:gN4=,iv:t3HUduLEK9FJkDRhA3w32LSWpTgW4hLUiWTYjDVdPf4=,tag:T0Y9UqvwGsdwYlS8MOGkCg==,type:str]
    MAX_AGENT_ROUNDS_INFO: ENC[AES256_GCM,data:OA==,iv:iCDWkPyBE6+WFqKokPpmZfKIFJ2jyZVnfmBeys0tiro=,tag:f7n2GJLavOtkc4zsN86LnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISEpKRlZXV0dZenJvb1pS
            YnhEK2dNTlIvRktFVm90ZW5pNUZrY25TWlNjCnpSN3hBTGNMeFJRS2VHTENTSzZr
            ZS85WkdoZVZXelcxbGtFMXlMbkxOcG8KLS0tIG9ENjdoNUduNDdPaVZ0S2V4cjNN
            REwyQWtDOHlBTjRqVWdidXpMNDlWdGcKC2ahUzE6k+ewcjdSrKffQCrWChmtUUl5
            I+1vjZVJdIZnNiez3ewL67KR9IPEc1wuRjduZIcbVJ1uH9jmmJNXsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMjFUN05ieHpBZ2NjT2pq
            S3N4STMyK1I3WGZXN2RqWklMWElWVU5meXdnCmxBUSs0dmJ6RmMzWjAwS2cyLzFV
            Z1ZnRnJvb1NKb1BFazJPQjNiVlRFZkkKLS0tIG55aDVOampSNmk3UkVPVVJTeGZT
            ZmVVTEl5SkhLcEtJMFpBV0hNZDczalUK/nrrGsCO+MMb7NJbYVTz0Iaq9VBLlkEe
            gFFLUIUNsUyldE5eIlmWisACPrJO3KUhNa1mxXUlTdAGWjpHSQ/6Mw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-05-09T12:04:22Z"
    mac: ENC[AES256_GCM,data:AfBnsO+AWi6JMI6G5Qx8w0wnGUQfhOIASmd/06Pn1mT5bI75LhfgAJFVXAtsWS4vKtznmPh9mKmkbI6ws29fwSXThKCFYUUX1bDhieMBhNlca4UFR63KgBr7ceJQanShh+/d7hGyIk5k/17pmHSTQYWo+CdJ5HlXbiD8Dnf1AiQ=,iv:yNECB9gQyOF5Y8gcn/bLtdEIXh9IHtOrwM7mu2XiQsY=,tag:mBoLXjtc5nyom28QJ+mpHg==,type:str]
    version: 3.13.0
