apiVersion: v1
kind: Secret
metadata:
    name: claude-alert-checkmk-analyzer-env
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    ANTHROPIC_AUTH_TOKEN: ENC[AES256_GCM,data:75H/803cBd9FP4zThewsD+VSovXIAkGptDlZIAYZeu+nBe9xZwWrCwD3OoE/KBixiI2G55KnDkNuMvcMZd+5ohAwAOKbOlnTYQ==,iv:YTpP0AyfFzPn52gSy+4npD5F1/5SWLbJ/1WQD2i/T1U=,tag:vBu1SeFrUpN9Cc4xRYQKqw==,type:str]
    ANTHROPIC_BASE_URL: ENC[AES256_GCM,data:TZkUZGSDgzWi+4D9C3aJVv/+OLuiAzcbXw==,iv:tumueBZQudNFPpLGzTh1oeK8Kt1VQMXykPxlusc5Xhg=,tag:LxCCPMnd7ltzcdZfX5vO5Q==,type:str]
    CLAUDE_MODEL: ENC[AES256_GCM,data:2XJdQVS+DH2uMri4IqlN1ryKm0UVwk6nyfGx,iv:j7yOFCBJ7GS6BvnCmvMl9IicG7shycR1MNySJ3QNkBs=,tag:cuAgmxM0A1cShZHpDxb1cQ==,type:str]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:1NSubAw+rAcdMkQ9A28qQeld9yR1rUbkmac3PlCSfiQ=,iv:M/Udzfq8e7IcpvBDXvOHOHxoenXxnRY8W9ze/1VDDBk=,tag:ZZHDn6EA56dpG773hpNJMA==,type:str]
    CHECKMK_API_USER: ENC[AES256_GCM,data:f6oRn/H04gG+kw==,iv:xe3eJqi1IW9qkG4WZW9I+O5fwWzOpISQh2mfWchpBLo=,tag:wMJ2V/yMEZNLlBNM9IgbvA==,type:str]
    CHECKMK_API_SECRET: ENC[AES256_GCM,data:1/E8zRe5Rj759pcwWPhokiMOmM+4nfgCuaPpGwEfzwM=,iv:/oj9XW7MYjFt1aEDwNp5/PjXue7G2DQOS7EzQOCl1lY=,tag:cBGSk7U/EYzRmTIP5Iph1w==,type:str]
    NTFY_PUBLISH_URL: ENC[AES256_GCM,data:zpKJtbTL4Q5pBqxV625fnAge6Tn7s6bV0v04,iv:0KzBpK+pqAse+scKnabStUbRQoUpzm3qjfdNkxoKJkE=,tag:VOsczveDA71CRM44MyjyAg==,type:str]
    NTFY_PUBLISH_TOPIC: ENC[AES256_GCM,data:CBhJH7Tw8dIJOgT6Nrcw4GMvmw==,iv:GBRamDDOP55rMI1R9Q3hr9/lLhaljS/ZyyrGwSrHtjI=,tag:BE8LYXNWyUHujrf77/65Cw==,type:str]
    NTFY_PUBLISH_TOKEN: ENC[AES256_GCM,data:HQ4kxrAmY58A8Blae+ucAEIjBp+ubiwUefHi8KAC2mM=,iv:xvHW1cTzWw8lOVASA09HXf74hVkFECYs00GLcz4BlTI=,tag:RbjVIt0joxqQZZ2QtIz31g==,type:str]
    PORT: ENC[AES256_GCM,data:yRXXHA==,iv:mKC5UKlAHnueLy7+IU7/nFHxR4SpVa576NAJAb0qfaM=,tag:oA0Gkz/MXvCZra2xyswLFA==,type:str]
    CHECKMK_API_URL: ENC[AES256_GCM,data:4ghigPAqYijawgJXD8Ga5xRVkWn8fBChF+rx730vhNZOf8nvCsks5MO3eR2hAFwa9K2YwT3CZ56OIocW,iv:kc7Gdn1pqHlMVScymh7H6epmmJwnbbaOVc+1USXWvpk=,tag:wISCJ4ISCzBQ+jFUo3VyEg==,type:str]
    SSH_USER: ENC[AES256_GCM,data:6RBT/2ob8A==,iv:RIflEVEJWr9p5MNeWV4Op+HgWgCjrN9fD/u0E1YdU7c=,tag:5pzh1wwJDsb1arpcKpgNDQ==,type:str]
    SSH_KEY_PATH: ENC[AES256_GCM,data:sH1dIHMEoBjZXovGS/z5,iv:D4HywIdoaNUFm+HVp8jGjX90pYDUPEY5Y6jUv2EVvrc=,tag:+rWCb6ElBTJTEVGSLLJv3w==,type:str]
    SSH_KNOWN_HOSTS_PATH: ENC[AES256_GCM,data:z1mMvrZ/tLOyUWAi/8U9hg==,iv:oL/mAtEEUJ9Eo2XZQ+QxPOYQlP+GC36EOtYbzJVlLYs=,tag:B1UhT+M8hzCahWji9P2MVg==,type:str]
    COOLDOWN_SECONDS: ENC[AES256_GCM,data:5AID,iv:6hKHK6QYQhJIt9Gd4lLdKEQ/ERzFBBlp3Mkk3iIYvsQ=,tag:H/nrifiPUXRaBuLi4AkfuA==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK3UyWWNPYW8rS3pyY2xr
            b084UjV6bDluU0VlYjVQd0RTSHhzN01obFZvCnVrcGVxYm5DdTRLVW91YmJkajNq
            Q1dZcHBpMGY2M0w0b1BRbjQ2QjZSaEUKLS0tIFZtWTZKdWpwemN1djcxNXA0MnFW
            VWJqR0JyanAzL0hqT1NjUTNmYnFwZXcKJu10jk02ecH7WBdxQ5eqqXGQRHyPgAhR
            Cuy1x8ZqNpJqbGhrKpR8V9oEPhKHXt4G9hZLChgFzkzoMQMdjuJXig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrM0hXMUVXQnllc2tIU2V0
            a1lseGZ1Y1hrOGV5YzQ3MzdCR0xJVDA1OFhvCmlHU1FqR0lDYitXQ0J0d0dPaW5P
            cGtvMHN6STNwRzMxZDd5UlpIVlpjMGMKLS0tIHJsS01HeUkwUml1SU1ueXMyRjg2
            REJTZ1Y2dWsyWFdldTBkK2krN2pJUEUKPjSs4g1ZPzk+4w8S3/TMUEaTot/Fbx7Y
            Y0pqolYc9gxDB+1hqGCeDolLqDTiMJ/B61JaNx+QJ8AE0ugedGmFmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T16:43:11Z"
    mac: ENC[AES256_GCM,data:EFHTw17Jz5AxtiMm9QB4vXQzLKh9e/eBb6ZnV8LIkHsvZXVrxS+Yx9sbL0SkR085MK3m3lVIce/xD3W2AP8EwfzB9gerhcvA1JKIHp7urSTVYMKDs9P2P6//gmp5tXMutpaOIqNxx99v0R0DgzqHJn1Sw/3vB4KBfDG3RHndBVQ=,iv:Oz5L34KQPDHZa+I3T3zyL/MXJ9LnoNyf890vTuVtdSg=,tag:kAV19Fxi4lwE/M676n4e+g==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
