apiVersion: v1
kind: Secret
metadata:
    name: claude-alert-analyzer-credentials
    namespace: monitoring
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:qh1WRzZ+qmV9R/9JBxKrROuZM+OYKnlMm/2q3x0ryw1aEWGOjlQ7IVFltBd/G/o2fHva/o7x78+OHL/AuQqnflq19GgX1FLjBqd5nZne56cSk3D8WM8qYDS+EghC6OgHi9hm0Vn2osLNKZyLew45LJZDdutc9Eb/ulxM3KRoj2cL2isa6sftUrFDTZg8d4dzb2lxFa+wQWHSgQyHQRETRDAPrj1StWO5WrqkP8pQKPv5R1wI+eHkSeAU9i0Qmqm/KRBcUKAm/aV2qTPZdL7byvlkWllA9vGixF/ALRhrvLnM8mdQVDbpJaJF13Lg7x4PfLStNLCuElCW6lDoRW9/W7XrNDrD8giHgHkR6aWaQNIt9HJvU5CSvIn+8V9OdemPC+eFRSDfG9cYEShSiBQuqsOVzDkrV0+mEI50Mdq9hvIsXYxn6v//eVTdxjnJQNLHQcMEs/SwwEnK9drAeAie/6woyTFpMYMnuA==,iv:0iTzEaGfBl/jG9yxxWRz5hFCzDH75YjwdehZFvkEfJM=,tag:OvoszQBg0/Zjgvuqc8aPaA==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUnlJUXlNUHBMWW9RdlV3
            TTVFVHFsc01udnFyanl3Tmg3T2dMZ1ozakJvClZzcXlKc1lodDBIZm0xRmVkRDUy
            Q1lvMFZvcFNHV1RmYWMzVHhhUFViTjQKLS0tIHRINUEyREREdFd6MjBieXRXTVFG
            b2Z5WjM2dEZ3VWo3YjBicys3Nnp3V00KheI8bN99u/k85qoRcnMKs72IFhpFCNXw
            6rD32iReVHr9njOsAkVsTOLGRsHTIO1U7JmtuFygpVM2oovFcXxtJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeStvSnFwbXRQT3ViT0dv
            Q3VnWVV6V3ova0l5TnVQOGpWeWtSZG9UbGpZCnhFdVJBbDBFZ1Q3bERPaFlkTzNa
            S0dCRktQWkd1bGxIc3dSRGN3cFhhVVkKLS0tIDBvb3FMNWJibTBhUGQzVHJXbEI3
            Tys4azk5NksvcTlFbXBwQjh2TTFnNFEKLfkJ6dJlbzaTsvGFuMc8mu6+83pOmecg
            2Y7PsnjXcBZFcaifmPfVo+vy0z1DQttT8cxMGRU5/vLGiXnDM040ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:04:20Z"
    mac: ENC[AES256_GCM,data:quTYxdjI5NsggRbHkK0ijL0cUA1rOo77rnwiPyNvyCpXMm92EI6aBPhM4p7gZX6Gr2lGzazgtoUSuUYp60IjnVg+tc723uIGWeCEhbN1M0wexYVI1Eq/CBl9AY9ZAZJ3ilW7kw911oFoG4Sm+mkJv9Eunhol0eL4dthOQ3YzFo8=,iv:vPAJ5U3mzWphH1m5QomCDKYwa467hgCFFTG/z7TVb9A=,tag:bDtMQz5XZMMBzcQnRdUyZg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: claude-alert-analyzer-env
    namespace: monitoring
type: Opaque
stringData:
    NTFY_PUBLISH_URL: ENC[AES256_GCM,data:Agw70y4JmABtMQaTXFRYr9vpTz7TXoZRjmHV,iv:3zfsGOMWjI0Nnk19BvBMQp059XyIEndY1ceS8isea+o=,tag:CvCwyr+5jhsJFLLRP5rTUw==,type:str]
    NTFY_PUBLISH_TOPIC: ENC[AES256_GCM,data:+edtkUUPZbIUyqzxplg3I4sIfA==,iv:ZxHlEBS21BHGaAfLcrhBp2K1ijGq9lfcXawWoAmWSjk=,tag:dR3pxLsm6WOkMvspC4Omyw==,type:str]
    NTFY_PUBLISH_TOKEN: ENC[AES256_GCM,data:OfvBREP6tQowXFT1hhDUo4P5+RcVy13wBKbd6St8mT8=,iv:PoWLgCohBnwCDiyGmHYmrWOuxslPRpNV1M853lsGRUE=,tag:TGSSDcZn1s7Mg1trS4bQyg==,type:str]
    #ENC[AES256_GCM,data:L/xXcbkrvxJJ3Nog9qNrFy7J2xzU,iv:p17TZBWLYI5Mbsor2g3UUiEQdKCMXI9XB5dxSJGxXz8=,tag:Ud/s3e1MsQaNEVQiN3r+iQ==,type:comment]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:oPaZYoYk6hQeji7lP+u7gkSqkyaf0JUwbFCGYbzQoTrABw0Z5++Zx3LjDsOLxt3zUZtpf1G8GaLNYx7cio0nVA==,iv:EC0GbSYf6P6pgpqZ6ko9s4m5hgzhYbKZfWf1Ca90RvA=,tag:Ph5buiwy2+siMfTRv3QtiQ==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUnlJUXlNUHBMWW9RdlV3
            TTVFVHFsc01udnFyanl3Tmg3T2dMZ1ozakJvClZzcXlKc1lodDBIZm0xRmVkRDUy
            Q1lvMFZvcFNHV1RmYWMzVHhhUFViTjQKLS0tIHRINUEyREREdFd6MjBieXRXTVFG
            b2Z5WjM2dEZ3VWo3YjBicys3Nnp3V00KheI8bN99u/k85qoRcnMKs72IFhpFCNXw
            6rD32iReVHr9njOsAkVsTOLGRsHTIO1U7JmtuFygpVM2oovFcXxtJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeStvSnFwbXRQT3ViT0dv
            Q3VnWVV6V3ova0l5TnVQOGpWeWtSZG9UbGpZCnhFdVJBbDBFZ1Q3bERPaFlkTzNa
            S0dCRktQWkd1bGxIc3dSRGN3cFhhVVkKLS0tIDBvb3FMNWJibTBhUGQzVHJXbEI3
            Tys4azk5NksvcTlFbXBwQjh2TTFnNFEKLfkJ6dJlbzaTsvGFuMc8mu6+83pOmecg
            2Y7PsnjXcBZFcaifmPfVo+vy0z1DQttT8cxMGRU5/vLGiXnDM040ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:04:20Z"
    mac: ENC[AES256_GCM,data:quTYxdjI5NsggRbHkK0ijL0cUA1rOo77rnwiPyNvyCpXMm92EI6aBPhM4p7gZX6Gr2lGzazgtoUSuUYp60IjnVg+tc723uIGWeCEhbN1M0wexYVI1Eq/CBl9AY9ZAZJ3ilW7kw911oFoG4Sm+mkJv9Eunhol0eL4dthOQ3YzFo8=,iv:vPAJ5U3mzWphH1m5QomCDKYwa467hgCFFTG/z7TVb9A=,tag:bDtMQz5XZMMBzcQnRdUyZg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
