apiVersion: v1
kind: Secret
metadata:
    name: claude-alert-analyzer-credentials
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:PhQXfQeKhwCaTUGpYjRlDBBmnoWRfxnteCitya0gLhXjnT29CZdnvF0iOOTg1bip4BJrwyUnn12IwgPyuJjHhkRoXUuz2PtIbLWJPXwlt4VMih7qtNtF5lT5dnqS0sFHMnHqV34QL5zqaiNbkL7RQ3LuPG33QvAraVfxWhxE/ltN24ruXdqaAAvnV3sgdB86A5onXJjM4v02LLF8RFKGCG7kpPIk1ok50bWQi5OjI17Fiv1IvsopR0U32cevLaeHDjCcp9blX7yU0WUO1GbyDNGK39TTTQbEgQc/p0ltyJ7+Vuvwmy+bWYezcpRRdTYW8IqkDqi/3P3cKmoFb3w0tvwdfBK3Ga3scd7SwdyBSo9SLvb111A8+6MKUwz+bjCqdcCn7nuR/Xjwh2u4k5w12CLdJoOtVKYAr4SM6ynMrpWAbrW4MWTDk9enQ1SIgz81SC8r8QaelV8PHuHEnteJgsaHsRRxBHQ/Xw==,iv:bplZkB5WfH3ee6pkJJkts/eyOP+ANp5H6nTVplGpHvo=,tag:v5UqC08ZPWq3s72800AJyw==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bEFFRlIrQlNiZFRxK0g2
            WlQwMittRmxUUmg2dThRbWZlNVZmNUhudWdFCmZ1Um4vOGxFL1cxV2l5QXROaDFT
            Wnd1b3E1dlRYalJnM285Q2ZwOGRNTTQKLS0tIEx4U2Z1c1NEYWUwM2JyalY3VWZ3
            U3J6UUk0QmZMckw3SzNZbldPVHYwdXcKQmfxhveerl2uBftXffUdu56pDtZxmRBt
            Yx51pixoEAAnpKdmHtjBH1JRCHtLwKwDT4bEc2wOH7T9613glHDyPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RzEzOFhueVJRVzNoWTYw
            S3BUdzZHRXNIMXd2d1lFQ21xM0QyTnVQTkhzCjdmK2pzOU1JYXNQYXpQZzVGUUE3
            T0JNV3ZkWkVpWEFkaEFlVnhhbk9OZHcKLS0tIGtmRktnaVpibnBQdG85VUZ6Slhi
            bllMMnp4N3pKZVExTWhtbTBZdWQyazQKHb8b+WL+tac98qls9CMqh5MuQoyUcx8h
            atqO/OtXIsm5ABBh++i2Ub2nayo1CvwzrLUFWxTk9iHy2GPFQ919hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:08:56Z"
    mac: ENC[AES256_GCM,data:sppQZJGlg0sNx2/t31PATgvPQNOeT55h/zH/TCgqx5l0g+t/b8rYrIsjThF82ru/y3jYdTEodQDhFGGss2hmpGQ0vYXEt1Qu9Ow+sqjUSMyP4HlOThvOCtGMXwyl8IACcsZ/GO5Na7NodYl7x4h4T4kaqy1j2WOl3dVAta7wXi8=,iv:aPlKfLoFgb9ahFvnOxWXY0CG0yhxSbbMmVnYe66Q8Yo=,tag:63ivgyaklyiicU3lqiLjqA==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: claude-alert-analyzer-env
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    NTFY_PUBLISH_URL: ENC[AES256_GCM,data:7sd9bYD7y40ZfswPDTQHyh++HfIt3kIfz3Yq,iv:9YSww4Zu/HtDkT7MiT+RxamIezdlR3l2fq7djFRjOlk=,tag:T+dJsNSqDG3XCTITCV+gIQ==,type:str]
    NTFY_PUBLISH_TOPIC: ENC[AES256_GCM,data:otfKLVPkJda8febKUS5+p1CUHA==,iv:uzSZb3FlaCK+Iulh62Ccq7rlfqgkHm7F6lhC7DoAw3s=,tag:fFawYZuteIqlWcnWA6v3wQ==,type:str]
    NTFY_PUBLISH_TOKEN: ENC[AES256_GCM,data:fdl4qX2IkXKbrp7v/Sd3CmnigkegBOgcbilDxcIwrsg=,iv:9tTwbOSqBVElbR9vvYT/K3n8jHTKdiuQZECtGtTFNLo=,tag:pQeFpkKAlUECiV/vjAV3JQ==,type:str]
    #ENC[AES256_GCM,data:6AEm3KRXPo07BG05xR8tIdVl5Krx,iv:OLS4q/9pgOMTVeRLI/+iVtxdZwhLkVMT4igDkY9/eLI=,tag:rVZTxPg+L8BeyulNJNpayQ==,type:comment]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:8rZFs0ApbIeMVHbZS8sUKeF4SOO5HQ+ueD3e9NFuS18SqRM85bvVV3wKWcrxPDwMloIHG//noUuBSlImKb1Bmg==,iv:1of09IRTc65AvHos1o52PhrukCPJ4jOuUMyMTMwrxKY=,tag:4c5jhckRt/k6dLgY0009iw==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bEFFRlIrQlNiZFRxK0g2
            WlQwMittRmxUUmg2dThRbWZlNVZmNUhudWdFCmZ1Um4vOGxFL1cxV2l5QXROaDFT
            Wnd1b3E1dlRYalJnM285Q2ZwOGRNTTQKLS0tIEx4U2Z1c1NEYWUwM2JyalY3VWZ3
            U3J6UUk0QmZMckw3SzNZbldPVHYwdXcKQmfxhveerl2uBftXffUdu56pDtZxmRBt
            Yx51pixoEAAnpKdmHtjBH1JRCHtLwKwDT4bEc2wOH7T9613glHDyPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RzEzOFhueVJRVzNoWTYw
            S3BUdzZHRXNIMXd2d1lFQ21xM0QyTnVQTkhzCjdmK2pzOU1JYXNQYXpQZzVGUUE3
            T0JNV3ZkWkVpWEFkaEFlVnhhbk9OZHcKLS0tIGtmRktnaVpibnBQdG85VUZ6Slhi
            bllMMnp4N3pKZVExTWhtbTBZdWQyazQKHb8b+WL+tac98qls9CMqh5MuQoyUcx8h
            atqO/OtXIsm5ABBh++i2Ub2nayo1CvwzrLUFWxTk9iHy2GPFQ919hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:08:56Z"
    mac: ENC[AES256_GCM,data:sppQZJGlg0sNx2/t31PATgvPQNOeT55h/zH/TCgqx5l0g+t/b8rYrIsjThF82ru/y3jYdTEodQDhFGGss2hmpGQ0vYXEt1Qu9Ow+sqjUSMyP4HlOThvOCtGMXwyl8IACcsZ/GO5Na7NodYl7x4h4T4kaqy1j2WOl3dVAta7wXi8=,iv:aPlKfLoFgb9ahFvnOxWXY0CG0yhxSbbMmVnYe66Q8Yo=,tag:63ivgyaklyiicU3lqiLjqA==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
