apiVersion: v1
kind: Secret
metadata:
    name: claude-alert-analyzer-credentials
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:BJGxFx0CUK2MxeCfA5U/fiJfwgEhmkfxk1Km9Ql9XGYSUrDz6oVoelqmmF06CMNwBGPsig1RTW5pk76AkQnhP8enD07Oybo2Bx9BVVhhYFwICdpwPXzDsYqh6XMjEfvTyDjWQ/+quivaAvywjBmo1tF8LMz8KNSMG9mGrq/MWKH/T301wMYSgPP5zPgEi10zym9fFILnSIw2rKvGNhQNyEO2PNC1XLJ+l/+j5P3yMjsVw7NBN1UsGVLMjUM/d/FRRgwSHiSF2BIIh/NP9ARHTZrqaJJmK5E88GgUzg2RXD0TGPwF8MKctPa19dHoI5WGBQeqUR26fKFPlPUrvd5Aeeg73xSp1HA/WJ7SkTlMUTpREf04P/gB/Hs39zRR9lRcy4qT1EcBjCXttub/FZh4FdFfpjhsxBDrKO/S9UsswNeWhJYkbeYSwIMVTLnqIaq45ysjJ29GM3XrojCYZEjAQwyLnCUUEuyyXQ==,iv:6wpnKXnvEEci23xi70VaLXRlJfpOZWRLekzzY0rD//8=,tag:mgoAPT1O6KYYMJk5TtMPbw==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxS0lvekVpVmpKaHhvdnNt
            MmlrdDlsS1FlemsxeDVFbVNGZXNRSGFXR1RVCm02bXV4M0tIdmpSc1FhVkhaS2xW
            UElwSDZoOCsvVDRBa1plc1ZudkdkOVUKLS0tIE1Gb1VEdGZiS1BXblNlQU4wQzV2
            SDVJVENhQ2pMTGlvSmxMVUlDc0h0cTQKRn/yM3h+1g0MYKstT6PjyHLjcMUIHLIU
            AKaqEJw1oPvRCsIsERAfCJDX6jloriq7u7j9DZIXmHWhz9pdf5G2uw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TG5qYkJ5OVVVNW02VlQz
            ZmtkYllQQ0dBWi9UdVI4aUxUVVN0QnhnN3c4CmQ0L0kyTU5TRndJR0pzWmppNGtk
            aXNIRXZwR1lwb3pmbGx6MmhkTDVRdXMKLS0tIGt0alg3UzhPSTc0OE9xcWx0RUxv
            aktlTStTS05wOVV3SG9BOHhKa0RSeW8Kp+UHuSvtnq/eujydQtqN6r0GpDjkYZFy
            ZKWrxUGBne0dsgfCz4JiGSqhTkCDv68rVRv8UdCE5JK4yQm/yjKGHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:19:29Z"
    mac: ENC[AES256_GCM,data:yqu70FuG0k5K+yTfkw7WPLj0w8mFCttAfhQALGZ/g/5VQZo1EQ5gbXM68/slAYL+WxW/dvozQAzJ4gx73J4BYirMaJ/RxDsOxSqq9inLeIdyuHDiKMSbXLBrXNzjazX1F6dAIg3cVB2hZyGNrsAC312fsheo9m/RMG+6VQQa7wU=,iv:OyxMqyAJNVnn4cwUQebsdF1oegKx0LNxaztTYCrmVfo=,tag:UWZqiKuESMNhDZMKeSzHdw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: claude-alert-analyzer-env
    namespace: monitoring
type: Opaque
stringData:
    NTFY_PUBLISH_URL: ENC[AES256_GCM,data:XV94tbpYI8lnnZVNemKp6TvC/A1BINy7EkoG,iv:ufWsiTQ6jCyF0N/sNddmAHaW75GEbXfBcyWq2TnQgH8=,tag:OzcXVuarPoaJVw/ioJaAnQ==,type:str]
    NTFY_PUBLISH_TOPIC: ENC[AES256_GCM,data:gnWlGa6lrYA8+Y5bt4pu0kzg1g==,iv:/DLC3pxbEKV00xwfj098BifDIUGtno56BF2SAH0dKCE=,tag:sx9Q87gvczvw2nxEW37snw==,type:str]
    NTFY_PUBLISH_TOKEN: ENC[AES256_GCM,data:mdA8rKIhO4uUHVHT1W/aKg2L2pNVhRdAPuI9xMHCExE=,iv:pcT+OkeG/B5YZd+onogQ+3U87k+Q2A/FGmEp0AakXbQ=,tag:7gt2poZ4tcKHoT6SRdYzIQ==,type:str]
    #ENC[AES256_GCM,data:wa9GWL2J7Aqsq1gHqTDYT7PK5G6X,iv:CBJSPGWBboblMWH8gSQVXaJ+p3Jdv1sPM4QlXZejK6A=,tag:ULAzWZZGPZHLDFxVvu2tDQ==,type:comment]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:YAu1stmbpV/8xipLzdgSW0Z5keu9dY2HdEli93a8o1QNBerrLaeib6RR+R+Bvo6SOmDvSlBrhNCWMqcsHdog4g==,iv:mUF2l7smg9+yn94wQ+xhnOADTLnMmaum/jj3K7ov5fQ=,tag:RdmMfd4P8qD03juMgKg1Fg==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxS0lvekVpVmpKaHhvdnNt
            MmlrdDlsS1FlemsxeDVFbVNGZXNRSGFXR1RVCm02bXV4M0tIdmpSc1FhVkhaS2xW
            UElwSDZoOCsvVDRBa1plc1ZudkdkOVUKLS0tIE1Gb1VEdGZiS1BXblNlQU4wQzV2
            SDVJVENhQ2pMTGlvSmxMVUlDc0h0cTQKRn/yM3h+1g0MYKstT6PjyHLjcMUIHLIU
            AKaqEJw1oPvRCsIsERAfCJDX6jloriq7u7j9DZIXmHWhz9pdf5G2uw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TG5qYkJ5OVVVNW02VlQz
            ZmtkYllQQ0dBWi9UdVI4aUxUVVN0QnhnN3c4CmQ0L0kyTU5TRndJR0pzWmppNGtk
            aXNIRXZwR1lwb3pmbGx6MmhkTDVRdXMKLS0tIGt0alg3UzhPSTc0OE9xcWx0RUxv
            aktlTStTS05wOVV3SG9BOHhKa0RSeW8Kp+UHuSvtnq/eujydQtqN6r0GpDjkYZFy
            ZKWrxUGBne0dsgfCz4JiGSqhTkCDv68rVRv8UdCE5JK4yQm/yjKGHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:19:29Z"
    mac: ENC[AES256_GCM,data:yqu70FuG0k5K+yTfkw7WPLj0w8mFCttAfhQALGZ/g/5VQZo1EQ5gbXM68/slAYL+WxW/dvozQAzJ4gx73J4BYirMaJ/RxDsOxSqq9inLeIdyuHDiKMSbXLBrXNzjazX1F6dAIg3cVB2hZyGNrsAC312fsheo9m/RMG+6VQQa7wU=,iv:OyxMqyAJNVnn4cwUQebsdF1oegKx0LNxaztTYCrmVfo=,tag:UWZqiKuESMNhDZMKeSzHdw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
