apiVersion: v1
kind: Secret
metadata:
    name: claude-alert-kubernetes-analyzer-env
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:pnjVKg==,iv:rUfmcE7axPWYQgXUSXGq41BxfydKL72bJz78eo8FffI=,tag:yt41fCzWUR4fQtklBhhQXA==,type:str]
    PROMETHEUS_URL: ENC[AES256_GCM,data:SdRxUkIBvJWV9txyTKZDf4p5CQWwEgBcrKWhfuwlDmmQ/YUL1pQwjoUzlXjfPV9W/H++eQuDrOE3ZKgDIPANZNbv/tvhjtgykw==,iv:7ribpwhFmjxb6zI8cZ0rQoIqaBwZUvYz4SZp4bmOOx4=,tag:8YhUIKtQI5J1f5Vp/dBH7w==,type:str]
    ALLOWED_NAMESPACES: ENC[AES256_GCM,data:OAoBs6KUEbbIyZ4wfqycA7kRpe2+01OgJns8tSsfLv3Jl1Rj6p4=,iv:SzHIMLVhzCqMSgfVEpdTy5LJzliQiDDNSxpDn3k+vR0=,tag:YE+yudWR6Iu+eUlkMzYd8w==,type:str]
    MAX_LOG_BYTES: ENC[AES256_GCM,data:LMTdfg==,iv:PcxT439L6q7EzOr/Z+vxzSxigZEWsKdqdhQYLHzrXn0=,tag:jf4gaQyAiReEGkhMVv6lnA==,type:str]
    COOLDOWN_SECONDS: ENC[AES256_GCM,data:CEg5,iv:YyKdobuQSYqKBXjwch173Pk6oRtTUm7Jm+iNKH0Kyss=,tag:1Y3w/tt498Fjz/XXLNT07A==,type:str]
    NTFY_PUBLISH_URL: ENC[AES256_GCM,data:gMvoQnYCmwbwcfTJZE+hymVXihEflCqvGdJj,iv:3JuoFKlmpc6KnZHq/gc0i4BRtcB313fGs+2TNZVqO4M=,tag:kOBG9UEra/UtvREIX+RKJg==,type:str]
    NTFY_PUBLISH_TOPIC: ENC[AES256_GCM,data:wIU/b/5E1vqpbcg8yCKpK7a4Hg==,iv:Y5CpYsTaNG2j/FbpuMzTWvCgsBZvbmRt78CYjQShKn0=,tag:c1szXIWG8r4Z3pEGSCn19Q==,type:str]
    NTFY_PUBLISH_TOKEN: ENC[AES256_GCM,data:e9Yt/oHL+k6WlGPtXR1ZqS9seHJN5601Wumou8D7Ye0=,iv:Qhz2F5g9PWSkpzfMWTdW3lD3HfVQmu1kM+zuHaq1bUA=,tag:6LpQ1E6jrhUV16yLm4+MVg==,type:str]
    #ENC[AES256_GCM,data:r0tlh2AwlHPOV4R/A6mDXKQ9848w,iv:eyW+keHbQQRZ8lbXLq3bop8Duqh9fhwv1YQgGn1nlkk=,tag:umAvN8pSI8J4jLOPDrGD5Q==,type:comment]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:u20RXA7zhdRtC5wafIscpqttDr4oUL2vZZ1wm4tI3xYwEEzxElgUzpmWgtl246FR8DKLo/twiWFWA6kENDLWNw==,iv:woWX7P+XgWKi9QCHXT2/PxEiZZvkn2t8YagI5uXwVLs=,tag:HzDHBD+RVCqE4fTz7BI2PA==,type:str]
    ANTHROPIC_AUTH_TOKEN: ENC[AES256_GCM,data:wv9xB6uJipcbOYSq8+jNhZnK3cO64Z2FAdrP8PVDBMpcTHHoUrbPBPDAdkz+LUhqEXFpWziZYVB2S5OhuU4uOTmR4SP523p8kw==,iv:CQ8/Iz0lnT1gpWKf+HVSwEbG7dXY3yt2Urp+0oGGkys=,tag:pxPlLuEUjo+1PCPJVuScxg==,type:str]
    ANTHROPIC_BASE_URL: ENC[AES256_GCM,data:JQdyW8YfLafTO9V8WBweL1urexKtiCqK+g==,iv:XXcvYpVQvvtxMsa/XevAvo2FB8tzPetCjPPtqXQwPKc=,tag:ynLWzuRU558DACg7lpIGMw==,type:str]
    CLAUDE_MODEL: ENC[AES256_GCM,data:M7TO0B0RvnNmrObvfuJgFqWr5XP0mKacKQMg,iv:4+XGVi4Hbte3DChX2G+8b7r+1wjjJ3UVhsR/GyV+W/k=,tag:mDVUtHpVmMOFpkKB0AmdtA==,type:str]
    GROUP_COOLDOWN_SECONDS: ENC[AES256_GCM,data:Hq0=,iv:DOoVG8dfF7hwaWvQ0xaYf+2vC340mB3R7BrgWuTihsk=,tag:/bfeP6kLfqjYTF+zZZaf/w==,type:str]
    STORM_MODE_THRESHOLD: ENC[AES256_GCM,data:++I=,iv:ciBJC8GL2nIXglh4z23Lyb78sSMa3HXlPbSMyW8S20Y=,tag:s59olsU6kgSAIWyNXcnBqg==,type:str]
    STORM_MODE_NOTIFY_INTERVAL: ENC[AES256_GCM,data:It9Y,iv:8TsxNo+uOHRB9bjb42io902w/CtheKkVYinC7oZgNoQ=,tag:GGebWn/1P81F3uJyuRup8A==,type:str]
    CIRCUIT_BREAKER_THRESHOLD: ENC[AES256_GCM,data:XQ==,iv:nRAiv+wU6zwnCefPuTVZpzFd6z0W5bRnKgWAKnciD/c=,tag:8dXA3zKCWTi3JofxCESvSQ==,type:str]
    CIRCUIT_BREAKER_OPEN_SECONDS: ENC[AES256_GCM,data:4CI=,iv:tHKxQeFxrGGAjKcty1kPOCXla2EDJLkg1+Zjn8hZt4c=,tag:JZvnJ/ki6vFzLTE12XF+pg==,type:str]
    MAX_AGENT_ROUNDS_INFO: ENC[AES256_GCM,data:og==,iv:8Xfr150lEXd2p3nUq6foR7gNhV05S1hPVFTaKB0Lcq8=,tag:pngsWVXtCGqXrp7MadNOPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ekc4K3UrQmtqM3YzYU5u
            ZGVJMWFxYmtNc0lKYzNHRktEWTA4QXYzM2k0CkRjQ3pBMlIrWS9VWmoyVzI4clBR
            eVV6YytTcUVHNmMza1N1aDhBTW1kZ1kKLS0tIDFRNGsxbTZEdHl3Mk1yblIyRUNl
            eTNEVmsxVXFXZjZPNlhXQnlSMXFtTmcK4ApMyZcs1Afu8gfqdiHlOAMxo3BcxYGn
            ltHJy3CZS+R652ur7kH6j3+Elk6l7WuoN9hQ010nKXk5kxK4cfPXgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRjZpbytrWHlDZlQ4L2pk
            K2hSTytOTDVTekVQKzRwekVBMzNFQmFJRkc0Ck5VMUg3SW4zbnpOTkZsU2xPM3Rs
            NWZoWC84Q1RrSmR5dkVYeE5iVTBWdmsKLS0tIGpDTkxLV2kyU1hHZVZNRkFwRHZX
            WXZITkQyZGlXM2VxMUNsQ203TXJBWlEKIQv4hd0jKi28YuZuX/IDraZVx/Jo2BGh
            ambp1FbqU6OQodKuXFfgMJ4eGTKGzfZ/f30iDQrE59Mr6xKk93laiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-05-09T12:10:51Z"
    mac: ENC[AES256_GCM,data:FBsv9jH5ZjJTzrb2juFyg+glFJDtvTUPJWcPNijXmrKGk5U4gE+ZqNNP2gThj28PIsSpAXCErk/gYa85VDmhPX4sN9viBwcZ5FISquh7uElMQE3FEF42p6rzILgw9Eii183gsaKeaD8Fzzu6I3eSf5Kfx3MWoAqg1MonUafSOwc=,iv:dwognmRY9J0T1y/OGID/2cYZSsT/MM/IzCufk6zvpT0=,tag:mc6XznABt94BvQwVFF+YFQ==,type:str]
    version: 3.13.0
