apiVersion: v1
kind: Secret
metadata:
    name: claude-alert-kubernetes-analyzer-env
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:opvfAg==,iv:UsQKDt5tKW0dYpWL0ZmGu+P3iusg017dkfLv+v9R5q4=,tag:UgTwA+QTCjYyhRMNCXly8w==,type:str]
    PROMETHEUS_URL: ENC[AES256_GCM,data:WVtRw2vfBCG7Objnou1QOGHwAEORCmMCsfRcvpdLnG/Bcgijv+ZcL1O4lXXeooRYULhMLabxQqqJ7lKv0viO+ClwL/mWYQsKnw==,iv:JRhtzx3lt9J0Ou5qhAxXVYB0hYipgEHNQoXIsztWTyU=,tag:A4RQcLOeGZe3xR7Zsc7KLg==,type:str]
    ALLOWED_NAMESPACES: ENC[AES256_GCM,data:wRTmnNa5PjYCF4Lp1ijtiFYY+335ZlQPlWROfZ3Hzy618JtkKW0=,iv:ctqlvea03wgCZQ/Cnh0RFbj8LzAzkX+0/nJ+yLIi3AQ=,tag:AvgphEwWGYCEfIuEyqeKKQ==,type:str]
    MAX_LOG_BYTES: ENC[AES256_GCM,data:AHwpxw==,iv:Pk8jFQjkBFNOrSYUbw3yL2Yz+aTZaN/s8b2to9zGCv0=,tag:I6iAExMPN5hmclLz6Bz6ew==,type:str]
    COOLDOWN_SECONDS: ENC[AES256_GCM,data:82GQ,iv:CpaOKwp0eoUDePN9UT2qZxfsky8vev7p8puJirHRO0A=,tag:nWSNT2KR9AtFXGma9GTGCg==,type:str]
    NTFY_PUBLISH_URL: ENC[AES256_GCM,data:UdqtOg7B6VaGDVunTRzDAML4+uGyWgeXqlX5,iv:k9svyGOcP/7SnjK5emqD1tqBJoyRDexcodEluTlSm0s=,tag:VeIx0ivf7+d0gTlCFuh7mg==,type:str]
    NTFY_PUBLISH_TOPIC: ENC[AES256_GCM,data:E7aR50RnhkUAgZhwgYZTBPFP9w==,iv:M+8yGorPSW25/bQUrkb0Eu8JkLQQt6n/7SNAcIRN7RY=,tag:/LcLkwPRIUIsmHrWMfxhgg==,type:str]
    NTFY_PUBLISH_TOKEN: ENC[AES256_GCM,data:JqrSCDB9IAAzDu2WtEM0i89/DSbtgBZEtyDMqH+leZg=,iv:otHHp++c0cluCSbHKYbkF5i5Vh207ACwzsWVTGyIrUg=,tag:kvv+LtThaHt8h6ROd1Ep+w==,type:str]
    #ENC[AES256_GCM,data:zzHkjF5ZT5lXxUqWnHKUkHkg5SwJ,iv:5wz4l9mWg+T3n02qAUeKj+SwCesGNljYNH5eyxpgq8M=,tag:urVZIbTrMoCyhboJUjo1xQ==,type:comment]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:A9gJE4GMxQrnn3plv6ryEOxOTpQuKMpYzrTPhV8eHGACEc070uh4kI4Q+wXjYhh17ynKAnzyOx3rmbnOJYRRSQ==,iv:FJkoLJHat2VQRpnCcf3e3XUTQ3VeGr/ppKTOBBtOOyc=,tag:JE1MTYzBMZ6cidRGek1rwg==,type:str]
    ANTHROPIC_AUTH_TOKEN: ENC[AES256_GCM,data:jA08I1rxFNHaGWnnu7GyIMo6PoLeQ5ORuKXeIyqshgDD78ju10l6IQAzUBqCA1sI+3yBViYFk7YNZhbKQ0JbYp6m8tc8Djtmfw==,iv:OjTYikGk/ru9ufpFCBpciXrXp2HouMqY5fk33RWz7vI=,tag:GaWPTj5UakoSrgQhSekUYQ==,type:str]
    ANTHROPIC_BASE_URL: ENC[AES256_GCM,data:znTFjOxtcaFqK9L07uw4+HlxsE2IXuOncA==,iv:j6+TphJI0Z7ry+qblQACDTe42gBPF6hq5HnrNTNikZU=,tag:i90mCnX6rkSVcVEliwzkXw==,type:str]
    CLAUDE_MODEL: ENC[AES256_GCM,data:rojB7oXvSKupk92hmYn6zVAUKPKCNhfb9tFj,iv:q3OwKaFDWMppJ8kFvI8z5bXFCQrg4MKAGgvOpDl1yU0=,tag:AW54KDKdn5J8gCBEfNSyLQ==,type:str]
    GROUP_COOLDOWN_SECONDS: ENC[AES256_GCM,data:ZAo=,iv:yBKhHmQjFuhK+GhPBtLba3Mlnnv7D7ugvzocZ4WZ30w=,tag:G8/zHMCeAQGTUOrlbft6LQ==,type:str]
    STORM_MODE_THRESHOLD: ENC[AES256_GCM,data:5ZI=,iv:olklGKr+TjeZdJ4B34BWRvQmTAFAflWFPpcXa9XsXsc=,tag:x/sgKGX9FfRh4owFX1P0aw==,type:str]
    STORM_MODE_NOTIFY_INTERVAL: ENC[AES256_GCM,data:Kew=,iv:/m3fSXK3Uz/STGnPknU0rQuGwB5KO3SIPyJcs/nfOKQ=,tag:yo5is0F31aI6dm55y/DyKQ==,type:str]
    CIRCUIT_BREAKER_THRESHOLD: ENC[AES256_GCM,data:4g==,iv:Kxtol5WuzgCg4B1M/yDqXExE6v+Mw2wWkj+P+kf8Wis=,tag:Mowr1uj1NznomDCJh0G0ew==,type:str]
    CIRCUIT_BREAKER_OPEN_SECONDS: ENC[AES256_GCM,data:sCo=,iv:LKpcTf0Nj+yK8Zkw97yfl3/o+Tt7i7PTy4zcDzCuzDI=,tag:hAWI6+Zmklgb+oxJaiGbTw==,type:str]
    MAX_AGENT_ROUNDS_INFO: ENC[AES256_GCM,data:mA==,iv:ZybGghsNqFKlQHE960CNK8P6iobRnKsvaRnAyg2K7aY=,tag:J4kqJ8Uaq9VPMjR96NYOFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVFFIOVRtYm02N2NiWTZL
            MUhTV0h1MElzNENTVWZTTTIyUDRDUTB5VldvCnQ1NXE5NnIxcm8rMjBtRlB5b2Qx
            MFpyWk1TYWJCQU9qTUt4ZVNCL092K0UKLS0tIGpBR1Noa0hzMmNwdkNyNFI0Zmwy
            S0RFQzJ2MnAxQlhTVkZoNW1jNCtRTFkKQOIOoVVMc9Z3PLmxzDRJGtzC/cIrs9qp
            xsgbbVh9eNPM6kV5QHutMODNgG8SxtbCw6koBa4AB1Iq5XpiBCZ95g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU3pXTldxaCtwQng0Yjdu
            ZWx6MHhUU2hEeFJPV1hXZlNFSmZIb0JyOVJJCnFKMFl2cDY2eXN0MGxuQnhvTDlC
            SzJqRWROZHI4aEVIejNmNFdLTXVVRlkKLS0tIENCeXgvb1I1eDJzWSthK3IxVHli
            STF5NHBJdEhmS1pFTkplYytydDkyY1kK6GDV0whnL+7x0tQbZ5F0R3KBEEe/RQaR
            qY06vGzj7HahJaahZGSQ0EgBq2r2umdUX/N0T6zlLSuriYQj4dazfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-05-09T11:58:27Z"
    mac: ENC[AES256_GCM,data:9L2KtAyDSowi8TJu1snZvM7Z/yrTvYdAytt7N3qxAiVaWzZ82EYB6K5xUlaIF4mJ2cL5H6MsAndW/96E5Tvm1Pw5MK464axCZzchs7WW1XllhZyL0+7rasiOybsOGUm2LlB9Sl4CBed5fMwfrcI6fuTi6wQlFDKDE0yxniLnI/4=,iv:74+l7m3OwcbsW4QNOy5AUxIEDmrk9IU4EVEGYlFb0v4=,tag:rYuzk099PACocQ66LfPPzA==,type:str]
    version: 3.13.0
