apiVersion: v1
kind: Secret
metadata:
    name: claude-alert-kubernetes-analyzer-env
    namespace: monitoring
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
stringData:
    PORT: ENC[AES256_GCM,data:ndXoBw==,iv:n60hcrvCj7t19P4WJmsD2Grk7HMDsmXiMiGnB+hOh6k=,tag:USdnVwbq/RKeCD6g8AQq8A==,type:str]
    PROMETHEUS_URL: ENC[AES256_GCM,data:MkZXTZp8OzCLKzhi+soZRO+TPrz0MGY65MyDVF0rvxgHkn+uaLq0ZY44iH3szy7oK5Xs5aEPhJsTK39kr87059YdddcDMMzmgg==,iv:YcAZYoQXSsf+69jjJaFJrClFPC2XqdM24ocGYLMdL2o=,tag:Zof/9eOXn9wxoA8KEGJvqA==,type:str]
    ALLOWED_NAMESPACES: ENC[AES256_GCM,data:lL0qvgd8Gn9YDR8hZvpIEel823q1s8ZXe6AwDWx6tyy38xqas7U=,iv:j0TOKJG1qYmMjeNVxvzh2Y9rvYmC2CYCTPKwdB+Ph1g=,tag:A1ou2LrBjdR2qn1eYoWMyw==,type:str]
    MAX_LOG_BYTES: ENC[AES256_GCM,data:Hyq7Ug==,iv:9N1sU/f4PUzx6SyylACUOSQrrbLNDnSSwF6Ys7Z7F2c=,tag:a+JDaXBLlX0xtlS99uotZA==,type:str]
    COOLDOWN_SECONDS: ENC[AES256_GCM,data:UEf+k/0=,iv:LbrPWfwCg2AxVAGNtAzAdSOrJ01daoBrMUZq1BAzxIk=,tag:dflZKbXa9YRSIisEOimndg==,type:str]
    NTFY_PUBLISH_URL: ENC[AES256_GCM,data:iXWXuISLtFHaGJHi1HcJX7BNj/6QEqU31BnP,iv:AbmBlzhBExkgYmT1HCVUXK97lCc76+Q40irSVYcNefI=,tag:mfV0mx5mhOXojXZEBT9obA==,type:str]
    NTFY_PUBLISH_TOPIC: ENC[AES256_GCM,data:kh+ZmkBO2Mc25eWKZhzFwsgDXw==,iv:Nm6ZkGl+kjeFMhXgqR0EnKK9enLumVfNAQ3XLtAcC9I=,tag:c7pr79+x1TRiqwb7NkHJFw==,type:str]
    NTFY_PUBLISH_TOKEN: ENC[AES256_GCM,data:NfbsbKXaimiCFhpNVIRcYe366E0LkAkKna8a406naAk=,iv:jLgiZt6qkROgqR1KYzgRzuctuf8igHgs6vfcl8QZ8qE=,tag:zcLrioN7+N/e/dZ52IoL4Q==,type:str]
    #ENC[AES256_GCM,data:cR+QKpmWU90gHT5GxNNb5AxrCq4x,iv:fFP3aXx1dlU2t2RqJdq8qlF0sxq9zhcwVpsYOabqUfU=,tag:KjfvodI/2lRnqmfc70BtDw==,type:comment]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:/9jcyA9gYlda7q51Z0Mrtse+G+ngk+ZVCAhbjOEkSaEe/KCu39wrvPq3MXMehBX9nvGkhDMVXdB1INvhBe6i6Q==,iv:0y1U7BqJpMHvk0a+n07yrS8KZfy+egES7oEnpNq2MB8=,tag:3RRXq/5KnvDSa6QCtYXSBQ==,type:str]
    ANTHROPIC_AUTH_TOKEN: ENC[AES256_GCM,data:/bCUYS/pE6PIx8SPO0k/T02grrkKPbOVz0uQdhxO8RyEHp9iF0fzykGE0gdU7plE8ZJOUb0OTzcm6mvSyXKEZeeLjMiD1l2ltw==,iv:6mnSVIpwZ3DjrM5e6TRQRafPQdMj4CN1+kJX66w2Fis=,tag:JWB8jxEVGYVluFbMQfLpKw==,type:str]
    ANTHROPIC_BASE_URL: ENC[AES256_GCM,data:3AOu0z43qmW9RpMhaX+J/VUFB0XEwkUSlQ==,iv:O49/s2MnvePF/6KnCugXQLBsDhqIk2p/xzvMDXXJWUc=,tag:cseIXccCL+yIG/S5IA673w==,type:str]
    CLAUDE_MODEL: ENC[AES256_GCM,data:4AXUK3Go2ksWXTcKeHvxAeLma0TkJPYZ+AyN,iv:z7XqI6PJAcrwAyVqXfdoWl3EPD09j+jqhZoI3Uua9fQ=,tag:BfprLExU7dZkf2hfR6hxKg==,type:str]
    GROUP_COOLDOWN_SECONDS: ENC[AES256_GCM,data:8EI=,iv:jnJfkLSVJJt4PS2P2RqDMJet9kR9GuS3AG84p/+bg1I=,tag:RsDzkHordF9X9ejit+zYgQ==,type:str]
    STORM_MODE_THRESHOLD: ENC[AES256_GCM,data:0es=,iv:sNTMQX+ZqwoPD9mvpzEae56qCv597E+VU1RoIDe0DZk=,tag:xSFVqMJ+RapvKl7SHf0TOQ==,type:str]
    STORM_MODE_NOTIFY_INTERVAL: ENC[AES256_GCM,data:NNa6,iv:YuvKzMQ566pZ93rGsABVcsNJ76UtYHw6uuO20byMXIs=,tag:+Z7dWmU0AvL6fFFnoVUOmA==,type:str]
    CIRCUIT_BREAKER_THRESHOLD: ENC[AES256_GCM,data:1A==,iv:oCla0TLWDWam2EJTeEaR9SQy4MlcUezqgnsJKNRdYMU=,tag:S4wAlQo66/sfhhbFcNammA==,type:str]
    CIRCUIT_BREAKER_OPEN_SECONDS: ENC[AES256_GCM,data:lMA=,iv:lUQbv0dQp1ZTl0e5DiomnSlDC5kZUlzW0IERAzEwP7Q=,tag:asZH24ABjkF87AkJycGMdQ==,type:str]
    MAX_AGENT_ROUNDS_INFO: ENC[AES256_GCM,data:9g==,iv:FCT8HXY549sR89n2I3g8URnRFmIdNi55diWRtOYcU9k=,tag:CD/gv2aLPdTghRfxbl6jBA==,type:str]
    HISTORY_ENABLED: ENC[AES256_GCM,data:x/YDHA==,iv:U8cG8S2YCYjRbdXeI7EZoO5sBrWlSCybTDqDEHnkjrc=,tag:/dsICg3xewJ7CzeKd9iaYw==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueVNLNnVpcEJwcFY0NDdO
            M290TWVoaFhtMi9icjVoSGRTaEs5L05ZQVY0ClBNeUQxVjk5WmEyVTJNYlpvS2Y5
            OEROaDNLcDhVY0hET0NYdXJEUUFUbjAKLS0tIE9ucUhwdVpuWlVja2tZR2hPVERq
            UFhodVhFOUdHWVRXcWFVSzZLdzJnWGcKhEUJ84LTsWrvXiiA4rOvJemy9NhOjtmT
            3h9QCQfQ8vvDyNljEuAWXjJfn9HK9aqlY/wmAuQ5MTPIpkxAIiJeMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvektieWM5elJBT1hSSFFD
            WDZTY0VGTk1pTFM0ZjlzZE12WVptdUFOQXljCmxYeDhESVhGRk05Y0FWWkk1SkZI
            ZlRvbzBzTzdrZlJobkRHZDFxSlU4c28KLS0tIFRIaW01eVY4ZjRCcTJyNDBwWkhy
            TURGVEoyMnVHUENWUVlEbkI5LzdNUzQKfEn+NgDpRZ888L3tpoD1RKKn7CsRXBr0
            ivqVrd2OYySwt5oe2G/2geCIJ1Hwx5pAk0hwemzLUdhTF5JiV6KweQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-05-30T23:47:19Z"
    mac: ENC[AES256_GCM,data:nlCKfuqnXDGM26N1qe4xz+FlWxFTHWqD8pOgJToG9aoFAtGatTH/2r/7S7u/3gTx8Tpb1L0F1Ff6fVDgK993beiZh2+9lWoTG6Jdw8wPkBL7VEQ3atDqpytDyis0qA1wRL5fR+PvZi7VPNSzcnkt6RPCpO/qDG88uvKDOyx4RF4=,iv:KfNiUtMI0vtuR6EpfLxq8j4ArsUWvgaMpw6B4lV/oW4=,tag:ZrcG2KGYOkNUl3MyMQGO+g==,type:str]
    version: 3.13.1
