apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-downloader
    namespace: downloader
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:rdIBInL1QuTDKmkVQsz8wV2fOmybwox7L0lYcHnHivXzBSOs3Ghoz3zeZscVOmDJW9bCsPYZ0+tnz+hzE4Xg1ZuuxV5HOsMnIctNxMRWPXdmi69zQwSdV44ZULT3Ew==,iv:c+xBo93dHT/p+oFasJml9zPuel/ostfwGBLOnUbwc9o=,tag:wW7C7yuCEHrGm5ArWARVBg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:IpNYmyd9VutPBg7U2hxmE84vEqrQP2RZTHqm44m29YKukH/JtJpHIn1cyThdmhb9S0ZvHiz8t/Pi8taejbzrQzMr9mWN4fQ2Ou8/ka5mhvtk/ahFi7qRZ5UEzeN4lw==,iv:ZSdoyY9u86sXnVuta7mzMh5BJMHIwJT8YUxPHpzqL80=,tag:oiUqQhzTfGF/g/0aUmoduw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:MuSXW0gf5v94N8vGmV/ztWYclV/oQDfHuxC9YdvUdZ3gXkfA+0TZg84kR2YP4+W0IabcllFUoU3oIbV87MQjXw==,iv:x3If8FWTXd+ink1JaS7oMnHgZ5HDz4UOBlHkopn9fNI=,tag:TkeE2mlBOWEZBSf41XaiFQ==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:gK+VdmhZWcb56A==,iv:J1YDwwCAkAlMUn57wJ7kGjvTN4a8xDglPpNAi6BXjmU=,tag:BoIMJKVGwg5w1LHjX5bGow==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:e8qlzO5q/+L+xD50XV/PIibNYUNv1tq8YNjsjZ3IKionazp2yQvh+8962cQzXpBWhvd2UySVIAD8PpKnVarfGDk5XrYT/A==,iv:+a4mdxwHsjBo6g86VKt+3JEkc8LW5YoaKpfiXMvI2Vc=,tag:TeUbqfAlREt0z2tT3jP1Mg==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:gnlGXOk=,iv:76fT3YGQrnXALCj/4CAiDMxkU9BZRA4VWwEVaWjHVRQ=,tag:UYpmkF89ZFl57l+GELRJyA==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:8zSVsQ==,iv:+8VF64jdvURnG3BS7CmohXztAj8nGnDIPYQproODsXs=,tag:rXs7wujWrYJ/VLD4WI+VYg==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:SKott9sPgL6rzbWtS3BUBA61Z6efv2TAJ+uD7eXVC1UjM+R2JiU9rWgZWN1sOsuETWxJLxWu7saSArNshdmAxELgHPck72hiyfYk,iv:Gcgk2NpF7AmXYqHsQUvq9/VYcqO+2DPE+ot+lqk0H4c=,tag:x/+Fr2qSYLJFVXJh3At1VA==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:vwLmnZ2p7/v0jzxTRKLOTy2mnFu68m48jALJ,iv:KkgPvZ1ZzXs9w/DuS3B3ba79XAsWJF7NwPo/fgLOSG0=,tag:/pClKCmIrHz6SeqVQQibDA==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:qW29BsxKzS4Xvs6ynwPjEYEy,iv:uTXJ7vqdbl6OGYOdIwHnyTZz2+zsJcYRrS45LAIB+XA=,tag:00sb44Bsli5qu4TpgstDPA==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:Po0MCg==,iv:nI4c4ztTW9i2XysSFF+EHpTAmDBOCvT9Nz8cGZM4ths=,tag:+Adr6BH3WmZTEobfWIsNqA==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:akIInWRCe8kutLnawcPj0I/g+srAYRXXGHnj4c0DUP4d4byjTytxBfrLyJ5y4z1uEG0yExKjwoRHLW0mzHfs,iv:2MduivfcrJRnDG6tsfiaFzBbdp7phZWp08GybZQJrus=,tag:O1YqR9hMFDORMe219TmJyg==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXS1hVZDlZellUUWVaTXdJ
            b1pJNzZIdDFLUEhWQlhRc3VCSW4zdXg5SVNnCkpRRFFXeXdJU0c4QXBYY003ZFZn
            K25kMzl5dGVKbER0QmlrWndlQXY5MWcKLS0tICtPczlZRTZQYS9HL2ZNd0laWXMy
            SUptbFFwL1R2RDVsbVhPZUptRGhCc1UKpxnysEAZZLcqwTuJk8EnsQyasCm/7Sie
            Zq01nvYt6WGIFNcruX7C4Mk7v7lTl0CROps1XDPrW1VPSUVqPFvqTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVnRtcC9KdzYyR3VKMHRx
            cS95S1A3blM4ZkVJZHphWXVmd3Q4dG4rTFFNClYrbUZFU29QZ2pBL2U3NkRnak9C
            Uk1sTmYxNFFGbVV6OGVmdEFnRFhzeEEKLS0tIEsrbVRMQkVTT1FHeTJwV09aWm9G
            L3F0MU4xWXBJbDA3UTc5T0NDd3o4TjgKVoqfPpifo0BNuDa45xhj1NpBx+OSfL6H
            9z+2/gONAfG99IkfwIAUXiU4cBR5b6iXKA5LtJNHL/nBbemdZaaryA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T18:39:40Z"
    mac: ENC[AES256_GCM,data:bwPQjhkuc8o0+1Wvscn9QKVHj+XWFljYE30fcawDd7QYyrjvYL3O+weYGUEzPJi0BlEgn3WtHDJg01T2v4ODRhxvzpNWoDBF/PEbmqVtiVo25CleztQfIWFDXPI/5iMSi3aQFOh0zNSX9Oh1Tbnird2hPgiPbVYYd0iXKmJbU5I=,iv:36doHycWgIIuD5yr0AsLychcZZD2vdMEbApG1wc8NZM=,tag:yDqYoJEgcZ7r+XU2NfWQ1w==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
