apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-downloader
    namespace: downloader
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:7EvhpNzm+pdsXuO/TJrLkNBgkKfHGiu/Recs7rJETvQv96bypAUpoqcn3eEF85jC1AnxcRUpEIo+Ou4jUmOY+HQuecpYS+uI2gSBFgbjZKs/H2gP8hn1zIaxTzsfVA==,iv:Y7BAmjneAl4b6PhVqFs/WUN4jPzEoJuaMx1JzsfeTcs=,tag:hwCO+mjJd5ycjzbEGZQidg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:c2OUW92gJf0Ws9J6B7aH27VGgbUQiuaf0uNZhsqRGA8d6sjtysp7JyNE7h5B7jC3XL6VyXk4kqOeLoEl/g==,iv:/E1DjD6nnqqowhAYlqE/OrkwjKDhlbMXVVyT6uzft/E=,tag:efqPDNqUgZXaIZ6u/uX1rg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:WilNTd4ntSc+zmvebPJFdHWlgbsx5Yx4JxNcLN07ZrH8PuLVr/njlRwXHvOyOVXWP2UHz0r7hdjU6032krHcjQ==,iv:dpdHALL0SBoQcjg/QYld0jZ0frVHeJG76DZlfHAuWZo=,tag:BmRHxX5MkHOjIGBFr4Y7Pg==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:2gv1JZLZceXw3A==,iv:qeM5t8cQynUmey+xunXLBaWqOqphEu716/3LZVHz1yw=,tag:S3OlEoRnJHKpcK68j4Q7eQ==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:cFmdgxMMO4tOtXzoEWAAAQ==,iv:fZsKYiggHGsthqylUVUSsnZPtXVEsP1pc12Y+ljZJXY=,tag:ysyaZwahVFIGEyXHN5PJgw==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:0kAdZPw=,iv:CuAx/ORGTbqwM5EgspKDhUptwR28p/mQUMDFAc1p/R4=,tag:9cbKNW+kgZxZbun6iyLazA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pqokQ+z7PchwuS8ItCJHT7iDyMc=,iv:zg93kS/fuIy8DKNJfIeGtRg2ryMj5Y3Dd/IZMGwHfhs=,tag:R6Q1pzwThXl3jfpmiLqDww==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:nGwIYWrV8IZIbVRIWXjvv/Dyp3EOtihwxlJtE0D2QHKci1v/eT7cVg==,iv:XikHk3KsRSJFuUpELdAn0OETWRBUHFIN0MOiAqnTVUY=,tag:qjLqyFrVPEDhSAwad03mqA==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:SduxbA==,iv:4j72tgJ2f1mtsvhz1Pw/pwPkBmitrF4oiE8O6acHw7c=,tag:eYB0FEA5MLFpMQ5odcmPgQ==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:cXZq09diOQEEI8hGQzW0Yw+NKIuFCB2m3TTfz6ixLO5jATIqsLDg1Pp0vZu43yvW4vDvUEQ9J+/4JkHre1w4y8hYdtG+3u2DC94R,iv:hb4OZxx5daTkELXDWjUB/MlJbGmGXTpGa4JBt5teMtc=,tag:OfUVTl1sBnFkxXmyYhD4mg==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:/4RSmMjZbml5Spksbf2zoY0fWc8K92/BbJng,iv:rCJ4HEovAhL+Y+m0ef9l1pQBEXcuftQ4bfmBIj3dNeA=,tag:6AdIn458/jMdVEWfDuS4wA==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:9FNybdxKxFbjUSTZX9NwiuOC,iv:MTxXvwdrDqSDLPDUCz6S5NZrr18E4BSd8tys/Nq8C9g=,tag:VTGtQ7JWYYnb+N8CI+qfog==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:Tidrug==,iv:VSRhafvszQhefz09MvcNrrMqHou/JkxoY5AUeCabkuU=,tag:nhzd7ZukGeig0tFc1ukYHw==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:oq8p128AG7yPxhthVOFomZ5tOpgbsX6HxQpSpNVn0mbmGNOUkJOMiKaDIiuskQZgLtElvHDHCQOgxNVD4DO5,iv:0aCkuztZNnj/8W2x2c3LSFP8BoMcjZQ+EIZjIiQxYuc=,tag:mPj0LfM6qc0WH+TXwYHUeQ==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRDB1ekdzSkxRSFBhOFpW
            dzd3V1ZpMnNvdTdVUXZUdUh4TEc5RDJiREI0Ck5tUDlFV3lsT0xFeGRSZ3BVNXB4
            VVltamh4QVZYZ1N5NW1yTGVhZEYxQW8KLS0tIEhCQjhNRVU1STNIMkNMYlNpUXMz
            d3NNWGJiL25YY1VKUzhRVkcxd3BlZEEKwPP1Y+/dS2vI9Fuj4IR/5aggh3vnhi8a
            4piVKP73+F0ov2lmte+0nTNzMCBM2M4Ab7U8IjrwXigmMdicC38Scw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK3BtKzYyR200encrWW9L
            SWZWVVpvNUVvZDRIL0NRSWxRRGVNaWM1YVdrCnBQM3ZTajRCWmx0WlF2THFDN1Yx
            UnVmUmNFMElGT1JCTVprcVhDQUVXNWcKLS0tIEljVmkya09wOHB2Sy9qdE1iSGh1
            VHREL29OM1lZVFFtcmUzQ2U4NmlTUWMKXo6QnCi5U3ZEP+VqPmvoNBFc24aCFQcH
            8PKjk9f7/rDdkCEx2dJ4yUVGMrFX0g/FT6dshgxOXKN5yQa5AxoMJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T08:50:11Z"
    mac: ENC[AES256_GCM,data:1Gc7ngdEEX4DLnCkl7maWXbMo4tyNTtzlJoPs6RcY8SNVaY3suX7QW7M+YXqkdVNibqqmF2SZ+WBVGhUGB9S++9Ih2FnOmiuWQyjUVd/nMngfuQ/wLkyxy92g1s/Qj9fAectZGiCShZwFQ201cyz2kpnkkuHhHWrrJ7P8O/1HMQ=,iv:0xJhd+IYNRZufeidFygEyfwMt7FOw8OZsyJCHnpGO2Y=,tag:yqZ3G4YQCo0Zu0py5KN3iw==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
