apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-downloader
    namespace: downloader
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:AwwzPZTAZT8hW0sATziTbaJbwS44eCM5eiuoDMbCf/g/oGX21nufnoR4BdNK8YbXAGHcn2uM4BMwiKTzs1Svk46bE5mtiVPTOObDVgCxwmGXPiEcFRk4l4S6GwFBKQ==,iv:KACQN+Zen8jcuqVP/LBAS1lhaBBff7iNeaf8Lhx0+uY=,tag:ZuXoOvzM2UxE3WuGWgDXAg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:PJk/6Sgcw36x34PXOl6WyMStDjCX2/Pj/kbwLMmBmvHJmf3X2wkmzNjlnCnjOOnUc+7RXHqTy9rjY2JlEU0+z8IbRzgtFkLBoFS9oWrE720cXBKiw2ENmkqSQZyePQ==,iv:fS2qIrAr6CM9QtW3algIgkRdlHzT3AqLBnwGgb/I578=,tag:FkKa/cY3Z2U+lXvpMSGN1A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:h1W3vD/pbIrYQaeJYz/IX4s3WwOBa4jsg+ve17CVu5j4FQBnGSlpHNuD9vHd2446uzEi685qWfu3VUK8nenGjw==,iv:T4B9oe/D4ubIINb59KVLjUEC6Cw8QnbY21oIx5/uekU=,tag:fMzBiQNCrpwQWUtAL7txKQ==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:MG059WBO0trEiQ==,iv:oVBxtltKykHK6ALOfWQ0U1ek5I+dirBJqL5uZ5t0KaU=,tag:wulTmXXiQp7b2wVEHQ8lPA==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:yKFFyQUdb/iQkYFilmHVcnVY8MycfHbYr4Uou9urYxpaq06U9xqi9yw+OaWL0kn3EdSXt+7XncXM168IHCGwk5fwnsjH8tl0fHSuAhclnn3OUmgFhiAai2UA,iv:4XlwZ+Pptsv+WtTNcCHRiYzE/o7SkdxmMOtKmJLYpFY=,tag:KuxcQrmudVsU7SbnMbuzwg==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:5cfZ4Hw=,iv:oyXyI/b661qX9bUlPPc0wsIZSoNdnbCsuKn45Z1EzMg=,tag:w4F2Av+Pt3/xiUGyg0h9ig==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:YdD6gg==,iv:WBeVrgPUH7qqnIHamXy9cVW10HKSgCVVTtkkUgtLwko=,tag:ZQjULWh4bqVo4e3QLCRglQ==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:aaVei//luj6rx93+mvPdQBmRWspoidv9jbzNW1JIPSJmMr4OSyNjaaY+NPvMYADO+gJ9A/MJkN8gypYrDpCu1jbjQa6Ge8Sh6ncg,iv:DskaapO4Wxy8GxTQJM4GOGyMlfYtDHao7K9Xfa+EFEI=,tag:OjsNPz546YO4qtxfeMMXRg==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:DXv9WgLxc5yyht5yY/fOCWXb/m1zgz08Gpla,iv:ru1v73oCMU1nV5nri5UpS23TfYLdWqSSApNsdLKJrJM=,tag:R3zAdCACu9koGByzxW6ZCQ==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:e+Ikh+e1LiWek1OnKFNFFYZu,iv:ibXKjBB/q6CN35MYL65A4nf0fNylOYAPdBOF/x08ugg=,tag:a1JnALqjw4TvALc2IPfyWg==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:ZzA1AQ==,iv:7TYS1a2ViCCy2r1u4w2nRbbwhdV04bTslIvoaPZvwBQ=,tag:W6FtQaqnQvk7t59VHje43w==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:TUkvWZ8fztqUQNdmdBrQzVew8XVvJxxLN+XhOO7P2MC62EjpmZkDXwJzIoGgg3cN8r2+FbBlYkPmn2YRGHgi,iv:5viIM6FsvXmxkFSrfv9VsS2tVzA3GtNxlMlnPzpPZDQ=,tag:i2GAYHzBystHh7zI2kuFJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMXBaRW9ady9YT1dURE5n
            eWozK09hSXhhQUwrbU1haDhZVnBDb3VralVzCm1SUldUcjFMTUlOU1ZPaDVTYU10
            WndieG5wanFKT0lzcys2U1o0NnNacEUKLS0tIDdVKzN1eGg4VWEvYzZCclIzc3lD
            QzV2Mlc0eXVoaGJpVmpoMVpKaFovek0KPO+kSnHF10eC2GUTfl9GuU21+VTIF1VA
            IhptuvE2dYO8TGKoS3ejOlPz6X2K1UJaNq1HFIAHEggYSBE5hJoNNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNXBRT0EvWmdEazBLQks3
            RDVRU0RMTmNva29iOVNva0VMMzhsNDgrNkNjCkJLSzRuNTk4S1hycVBBcStmT3Ju
            M2Zjc0FVYm1McnNZKzk4eVArTW91VVEKLS0tIHlNZFFNVFFoQzhuQkY2Ni9OdS9H
            NXprMVJwSkUyc2RSRjQwQmsxYTR2NkEKJVS228zlUtC209qxOg32RnsETXB3+DTl
            FB5MsOCSN3p/EitLIpo8q/hLF9PbfMExEd0mQUxaevNelFSQejeHKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-05-28T10:21:35Z"
    mac: ENC[AES256_GCM,data:Ai9DFDpyjcNxpdLrgKmScD23tzXKoq5KC0RfYK/62Rq5P9x/7VylnOaHF50dLHoTh2v2K7FhoX8qeJtlBrISUujVwyZc2M54OPQP+kC6nb3PrDD+2oA0jKaTx3/8q9vf/L6rCudvle9QOp7Qqoa6kl+3WnqEP14j/73MKVemY9I=,iv:mMX82BqiY5PP8lw8PQTOcpPmE2wdj2WcIXWWJKRfI5M=,tag:MMg5VcsYluHBIZibYQEOFA==,type:str]
    version: 3.13.1
