apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app.kubernetes.io/name: blackbox-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blackbox-exporter
    spec:
      nodeSelector:
        node-role/workload: zfs
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter:latest
        args:
          - "--config.file=/etc/blackbox_exporter/config.yml"
        ports:
          - containerPort: 9115
            name: metrics
            protocol: TCP
