---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: llama-cpp-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets.enc.yaml
  - llama-cpp.ingress.enc.yaml
