apiVersion: v1
kind: Secret
metadata:
    name: llama-cpp-env
    namespace: llama-cpp
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:saVzaSpPMlh6Eh9Kg8QyL/c6vFNGf8NEe8G7jyYNSjY4+cA7ZLzqN8WZe0IYPFzQ4OkJnxopqt79owku99X6Qg==,iv:QKYVx7tA8Vb7zzoen+fDYgUsWeQF6K0f7bDXhvkOTu0=,tag:uzCJyYMDkqim4TLso4Vk4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbFRaMFlzYmJlVnBUajNZ
            TkVBUEgwUC9HNUZlWnh4aHl1aFhyMjJJQXl3CmszVnkybVFIYXhQK2M3SnpZWlQx
            S0NDN0tXU2QvQTlZZXZMcEhvMTVIMWMKLS0tIE9RSTFlYnFaMVJDTkVIMzVrQ3Zu
            a1VIeUVjMlNObTVTQTh1d3ZINWdndmsKpllyTxNlUtGANN7N1FuVdb78UQ7Rts0b
            K5YxvR5NDIYXISxcSetADfsbm9cLKJzoMeuCJ5PcNmadM8s7XD+0bQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb0U5RUd4QkJXdDhmZ2wx
            OS85bUZ4cThaYmxZbzRodGcyaFZBWEt1VG1ZCnZEZlBwbnFuVzFVaWQ1ODZpTGpk
            clF6MHNsLzFJdDkzd1hyWnVURUdqUEEKLS0tIHpaNnFwNkJ4cUhUWUlXOWNNTHdx
            STE2Z1NrQW1PZEU4Z2FuOXR2QUl4T1kKDINV3Ie5mh93k98pVDW7anN4bYdXUTop
            cYggH9Q8SH6VpJa5PUZ6h3gUDUM8BxERQHyt5H9l58mbnL9sAdVFsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-05-09T13:16:27Z"
    mac: ENC[AES256_GCM,data:pdYHc7b+jID+N6/DvI9+84yt3ZV5VIT836a7qQkfB5cRLwFPJrK7ZRebqbJAwWmY1wia+YydUE1FKMOGAB68jfSZTQtqsVWw+QnDrQ66RKIkkS5ATkmfgPdiUgW9OJ1ZA9LcX1wIJQGzC3nz4S/+MnGr9WtzS7uubIOjD9DXQ0o=,iv:qeqpPLqnSbN4sxfPJeIligE6Nl9bzbeOf0B4aQjy2mg=,tag:sL9AFg+qebJlHc4DNb81tw==,type:str]
    version: 3.13.0
