---
# Config volume for nzbhydra2. Replaces the hostPath mount on
# /vol_raidz1/docker/configs/downloader/nzbhydra2/config.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-nzbhydra2-config
  namespace: downloader
  labels:
    app.kubernetes.io/name: nzbhydra2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeMode: Filesystem
