apiVersion: v1
kind: Secret
metadata:
    name: deye-logger
    namespace: solar
type: Opaque
stringData:
    serial_number: ENC[AES256_GCM,data:Zx3D3DwdX6txAg==,iv:CLBCQSAtsyEKnl9OiVOdLBHVEOk/9+8vEHg+lF3uHW4=,tag:6JC662oMX1o2NPht14qPIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY2t1cHFSMUF6MmtldGdH
            MnpPUUU0UjJuaSt1VHNvY09kQjc0VDRxcVdjCkQyY2crMGhTUHZZSVVCWXNYS1Ns
            ckFZQUhhVTFNci96dlJjT0FHRVhrOXcKLS0tIHk2YVhmYlBnRGUwQ0JPcU1leml0
            OW5lL0J5UlFOMmowb3BMNjdTbCtkOG8KYj+EDWzfeuLQI5Qn/qQcRNQYWnpScxPE
            NXfRqJt9VHG5Yrkx/inImIXW4R4IXB5eBHFmHZgYJqFB5g3Bo8hE0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1R0k2aU1ub1NGWEVYQ2o4
            cWo3RHlxKzNHUDRIQjNQcXhVbE9lRTRNSWxvCld1aXVSUVNqNkphNk5CT1gyN2Rz
            QUFqd3p6SXZGYW51RlpwWkx2Wkd5SUUKLS0tIFN3MjlRa2xRS1VWZ0VCQ0EwUVVa
            YUlQclhjMmcwZm5aaVhZNmpNNmhGR3cK2Pj1FLkBTVWNICE2p+NDEQlLM1b/rUmP
            9S/7Jz1666SSvNT6Z0leYWv5p1PWWiG23MQHu55hPbbzedID9/mVew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-09-07T15:42:41Z"
    mac: ENC[AES256_GCM,data:BMTM0iGUBoFF/9bSVbgOfCdUvgon8mxQI46l0oiGTnhgj4wQGY/ngwNs2XbfQgV0LVGgztduYc0l3/1v1kTie6+vc8T7ys1dsFQcBQMhhZUDc82XpC3sqSiPLVVeryzUlgICgIGQCVPLIyhy2KWbH58GDU+OhC6W1F5V2Xu8ErI=,iv:rdJuR54SyL+u8qtkguCEdWXtVSARxtsvv6PuZmdVk8I=,tag:433JOfkPN7giKEFqg+7n6g==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: openmeteo-site
    namespace: solar
type: Opaque
stringData:
    latitude: ENC[AES256_GCM,data:Zdvsfz/WYA==,iv:QniOPTKSHzbzEIKJlejnnHzM55DcGrRzwUaytGDZ8AU=,tag:UFQlpHNAJf0+vAuZCH7ygQ==,type:str]
    longitude: ENC[AES256_GCM,data:vT37Ky02,iv:7KkrgzZnPddCefSvByTkdpTlPXJ9E45ST5+YZmpq2DY=,tag:KoN2K2jbmFPvboeVvLlQ9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY2t1cHFSMUF6MmtldGdH
            MnpPUUU0UjJuaSt1VHNvY09kQjc0VDRxcVdjCkQyY2crMGhTUHZZSVVCWXNYS1Ns
            ckFZQUhhVTFNci96dlJjT0FHRVhrOXcKLS0tIHk2YVhmYlBnRGUwQ0JPcU1leml0
            OW5lL0J5UlFOMmowb3BMNjdTbCtkOG8KYj+EDWzfeuLQI5Qn/qQcRNQYWnpScxPE
            NXfRqJt9VHG5Yrkx/inImIXW4R4IXB5eBHFmHZgYJqFB5g3Bo8hE0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1R0k2aU1ub1NGWEVYQ2o4
            cWo3RHlxKzNHUDRIQjNQcXhVbE9lRTRNSWxvCld1aXVSUVNqNkphNk5CT1gyN2Rz
            QUFqd3p6SXZGYW51RlpwWkx2Wkd5SUUKLS0tIFN3MjlRa2xRS1VWZ0VCQ0EwUVVa
            YUlQclhjMmcwZm5aaVhZNmpNNmhGR3cK2Pj1FLkBTVWNICE2p+NDEQlLM1b/rUmP
            9S/7Jz1666SSvNT6Z0leYWv5p1PWWiG23MQHu55hPbbzedID9/mVew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-09-07T15:42:41Z"
    mac: ENC[AES256_GCM,data:BMTM0iGUBoFF/9bSVbgOfCdUvgon8mxQI46l0oiGTnhgj4wQGY/ngwNs2XbfQgV0LVGgztduYc0l3/1v1kTie6+vc8T7ys1dsFQcBQMhhZUDc82XpC3sqSiPLVVeryzUlgICgIGQCVPLIyhy2KWbH58GDU+OhC6W1F5V2Xu8ErI=,iv:rdJuR54SyL+u8qtkguCEdWXtVSARxtsvv6PuZmdVk8I=,tag:433JOfkPN7giKEFqg+7n6g==,type:str]
    version: 3.13.3
