apiVersion: v1
kind: Secret
metadata:
    name: deye-logger
    namespace: solar
type: Opaque
stringData:
    serial_number: ENC[AES256_GCM,data:A7LnFd//YWzpdA==,iv:1t7XVKYrIcEL8Gn4x/qjfpGTT2QBzuB2yujnzwmijeI=,tag:h9eGMUk10SJD//4O8OLo3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZW9vQlRPMHB1OHA1NkJu
            cHY3cXNEVFU5THRmd1ppNjBnUFhXaWJOY3pJCkh0ckJVMWtFWkFDNDd2ODNGSzAz
            RHFBNGUybDJtT0tqbFpCeXR0RXRtYTgKLS0tIFF1WWRDVk5PM1RuSGx0NUF1WDJ3
            b0xvYlVzQUx3TDlET1dDQXpvRVR4QzgKn+AvwsP31pcyxQAyovRI7LC2PNIPzKEa
            ugYH9fbTGmlkpKwPQcxKD4JUBaoBZ0ricG1bFzgTKhN+b2GfMHgDvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WXkwNzBiRFpIc2x2MzQw
            VU92N1RoTlA4aHlCdDV2SHVWOXhUS3NZWmhrCnI3R2QzenhJRi94T0RYMTBObDJo
            Vm5DMGZ4aHEySVZ1amZyajVVTUFubGMKLS0tIHVuemRaUSt6cnM2QnFINmpKRjhG
            SnRvVG8yejYxYmVJVVRHeFlrSjdIR0EKoV+Lr2LHbnNYZvsAH5ZgQ3DeWc+tVc9J
            c1ebEH9yjIFSAPVhDvFcOu7dak4hXugBZfW+myad9/T7hlitDgeB0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-09-06T08:28:23Z"
    mac: ENC[AES256_GCM,data:j57HaqedOf+31qgIYNqnucaze5yqpv+mpRu7SAT6aZKmThIfH7VOqISvt5dsecGdJjmphBm12L3Ou5brEzG2vmGWWQlkKDIfxNGwKNJglKKW5PvvX40Uk0rJwdAOiws1XxSyud8wrTSwsBQ/cQXvxoYHCdN3/7myKTIhFLjKjYw=,iv:B1M55VTuU8c+6H0dgbDOhRRG9q6OhSUa9lW4xPif6KA=,tag:toIeEo7TK7fVVbWEJHIbYA==,type:str]
    version: 3.13.3
