apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-paperless
    namespace: paper
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:CMWvD/tDNSgvVZO9e40nd3aIoKnGvgzjLh3J3uh5qfHxKNtad2iN+0I5Jn+LAA/kxzDrBPeLnEpMduFk21QYas8GpJ7Y/A8=,iv:l3tjt/iiw+hojYmQCUBUtXYlWi4D2KGBlXfnRR2rEY4=,tag:ioET5AdSkNHHCSsNIL0ADg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:gW3KHxii7n9yF9za8IJGzYIBUi90vZv3Nu7r0f1EZPbHTzPDROvlNsMZI2IkZM5k9P2zslqCVjbI3yk20Vkf844s+w2zq5VGf6PAy6llvi9twuB9NHq5xfhnOQr8TA==,iv:3OXiCulKjqT7xfpGR5v683Wh/70pIkzTfLDeXLDA+mw=,tag:ygW/avPQsOgkD3ccjKzJww==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:mYusFgQ3UqhLwJT6kEt//I1GQ8uhwQ4/MGmFoK7e1dFqCyAcq/oPTdZOYDI0OE9gZ1BDdt+P62+YwXVbfzV+aw==,iv:KVSnh1KSZiQid1/2wpKDOFaYfDbaF8G//0d9pcshgzs=,tag:8EH12PD+IWmqTAxJgijGpQ==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:Jb3+fq9DkX4C,iv:xmIsG/FEtfiCJIOgvMYXqsV4gqgC723Y/Dgs1AAItJc=,tag:/GU9TDVN0OngvpxwLrVBPQ==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:3eISTthIVVoClpykYYwXCzq26rfBJtPaHHczAo9FwMrxdbW+ygoPKWHR00PLj2FYjLX2oNMXMEw=,iv:EGduCbbVvuEU1PhAJWm/MqDRcTPRRNjmIJ5K4fDb0io=,tag:K727i18YqhGnUPgHpoUBcw==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:ONZXajg=,iv:qyEF8MRZ4N3WcsbgPftz/rs1H94l6U7xvZZeYOIeyho=,tag:zR9nyW1f7M+YlvkKtjnjtw==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:K/zpbw==,iv:KSv9y1GTW81pN2EKd5lgtYsqTIHGCAkIUPa5sS82SMc=,tag:Ynpv7FUdJdxlsjuxGi4deQ==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:fiRuAOHwKJsuymtzFzGb3wAwJ+Y+xypjBwD5VcTagOUD9hl49LVjktSSL7ShMAJTs+8QiCTCetX90lW2+zVYjB5uavSPwFMJ1kHT,iv:ju8PUzP1vKO4CcyOUEa8B0nNp41paPeAjueuwt/MUkU=,tag:qSewm6LgRLB2tyEvflVqcg==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:mM2aV6wzwOvF7Jy/Fy0J2czXzobHkXHFVJPN,iv:u13hvg4lDNGsrnNCTPKKT+p0WJNq+0RUpydMvW3aG4I=,tag:svuL27KIncnfJA2rosmpvw==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:n0dGe1jAnN49HAevgSAUBwOH,iv:HhkwCSAdyYvWKuQ/Fuu7u5/7TehqCUXr5w+HKIHzqjA=,tag:WlDyEZqS/dXsQUmWj3Zcow==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:A4RMAw==,iv:aPDWb8XTIyBT6850/pehmYWmnOS5VNHrWGUMzWujRzc=,tag:FvxlgiefVr8g1h9CWDaIDw==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:3FrXre5wkarmgox+4TvaZWIcg/wo8Cs/zc2vZ3yV/1yB8WNTEzNsfUeTkJFOhVLJso2FtK81VUDyw0KV/DEl,iv:Sr57K/tqrcc8+6JkKeiyQtli3+/5fawlksw+Lzy6lNg=,tag:DJ3Q2OFLty51IvN1c1w3Rg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UGpUSzNqRVN6MkNNd0tF
            UkV1ZXZ1anpVUW05L0VWdjJvdHJTY215cFJjCitTcjFBMUtwY2xQOHI5QmwxYSto
            bGxZdXBXVVF1OXp5SU1pb2ZMU0RSWTgKLS0tIGxINURDZkdFMEJ4bGgzRUlaTWZN
            SWtjUlJLSXJ3SmtadUtjWDdCSDRWZlEKgH2PTgC9Imvab6xDEmFQVg9GOuloAgTp
            e5PcFpRi7F7BVyHQQM2g1O3/8Aj6lxFnhaWKoYSBhMASX0FO7YsAnw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRnVid2lkamdBUGh4MFdt
            VTlOaHB2WXRiUHJUUit4WGpFYUdtVVNMemtvCllBMC8rUWQ4ZHlua3VPUktZR2Vv
            N2RVbnBTaHp2TXRjWnZpMGxrdmlEODAKLS0tIEVaU1RISkdWUS80WUdQRzQzRDNM
            c2lKbUJScVBNY3I0MmVEL1Fwb3FEd2MKkLRjO4B9tMUi90s9moZ3p9EayJn4HKFk
            JWWhJ/xvijXSxZptjRN+mhBInIFt4z//SknjWBq+sKHpaTBtDolnjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-05-28T10:20:08Z"
    mac: ENC[AES256_GCM,data:PchnMseKV/5+QFV4m61fbCkIjAkAsbE1dgP8w0T9xoeC9EkFx82zJ7mqBbpYnfNGWAFDkQW0zN/cg9YEPuImEDCzml98O27A5W1IniwfmWYrHjUsuUE5OBcDbEIMCoCFRW/VEa74f2CUsTGEqmOxiEg18znIYlkRxX0brIYkYGM=,iv:Mbk2MoNyfAUtnSzpgClQB2vJ5ObjRBnGY+sDXkTbeyc=,tag:7QPFWu5Sbeay6vQjtHYZTQ==,type:str]
    version: 3.13.1
