apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-paperless
    namespace: paper
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:YhTvTVRJwZiRvaqQfF6ZBvIb1/KiGpx3kZZH3E5bZ/mobe8FnRgpz4MUZKD/HNDcQnY16UPlh5mciYC7I0KOT4p3ILB5a9w=,iv:49OhoHdxMzdTIMe4PKKvH0s5yRXdfZIZRM6xqvHVJw8=,tag:nM+NvflviFh/7QHL1pFYzQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ka+FbkdYO+pNRguCdk523MMKJoIHf4Evv57eeEZuiG/QSb23I7Iult7we6EbGbJEZrNNJkMFIWSmnBYkNwTzBL3vkfhTUO6NPs73WZaqrJAYrw2Q5ytYbDZj7iM3Sw==,iv:4xCTnTj1d4Qz5YxRkymBWgXvvSXCueKKeT3Ap6XM/Uw=,tag:smmG0GhJf7dYXnO+fH+USg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:NVS8xDjyan7B5ewL/0QMx0hZBPkeERXTqjXa9USosOsFf56b3jhiwkKbjIl7Yb2nTicp5ZVPkXv+zIZs7kBEUw==,iv:fu+GgU0OJcg0gPnChrKZUPRA51EfQspo+CR9TEpGTHQ=,tag:pBrFjuImCm1rnZ/5nV3B2Q==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:KdSAa8+yNuOn,iv:KSLGCWt5h1R0DrlKnsDwlYF28JXHVILJN1XrhG9DP4o=,tag:vvLE+TjDG3jZobZCE4ucCA==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:TOW34OVM4taNghRTWsPTBZ/Bv17JLzAQ7UMjSppy+2C+lmMK,iv:XMHWXITTIHhPLwZ5CVzHhtqe3TDmiky8XoO5f8ruh7Q=,tag:r3Y0mAtN3DiIoBJCGN19xA==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:mDYo934=,iv:X1+dZpDuXcoD8EKwXBcOkrLzoaLJupNafnt2UIr/S28=,tag:9eIMIkXGQg28w2XXmC6AIA==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:xx1lww==,iv:WGom4v2v+SsRgjsi3Yh4hxxvDMldjH5/EUTkCdQcOeI=,tag:PkDjn1niGLujdGz1FDTF9w==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:+0hU29vLl8qbGFBPPZSwz0pN9uBwx+cBfq42DkcYCb3npOoS0mhsEC/K3DsrjpCYuBoBFOvZ73gi4ffzchJ3b4r/F0aLw/PRXk3I,iv:YeA54jDPqGC8u9GOLza+AxmzWO2boszL8L7Uuw3/4jw=,tag:hh/bv2ccjg+3ac2WUr3i7w==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:xa6XHUFFCaUGAb3Y/FgCgqVyqAEx8cXiu6JZ,iv:ZxzFT1CqtZf/nE3mg67Nw+X+LHhpVABTib53Z4ZuSPU=,tag:I5onjCpQ/znefclPkdPg0A==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:i0wTuoFAAZFafdx37yFmZq1n,iv:ENjM+Yklg17PzHg/CM8wjRvkpF9o/WLv2vjli6HIPKE=,tag:P0LdIvM2l1Y6axoD/STSbg==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:NipPHA==,iv:7flRjPttQuZVkFYKD+HYSWLhOOZQD3o26D2Cg8Ja0jM=,tag:XjBhIrsH1pLNV7KSRIcIWA==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:PtHRbiT52wWnRivw/cgcO6KrIPR8ZG5yoRGcDbrUo56OBF6TH/NxA1GkjuuIlOj5Qd0UpfLqAT4BmD2VDrYD,iv:/Z0xV/n0N7MwbYDhqO95Jt0CxAhdazko33J9dYCWD5I=,tag:MhyTDrn0vmYFsB3t91etqg==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZURwSTZsSUgvVWhqUlIv
            ckxIZlJ4aHlsaWJSS0dxMS9POFRwWmJ5ckNJCmNPbnBOV2srU0wzYmI1dHFDekw1
            Q3hBY2cyc0ZSZEhiTTI2NGJzZTA0OVEKLS0tIGFJMUp3REZKODZJbHdUZ3ViQ3Ex
            RUh4L2k0d2k5c1M1ajZmeFp2OC82ekkKf42K6wB501jYXxAU3LMx1u/WFg7Yxko9
            ciw1FikyEahjnlNd5reRD2NQ2Zo4OS3NDr211+F4DaRSTWx4Yi2NYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZ0hMVzdwSTBlRXYvWkov
            OThMcFpaczVPU2ZYRi9jTDhnOFZVdVZIZ1FjCjlCWWZTVDFmRkc1cjJYZzZLNDla
            bHNpK3E4WFVIditId2lZakQvRWpGM0EKLS0tIFNESXR4VW9UemdrbTN5ZE5BRkFI
            cVBHNXpEaFBGMXF6T29hcVdvL2VRRWsK/0dLAleDu9nWonsEkNxURrIgK8CCSwSn
            2PC7eTmYkCC9f3sm/nJ9wN+e8QnpVkKrwZ0XlBWwHWaQX6bp17Prcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T14:05:27Z"
    mac: ENC[AES256_GCM,data:kpN+Z+g7jpI6upQFU5SjdBQEwRu1esofllTlCDr4jDqPubAupCZ0asas3pyZIxO/Zy4muq0oHa2jc/4IPFA4Y8IituITtoJRw7ckrNxs5VbwfYvt1C1c5ylGnKbgd6bF/m7fZHKZ1zXQr7DyhEmwR9L8sfKxh/GPwGn92RwrPhg=,iv:4yy6nr/ANHJL7yspS1+JyY6YeiRV0B2OIFX64mI6hVA=,tag:ulXqQw7XCoKJ7iGNCpfdew==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
