apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-paperless
    namespace: paper
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:dtNn7iusKX6LuUNnZyvwpZhtjrRbVQye4ovPc/5vXzZP7tZwu2EXSxRXf7wJlgRQnOcbJcqfWf6BNVkBb2Cqr7sxnzTapg4=,iv:1UAqFBDrqT+ZYj4m1H6QR9HPXRIgvOyf18lc+9qGOXw=,tag:17U6RKImeRt/lSXq4tjOxQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:LduCrY9i2PzjOvr5XzqDn8bhpJP+KWr+3wC6jsIYhTBu8LHBKSVJ2LlychN5OyC2UUMNXk+wNicxCpIP66PDTq1O46O2gp9fCgwTaTzIr3BZnQa/vgT1es63CcrKFA==,iv:4BwheUuzIndD4506jUL+02sgc/R0gx3031yROvWkJTc=,tag:ZT/xoC28ApbiYCMtv4HvUg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:butLBW5Kxame/OWn1wtZVPvkiSDkv9fz/Y1Cyh/Zb4pyU45PYesKkQsnq4gJE49CQwjYxrP3rRH3xdK0C3MtEA==,iv:QiOhD7kXbDYWcoATFN7LA2SkBdDH5QaUo32acpnlIug=,tag:Cggm6E27rd63Eos/0sDaaQ==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:XA1v/pbUMn2D,iv:0rwA8qY4xbOtzFotYwpmHbEBjYOZ84mpJvtjAOq/+UA=,tag:Kg/eSyNI+hCZ6/5JjRqQOg==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:uXtHBJVxHbJOzHtiEpNh4aIkaGYKVRkaML0RE2JDhzSMYv35,iv:f80/DQaRRf+jSqZ+tsfdIcISRgRO6hV/rkh0hpO93xY=,tag:afXjCCtpn8kHPN1SL3j5mg==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:/QEtCPQ=,iv:JfJdu4hUEY5ijUFlc9R6yDwb+v6DoPexhEBJjQruHBA=,tag:ESv6T/lhfqthD6B6Stic2w==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:cOfiyw==,iv:q00QOhlvVLN+ytmtlwSe1xC1Fr/xp87k1cM/hPojOz0=,tag:3m2vYlgctZNxvhvmMELAJw==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:/gJhfRa1bbZ8hSndrknH6YiVQRt0FAO5xttYyV7e3mpYMdtuumheakV9uIDYp/cIxqw9enLK9CDpPZJHe/NejqmzGRHhrkdYqjC5,iv:wkfYYB7o/+y9XxmRYrRIl91AxFpOkcndLmUImXkUDYY=,tag:hTs6ilo3mkC2hopGWBUgIQ==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:CpxnipV8JaPM8v80qy858psKv79orQbPKLZe,iv:nSzIEgBHcViuQ4Kk4fmQPVq6FRWrv6V6nFd1Pahhr2s=,tag:MxSKc2kSkmedaC+wxZ+CAg==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:21FEkNupQZbPfiZHr9DAoysH,iv:5p7GY5ClGiLaB+1rG75UhjXdM5z8JwEnU0HT/8elqZ8=,tag:dQeEE5oEmO9rfw+yuSQ3mg==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:3Q9z8A==,iv:vpM9ZP3s7A1BF9Anawa3HxDbN9veRWFstnTL/4ZGE8c=,tag:0ad28H28WHOk9hQt1gVuiQ==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:EUtZerPpBgDcktsIC0JUmF3wiEegsSIRneRMJQ4YnN9iWjWjMV8uQjJY8BkQ80vfDNyJCY2w/6fzCgk/zyb3,iv:bICHuCQHyvv+09quz1naEQyfbm5wgxtC/ljOkqZzC5U=,tag:KxBU6iaDcC2cE8j2X2DkLA==,type:str]
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSkRRT3RPMTJoc2JVK2lT
            azByeS94NWJ0dnc0citDVmxOWVpIMURETDJzCkF5Yllhd1JNYTEva3pZNHBJMzVI
            eC9zQUxsUnlPVUNZK2RTMVEwMnR3N2cKLS0tIFhDUzg3UjloaXVmc2VjeWh3S1Iw
            eXNqREU5aXQ1VjVneEVIZUN2UDVaNEkKGXksL6/gO9hJVY2ZheLqgugt6nq0KEQh
            3USBK01D0USlWn1SJLrh0eMdTdu7Adx7Fua6bgAX6DLHSuULHNk+Ng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibk5UUFp1QXRQV3VFV1Uz
            eVd5aXo0WEozeDM4cjBsVVlZT1Y3ZmE5S3hFCkxGRy9tdkRLMEVMTjNTYkMrSWlm
            Snd3ZHVpbzEyS29ySUNoNEtXK1dOcUUKLS0tIGxLTlpFU0xXekYxYUFEVDVJTDVw
            dVBPMFE1dU8zMzh2bnE2czF4ejRmWHcKcNtsA73DoQu4koiqE7dSxFk2TwYcs3QA
            O9e2zn+nWhAsEHLADwo101y+bktTXML2jUQbzUfsXsHxDsOtGuuv5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T18:39:40Z"
    mac: ENC[AES256_GCM,data:/jBDEVetSkKyGeSfKfyJUKBBGQLUdvQqXHpV/nPrXW4/oZFQC7vlkfqgztjVuf4tl2eQOMkp6arp0DRxGGJfLUXsXYv4Zb4eBN8CsprMwKjybMJ/yVNZGcsTG+9bHGiFBRoI8ZNOaz9Ohmhm8ioGDpcuG1VPVzBkHRDL9Pq0UHI=,iv:dl7jovqnSX/CLDtTPCQ9Zz2HUoZp3Pe6FdZF+uDln4g=,tag:pV6dBR7UlY5mqb+UBDoyxg==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    version: 3.12.2
