image:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    tag: 2.20.2
env:
    - name: TZ
      value: Europe/Berlin
    - name: PAPERLESS_TIME_ZONE
      value: Europe/Berlin
    - name: PAPERLESS_REDIS
      value: redis://redis-master.databases.svc.cluster.local:6379/2
    - name: PAPERLESS_DBENGINE
      value: mariadb
    - name: PAPERLESS_DBHOST
      value: mariadb.databases.svc.cluster.local
    - name: PAPERLESS_DBPORT
      value: 3306
    - name: PAPERLESS_DBSSLMODE
      value: PREFERRED
    - name: PAPERLESS_FILENAME_FORMAT_REMOVE_NONE
      value: true
    - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
      value: true
    #- name: PAPERLESS_ENABLE_HTTP_REMOTE_USER_API
    #  value: true
    - name: PAPERLESS_OCR_LANGUAGE
      value: deu
    - name: PAPERLESS_OCR_MODE
      value: skip
    - name: PAPERLESS_USE_X_FORWARD_HOST
      value: true
    - name: PAPERLESS_USE_X_FORWARD_PORT
      value: true
    - name: PAPERLESS_CONSUMER_RECURSIVE
      value: true
    - name: PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS
      value: true
    - name: PAPERLESS_CONSUMER_POLLING
      value: 300
    - name: PAPERLESS_CONSUMER_ENABLE_BARCODES
      value: true
    - name: PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE
      value: true
    - name: PAPERLESS_OCR_DESKEW
      value: true
resources:
    requests:
        cpu: 100m
        memory: 1792Mi
persistentVolumeClaim:
    create: false
    storageClassName: longhorn
    existingPersistentVolumeClaim: smb-pvc-container-paperless-data
consumption:
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-documents
media:
    enabled: true
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-container-paperless-media
export:
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-container-paperless-export
trash:
    enabled: true
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-container-paperless-trash
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArelVXRC9SSDJMUVBoYWFP
            ZzFqb1dydUhKTkFoak95T0pVdHdsbm5ZblJnCjk4QWRWN3JsKzNBbTdVWjJqcDNp
            NHk2QUt4MlBjSktvdVN3VU9TbERGUlUKLS0tIExYdW9XbGJZZ3p6ZEg4WHptdVVO
            RmJ1S3YvbFNDQWRjQnljVkJpL1BZZlUKV7+o29iBCChy2syIIOPsJSDkh/Ahqux8
            qomPALaEeuPrriyhlLN5h/rlengzmqWSg41hHUky2dl4+z6mLjYMBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMURzTHIvWXNOSUhzUE00
            QWdhVHVwU2Q3QzhLRHlYRUFkMFMwRjJEWVdJCklCVFZIR0l1b2owVGZrOW5BRS9l
            WTNqK21Ia04wVDB1UmxiYWF4dUR0UnMKLS0tIGxsVFRHaE91YjRSYmVZYTZ6WUsx
            VlRSSWVjWERjZERDeGRQY2hiRmdXWmsK81us0K0fUVXgFyWQ+g5o7SB0s0OelGd1
            m7RZic1TX1d7S+uoE+tu5d8U2/ONsnWh+aD9eMN7r6c9yTCXs0dVIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T16:30:02Z"
    mac: ENC[AES256_GCM,data:8K/1x3D8/xyh9CIPP4u5egsYnfsTX5xeA385mvsJJCDQakIwZqqbQvnsWmKjBv6cpB/WlZV2glgHSo/MwcP61Ru4re/FVF+obDs5nRHb8MZN9hu7MUlk9dl7+qQKErj320NxbpOjVedJKFBmffDOp1+QJ/mnOb4+qKzgFQ2m4Zc=,iv:HDEpDJu/Nb4d2rPpML3KGm8D+j5cFJmiNOjF/4T3ga0=,tag:uh96TaI3YKKp9CluOcALQQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY)$
    version: 3.12.2
