image:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    tag: 2.20.13
env:
    - name: TZ
      value: Europe/Berlin
    - name: PAPERLESS_TIME_ZONE
      value: Europe/Berlin
    - name: PAPERLESS_REDIS
      value: redis://redis-master.databases.svc.cluster.local:6379/2
    - name: PAPERLESS_DBENGINE
      value: mariadb
    - name: PAPERLESS_DBHOST
      value: mariadb.databases.svc.cluster.local
    - name: PAPERLESS_DBPORT
      value: 3306
    - name: PAPERLESS_DBSSLMODE
      value: PREFERRED
    - name: PAPERLESS_FILENAME_FORMAT_REMOVE_NONE
      value: true
    - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
      value: true
    #- name: PAPERLESS_ENABLE_HTTP_REMOTE_USER_API
    #  value: true
    - name: PAPERLESS_OCR_LANGUAGE
      value: deu
    - name: PAPERLESS_OCR_MODE
      value: skip
    - name: PAPERLESS_USE_X_FORWARD_HOST
      value: true
    - name: PAPERLESS_USE_X_FORWARD_PORT
      value: true
    - name: PAPERLESS_CONSUMER_RECURSIVE
      value: true
    - name: PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS
      value: true
    - name: PAPERLESS_CONSUMER_POLLING
      value: 300
    - name: PAPERLESS_CONSUMER_ENABLE_BARCODES
      value: true
    - name: PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE
      value: true
    - name: PAPERLESS_OCR_DESKEW
      value: true
resources:
    requests:
        cpu: 100m
        memory: 1792Mi
persistentVolumeClaim:
    create: false
    storageClassName: longhorn
    existingPersistentVolumeClaim: smb-pvc-container-paperless-data
consumption:
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-documents
media:
    enabled: true
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-container-paperless-media
export:
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-container-paperless-export
trash:
    enabled: true
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-container-paperless-trash
sops:
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicGZZUWFsaStObUdGdDBz
            MU9HRkJYNloxTjlDNTBqZXJlVk1VOXA4cnlBCmprM1BYUzRJeXVQd0xTRitEZ0cv
            NW1ZMEZGZEZMU3d5OHpTQStJbGpPT0UKLS0tIEFzdmp3M3lRTlNnSC9xcnFHYmtN
            SGxMd0JQS3F2QmpLSWtXMlJSTjREYkEK5LyJ2HIJSzGxAUGmmCasoezd7lXrYv2v
            ni4wIaHLInp2i+IDZK75r63MPJoskV+FNTeBPGAjypEh22doHyDi1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcEwzOUF3andVb0JSZi9m
            L05LRm01K053eXJyLzFQcmpmdUVoL1BEY1VzCjNtZ3UwTWw1bldDTS9ZRS9POEFp
            YnNlMWNKUzJvTGd6Q3VSTU1uSzlKQmcKLS0tIHd6YWhhVEsxQmpPcjNZSWpKdHVy
            T2VaclorOW1odXlsZFd0QXdCTm9nWHcKrKc66B1vMG3okUV2BoLjwMzXmJRj/LLK
            bLCkJ9NhEs1SzvPrcpjhSF3bSyb4OXFIVpgUSray4iNjS0HVpJmOPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T06:12:35Z"
    mac: ENC[AES256_GCM,data:fnvPokP7/wTYWnJRqFG6YAxWisS0OcmK0pXU84+ld6ikUjlxkd6oM5HmR333PmUzv6ZTOUytqX9sSt0ExNPYpzztSnVB7eTXk+pEjghTQyZ9OwPj7fotgBcVmLDWGUCREaFQvtmbDJlpF1HWQxRSPDRrY1Ku924914wXGI6ZNps=,iv:Shb+bFp43j7H8dXoScbHjaSJSS8W4Tr1hDv8Ugrcero=,tag:4rpbXvUCoSmdP7AKmeWPmQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY)$
    version: 3.12.2
