---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: open-webui-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets.enc.yaml
  - ingress.enc.yaml
