apiVersion: v1
kind: Secret
metadata:
    name: open-webui-env
    namespace: open-webui
type: Opaque
stringData:
    #ENC[AES256_GCM,data:u9SopcbcvFYRKCuX,iv:31eXeUSrUOnSUO8OdeQ1YZkLcvmD77zLQJAZR6l+r+g=,tag:7TGoyl1GbYcJfSRmxzI2cg==,type:comment]
    WEBUI_AUTH: ENC[AES256_GCM,data:ZA6E/A==,iv:MeteIsXzbnp0qWHdmBt+ur8x8qlHcUDg0PWn7INjm5E=,tag:WH00MbpQAZt9SwNWWDAOjA==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:ioCZhTE=,iv:2CYTvXGi81kMs/7xEFdAPa6/PUi1HG/Y3pC17yyNl3c=,tag:QrytfBmuNkYK2Quph+bY0w==,type:str]
    ENABLE_OAUTH_SIGNUP: ENC[AES256_GCM,data:qu32kw==,iv:lWUOVOAVtp7GwIAo4aGi8BXBwVplwLMISi4mh7VdQ/o=,tag:W+uFdrehOWzu3AAAFEQK1w==,type:str]
    OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:HfUEdiBD+Xg=,iv:b+/cX376eeko2qFuiiSX18e9U3NqdLZcWx45NBvikh8=,tag:aLL5o2K+lIkVBI+HfDmiNA==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:ovj3bhisEkkH,iv:ICgEcqjd55Uo99oOPAB2VGC1bsgZA8nJSSaCXOZuZ20=,tag:4e0ouFKONYOu7Tq9xYoO5Q==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:OnIq7bCVVi5XQ+3RcqhoID8/HxOWxKf75VINPiTO1wTuazHlg0zGP8M8NbdMfO6Q00PsTH1qh4GRHwtzupb3P0YfA7MOlCVI,iv:QOeqL+h81yOygKcfhmHfRzmeU2e/gkGvEJFhZOkL26g=,tag:gWphcTFUL11WWs8CJiwSrg==,type:str]
    OPENID_PROVIDER_URL: ENC[AES256_GCM,data:41HUtHjF3IsQk51/zW3YJcaDeXnNz2TXraQaoXx8rjJwPzCR9y4f25XTTZusNjC9piIzWQvm01Xvp0baOqg=,iv:yVJTCdFSXHYYygLljmi5hqgVJMdyrLPyVTiHtIaYpxE=,tag:Ory7El3NKbXNTzV7Czgybw==,type:str]
    OPENID_REDIRECT_URI: ENC[AES256_GCM,data:meF3W6h3CKoshqATC97xLHcjvhih1pbwErV2CktSJ1YW92FbDw4ecmVUbQtMsZruqCiQFJi+,iv:8BLgIZP6IN/HNzIYVe01+QDZD9TMLywy4bsYPoEnKak=,tag:8w/I4HZ45EqpG71I6y0tAA==,type:str]
    OAUTH_SCOPES: ENC[AES256_GCM,data:046ZLiSc4y4MSS45hj8JyBlo6omWcmke9Ts3,iv:TxxuDTx8ijf9owiY9KZf0l3Z057eJ/QjVaBi626vW/0=,tag:v4pB+qBdhbg3bQmOk7cLnQ==,type:str]
    OAUTH_MERGE_ACCOUNTS_BY_EMAIL: ENC[AES256_GCM,data:10rpGA==,iv:XaLd5vfIiSHBoDsQFC8c5Csp2bngL/6ApP7l2eXFS1U=,tag:rNWfoIuXoRxcE02Lo9UhBA==,type:str]
    OAUTH_UPDATE_PICTURE_ON_LOGIN: ENC[AES256_GCM,data:Haifyw==,iv:neq2OY8W6v0sxqXo5KMXTloh8TQBY2SkOKO5s5ITxvw=,tag:orbI2rwCN5eijwCwunMj8w==,type:str]
    DEFAULT_USER_ROLE: ENC[AES256_GCM,data:+ddGeZffeQ==,iv:aX+wrC54ErmA0DKaVdELqZnDH0zbu3L09v1KXnnysCA=,tag:uVU25dsu/Q5L8Mfd2T+d0A==,type:str]
    #ENC[AES256_GCM,data:RPnAVyN3j0nncJiLeRyDBQ==,iv:7yvnRqD6wOJCDhbaDgm8r9sc2RN2U0rhN/yZX78c+xU=,tag:MEJqvFd7s50eDhBuNde4RQ==,type:comment]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:7/B/U8fYLjn8USRsRpwdZVc8fd3NR+FbjVhsc76yMTGqv4I2oXPaWyj02A89WSvLdu6fyv9nuzlefB/IUaOgOg==,iv:EhVhbBgtm84abzWMbO/YBiLYj4ZeBS4ngG/JBfS2O8Y=,tag:FPjyc7MTWldt/A+dvlQeDQ==,type:str]
    #ENC[AES256_GCM,data:wfH/1u2GBwOYxsKOndmP1tZB,iv:EKb3guUKNhJsn8AnCdm9ktjnr0FcJS4/N6auqk/7LkM=,tag:eOYMt6Z908c4GAyCdOsIDw==,type:comment]
    ENABLE_OLLAMA_API: ENC[AES256_GCM,data:/xMlr4Y=,iv:tMQwO3XIpuCfsUlOhjZChePQuOcDMfv/KzADWvSF7aI=,tag:ogVL+siJXQTUXK2xXMolVA==,type:str]
    OPENAI_API_BASE_URLS: ENC[AES256_GCM,data:NZzmB4Yr92mCedqRerqhs20kLGPg9CiR5h4XAXuW34/lZsvOkwTqQeAbE2aNvcfLRiFsIA==,iv:QMN/uqQaL91Ebx1s/5JVAwW+pgnjq1I3sVgopXy3a2o=,tag:djkk0xq1seNyoxHVDHZoJw==,type:str]
    OPENAI_API_KEYS: ENC[AES256_GCM,data:7fqGIBT7mIyvQdRaQ3wafYS8zGjwVX7njbt378Yu7QlhvqoMpjI7K3TZRkd5tUn+b5y5DtBk93uYiO6ofdy3Bg==,iv:c89h2+pGcgg6zGk2sZQMMkt5YjV1EJvu2BhsgbWxrAs=,tag:PsZkhx4hQ+RBCQaMQpzFIQ==,type:str]
    #ENC[AES256_GCM,data:UsH/6VFrVX/ctyn7LOTB95jV5cpmAw==,iv:t680Uk0S+75I3B9qa/LM3FCzBaY0yUkFQJ0zkUx3X/U=,tag:LgMqGLJwSv8wYZc/MNYe/A==,type:comment]
    ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:NaFizQ==,iv:KbMxF4jxMsNNieawR0mkE/eB1GyOs330qWJQt0hel6Y=,tag:ccZQcAZ6Wx75MCDT2q1kaA==,type:str]
    RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:o5Iyy1cQ,iv:qzYxPr4HGPvtszegpm7ScP5VJxe9JRHJY4L4orIeWqg=,tag:caDT4Os1rH9MsAUjAZwtKA==,type:str]
    TAVILY_API_KEY: ENC[AES256_GCM,data:cPFNFIqgbt4fMckbiLVliLsvtYsOBzNwkEUm1qQy/Djk+k2MKjYmtz+7CaDxb5Yk96Vg8Plbvpu6RA==,iv:gH0xlTvj45BNzepnmoCU6ADhgNhFt7Ragm61rrPM1E8=,tag:hV/g7dz6ottm+5N6G9J0Ww==,type:str]
    RAG_WEB_SEARCH_RESULT_COUNT: ENC[AES256_GCM,data:Eg==,iv:+v9C1AOM820cq1X956QbAD2XIKzE3xzNn2BjNoR60sQ=,tag:qK/tEBcaKjXFyQ3Zl2T75Q==,type:str]
    RAG_WEB_SEARCH_CONCURRENT_REQUESTS: ENC[AES256_GCM,data:RG4=,iv:d9W2WzTkjCRsfBRDBAra5DJGC/wZDglR89lJgrr6pOQ=,tag:6wx0bGSJx934Ak5Qevd3iQ==,type:str]
    RAG_WEB_SEARCH_TRUST_ENV: ENC[AES256_GCM,data:Exajo9M=,iv:4XecrsMyNaD9yPj38CXXooJfOG1d+vKvwYzsuuQ+MyM=,tag:C53hXaLybPSzRZ51afAPLQ==,type:str]
    #ENC[AES256_GCM,data:4sYd6Yw3e01tpM7Nov5ODOdtrGGqIMLX5iOkUTbzlAssmIQyVVENP3KDHMTv8FBuqve2lBDiQaV4O0n8BkO2RHRyHH55tQ==,iv:QiTBqBL+7rIx6CX0hmJS4f//nLF/SKLU1JDmyqp8xBE=,tag:Ib8LCS9cJyFoc7FlbZ9T6w==,type:comment]
    BYPASS_EMBEDDING_AND_RETRIEVAL: ENC[AES256_GCM,data:7yCnVw==,iv:erRBonC1MDas2Pk1A/+D8h9XzA5D9hw2lH07SWguE+k=,tag:N9FU9Xr34OjfGYXY6mocIw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbS9mZmpEeFA3TlczZGwv
            RjZlRUtHYWYrR3RFRzY1NkxEQzZhTWlTK0NJCkNjajV2Wjd6L2NlbTh5ZWFCUlhw
            Y1lGWnZzN1E0UGJ4dDh5UGd6SEZTZ2MKLS0tIDlrV3pOOURRcktITElCY2l1MHBS
            OGMwU2RCVDZrbk90blpuWjlLN2E4elEKSkjVU25mWlqskVYv1BJM1+DXxylCiyW3
            Y5hEhiDVifxgv4TUkZR+rkuTO/laMWVBKpY+JS5SPm7Fbndd4NzNBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NUs0MHl6WWtKaWRDUE05
            MmFQMEZoVzg0OFFjTnNBbGU2NllxVWpyNmhJCjhycUxSSHErUGUwTC84bmlCYWJV
            QmwvYXFkdnpQd1J5YkU2N2x2cFRZT3cKLS0tIHM4bWZ6a243eWlubERKMXVUYmFm
            dmFaYTdNbkhSdk92QmVrR3RheGxqSUUKWG9KdL6yJy1ej7H6C0Ncn462SW+QJ71M
            eZIddx7dNKNZ/9zws8xLezTElA0JgQXc2+iOtu8dZSyRWxkNjTnKCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|server_name|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients|.*provider_url|.*redirect_url|.*accesskeyEncryption|SEMAPHORE_WEB_ROOT|token|cookieEncryption|cookieHash|^ldap|.*match|instance|X-API-KEY|credentials)$
    lastmodified: "2026-05-20T13:14:54Z"
    mac: ENC[AES256_GCM,data:1LE8IWVP67mDtkZtTX2nDRYIIwEGPGPTk/b4aWNZ5YfvV8TfhXQEDvm2dHqdx0+UOhGGvstLm8slse7Q0zutL5Q8EGYrBoUvSr0YVXwgZl5J1gIcg/R7AFaT6JhVzLnX8w36lKn3aAhCmkoSSy6dBB96jbv+64RSvFY/wPpvwFc=,iv:NrMiaX6e5JxutelqrlXMrIinynCURE87C0bdOTd+Yd8=,tag:cCWrnjli9/0HSjSv5YAeSg==,type:str]
    version: 3.13.0
